### ISSUE TITLE
CombinedResourceHandler combines in development mode

### ISSUE THREAD

**Issue by karlkilden** [omnifaces/omnifaces#101]
Hello,

Using TomEE with Myfaces 2.2.7 I have problem with CombinedResourceHandler when upgrading from the latest 1.x branch to Omnifaces 2.0.

Seems since 2.0 you always combine even for development? Bug or change in feature?

**Comment by karlkilden** [comment]
Sorry I saw that the docs had a new parameter

**Comment by BalusC** [comment]
I imagine that http://showcase.omnifaces.org/whatsnew could have made more clear, too. "CDNResourceHandler and CombinedResourceHandler are now by default always enabled and can be disabled via a context parameter supporting a request based EL expression".
