### ISSUE TITLE
[feature request] add o:repeat

### ISSUE THREAD

**Issue by Centaur** [omnifaces/omnifaces#106]
The design of jsf built-in `ui:repeat` is not very practical in some cases. It only generate one component in server-side component tree and renders multiple client side tags at render time. This makes it impossible to reference individual cell of `ui:repeat` by id or clientId in managed beans. Some may suggest use `c:forEach` instead but it is not friendly to ajax operations. 
It will be very helpful if we have a `o:repeat` as `ui:repeat` replacement. It has the life cycle of `ui:repeat` so can be updated by ajax operations but generate multiple cell components in server-side component tree and each cell has it's own id/clientid.

**Comment by BalusC** [comment]
Problem is understood, we also stumbled upon this, but didn't really look closer as c:forEach works just fine for us, also with ajax.

There must indeed be a way to ajax-update a specific ui:repeat iteration. E.g. PrimeFaces p:dataTable also supports this when e.g. row editor is used (albeit only internally, i.e. it's not possible to externally specify it via p:ajax).

We'll definitely look at it when the time allows it.

**Comment by BalusC** [comment]
To my surprise it works in Mojarra since 2.2.5, but only when referenced as an absolute client ID (prefixed with ":" from root on). 

```
<h:form id="form">
	<ui:repeat id="list" value="#{['one','two','three']}" var="item">
		<h:outputText id="item" value="#{item} #{now}" /><br/>
	</ui:repeat>
	
	<h:commandButton value="update second item">
		<f:ajax render=":form:list:1:item" /><!-- render="list:1:item" does't work (yet?) -->
	</h:commandButton>
</h:form>
```

It doesn't work in MyFaces 2.2.x so far (current latest is 2.2.7).

The related Mojarra issue report which fixed this is https://java.net/jira/browse/JAVASERVERFACES-2958

**Comment by tandraschko** [comment]
PrimeFaces should work fine with this absolute search expression since 5.2.

**Comment by BalusC** [comment]
@tandraschko Cool! Does it actually validate the given ID? Mojarra doesn't do it anymore, which may be confusing to starters, see also https://java.net/jira/browse/JAVASERVERFACES-3847

**Comment by tandraschko** [comment]
We actually have many validation at this place :)
We also e.g. validate if the user would like to update a component without a renderer.
For a plain ID (without any keyword or PFS), we do the following:
- try findComponent
- fallback to invokeOnComponent
- if both returns null, we throw a "Can not find component ..."-Exception.

**Comment by BalusC** [comment]
Since Mojarra 2.2.5 and PrimeFaces 5.2 you can do this. So, not really a reason to add o:repeat.
