### ISSUE TITLE
[feature request] browser history management for ajax GET requests

### ISSUE THREAD

**Issue by Centaur** [omnifaces/omnifaces#107]
I am currently using ajax menu and `ui:include` to dynamically load partial views into some div in the main page (which is the mainstream navigation strategy nowadays). A badly-needed feature is to make `f:ajax` automatically manage browser history (using `#`) when doing ajax GET.  

I found [this blog](http://blog.hatemalimam.com/primefaces-hash-navigation-using-jquery-bbq/) but I guess this should be encapsulated into something more reusable. 

I don't have clear idea how the api should be like, maybe `<f:ajax hash="/target/page.jsf"/>`? When we click a button or link to trigger the action, the browser uri becomes `/mypage.xhtml/#/target/page.jsf`, and when we input this uri into address bar and hit enter, JSF should automatically trigger the ajax action after rendering the page . 

I am new to JSF and don't even know if this is possible.

With this implemented, maybe we can first ajaxify PrimeFaces Showcase and Omnifaces Showcase site whose current full-page-refresh behavior feels so 20th-century.

**Comment by BalusC** [comment]
As to the JSF ajax + hashbang, I've tossed around with this idea some years ago during the hashbang/shebang hype, but concluded it was impractical to properly deal with JSF view state during postbacks and have it populated in the hashbang fragment.

However, when used for pure ajax navigation purposes (absolutely no bean actions/listeners involved), it's in turn quite doable. I could think of an `<o:link update="...">` extending `<h:link>` with a fallback to synchronous GET in case of browsers not supporting window.history.

**Comment by Centaur** [comment]
But we do need actions/listeners to modify the "current selected" state of the link. Anyway, it is good to know one of the directions is not worth trying. Thanks a lot.

**Comment by BalusC** [comment]
Yes right, if it only performs the task which would have exactly the same effect as when doing a GET request, then it's affordable. This should only be carefully documented.

**Comment by Centaur** [comment]
For those who is seeking this kind of solution, [here](https://github.com/Centaur/jsf-ajax-navigation) is a small demo project that implement all desired behavior at page level. Navigations are all ajax with browser history updated/restored accordingly.  BTW, there is no doubt that Omnifaces is a must-have for JSF dev.
