### ISSUE TITLE
<o:ignoreValidationFailed> doesn't work in datatables or ui:repeat

### ISSUE THREAD

**Issue by joergmattes** [omnifaces/omnifaces#109]
I recently tried to use o:ignoreValidationFailed in a p:commandLink inside a p:datatable (trashcan to delete the row), but did not want to use immediately=true or process="@this". I thought I could use o:ignoreValidationFailed, but found out it doesn't work (although I use it successfully in other places).

Searching on stackoverflow, I found http://stackoverflow.com/questions/17471304/ignorevalidationfailed-doesn%C2%B4t-work-inside-uirepeat, where you suggest to create an issue.

My Omnifaces version: 1.8.1 (didn't find any hint that it's fixed in 2.0).

**Comment by BalusC** [comment]
It's fixed as part of `Components#hasInvokedSubmit()` which is available in 2.0 / 1.10. See also http://showcase.omnifaces.org/whatsnew and https://github.com/omnifaces/omnifaces/commit/9870108fdf6b2dec0f9c58e81ecac8f5c57051ec#diff-2e8c16ed625b52a0818c076e83869a91

**Comment by joergmattes** [comment]
Thank you, we'll upgrade to 1.10 then. Sorry I hadn't seen the Components#hasInvokedSubmit() fix.
