### ISSUE TITLE
BUG - of:formatPercent ignores fractional digits

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#110]
of:formatPercent ignores fractional digits.

#{of:formatPercent(0.123)} renders as 12% instead of 12.3%

See showcase http://showcase.omnifaces.org/functions/Numbers

**Comment by BalusC** [comment]
It formats in locale-default percent format. 

If you need a custom format pattern, use `#{of:formatNumber(number, pattern)}`.

**Comment by djmj** [comment]
Did not knew that the locale java format thinks fractional percentage values are uncommon.

What about a new fractuibak percent number format function?

I am no java Math and locale specialist but i created following function including a unit test that passes with wide range of inputs.

	public static String formatPercentFraction(final Number number)
	{
		if (number == null)
			return null;

		// get string representation with dot
		final String strNumber = NumberFormat.getNumberInstance(Locale.US).format(number.doubleValue());
		// create exact BigDecimal and convert to get scale
		final BigDecimal dNumber = new BigDecimal(strNumber).multiply(new BigDecimal(100));

		// test with german locale
		final NumberFormat percentScaleFormat = NumberFormat.getPercentInstance(Locale.GERMAN);
		percentScaleFormat.setMaximumFractionDigits(Math.max(0, dNumber.scale()));

		// convert back for locale percent formatter
		return percentScaleFormat.format(dNumber.multiply(new BigDecimal(0.01)));
	}

	@Test
	public void testFormatPercentScale()
	{
		final String exp1 = "0,1%";
		final String exp2 = "1%";
		final String exp3 = "1,5%";

		Assert.assertEquals(exp1, formatPercentFraction(0.001));
		Assert.assertEquals(exp2, formatPercentFraction(0.01));
		Assert.assertEquals(exp3, formatPercentFraction(0.015));

		Assert.assertEquals(exp1, formatPercentFraction(0.001f));
		Assert.assertEquals(exp2, formatPercentFraction(0.01f));
		Assert.assertEquals(exp3, formatPercentFraction(0.015f));

		Assert.assertEquals(exp1, formatPercentFraction(0.001d));
		Assert.assertEquals(exp2, formatPercentFraction(0.01d));
		Assert.assertEquals(exp3, formatPercentFraction(0.015d));

		Assert.assertEquals(exp1, formatPercentFraction(new BigDecimal("0.001")));
		Assert.assertEquals(exp2, formatPercentFraction(new BigDecimal("0.01")));
		Assert.assertEquals(exp3, formatPercentFraction(new BigDecimal("0.015")));

		Assert.assertEquals(exp1, formatPercentFraction(new BigDecimal(0.001)));
		Assert.assertEquals(exp2, formatPercentFraction(new BigDecimal(0.01)));
		Assert.assertEquals(exp3, formatPercentFraction(new BigDecimal(0.015)));

		Assert.assertEquals(exp1, formatPercentFraction(new BigDecimal(0.001f)));
		Assert.assertEquals(exp2, formatPercentFraction(new BigDecimal(0.01f)));
		Assert.assertEquals(exp3, formatPercentFraction(new BigDecimal(0.015f)));

		Assert.assertEquals(exp1, formatPercentFraction(new BigDecimal(0.001d)));
		Assert.assertEquals(exp2, formatPercentFraction(new BigDecimal(0.01d)));
		Assert.assertEquals(exp3, formatPercentFraction(new BigDecimal(0.015d)));

		// test with different scale
		final BigDecimal value1 = new BigDecimal(0.001f);
		value1.setScale(4, RoundingMode.HALF_UP);
		final BigDecimal value2 = new BigDecimal(0.01f);
		value2.setScale(4, RoundingMode.HALF_UP);
		final BigDecimal value3 = new BigDecimal(0.015f);
		value3.setScale(4, RoundingMode.HALF_UP);
		Assert.assertEquals(exp1, formatPercentFraction(value1));
		Assert.assertEquals(exp2, formatPercentFraction(value2));
		Assert.assertEquals(exp3, formatPercentFraction(value3));
	}
