### ISSUE TITLE
Expose coerceToType as el function

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#117]
# Specific bean population

I am saving key-value pairs in database to populate a bean of a specific class with values to reduce work in content management and since values are all saved as String's I need to coerce them back to their respective types in JSF view for proper displaying (locale aware numbers, percent, enums).

## JSF `coerceToType` function

    context.getApplication().getExpressionFactory().coerceToType()

## Example

    public PopulateData
    {
        private String value;
        private Class<?> type;
    }

    <h:outputText value="#{of:formatNumberDefault(of:coerceToType(bean.value, bean.type.name))}" rendered="#{of:isCoercePossible(bean.value, bean.type.name)}"/>
    <h:outputText value="#{bean.value}" rendered="#{not of:isCoercePossible(bean.value, bean.type.name)}"/>

## Request

Two functions like:

* `of:coerceToType(String value, Class type)`
* `of:coerceToTypeByClassName(String value, String type)`
* `of:isCoercePossible(String value, Class type)`
* `of:isCoercePossibleByClassName(String value, String type)`

In my use case the targeted parent class is known so i am right now using a dummy instance of a bean and use apache BeanUtils to populate it and get the converted values. 

But this is not possible in a generic key-value table where type informations could be stored in database, so this may be useful for others.

**Comment by BalusC** [comment]
Sorry, this doesn't solve a generic JSF problem, but an application-specific problem. I'd rather not via OmniFaces create the impression that it's "ok" to perform model's job in the view side.
