### ISSUE TITLE
ConcurrentLinkedHashMap --> Caffeine in OmniFaces 3.0

### ISSUE THREAD

**Issue by ben-manes** [omnifaces/omnifaces#121]
When transitions to requiring Java 8 please upgrade to [Caffeine](https://github.com/ben-manes/caffeine). The performance should be relatively the same and the per-instance memory usage should be smaller. I know this may be challenging due to embedding (rather than shading) the caching library. Another drawback is that the jar size is larger due to code generation, though that may be trimmed over time and usually is not a concern for server-side applications.

[ConcurrentLinkedHashMap](https://code.google.com/p/concurrentlinkedhashmap/) changes will continue to be minimal, even more so now, and driven by requests from Java 6 users unable to upgrade.

**Comment by BalusC** [comment]
Thank you for the hint! We'll keep this in mind when we move to Java 8 with OmniFaces 3.0 (not before JSF 2.3 is released).

**Comment by arjantijms** [comment]
To be clear, OmniFaces mostly aligns with a specific JSF version. OmniFaces 3 will align with JSF 2.3. JSF 2.3 will require Java 8, so naturally OmniFaces 3 will require Java 8 as well.

**Comment by BalusC** [comment]
While working on the migration to Caffeine 2.4.0, I noticed that it uses sun.misc.Unsafe directly, along with a comment that it will be removed in Caffeine 3.0.0. I'd therefore rather wait until Caffeine 3.0.0 is released.

**Comment by ben-manes** [comment]
Note that 3.0 will target JDK9 and migrate to VarHandles. I don't know if it will be a multi-release jar or a require a JDK upgrade.

CLHM embeds a copy of JDK8's back ported ConcurrentHashMap, which uses unsafe. For embedded usages one can remove switch back to the JDK's and Unsafe won't be used.

**Comment by BalusC** [comment]
The direct sun.misc.Unsafe usage is blocking me from embedding it in OmniFaces as I don't want to provide a library having JRE impl specific dependencies.

The embedded use case is strictly a LRU with strong values and an optional removal listener. In case of Caffeine, it boils down to LocalCacheFactory.SSLiMS (with an optional removalListener) and NodeFactory.SStM. I'm not seeing a clear way to substitute the ConcurrentHashMap here which forces me to keep using the CHLM, which I'll upgrade to latest version and remove the ConcurrentHashMapV8.

**Comment by ben-manes** [comment]
Just fyi that Caffeine 3 removed Unsafe by moving to a jdk11 baseline. That matches your v4, if I read the pom correctly. It’s a larger dependency due to more features, so you might prefer to ignore this and stay on the embedded CLHM as it seems to have worked out well.
