### ISSUE TITLE
jsf resource handler for resources outside of app with library lookup support

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#122]
A resource handler that allows resource not to be within webapp like the `CDNResourceHandler` behaved prior to 2.0 release.

There are several advantages:
- Migration from CDN to local resources or back is just a matter of moving resources (No code must be updated)
- JSF library mechanism for `h:outputScript` and other tags serves as single interface to obtain resources, regardless of their location
- Using library syntax the base url can be `hidden` since its defined in `web.xml` (more separation)
- Versioned resources can be declared without need of version number since `web.xml` decides which version to take.

This resource handler could have precedence over `CDNResourceHandler` or just be used in case no local resource was found.

**Comment by djmj** [comment]
Any love for this issue? Else i will extract `CDNResourceHandler` from version 1.8.1 and rename it before I update omnifaces to a current release.

**Comment by BalusC** [comment]
I looked at it several times during #27. Can't find a satisfiable solution without breaking resource handling and architectural design principles. Will look again for OmniFaces 2.3.

**Comment by djmj** [comment]
Thanks to let me know and for your work :) omnifaces rocks!

**Comment by BalusC** [comment]
As more and more people are asking for this, and I couldn't nicely implement https://github.com/omnifaces/omnifaces/issues/27, I've enhanced the CDNResourceHandler instead.
