### ISSUE TITLE
Separate non-JSF utility classes

### ISSUE THREAD

**Issue by eliandroribeiro** [omnifaces/omnifaces#123]
You have very nice utility classes, like JNDI, Servlets, HttpFilter and WebXml, that are not necessarily related to JSF.
Well, I'm in a REST project, now. Is there any chance of those classes to be in a separate jar?

**Comment by BalusC** [comment]
OmniFaces aims to be a single-JAR solution for JSF based web applications, so unfortunately it's for us not an option to split it into separate projects take this all into account. You're however free to fork and maintain it yourself while keeping the same Apache 2.0 license.
