### ISSUE TITLE
add 'autoRun' option to commandScript

### ISSUE THREAD

**Issue by kukel** [omnifaces/omnifaces#124]
Just like PrimeFaces has. This would make the [omnifaces example](http://stackoverflow.com/questions/16588327/how-to-invoke-a-jsf-managed-bean-on-a-html-dom-event-using-native-javascript) shorter

**Comment by BalusC** [comment]
I hesitated for long between "autorun" and "autoRun". While using p:remoteCommand myself so now and then, I remember to often have typo'ed "autorun", so I decided to stick to that.

It's available in today's 2.2 snapshot.
