### ISSUE TITLE
ResettableBufferedOutputStream doesn't reuse buffer

### ISSUE THREAD

**Issue by yate** [omnifaces/omnifaces#126]
I'm using GzipResponseFilter in my project and I noticed that large gzip responses were downloading slower than non gzip.  In ResettableBufferedOutputStream there is a line that sets buffer to null after the buffer is filled.  Since buffer is null on the subsequent writes, it writes a single byte at a time (the length is always 1 for me).   Should this not be changed to reset()?  After changing it to reset() it's downloading in the correct chunk sizes.
```
 public void write(byte[] bytes, int offset, int length) throws IOException {
        if (buffer != null) {
            writtenBytes += (length - offset);

            if (writtenBytes > bufferSize) {
                output.write(buffer.toByteArray());
                output.write(bytes, offset, length);
                buffer = null; // change to reset() ?
            } else {
                buffer.write(bytes, offset, length);
            }
        } else {
            output.write(bytes, offset, length);
        }
    }
```

**Comment by BalusC** [comment]
I see, the output.write(bytes, offset, length) on HttpServletResponseOutputWrapper is delegated to java.io.OutputStream.write() which in turn iterates over the array and then delegates further to output.write(b) which ends up being delegated further to the above method with length=1. I fixed it by not letting the code delegate to java.io.OutputStream anymore.

**Comment by BalusC** [comment]
The fix is available in todays [2.1 snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.1-SNAPSHOT/). Can you give it a try?

**Comment by yate** [comment]
Hi BalusC, thanks for looking into this.  I'm still having speed issues with the fix applied.  I'm just using wget to hit my service locally and looking at the download speed, hopefully that's enough to show the problem.  Let me know if you need more information.

No GZIP **23.8M/s   in 0.8s**
```
[n0210015@VDDP13C-FBA8289 ~] $ wget localhost:9080/services/endpoint
--2015-05-05 11:06:18--  http://localhost:9080/services/endpoint
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: \u201cindex.html.1\u201d

    [    <=>                                                                                                                                    ] 19,519,762  23.8M/s   in 0.8s    

2015-05-05 11:06:38 (23.8 MB/s) - \u201cindex.html.1\u201d saved [19519762]
```
GZIP **582K/s   in 1.2s**
```
[n0210015@VDDP13C-FBA8289 ~] $ wget --header='Accept-Encoding: gzip' localhost:9080/services/endpoint
--2015-05-05 11:06:54--  http://localhost:9080/services/endpoint
Resolving localhost... 127.0.0.1
Connecting to localhost|127.0.0.1|:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: \u201cindex.html.2\u201d

    [      <=>                                                                                                                                  ] 731,773      582K/s   in 1.2s    

2015-05-05 11:07:13 (582 KB/s) - \u201cindex.html.2\u201d saved [731773]
```

**Comment by BalusC** [comment]
I see. This is more related to the overhead of performing the job at localhost. The very same CPU has to zip and unzip (and chunk/dechunk) all the thing and there's basically no network overhead. I'm observing the same. However, when it's actually on the other end of network, then GZIP clearly shows an decrease in total time as the total network bandwidth decrease is at a much higher ratio than the speed decrease.

**Comment by yate** [comment]
What kind of speed decrease are you seeing?  I tried wget on another machine and I'm seeing almost the same download speed drop as before, although the gzip response did finish faster
```
$ wget dev-machine:9080/services/endpoint
--2015-05-08 10:44:05--  dev-machine:9080/services/endpoint
Connecting to dev-machine:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: ‘index.html’

index.html                             [              <=>                                                 ]  
18.62M  6.73MB/s   in 2.8s

2015-05-08 10:44:35 (6.73 MB/s) - ‘index.html’ saved [19519762]


n0210015@machine ~
$ wget --header='Accept-Encoding: gzip' dev-machine:9080/services/endpoint
--2015-05-08 10:44:44--  dev-machine:9080/services/brk/v1/endpoint
Connecting to dev-machine:9080... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/xml]
Saving to: ‘index.html.1’

index.html.1                           [       <=>                                                        ] 
714.62K   517KB/s   in 1.4s

2015-05-08 10:45:06 (517 KB/s) - ‘index.html.1’ saved [731773]
```

Something I'm noticing when I step through the code is that the first time it hits the `write(byte[] bytes, int offset, int length)` method in ResettableBufferedOutputStream, it writes it to the buffer.  Only when it exceeds the buffer size does it call `output.write()`.  Each time after that it always writes directly to the `output` without writing anything to the buffer (since the buffer was set to null).  I'm also seeing the length of the write alternate between high values like 1022 or 1023 and small values like 18 or 5.  Could either of those be causing this as well?

**Comment by BalusC** [comment]
It went from MBs to KBs. As to the writes, this all really depends on the underlying OutputStream. If you have control over that, consider wrapping it in a BufferedOutputStream with a "large" buffer.

The ResettableBufferedOutputStream is just there to prevent auto-commits caused by explicit flushes while not having exceeded the JSF- or server-configured buffer size.
