### ISSUE TITLE
Ajax.updateRow error in Primefaces datatable with paging

### ISSUE THREAD

**Issue by GithubJohn3031** [omnifaces/omnifaces#127]
Ajax.updateRow has problem with Primefaces datatable component, if paging is activated. The row will not be updated if it is on page with number `>1`. I reckon it is some problem with primefaces incompatibility get.Rows() and table.getRowCount() and standard JSF Table component.

Relevant code snippet from Omnifaces Ajax.updateRow():

    int rowCount = (table.getRows() == 0) ? table.getRowCount() : table.getRows();
    if (index >= rowCount) {
      return;
    }

We fixed it locally (comment out this code part), but it would be cool to fix it for future Omnifaces versions.
As far as I know Primefaces 5.2 has this feauture already and permits to update the specific row.

**Comment by BalusC** [comment]
Makes sense.

**Comment by BalusC** [comment]
Fix is present in today's 2.2 snapshot. Thank you for reporting!
