### ISSUE TITLE
FacesConfigXML - retrieve welcome files

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#128]
Retrieve list of welcome files. This is usefull if programmatic redirects shall be done to main page. For instance in a login filter or redirection on failed validations.

**Comment by BalusC** [comment]
Welcome files are specified in web.xml, not faces-config.xml. OmniFaces has already a WebXml for that: http://omnifaces.org/docs/javadoc/2.0/org/omnifaces/config/WebXml.html

    List<String> welcomeFiles = WebXml.INSTANCE.getWelcomeFiles();

**Comment by djmj** [comment]
Oh sorry mixed things up.
