### ISSUE TITLE
Let o:tree behave as a Tag Handler

### ISSUE THREAD

**Issue by degenerinfosim** [omnifaces/omnifaces#129]
Using o:tree the var attribute always resolves to null when combining it with a TagHandler like c:choose. It would be great if the o:tree would work like a TagHandler in this respect so one can use the c tags. At the moment the only solution for me is using the "rendered" attribute of the components that I want to render based on some conditions of the var attribute.

**Comment by BalusC** [comment]
I disagree. The main purpose of `<o:tree>` is to render HTML based on a dynamic data model, possibly prepared/updated during a JSF action, not to build the view based on a data model which is required to be already prepared during bean's construction. If it were a tag handler, the showcase example wouldn't work without additional hacks.

Using `rendered` attribute is the correct approach to conditionally render HTML.
