### ISSUE TITLE
Using quotes in #{of:format1(string, param)}

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#130]
I did these tests:

1. #{of:format1('\'{0}\'', 'test')}
2. #{of:format1('\'\'{0}\'\'', 'test')}

Results were:

1. {0}
2. 'test'

Is that expected behaviour? I expected the results to be:

1. 'test'
2. ''test''

**Comment by jepsar** [comment]
Had a look at the source and found the reason for this behaviour. http://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html is used:

    Within a String, a pair of single quotes can be used to quote any arbitrary characters except single quotes. For example, pattern string "'{0}'" represents string "{0}", not a FormatElement. A single quote itself must be represented by doubled single quotes '' throughout a String. For example, pattern string "'{''}'" is interpreted as a sequence of '{ (start of quoting and a left curly brace), '' (a single quote), and }' (a right curly brace and end of quoting), not '{' and '}' (quoted left and right curly braces): representing string "{'}", not "{}".

Maybe an idea to add link in the documentation?

**Comment by BalusC** [comment]
Better now? Fix is present in today's 2.2 snapshot (to me, javadoc with link appears in EL complete in Eclipse).

![image](https://cloud.githubusercontent.com/assets/173372/8669088/baa51612-2a11-11e5-8080-c395a20dd00f.png)

**Comment by jepsar** [comment]
Indeed! Thank you :-)

**Comment by BalusC** [comment]
Thank you for reporting and improving OmniFaces!
