### ISSUE TITLE
Disturbing debug messages with Mojarra 2.2.11

### ISSUE THREAD

**Issue by stephanrauh** [omnifaces/omnifaces#135]
In our BootsFaces showcase project, I've observed a debug log message on the console that reads like a memory leak. After long hours of debugging, I've come to believe this might be a side-effect of the CombinedResourceHandler of OmniFaces. OmniFaces replaces a couple of resource components by another component, but there seems to be a copy of the original component list, which still contains the ids of the no-longer-existing resource components. As a result, this log message is printed on AJAX postbacks:
```
Mai 24, 2015 9:30:28 PM com.sun.faces.application.view.FaceletPartialStateManagementStrategy saveDynamicActions
WARNING: Unable to save dynamic action with clientId 'j_id190' because the UIComponent cannot be found
```
The error message is suppressed in production mode, but I'm not sure whether it's harmless or a memory leak.

Did you see this message before?

**Comment by BalusC** [comment]
Indeed, they appear only in Mojarra in development stage (not in MyFaces nor Production). This is technically harmless, but I understand it's disturbing and confusing.

I could workaround it by calling `resourceToRemove.setInView(false);` right before `view.removeComponentResource(context, resourceToRemove, target);` in the `removeComponentResources()` method. However, I can't tell if this would be free of side effects, in any edge case. I'd rather not implement this so shortly before OmniFaces 2.1 release and also discuss about this with Arjan / Manfred.

**Comment by stephanrauh** [comment]
Well, now that I know it's technically harmless, I'm going to document this behavior in the BootsFaces showcase and stop worrying about it. I already started to suspect its harmless, but it's good to read your confirmation. I guess there's no hurry, fixing the ~~bug~~ nuisance in OF 2.2 is fine by me.

**Comment by BalusC** [comment]
I'm not seeing any other ways to suppress this warning. I'm going for the UIComponent#setInView(false) trick. The workaround is available in today's latest snapshot. We will test it on a.o. ZEEF and see if it doesn't cause any side effects.

**Comment by BalusC** [comment]
Works perfectly fine so far. Closing off.

**Comment by stephanrauh** [comment]
Thanks!
