### ISSUE TITLE
Minify Resources in CombinedResourceHandler

### ISSUE THREAD

**Issue by MSzturc** [omnifaces/omnifaces#137]
To improve the page speed even more we use YUI Compressor in our maven build to minify scripts and stylesheets on build. I would like to request this minify functionality for CombinedResourceHandler since it would fit perfectly in the focus of the CombinedResourceHandler.

**Comment by BalusC** [comment]
I understand that, but that's not the primary focus of CombinedResourceHandler and it would also be rather expensive to minify the resources on every request (leaving caching outside consideration). Minification does also not require a JSF specific API, which gives you the freedom to choose the desired library. You can just combine the both techniques. Just run minify during build and the CombinedResourceHandler will just combine those already-minified resources.

For ZEEF.com we use http://samaxes.github.io/minify-maven-plugin and it works flawlessly this way.

**Comment by BalusC** [comment]
Wontfix for reason in previous comment.
