### ISSUE TITLE
apply attribute conditionnaly

### ISSUE THREAD

**Issue by xqvier** [omnifaces/omnifaces#138]
HI,

I don't know if it can be of any use but i came onto an issue with a primefaces' components and i used a little trick rewriting the AttributeTagHandler from mojarra jsf impl. I don't know if you wan't to include it in your library as, in my knowlege, it only resolves this particular issue but it could come handy.

# TLDR
I rewrote the com.sun.faces.facelets.tag.jsf.core.AttributeHandler to add the attribute "applied" as to know when to apply an attribute logically. If you want it, how can I share it with you ?

# The need 
### Basic
I wanted to have a list who could have, depending on a functionnal algorithm, either a single selection or a multiple selection.
On primefaces the attribute selectionMode can take 2 arguments : "single" or "multiple"

### Further into the need (ergonomy strikes)
The fact is that, in term of ergonomy, i needed to make 2 cases :
* multiple selection with a first column checkbox
* single selection with no first colum but clickable row

The solution for each case then were :
* multiple selection : use a `<p:column selectionMode="multiple" />` 
* single selection : add the attribute selectionMode="single" within the dataTable component.

# The issue

In my case i wished to use this code (simplified):
```
<p:dataTable selectionMode="#{bean.selectionMode eq 'single' ? bean.selectionMode : '' } >
    <p:colum selectionMode="multiple" rendered="#{bean.selectionMode eq 'multiple' }" />
<p:dataTable> 
```

in multiple selection, i came accross the issue that primefaces set the selectionMode attribute to single when left to blank and causing it to don't work as it was single selection and multiple selection at the same time.

# The solution
What i was needed is to set an attribute to a component conditionnaly.
The standard `<f:attribute />` could not do the trick as i couldn't apply it only when i chose single selection.

What i did is : 
create a new tag attribute (within my namespace) and just program a new TagHandler (mostly copy /pasted from com.sun.faces.facelets.tag.jsf.core.AttributeHandler) and adding the attribute "applied" who could take a logical ValueExpression so it would be applied (and unapplied - for ajax request) only when needed.

# Conclusion

I'd like to share this with you guys so you can see if it's worth it and if you'd like to add it to omnifaces.

Regards,

And sorry for the grammatical english errors

**Comment by BalusC** [comment]
You could theoretically use JSTL for this.

```
<p:dataTable>
    <c:if test="#{bean.selectionMode eq 'single'}"><f:attribute name="selectionMode" value="single"/></c:if>
    <p:column selectionMode="multiple" rendered="#{bean.selectionMode eq 'multiple' }" />
<p:dataTable> 
```
Does that also work for you?

**Comment by xqvier** [comment]
I tried this one. In this case it wasn't reapplied on ajax request. 

the attribute was still set on the component. 

Probably I didn't understand something about how the tree view is rebuilt with JSTL but i think it's not correctly rebuilt from scratch. (i mean not starting back with 0 attributes set and not interpreting the jstl again)
