### ISSUE TITLE
Add PageableDataModel

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#14]
https://code.google.com/p/omnifaces/issues/detail?id=197
http://wiki.apache.org/myfaces/WorkingWithLargeTables

**Comment by JaXt0r** [comment]
Unfortunately your first issue-link is broken. Also: can you provide more information on how the feature shall work like? Maybe kind of endless scroller?
Would be glad to deliver a first prototype if feature is still wanted.

**Comment by BalusC** [comment]
Original issue was just a kind request if something like as provided in Apache link (abstract DataModel implementation with pagination support) could be added to OmniFaces.

**Comment by BalusC** [comment]
+sorting +filtering

**Comment by BalusC** [comment]
PrimeFaces did much of great work already. I'd rather not reinvent it but instead just enhance it further. As consequence, subproject OptimusFaces has started: https://github.com/omnifaces/optimusfaces
