### ISSUE TITLE
ListConverter doesn't take in count target list while converting

### ISSUE THREAD

**Issue by Janario** [omnifaces/omnifaces#142]
In showcase http://showcase.omnifaces.org/converters/ListConverter
Select in picklist Amsterdam and click in Select. It shows "Selected items: Amsterdam".  Ok
But clicking again it shows "Selected items: [no selection made]"  and Amsterdam is not showed anymore in the picklist

This happens because the converter is using only the source from DualModel, It should try from target and source:
list="#{bean.dualListModel.source}"

**Comment by BalusC** [comment]
Fixed on showcase : https://github.com/omnifaces/showcase/commit/b42b7bd11f2a015441c367e987759be9058b68ee

Thanks for reporting! For future issues with showcase, you you please report at showcase repo? https://github.com/omnifaces/showcase/issues
