### ISSUE TITLE
org.jboss.weld.exceptions.AmbiguousResolutionException in subclassed @FacesConverter in conjunction with <f:convertDateTime>

### ISSUE THREAD

**Issue by vmuth85** [omnifaces/omnifaces#146]
Using the &lt;f:convertDateTime  /&gt; tag in conjunction with subclassed Converters causes
 an org.jboss.weld.exceptions.AmbiguousResolutionException. To be more precise, create a @ViewScoped CDI Bean, TestBean for instance.

``` 
import java.io.Serializable;
import java.util.Date;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class TestBean implements Serializable{
    
    private static final long serialVersionUID = 1L;
    
    /**
     * @return no magic, just the current date
     */
    public Date getCurrentDate() {
        return new Date();
    }
}
```

Add the converters to your project.
```
@FacesConverter("relativeDateConverter")
public class RelativeDateConverter extends DateTimeConverter {
    // No implemenation necessary, this is enough for causing the error
}
```
```
@FacesConverter("yearConverter")
public class YearConverter extends RelativeDateConverter {
    // No implemenation necessary, this is enough for causing the error
}
```
And the according HTML snippet.
```
    <h:body>
        <h:form>
            <h1>Test PAGE</h1>
			
			<!-- works just fine -->
			<h:outputText value="#{testBean.currentDate}" />

			<!-- causes the exception -->
            <h:outputText value="#{testBean.currentDate}">
                <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
            </h:outputText>
            
        </h:form> 
    </h:body>
```

Adding the  <f:convertDateTime pattern="dd.MM.yyyy HH:mm" /> tag will lead to 

> WELD-001318 Cannot resolve an ambiguous dependency between [Managed Bean [class de.test.YearConverter] with qualifiers [@Any @Default], Managed Bean [class de.test.RelativeDateConverter] with qualifiers [@Any @Default]]

Environment:
- GlassFish Server Open Source Edition 3.1.2.2 (build 5)
- Mojarra 2.2.10
- WELD-000900 1.1.8 (Final)

Same procedure with
- GlassFish Server Open Source Edition 4.1 (build 13)
- Mojarra 2.2.10
- WELD-000900: 2.2.14 (Final)

**Comment by BalusC** [comment]
Can't reproduce on WildFly 9.0.0 in its default trim (it's using Mojarra 2.2.11 and Weld 2.2.14).

How does your beans.xml look like?

**Comment by vmuth85** [comment]
<code>
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://java.sun.com/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/beans_1_0.xsd">
</beans>
</code>

Keeping the beans.xml empty also doesn't fix the issue.

**Comment by vmuth85** [comment]
bean-discovery-mode="annotated" did the trick!
<code>
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://xmlns.jcp.org/xml/ns/javaee"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee 
		http://xmlns.jcp.org/xml/ns/javaee/beans_1_1.xsd"
       bean-discovery-mode="annotated">
</beans>
</code>

**Comment by vmuth85** [comment]
Have the same issue with your configuration  (WildFly 9.0.0 ). To reproduce the error I published the application on https://github.com/vmuth85/TestApp

**Comment by BalusC** [comment]
This can be solved by using `@Specializes` annotation on the subclass, while keeping `bean-discovery-mode="all"`.

**Comment by BalusC** [comment]
I updated javadocs of FacesConverter/FacesValidator to cover potential troubles.

Thank you for reporting and the reproducer! It was helpful.
