### ISSUE TITLE
Add two utility methods, one that includes a view into the response right away, while another captures the output to a String. One step further and we may give it a prefabricated (newly instantiated/fake) request/response (if possible)

### ISSUE THREAD

**Issue by AnghelLeonard** [omnifaces/omnifaces#149]

**Comment by BalusC** [comment]
Not sure if I understand the first part. There's `Components#includeFacelet()` which allows programmatic inclusion of a Facelet.

Second part is sound.

**Comment by BalusC** [comment]
Hm, I initially understood/guessed something like 

```
UIViewRoot view = Components.build("emailtemplate.xhtml");
String html = Components.encode(view);
```

Which I think is indeed useful. 
The servlet example in the idea doesn't look terribly useful.

**Comment by AnghelLeonard** [comment]
"The servlet example in the idea doesn't look terribly useful."
Bad ideas must go to trash! So, just ignore it. 


     On Monday, August 31, 2015 10:11 PM, Bauke Scholtz <notifications@github.com> wrote:
   

 Hm, I initially understood/guessed something like UIViewRoot view = Components.build("emailtemplate.xhtml");
String html = Components.encode(view);
Which I think is indeed useful. 
The servlet example in the idea doesn't look terribly useful.—

**Comment by BalusC** [comment]
New feature is available in today's latest snapshot.
