### ISSUE TITLE
Add <o:lazyPanel>

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#15]
https://code.google.com/p/omnifaces/issues/detail?id=250

Something like `<p:outputPanel deferred="true">` but then using standard JSF ajax API and with the possibility to show via JS API instead of during onload.

**Comment by Rapster** [comment]
I woud really appreciate such component, I tried to make my own (defined as a facelet tags so it can be reusable in the same view):

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:sf="http://www.spark-archives.com/ui"
                xmlns:o="http://omnifaces.org/ui">

    <o:tagAttribute name="id" />

    <h:panelGroup id="#{id}">
        <ui:fragment rendered="#{viewScope[id] eq true}">

            <ui:insert />

        </ui:fragment>
    </h:panelGroup>

    <o:commandScript name="func_#{id}"
                     render="#{id}"
                     autorun="true"
                     action="#{viewScope.put(id,'true')}" />

</ui:composition>
```

First, doing this, I have an exception:

```
java.lang.NullPointerException: null
	at org.apache.el.parser.AstValue.convertArgs(AstValue.java:266)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:243)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at javax.faces.component.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:87)
	at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
	at org.primefaces.application.DialogActionListener.processAction(DialogActionListener.java:46)
	at javax.faces.component.UICommand.broadcast(UICommand.java:315)
```

It seems, it can't find put method... I guess the map is Map<String, Object> while I'm passing a String and a Boolean.

Second, instead of action I used f:setPropertyActionListener but it does seem to be called at all. Could it be an issue with `o:commandScript`?

**Comment by Rapster** [comment]
Here is a workaround:

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:sf="http://www.spark-archives.com/ui">

    <o:tagAttribute name="id"/>

    <o:commandScript autorun="true" render="lazy_#{id}">
        <f:setPropertyActionListener value="true" target="#{viewScope[id]}" />
    </o:commandScript>

    <h:panelGroup id="lazy_#{id}">
        <ui:fragment rendered="#{viewScope[id] ne null}" >
            <ui:insert />
        </ui:fragment>
    </h:panelGroup>
</ui:composition>
```

It's not the best option, creating a custom component would certainly be better, less fiddling and more performant

**Comment by og-zyos** [comment]
@Raspter. Do you have the full implementation?

**Comment by Rapster** [comment]
My impl is not really clean, it's a mix of PF and OF... Though I fixed an important issue on `p:outputPanel` of PF. So if you have PF in your app, you should have a look on this component

**Comment by og-zyos** [comment]
Yes, I have PF 7 + OF 3.7

**Comment by Rapster** [comment]
If you can upgrade PF 8.0 using deferred option that would be the best option, it contains a big fix https://github.com/primefaces/primefaces/issues/3815

**Comment by jepsar** [comment]
In PrimeFaces 11, you can use the Ajax `load` event with `p:outputPanel deferred="true"`. For example:
```xhtml
<p:outputPanel deferred="true">
    <p:ajax event="load" listener="#{bean.loadData}"/>
    <f:facet name="loading">
        <p:skeleton width="200px" height="21px" class="p-mb-4"/>
        <p:skeleton width="100%" height="63px"/>
    </f:facet>
    <h5>#{bean.data.title}</h5>
    <p>#{bean.data.body}</p>
</p:outputPanel>
```

**Comment by melloware** [comment]
@BalusC I think this one is safe to close as you posted a workaround and now PrimeFaces has this in its `outputPanel`

**Comment by pizzi80** [comment]
at some point in the future....

[https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility](url)

**Comment by BalusC** [comment]
Agreed.

**Comment by pizzi80** [comment]
which is the most "performant" and/or "best practice" solution without PrimeFaces ?
the @BalusC one or the @Rapster one?

the loading function could be called with an IntersectionObserver,
in this way it will be deferred and lazy loaded ...

it would be nice to add this implementation
in OmniFaces or in BalusC blog or in BalusC next book ( ... ? )

thanks

**Comment by Rapster** [comment]
I wouldn't rely on my solution tbh, I didn't do a lot of testing

**Comment by BalusC** [comment]
o:lazyPanel has been added for 5.3

**Comment by Rapster** [comment]
Great news! I've been waiting for this one for a long time! Thank you @BalusC !
