### ISSUE TITLE
Messages could inform if there are error messages added

### ISSUE THREAD

**Issue by ramonchiara** [omnifaces/omnifaces#157]
Sometimes I have to do some validation in action method.
So, after validations, I'd like to know if there were any messages added.
The feature could check globally or for some specific cliendId.

**Comment by BalusC** [comment]
The `<o:messages>` already supports it.

Check the "Displaying single message" case in http://showcase.omnifaces.org/components/messages

The client ID can be the form itself for a "global" check.

**Comment by ramonchiara** [comment]
Probably I didn't make myself clear...
The problem is when I have to test if there were some message added in the action method of a back bean.
Example:

```
pubic void action() {
   if (...) {
      Messages.add...
   }
   if (...) {
      Messages.add...
   }
   ...

   // problem is here
   if (!Faces.getContext().getMessageList().isEmpty()) {
      return null;
   }

  ...
}
```
I would like to do something like:

```
if (Messages.isNotEmpty()) {
    return null;
}
```

**Comment by BalusC** [comment]
I see. Thank you for clarifying.

**Comment by BalusC** [comment]
New methods are available in [today's snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.2-SNAPSHOT/).

**Comment by ramonchiara** [comment]
Cool!!! :-)
