### ISSUE TITLE
Add support for Spring DI

### ISSUE THREAD

**Issue by slavus** [omnifaces/omnifaces#158]
I would like to have support  for Spring DI instead CDI. Most of my applications use Spring as DI, after 2.x version Omnifaces can't be used with Spring and it does not make sense to use two different DI in one application.

**Comment by BalusC** [comment]
JSF itself is moving to CDI as standard DI API. JSF 2.3 will have CDI as required dependency. Spring DI is going to (partially) implement CDI API. An optional CDI dependency is troublesome as to maintenance and compatibility across all containers. We wasted quite a lot of time on that during OmniFaces 1.x. For mainly those reasons, OmniFaces 2.x started to require CDI, hereby simplifying development and less or more forcing users to prepare for the right long term path.
