### ISSUE TITLE
FullAjaxExceptionHandler, rendering of an error page on ajax exception gives JS warning.

### ISSUE THREAD

**Issue by mikhailChibel** [omnifaces/omnifaces#159]
Hi, 
I'm trying to use FullAjaxExceptionHandler exception handler to show an error page to the user on AJAX exception and I'm facing some issues. The server response results in an JS error and also I can see a warning message in the browser's console <i>'XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.'</i> 

I dig into the JS error and found that it caused by an attempt to reload Primefaces javascript and has been fixed in Primefaces version 5.2.2. (https://github.com/primefaces/primefaces/pull/143). However, the problem seems a bit more complicated. Switching to the latest version of PF eliminates the JS error, but the page is not usable after it has been loaded. First click on any components doesn't trigger the action on the server. Looks like the page has invalid ViewState, but I'm not sure.

Do you have any idea how the error page could be rendered in other way which will not screw JSF up? (tested on Mojarra 2.2.8)

![image](https://cloud.githubusercontent.com/assets/8921222/9346627/77a4981e-4673-11e5-95f9-030754b4fd31.png)

The issue is reproducible on Omnifaces showcase website at http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler, to reproduce it just click on  "throw runtime exception on ajax request" button. 

Thanks

**Comment by BalusC** [comment]
The warning needs to be fixed on Mojarra side as it's the one responsible for handling the ajax response. You'd best report it to Mojarra guys.

The error needs to be fixed on PrimeFaces side as you already figured out.

The non-working form is because the form submit points to the error page location which is not public. Just don't put any forms in the error page. If it are navigation links/buttons, then you should in first place not use POST for this.

**Comment by mikhailChibel** [comment]
I think the issue is not only that error page location is private, In my case it is not private, but JSF seems confused with page content doesn't match the page location. I'm looking into it, but wasn't able to figure out whats going on. Seems like, after all, it is not a good idea for me to render error page content into the same page.  Anyway thanks for clarification.

**Comment by BalusC** [comment]
Ah, I now get what you mean. The view state problem is most likely fixable by http://showcase.omnifaces.org/scripts/FixViewState

As to JS warning on Mojarra side, I've yesterday fixed it: https://java.net/jira/browse/JAVASERVERFACES-4024

**Comment by BalusC** [comment]
Closing off.
