### ISSUE TITLE
Enhance Xml parsing to support XML ENTITY declartions

### ISSUE THREAD

**Issue by thomaswoeckinger** [omnifaces/omnifaces#160]
Currently org.omnifaces.util.XML.parseAndAppendChildren(...) uses only the given InputStream.
Therefore it is not possible to use enhanced XML ENTITY declaration during parsing, so an exception will be thrown.

This could be easily done by check if the giver URL is absolute and use InputSource as parameter for the parser.

The implementation could be following:

```java
public static void parseAndAppendChildren(DocumentBuilder builder, Document document, List<URL> urls) throws IOException, SAXException {
		for (URL url : urls) {
			if (url == null) {
				continue;
			}

			boolean absolute = false;
			try {
				absolute = url.toURI().isAbsolute();
			} catch (final URISyntaxException e) {
				// noop
			}

			Document sourceDocument;

			try (InputStream input = url.openStream()) {

				if (absolute) {
					final InputSource source = new InputSource(url.toExternalForm());
					source.setByteStream(input);
					sourceDocument = builder.parse(source);
				} else {
					sourceDocument = builder.parse(input);
				}

				final NodeList children = sourceDocument.getDocumentElement().getChildNodes();

				for (int i = 0; i < children.getLength(); i++) {
					document.getDocumentElement().appendChild(document.importNode(children.item(i), true));
				}
			}
		}
	}
```

**Comment by BalusC** [comment]
What is the use case? The Xml utility class is kind of for internal usage only. It's not listed on showcase and OmniFaces is not intented to be used as a Xml parser library.

If it solves a problem caued by JSF or OmniFaces, then I will of course fix it, but I'm as of now not seeing it.

**Comment by thomaswoeckinger** [comment]
It's particular useful when using XML Entity References to include common parts into the web.xml.

Example give: 

```
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE web-app
[
  <!ENTITY web-login-config SYSTEM "web-login-config.xml">
]>
<web-app xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd" version="3.0" metadata-complete="true">

	<display-name>MyWebApp</display-name>

	<welcome-file-list>
		<welcome-file>index.jsf</welcome-file>
	</welcome-file-list>

	&web-login-config;

	<absolute-ordering></absolute-ordering>
</web-app>
```
and the web-login-config.xml
```
<login-config>
	<auth-method>FORM</auth-method>
	<realm-name>Secure Area</realm-name>
	<form-login-config>
		<form-login-page>/tiles/login/login.jsp</form-login-page>
 		<form-error-page>/tiles/login/error.jsp</form-error-page>
	</form-login-config>
</login-config>
```

**Comment by BalusC** [comment]
You're basically utilizing a Tomcat specific security hole which should never have been possible in first place and isn't necessarily portable to other servers. Here's the related security report: https://bugzilla.redhat.com/show_bug.cgi?id=1069911 This security hole was fixed in Tomcat 6.0.39, Tomcat 7.0.50, and Tomcat 8.0.0-rc10.

I don't like giving a signal that OmniFaces implicitly supports this security hole by fixing the XML parser.

**Comment by thomaswoeckinger** [comment]
This is not the case because it was limited to scan external resource and not local one!

The resource is local and not from an external URL!

**Comment by thomaswoeckinger** [comment]
The fix was that external URLs cannot be used. Which was an security hole.

**Comment by BalusC** [comment]
I tried to reproduce it, but I couldn't because the given configuration didn't work for me on 8.0.24.

**Comment by thomaswoeckinger** [comment]
It seems that the configuration changed again in 7.0.52 and 8.0.23, now xmlBlockExternal must be set to false, which disables Entity References in general not only the external one.

So I agree with you that this is not possible without open a security hole.

Thx for your time.
