### ISSUE TITLE
Missing link to sonatype snapshot site

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#161]
I am missing link to sonatype snapshot site on omnifaces homepage. Had to google to find it.

**Comment by arjantijms** [comment]
There are actually 2 sonatype URLs:

* https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/org/omnifaces/omnifaces
* https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/

I'll add them both, thanks for the suggestion!

**Comment by BalusC** [comment]
Second one is most relevant, I've further improved the section in homepage, along with a maven coordinate ready for copypaste.
