### ISSUE TITLE
post method in form stops working after enabling FacesViews on /*.xhtml

### ISSUE THREAD

**Issue by guisilver** [omnifaces/omnifaces#169]
I noticed that "Post" method in a form stops working when i put the following code in the web.xml:

	<context-param>
		<param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
		<param-value>/*.xhtml</param-value>
	</context-param>

**Comment by BalusC** [comment]
Works for us. How can we reproduce this when starting from scratch?

**Comment by guisilver** [comment]
Hello BalusC, thanks for the reply.
I have a jsf 2.2 web application running on tomcat 7 and java 7.
I have to pass data from a simple html page to the jsf web app, so a made a form like this:

<form method="post" action="localhost:8080/MyApplication"> 
     <input type="hidden" name="age" value="24" />
</form>

Then I try to get the values like this in a ViewScoped managed bean:

Map<String,String> params = 
                FacesContext.getExternalContext().getRequestParameterMap();
	  String age = params.get("age");

But the params come null.
Thanks for the help \o.

**Comment by BalusC** [comment]
It appears that you're submitting to the webapp root `/`, which would in turn thus point to the resource identified by `<welcome-file>` entry in `web.xml`. If you have specified e.g. `index.xhtml` as `<welcome-file>`, then FacesViews will **redirect** to to `/index`, hereby basically creating a new GET request and thus trashing all POST parameters.

This is already documented in [FacesViews documentation](http://omnifaces.org/docs/javadoc/2.1/org/omnifaces/facesviews/package-summary.html):

> ### Welcome files

> If a `<welcome-file>` is defined in `web.xml` that's scanned by FacesViews AND `REDIRECT_TO_EXTENSIONLESS` is used (which is the default, see below), it's necessary to define an extensionless welcome file to prevent a request to `/` being redirected to `/[welcome file]`. E.g. without this `http://example.com` will redirect to say `http://example.com/index`.

> For example:

> ```XML
>     <welcome-file-list>
>         <welcome-file>index</welcome-file>
>     </welcome-file-list>
> ```
 
So, if you fix your `<welcome-file>` to strip off the extension, then it must work for you.
