### ISSUE TITLE
Mime Type - application/xhtml+xml

### ISSUE THREAD

**Issue by echer** [omnifaces/omnifaces#170]
Im using org.omnifaces.resourcehandler.CombinedResourceHandler to combine me resources, but when i enable this the response header of request is "application/xhtml+xml", and resource not loaded correctly. The file extension is css.xhtml. =/

Remote Address:127.0.0.1:8080
Request URL:http://localhost:8080/javax.faces.resource/eNqtT0sOgjAQPVFbgzsPYFyaeIKhDqTazmA7TSTx8BIQFgLqwk1n-j6T92xOwmFnbEomgGB04FXFJDo40h36sAuKj6QawElTey7B70zjc-0omUyu4hh6z2vXZ6wge1n1lMySJELTu6bfLMdMr4ShW8wwFnNn6t4DBzxCjd8TqIQercyAVedAF-P8VacCSmRydrWkY9IRqMaTd2eMqtAbve0rvTF_uJCujvYe1ltWQLYt-W4S52jRXG4ZY6tHePQ9AeJM7sE.css.xhtml;jsessionid=q0O9JqdwEifEbT8xs3ZBwKZNAcahrRY0hBxQ3mSh.echer-aspire-5742?ln=omnifaces.combined&v=1443726922000
Request Method:GET
Status Code:200 OK

Request Headers
Accept:text/css,*/*;q=0.1
Accept-Encoding:gzip, deflate, sdch
Accept-Language:pt-BR,pt;q=0.8,en-US;q=0.6,en;q=0.4
Cache-Control:no-cache
Connection:keep-alive

Response Headers
Connection:keep-alive
Content-Type:application/xhtml+xml
Date:Thu, 01 Oct 2015 21:51:28 GMT
Etag:W/"1932806804-1443726922000"
Expires:Thu, 08 Oct 2015 21:51:28 GMT
Last-Modified:Thu, 01 Oct 2015 19:15:22 GMT
Pragma:
Server:WildFly/9
Transfer-Encoding:chunked
X-Powered-By:Undertow/1

**Comment by BalusC** [comment]
This is not the default behavior. Did you change anything in web.xml as to `<mime-mapping>`?

**Comment by echer** [comment]
My faces-config have

<resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>
<resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>

And web.xml

<context-param>
   <param- name>
    org.omnifaces.COMBINED_RESOURCE_HANDLER_EXCLUDED_RESOURCES</param-name>
  <param-value>
     javax.faces:jsf.js,
     primefaces:jquery/jquery.js,
     primefaces:jquery/jquery-plugins.js,
     primefaces:primefaces.js
  </param-value>
</context-param>


	<mime-mapping>
		<extension>woff</extension>
		<mime-type>application/font-woff</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>woff2</extension>
		<mime-type>application/font-woff2</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>ttf</extension>
		<mime-type>application/x-font-ttf</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>css</extension>
		<mime-type>text/css</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>xhtml</extension>
		<mime-type>application/xhtml+xml</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>ico</extension>
		<mime-type>image/x-icon</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>json</extension>
		<mime-type>application/json</mime-type>
	</mime-mapping>
	<mime-mapping>
		<extension>svg</extension>
		<mime-type>image/svg+xml</mime-type>
	</mime-mapping>

**Comment by echer** [comment]
<h:outputStylesheet name="/custom/css/material-font.min.css" />
	<h:outputStylesheet name="/custom/css/material.min.css" />
	<h:outputStylesheet name="/custom/css/material-custom.min.css" />
	

	
	<h:outputStylesheet
		name="/global/plugins/uniform/css/uniform.default.min.css" />
	

	
	<h:outputStylesheet
		name="/global/plugins/bootstrap/css/bootstrap.min.css" />
	

	
	<h:outputStylesheet
		name="/custom/plugins/bootstrap-toastr/toastr.min.css" />
	

	
	<h:outputStylesheet name="/custom/css/uncssHomePage.min.css" />

**Comment by BalusC** [comment]
I see that you're also using `UnmappedResourceHandler` and that you've explicitly added a mime mapping for `xhtml` extension.

As per the [documentation](http://showcase.omnifaces.org/resourcehandlers/UnmappedResourceHandler), the `UnmappedResourceHandler` must be registered in `faces-config.xml` **after** any other custom resource handler like `CombinedResourceHandler`.

The explicit mime mapping for `xhtml` is unnecessary and suspicious.

If you fix both (swap resource handler ordering and remove xhtml mapping), then it should work.

**Comment by echer** [comment]
hei man thank you, this work now!!! 

I have added UnmappedResourceHandler above CombinedResourceHandler and removed xhtml mapping.
