### ISSUE TITLE
f:convertDateTime not working as expected

### ISSUE THREAD

**Issue by synsoft** [omnifaces/omnifaces#171]
Updating to the latest Omnifaces versions (both 2.0 and 2.1) f:convertDateTime doesn't work as expected.

Example:

```
<p:dataTable id="idTable" value="#{measureMB.measureModel}" lazy="true" var="row">
		<p:column id="dateColumn">
			<h:outputText id="slDueDate" value="#{row.date}">
				<f:convertDateTime type="date" dateStyle="default" />
			</h:outputText>
  		</p:column>
...
</p:dataTable>
```
shows:

`15.06.2013 00:00:00 ` in date column

with omnifaces 1.4.1 I got:

`Jun 15, 2013` which is the correct one.

#{row.date} is java.util.Date
measureModel is LazyDataModel from Primefaces

Same applies with 

`<o:converter>`

Environment::

- Tomcat 8.0.14
- Mojara 2.2.5
- Weld 2.3.0.Final
- Primefaces 5.1.21

**Comment by BalusC** [comment]
Please upgrade to a minimum of Mojarra 2.2.9 and retry. Current latest is 2.2.12.

**Comment by synsoft** [comment]
I have upgraded to both 2.2.11 and 2.2.12 and got the same result. 

I also tried to downgrade omnifaces from 2.1 to 1.11 with Mojara 2.2.12 and it works as expected (Jun 15, 2013).

**Comment by BalusC** [comment]
Sorry, I can't reproduce it in a completely blank scratchpad project with Mojarra 2.2.12, Weld 2.3.0.Final and PrimeFaces 5.2 on Tomcat 8.0.27.

Just wondering, are the <p:dataTable> and LazyDataModel parts really significant in your specific problem? Are you implying that it works fine without LazyDataModel? Are you implying that it works fine in <h:dataTable>? Are you implying that it works fine outside any table component?

**Comment by BalusC** [comment]
Any feedback? I'd like to naildown if this problem is caused by OmniFaces or not so I can fix it.

**Comment by synsoft** [comment]
I have tried several use cases and again I got the problem only when I use omnifaces 2.x. 
`<p:datatable>` and `LazyDataModel` are not significant to my problem I just put them as an example. I also tried outside `<p:datatable>` and got the same result. My beans.xml is also empty.

I tried to attach my pom.xml file but I don't have write permission.

**Comment by BalusC** [comment]
Do you have in your application a custom converter which extends JSF `DateTimeConverter` class?

**Comment by synsoft** [comment]
Yes, I have. And when I debug my application it turns out that `<f:convertDateTime type="date" dateStyle="default" />` calls custom converter even if it is not declared in `f:convertDateTime`!

Now when I found the problem, how to solve this and why do I have this problem only with omnifaces 2.x?

Custom faces converter:

`
    @FacesConverter("kpiFrequencyDateConverter")
    public class KpiFrequencyDateConverter extends DateTimeConverter{ 
`

**Comment by BalusC** [comment]
That was a known problem, but it shouldn't happen on latest Mojarra, Weld and an empty beans.xml, so I'm a bit in the dark as I can't reproduce it here after adding the extended converter to the WAR.

**Comment by synsoft** [comment]
Actually, I found that my converter extends `org.primefaces.convert.DateTimeConverter` not `javax.faces.convert.DateTimeConverter`, so when I switch to the `javax.faces.convert.DateTimeConverter` the problem was gone. 

But again why this makes problem since primefaces converter extends jsf converter class?

**Comment by BalusC** [comment]
That was helpful.

It's because PrimeFaces has overriden the builtin javax.faces.DateTime converter. So `<f:convertDateTime>` will actually reference PrimeFaces converter. Since your converter extends from PrimeFaces converter without `@Specializes` or `@Alternative`, CDI will find your converter instead of PrimeFaces converter for <f:convertDateTime>`. 

This is an unfortunate technical limitation. If you can't extend from standard converter, an alternative is putting `@Alternative` annotation on the converter.

An related issue is #146.
