### ISSUE TITLE
Make FileServlet.getContentType protected

### ISSUE THREAD

**Issue by GithubJohn3031** [omnifaces/omnifaces#173]
Could you make FileSevlet.getContentType() protected ? Now it is private. So one can use MimetypesFileTypeMap or another method for file type detection.

**Comment by BalusC** [comment]
Sure. Thought of it as well. The isAttachment() too.

**Comment by BalusC** [comment]
Available as of today's 2.2 snapshot.

**Comment by GithubJohn3031** [comment]
Thank you. To make isAttachment protected is good very good idea :)
