### ISSUE TITLE
Cannot inject EJB into a converter when forClass attribute is used

### ISSUE THREAD

**Issue by ssette** [omnifaces/omnifaces#174]
Omnifaces 2.1, jdk 8.0, Glassfish 4.1 with Mojarra 2.2.7

I've created a very simple Faces Converter and annotated it with @FacesConverter(forClass=MyClass.class). The converter uses a stateless session bean injected with an @EJB annotation. I've noted the ebj reference is always null, so I've tried with the @FacesConverter("myClassConverter") and all works fine. Is there an issue with the forClass attribute ?

----------------------
@FacesConverter("socioConverter")  // this works
//@FacesConverter(forClass=Soci.class) // with this SociService get not injected
public class SocioConverter implements Converter {
   
    @EJB
    private SociService sociService;
    
    @Override
    public Object getAsObject(FacesContext context, UIComponent component, String value) {
      if ((value == null) || (value.isEmpty())) 
          return null;
      else
          return sociService.find(Integer.parseInt(value));
    }

    @Override
    public String getAsString(FacesContext context, UIComponent component, Object value) {
      if (value == null) 
          return null;
      else
          return String.valueOf(((Soci)value).getIdSocio());
    }
----------------------------

**Comment by BalusC** [comment]
This is most likely caused by a known Mojarra related issue. 

- Upgrade to at least Mojarra 2.2.9 (or GlassFish 4.1.1).
- Or, set CDI 1.1 beans.xml to bean-discovery-mode="all" (it's the default already).

**Comment by ssette** [comment]
Upgraded to Mojarra 2.2.9 still not working, changed discovery mode to "all" solves the problem!
Btw there should be a 2.2.12 version of Mojarra but i cannot find where can be downloaded
Thanks a lot!

s7

**Comment by ssette** [comment]
Tried with 2.1.12. Same error. If discovery mode is not "all" (prior was "annotated") still not working.

**Comment by BalusC** [comment]
Nevermind, I got confused myself wrt bean-discovery-mode and Mojarra version. 

Only Mojarra 2.2.8 and before works with empty/default beans.xml.
After Mojarra 2.2.9 you need explicit bean-discovery-mode="all".

See also http://stackoverflow.com/q/29458023/157882
