### ISSUE TITLE
Omnifaces.js import does not work since latest snapshot

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#177]
Hi,

Since latest snapshot the omnifaces import looks like .../javax.faces.resource/omnifaces.js.xhtml?ln=omnifaces&amp;v=2.2-SNAPSHOT  , so it does not work. (it does work with CombinedResourceHandler activated since it does not include directly the omnifaces.js file).

It does work correctly in 2.2-RC1.

Myfaces 2.2.8 (tomee 1.7.2)

Relevant web.xml fragment:

    <servlet>
        <servlet-name>FacesServlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>   
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>FacesServlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
        <url-pattern>/javax.faces.resource/*</url-pattern>
    </servlet-mapping>

Relevant faces-config.xml fragment:
    <application>         
        <resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
        <resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>     
        
    </application>

**Comment by BalusC** [comment]
This was a consequence of a theoretical fix for http://stackoverflow.com/q/32758323/157882

I reverted it and took a better approach. It's available in today's snapshot.

Thank you for reporting!
