### ISSUE TITLE
URLs from CDN_RESOURCE_HANDLER_URLS are not excluded from combined resources

### ISSUE THREAD

**Issue by vanduynslagerp** [omnifaces/omnifaces#182]
Per documentation from `CombinedResourceHandler`:
> If you're also using the `CDNResourceHandler` or, at least, have configured its context parameter "org.omnifaces.CDN_RESOURCE_HANDLER_URLS", then those CDN resources will automatically be added to the set of excluded resources.

Although if a URL configured in **CDN_RESOURCE_HANDLER_URLS** contains a wildcard then it's not excluded from the combined resources, i.e.:
 - `jquery-cdn:jquery-1.9.1.js=http://code.jquery.com/jquery-1.9.1.js` will be excluded
 - `jquery-cdn:*=http://code.jquery.com/*`will not be excluded

I think the test `if (excludedResources.isEmpty() || !excludedResources.contains(resourceIdentifier))`
in`CombinedResourceHandler` should include the possibility of a wildcard in the name attribute of the `ResourceIdentifier`.

**Comment by BalusC** [comment]
Available in today's 2.2 snapshot.

Thanks for reporting and improving OmniFaces!
