### ISSUE TITLE
UnmappedResourceHandler and Filters stop working

### ISSUE THREAD

**Issue by svrolanski** [omnifaces/omnifaces#184]
Using Mojarra 2.2.10, Omnifaces 1.8.3, Primefaces 5.2, Tomcat 7.0.59

When I add UnmappedResourceHandler to my faces-config.xml my HibernateFilter (which opens and closes transactions, commit on sucecss and rollback on exceptions) stops catching exceptions that are thrown from my beans.

Full faces-config.xml 

		<?xml version="1.0" encoding="UTF-8"?>
		<faces-config version="2.0" xmlns="http://java.sun.com/xml/ns/javaee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			  xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-facesconfig_2_0.xsd">
	<application>
		<resource-handler>org.omnifaces.resourcehandler.CombinedResourceHandler</resource-handler>
		<resource-handler>org.omnifaces.resourcehandler.UnmappedResourceHandler</resource-handler>

		<locale-config>
			<default-locale>pt_BR</default-locale>
		</locale-config>

		<action-listener>org.primefaces.application.DialogActionListener</action-listener>
		<navigation-handler>org.primefaces.application.DialogNavigationHandler</navigation-handler>
		<view-handler>org.primefaces.application.DialogViewHandler</view-handler>

		<resource-bundle>
			<base-name>mycompany.properties.Menu</base-name>
			<var>pptMenu</var>
		</resource-bundle>

		<resource-bundle>
			<base-name>mycompany.properties.Dominios</base-name>
			<var>pptDominios</var>
		</resource-bundle>

		<resource-bundle>
			<base-name>mycompany.properties.Mensagens</base-name>
			<var>pptMensagens</var>
		</resource-bundle>

		
		<el-resolver>mycompany.faces.LookupELResolver</el-resolver>
	</application>

	<factory>
		<exception-handler-factory>
			org.omnifaces.exceptionhandler.FullAjaxExceptionHandlerFactory
		</exception-handler-factory>
	</factory>
		</faces-config>

I clean projects, debug main webapp, click a button with "throw new Exception();" (ajax request), the exception is not caught in the filter. If I stop tomcat and do the same but remove the resource-handler for UnmappedResourceHandler, the exception is caught in the filter.

**Comment by BalusC** [comment]
I gather that you already nailed down the actual problem?

**Comment by svrolanski** [comment]
I actually have not, after removing the resource handler the exception wasn't being consume anymore. But after I report it here, I test it again and it worked anyway, so the problem may be something else. I will resume my search for the problem now.

**Comment by svrolanski** [comment]
BalusC, I think FullAjaxExceptionHandler is consuming (handling?) the exception and not letting filters know about any exceptions thrown. Is that correct and expected behaviour (by JSF spec)?

**Comment by BalusC** [comment]
By default, JSF already won't delegate exceptions during ajax requests through the filters. So also without the exception handler, the chain.doFilter() won't throw and hit its catch block.

**Comment by BalusC** [comment]
I gather that you'd like to deal with business exceptions and rollback and alike. In that case, the following links may contain food for thought:

- http://stackoverflow.com/q/32853167/157882
- http://stackoverflow.com/q/32040779/157882

**Comment by svrolanski** [comment]
I will check it out, thank you!!
