### ISSUE TITLE
CombinedResourceHandler addCombined failed to add several deferredScript (version 1.12.1 & 1.12)

### ISSUE THREAD

**Issue by jlerbsc** [omnifaces/omnifaces#189]
In CombinedResourcehandler if CombinedResourceInfo contains several deferredSrcipt (group usage) like this [primefaces:jquery/jquery-plugins.js, primefaces:primefaces.js, primefaces:watermark/watermark.js] then the first is correctly added into the combined resource but others are not.

**Comment by BalusC** [comment]
Sorry, can't reproduce. Would be helpful if you could create a reproducer project.

**Comment by jlerbsc** [comment]
Thanks for the response. It worked for me on version 1.11. So for the moment i have no time to create a reproducer project.

**Comment by BalusC** [comment]
Closing off as no-repro, and reporter not able to provide a reproducer.
