### ISSUE TITLE
primefaces 5.2 5.3  AND omnifaces 2.2   BUG?

### ISSUE THREAD

**Issue by sjljsw** [omnifaces/omnifaces#190]
<p:dataExporter type="xls"  
                                            target="searchPHTableId"
                                            encoding="GBK"
                                            fileName="mdrklscx"/>

You can not export data after omnifaces 2.2 when DataTable using LazyDataModel

**Comment by BalusC** [comment]
Sorry, couldn't reproduce any problem using code from http://www.primefaces.org/showcase/ui/data/datatable/lazy.xhtml. It would be helpful if you could create a minimal reproducer project.

**Comment by BalusC** [comment]
Closing off due to lack of feedback. If you still face the issue and have a minimal reproducer project, of course open a new issue.
