### ISSUE TITLE
use showcase omnifaces with 1.8.3 jar and tomee 1.7.2

### ISSUE THREAD

**Issue by maurojava** [omnifaces/omnifaces#191]
Hi all . 
I would use the showcase of omnifaces with tomee 1.7.2 
Tomee use jsf2.1 .and cdi1.0
Now i would try to install locally for use it offline the showcase of omnifaces.
But from github i get only the version with omnifaces 2.2
I you ask: if i create a web proget with the sources of showcase omnifaces and use the omnifaces 1.8.3 library it work?
or where i can donload the sources of showcase of omnifaces that work with omnifaces 1.8.3 library ?

tnak you in advance.
Mauro

**Comment by BalusC** [comment]
We don't maintain/publish old showcases. We must admit we forgot tagging the showcase branch for every specific release. This indeed makes checking out the right version harder. We'll keep an eye on this for future releases. 

At least, I can tell that you need to checkout this commit to have latest state of 1.8.x showcase: https://github.com/omnifaces/showcase/commit/8561ae41868fc47cb2d31ee636ddf7717bd0b3da

**Comment by BalusC** [comment]
FYI: I've added missing tags: https://github.com/omnifaces/showcase/releases
