### ISSUE TITLE
@ViewScoped in EAR Project | WildFly 9.0.2.Final

### ISSUE THREAD

**Issue by gvieiradot** [omnifaces/omnifaces#192]
I'm using WildFly 9.0.2.Final.
Omnifaces's @ViewScoped in a WAR project works just fine!
The problem is when I change to a EAR project (1 WAR and 1 EJB). It doesn't work :(
There is no error messages too.. It's like the Bean doesn't exists.
Thank you!

**Comment by BalusC** [comment]
Where is OmniFaces JAR placed in EAR? It must end up in WAR's /WEB-INF/lib.

**Comment by gvieiradot** [comment]
Yes, its at /WEB-INF/lib in WAR. I checked the EAR build and it's there too at "WEB-INF.lib" :(

**Comment by BalusC** [comment]
Can you assure there's no duplicate OmniFaces lib elsewhere? E.g. EAR/lib? Else a minimal reproducer project would be terribly helpful to naildown the issue.

We have in production environments so far exclusively used EAR projects. We haven't faced any trouble with OmniFaces @ViewScoped. We're also using WildFly 9.

**Comment by gvieiradot** [comment]
No, there's no duplicate lib :(

Informations to reproduce the problem:
-IDE is Netbeans 8.1;
-Wildfly is in standalone version;
-I'm using JRebel (If it matters);
-I'm not using Maven;
-Create a normal EAR project (Add a WAR and a EJB module);
-Create a very simples @ViewScoped and call any value from a JSF page;

Thank you so much BalusC :D
I appreciate your help!

**Comment by gvieiradot** [comment]
Heres my simple EAR project: [https://www.sendspace.com/file/wxbipu](https://www.sendspace.com/file/wxbipu)

**Comment by BalusC** [comment]
With source would be more useful, yes. Just create a github project.

**Comment by gvieiradot** [comment]
Ok. I'm a lil buzy those days.. But I'll post it soon.

**Comment by BalusC** [comment]
Closing off as not reproducible and no feedback. If you have a reproducer, open a new issue.
