### ISSUE TITLE
Document TomEE compatibility

### ISSUE THREAD

**Issue by rmannibucau** [omnifaces/omnifaces#193]
Hi guys

Would it be possible to speak about TomEE 1.x - CDI 1.0 - and TomEE 7.x - CDI 1.2 - on the website and list compatible versions. On tomee list users are confused.

Thanks

**Comment by BalusC** [comment]
Thank you for your concern. You can find the compatibility matrix here: https://github.com/omnifaces/omnifaces/wiki/Compatibility-Matrix

I will re-test the current versions and update the compatibility matrix where necessary and let you know here.

From own experience I can at least tell that OmniFaces 2.x showcase has for every OmniFaces 2.x version been tested on TomEE 2.x/7.x  snapshot available around date of a OmniFaces release.

**Comment by rmannibucau** [comment]
Great thks, not sure where the confusion comes from but here is tomee thread if it can help http://tomee-openejb.979440.n4.nabble.com/what-omnifaces-version-use-with-tomee-1-7-tp4677331p4677333.html

**Comment by BalusC** [comment]
I think it's because TomEE is relatively late with a final Java EE 7 compatible version while OmniFaces keeps moving on an also because OmniFaces 2.x deploys fine on TomEE 1.x, but fails later during runtime.

**Comment by rmannibucau** [comment]
Think it comes from http://omnifaces.org/cdi/ which doesnt deal with versions

**Comment by BalusC** [comment]
I just tested once again and added versions to https://github.com/omnifaces/omnifaces/wiki/Compatibility-Matrix

**Comment by rmannibucau** [comment]
Hi @BalusC , TomEE 1.7.x is not mentionned, is it intentional?

**Comment by BalusC** [comment]
TomEE is still Java EE 6 / JSF 2.1.

**Comment by rmannibucau** [comment]
Maybe it should be mentionned ("min version" or something like that), wdyt?

**Comment by BalusC** [comment]
Just tested 1.8 showcase on TomEE 1.7.3, all works fine. Wiki has been updated.

**Comment by rmannibucau** [comment]
Thks a lot!
