### ISSUE TITLE
Allow FullAjaxExceptionHandler to be configured to unwrap more Exception types

### ISSUE THREAD

**Issue by kalgon** [omnifaces/omnifaces#196]
One of the reasons I extend `FullAjaxExceptionHandler` is to add more `Exception`types to unwrap like this:

    import static org.omnifaces.util.Exceptions.unwrap;
    
    public class ExtendedFullAjaxExceptionHandler extends FullAjaxExceptionHandler {
        ...
        @Override
        protected Throwable findExceptionRootCause(FacesContext context, Throwable exception) {
            return unwrap(unwrap(super.findExceptionRootCause(context, exception), EJBException.class), RollbackException.class);
        }	
    }

After that, you also need to write the corresponding `ExceptionHandlerFactory`.

Do you think it would be a good idea if `FullAjaxExceptionHandler` could use a list of `Exception` types to unwrap coming from `web.xml` or `faces-config.xml` ? We do that already for `error-page`s.

**Comment by BalusC** [comment]
EJBException? You might want to read this: [Handling service layer exception in JSF](http://stackoverflow.com/q/32853167/157882)

**Comment by kalgon** [comment]
I agree for `EJBException`, you can annotate exceptions with `@ApplicationException` or declare them in ejb-jar.xml if you don't have access to the source code (I tend to re-use exceptions like `NoSuchElementException` for 404). Lazy as I am, I just unwrap `EJBException`.

The reason I unwrap `RollbackException` is to catch exceptions like `OptimisticLockException` to explain to the user what happened (concurrent modification) and invite him to reload his page and start over what he was doing.

**Comment by BalusC** [comment]
It's available in today's 2.3 snapshot. Let me know if it does the job you asked for.

**Comment by kalgon** [comment]
I tested it and it's working as I expected. Thanks!
