### ISSUE TITLE
InjectionPoint null when using BeanManager.INSTANCE.getReference(...)

### ISSUE THREAD

**Issue by dcdh** [omnifaces/omnifaces#197]
Hello,

I am using BeanManager.INSTANCE.getReference(Logger.class) to inject my Logger CDI bean into a SOAPHandler.

My logger is declared as this:

```java
@Produces
public Logger produceLogger(InjectionPoint injectionPoint) {
    return Logger.getLogger(injectionPoint.getMember().getDeclaringClass().getName());
}
```
However when using BeanManager.INSTANCE.getReference injectionPoint is null. Is it possible to add the reference of the class calling the BeanManager.INSTANCE for the injectionPoint (if it is possible, I am not a CDI creational expert ...)

Thanks by advance.

Regards,
Damien

**Comment by BalusC** [comment]
Which CDI environment? Weld or openWebBeans? Which version? Telling server make/version is also helpful.

**Comment by dcdh** [comment]
am sorry for these missing informations.
I'am using Weld with Wildfly 9.0.2.
Weld version is 2.2.16.SP1.

Regards,
Damien

**Comment by BalusC** [comment]
After all, there's just no means of a `InjectionPoint` when a bean is manually created this way instead of injected via `@Inject`. So the behavior is expected.

**Comment by dcdh** [comment]
Thanks for your response.
Regards,
Damien
