### ISSUE TITLE
Problem about tabAttribute

### ISSUE THREAD

**Issue by vipcxj** [omnifaces/omnifaces#201]
`<o:tagAttribute name="type" default="text"/>`
I use it in a tag file. The tag name is "gridInput".
And this is a usecase
`<cxj:gridInput type="submit" process="setter" update="setter"/>`
I except that the attribute "type" is "submit". However, it is "text". So the fact is that even if I set the attribute to some value, the attribute still be set to default value.
So I saw the code.
In `org.omnifaces.taghandler.TagAttribute.apply(FaceletContext context, UIComponent parent)`

		checkAndMarkMapper(context); //This make variableMapper to be a DelegatingVariableMapper. This is the key to the problem.
		VariableMapper variableMapper = context.getVariableMapper();

		//This is the key to the problem, too. The function 'setVariable' get the variable from the private map in the Delegate mapper. It does not check the real mapper! So in my use case, it return null, but 'submit'. This result in the issue!
		ValueExpression valueExpressionLocal = variableMapper.setVariable(name, null);

		if (valueExpressionLocal == null && defaultValue != null) {
			valueExpressionLocal = defaultValue.getValueExpression(context, Object.class);
		}

		if (valueExpressionLocal == null) {

The reason of the issure is in the comment above.

**Comment by BalusC** [comment]
Which JSF impl/version?

**Comment by vipcxj** [comment]
MyFaces

**Comment by BalusC** [comment]
Which MyFaces 2.2 version? 2.2.9?

**Comment by vipcxj** [comment]
Yes, 2.2.9

**Comment by BalusC** [comment]
Reproduced.

However, upon inspection, it appears that MyFaces has already internally solved the problem the `<o:tagAttribute>` is designed to solve and therefore the `<o:tagAttribute>` basically takes you a step back, causing the same problem you're seeing in Mojarra.

In other words, when using MyFaces, the o:tagAttribute is unnecessary. It's only useful for Mojarra. I must say that this all is working "as designed".

I gather that you actually wanted to have a default value for a tag attribute when unspecified. You can continue using JSTL for this.

```
<c:set var="type" value="#{empty type ? 'text' : type}" />
```

I will clarify the `<o:tagAttribute>` javadoc on this.
