### ISSUE TITLE
First name used at last name column in moveComponent demo

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#203]
http://showcase.omnifaces.org/components/moveComponent

    <p:column filterBy="#{user.lastName}" filterMatchMode="contains">  
      #{user.firstName}
    </p:column>

Should be:

    <p:column filterBy="#{user.lastName}" filterMatchMode="contains">  
      #{user.lastName}
    </p:column>

**Comment by BalusC** [comment]
Locally fixed, thanks!

In the future, please report showcase issues at showcase repo https://github.com/omnifaces/showcase/issues

**Comment by jepsar** [comment]
Sure thing. Sorry about that :-)
