### ISSUE TITLE
Faces method to get the short viewId of view

### ISSUE THREAD

**Issue by julianomqs** [omnifaces/omnifaces#205]
Hello,

I checked `Faces` class docs about methods to get the current view id of view root.

If I'm not wrong, `Faces` class only have the method `getViewId()`, which gets the full path of viewId, like this:

`/pages/product/product-add.xhtml`

I think it will be nice to have a method to get only the "real name" of the view (in other words, the file name), like this:

`product-add`

Then I will can use it in the view with `o:importFunctions` for showing a button only in a certain page.

What you think?

**Comment by BalusC** [comment]
Makes sense.
