### ISSUE TITLE
Make omnifaces usable within portlet environments (e.g. jsf-2.2 portlets in liferay-6.2.x)

### ISSUE THREAD

**Issue by reneol** [omnifaces/omnifaces#207]
As an user i want to use omnifaces within a jsf-2.2 portlet in liferay-6.2.x
Now only servlet environments works with omnifaces.

**Comment by BalusC** [comment]
Thank you for your interest in OmniFaces. Sorry, we'd rather not maintain a separate branch for Portlets. OmniFaces is from the beginning on designed to require the Servlet API, part of standard Java EE API.

Feel free to fork and maintain on your own under same license.

**Comment by stiemannkj1** [comment]
@reneol, unfortunately there doesn't seem to be any fork for Omnifaces in portlets. Liferay Faces does support some similar features like `alloy:loadConstants` (similar to `o:importConstants`). If you would like Liferay Faces to provide support for Omnifaces, please create an improvement request in the [Liferay Faces JIRA](https://issues.liferay.com/secure/CreateIssue.jspa?pid=12081&issuetype=4&components=16655). Alternatively, you could create [a feature request](https://issues.liferay.com/secure/CreateIssue.jspa?pid=12081&issuetype=2&components=16655) for the Liferay Faces team to create a portlet compatible version of your favorite Omnifaces components.

**Comment by msgeissler** [comment]
If anyone is interested in / wants a portlet-compatible fork of Omnifaces please post in the [Portlet compatible version of Omnifaces-thread over at the Liferay Faces Bridge forum](https://web.liferay.com/de/community/forums/-/message_boards/message/82531190) to let the Faces Bridge Team know!
