### ISSUE TITLE
adding generic client parameter support to method expressions for o:methodParam 

### ISSUE THREAD

**Issue by wsaxton** [omnifaces/omnifaces#210]
o:methodParam already supports the default ActionEvent argument as a client param. 

    actionListenerWithClientParam(ActionEvent event)

It would be nice if it accepted any arguments.

    actionListenerWithClientParam(Foo foo)

So that it can be used by a client:

```
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:o="http://omnifaces.org/ui"
>
    <o:methodParam name="method" value="#{listener}" />
    <h:commandButton value="test" actionListener="#{method(foo)}" />
</ui:composition>
```

**Comment by wsaxton** [comment]
For those curious, a workaround for this is to pass the value as an f:attribute so you can get the value from the ActionEvent:

    <h:commandButton value="test" actionListener="#{method}" 
        <f:attribute name="foo" value="#{foo}"/>
    >

  Then get it via:

    actionListenerWithClientParam(ActionEvent event) {
        Foo foo = (Foo)event.getComponent().getAttributes().get("foo");
    }

**Comment by BalusC** [comment]
This works fine for me when using action instead of actionListener. We never really use actionListener for this kind of stuff (actionListener isn't intented for business actions, see also http://stackoverflow.com/q/3909267/157882)

**Comment by wsaxton** [comment]
Didn't even try that.  Thanks.

**Comment by wsaxton** [comment]
So, I tried using the action instead of actionListener and it still does not work.

I copied the showcase demo code from here:

http://showcase.omnifaces.org/taghandlers/methodParam

I modified the "demo:actionmethod" tag so that it used a parameter:


```
<ui:composition
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:o="http://omnifaces.org/ui"
>
    <o:methodParam name="method" value="#{action}" />
    <h:commandButton value="test" action="#{method('test')}" />
</ui:composition>
```


I then created a simple test web page:

```
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:demo="http://www.example.com/demo">
    <h:body>
        <h:form>
            <demo:actionmethod action="#{methodParamBean.doActionWithParam}"/>
        </h:form>
    </h:body>
</html>
```

And got the following error message when the page loaded:

**/WEB-INF/tags/actionmethod.xhtml @9,64 action="#{method('test')}" Not a Valid Method Expression: #{method('test')}**

**Comment by wsaxton** [comment]
Just to clarify, the reason I want to do this is because my own custom tag contains a datatable with buttons for each entry.  I want the buttons to execute an action with the current entry as the parameter.  

Now, if o:methodParam doesn't work within a datatable then I can't use this anyway :)  Just wanted to give you a heads up so I don't waste anyone's time!

**Comment by BalusC** [comment]
Sorry, I misinterpreted the problem. You wanted to pass a param in the tagfile itself not from the client on. We actually never took into account this case and I'm not sure if that would work.

**Comment by wsaxton** [comment]
No problem.  Thanks for the response.
