### ISSUE TITLE
Add function to retrieve el enum values.

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#211]
Based on this SO question its often needed to retrieve Enum values to be displayed in menu. What do you think about this function:

http://stackoverflow.com/questions/8229638/how-to-make-a-dropdown-menu-of-a-enum-in-jsf/35385599#35385599

El function:

	public final class ElEnumUtils
	{
		private ElEnumUtils() { }

		/**
		 * Cached Enumerations, key equals full class name of an enum
		 */
		private final static Map<String, Enum<?>[]> ENTITY_ENUMS = new HashMap<>();;
	
		/**
		 * Retrieves all Enumerations of the given Enumeration defined by the
		 * given class name.
		 *
		 * @param enumClassName Class name of the given Enum.
		 *
		 * @return
		 *
		 * @throws ClassNotFoundException
		 */
		@SuppressWarnings("unchecked")
		public static Enum<?>[] getEnumValues(final String enumClassName) throws ClassNotFoundException
		{
			// check if already cached - use classname as key for performance reason
			if (ElEnumUtils.ENTITY_ENUMS.containsKey(enumClassName))
				return ElEnumUtils.ENTITY_ENUMS.get(enumClassName);
	
			final Class<Enum<?>> enumClass = (Class<Enum<?>>) Class.forName(enumClassName);
	
			final Enum<?>[] enumConstants = enumClass.getEnumConstants();
	
			// add to cache
			ElEnumUtils.ENTITY_ENUMS.put(enumClassName, enumConstants);
	
			return enumConstants;
		}
	}

Register it as an el function in a taglib file:

	<function>
		<description>Retrieves all Enumerations of the given Enumeration defined by the given class name.</description>
		<function-name>getEnumValues</function-name>
		<function-class>
			package.ElEnumUtils
		</function-class>
		<function-signature>
			java.lang.Enum[] getEnumValues(java.lang.String)
		</function-signature>
	</function>

And finally call it like:

	<p:selectOneMenu value="#{bean.type}">
		<f:selectItems value="#{el:getEnumValues('package.BeanType')}" var="varEnum" 
			itemLabel="#{el:getEnumLabel(varEnum)}" itemValue="#{varEnum}"/>
	</p:selectOneMenu>

**Comment by BalusC** [comment]
Looks OK, but not sure about additional benefit on top of `<o:importConstants>`.

**Comment by BalusC** [comment]
I added `<o:importConstants>` hint to the related question.
