### ISSUE TITLE
Feature request: relative date function

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#212]
To display dates like "moments ago", "59 minutes ago", "23h 59m ago", "6d 23h ago", "30 days ago", "full date pattern for more than 30 days".

I don't have existing code to do so layout around, but I could write some code and donate it if that comes in handy.

**Comment by BalusC** [comment]
That's already done by [PrettyTime](http://www.ocpsoft.org/prettytime/). We also use it and it works quite good.

**Comment by jepsar** [comment]
Let me see if I can get it to return the (compact) format I need, else I'll write my own method. Thanks!
