### ISSUE TITLE
Custom parameter to allow API usage without CDI

### ISSUE THREAD

**Issue by michelrisucci** [omnifaces/omnifaces#214]
Is there any way to use Omnifaces without CDI environment?
I'm getting "CDI API is not available in this environment" all the time, and I would love to see a custom parameter to disable this behavior, if possible.
By the way, I have a custom JSF environment using Spring context, instead of CDI.

**Comment by BalusC** [comment]
Sorry, OmniFaces 2.x cannot be used without CDI. The check is just proactive to avoid confusing and ambiguous runtime exceptions at a later point.

Use OmniFaces 1.x instead of 2.x. It can be used in a CDI-less environment.
