### ISSUE TITLE
Add to  FileServlet getAttachmentName() 

### ISSUE THREAD

**Issue by GithubJohn3031** [omnifaces/omnifaces#216]
Is it possible to add to FileServlet a possibilty to say from inherited class  the attached file name. 
Something like that:

```java
		try {
			resource = new Resource(getFile(request));
                        resource.name = getAttachedName();
		}
		catch (IllegalArgumentException e) {
			response.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}
```

or another idea were to make a protected method that  modifies the resource. 

```java
		try {
			resource = new Resource(getFile(request));
                        resource = modifyResource (resource);
		}
		catch (IllegalArgumentException e) {
			response.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		}
```
EDIT: it would be cool to have a possibility to react to an error in derived class, for example we make a redirect, if some error occurs:

```java
		try {
			resource = new Resource(getFile(request)); 
		}
		catch (IllegalArgumentException e) {                        
			response.sendError(HttpServletResponse.SC_BAD_REQUEST);
			return;
		} catch (IllegalStateException e){
                 //No action, errors should be set in derived class
                return;
       }

```

I should make an example of FileServlet with proposed changes.

**Comment by BalusC** [comment]
All is possible, I like changing the attachment name. Others not so.

But what exactly is the business requirement which you tried to solve? I feel there might be a better solution.

**Comment by GithubJohn3031** [comment]
Use case 1:

```java
protected File getFile(HttpServletRequest request) {
  File file = find file somehow
   if (file type is image && file not found){
       redirect to special error image on external server
       return null;
   }
   
   return file
}
```

Use Case 2:

```java
protected File getFile(HttpServletRequest request) {
  File file = find file somehow
  response = Get HttpServletResponse somehow
  if (file == null)
    get file error somehow
  if (file error of type 1)
     response.sendError (SC_INTERNAL_SERVER_ERROR)
     return
  else if (file error of type 2)
     response.sendError (SC_NO_CONTENT)
     return
   
     //SC_UNSUPPORTED_MEDIA_TYPE
     //SC_NOT_IMPLEMENTED

   return file
}

protected String getAttachmentName (){
  String attachmentFile =  get file name to download
   return attachmentFile;
}
```
In Use Case 2 I don't know if there are rules for error messages in file downloads, that prohibit to use error codes as in this use case.

**Comment by BalusC** [comment]
How about below method which you can override?

```
	/**
	 * Handles the case when the file is not found.
	 * <p>
	 * The default implementation sends a HTTP 404 error.
	 * @param request The involved HTTP servlet request.
	 * @param response The involved HTTP servlet response.
	 * @throws IOException When something fails at I/O level.
	 * @since 2.3
	 */
	protected void handleFileNotFound(HttpServletRequest request, HttpServletResponse response) throws IOException {
		response.sendError(HttpServletResponse.SC_NOT_FOUND);
	}
```

**Comment by BalusC** [comment]
I added handleFileNotFound() and getAttachmentName() as per above commit. It's available in today's 2.3 snapshot. Can you give it a try and let me know if no more things/changes are needed?

**Comment by GithubJohn3031** [comment]
Thank you very much. We've tested implementation with new methods. It fits all. The implementation of our servlet with omnifaces.FileServlet is simple and easy to understand. Better as before. 
We don't need changes any more. 

P.s. Theoreticaly I could me imagine the situation where the resource is not a file but a stream. But it will be  StreamerServlet then :) And you can save the stream in a file and use FileServlet.

**Comment by BalusC** [comment]
Great.

With streams, supporting Range requests is not trivial. Hence Files only. You could always have a temp file directory.
