### ISSUE TITLE
Use hardcoded constants

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#219]
Nothing important but i saw the usage of a Strings like `"javax.servlet.forward.servlet_path"` which is not necessary since there are hardcoded constants like `RequestDispatcher.FORWARD_SERVLET_PATH`.

Less error prone in case it will change (I know it won't :D).

**Comment by BalusC** [comment]
Fixed. This was already taken into account in FullAjaxExceptionHandler, but others were simply overlooked.

Thanks!
