### ISSUE TITLE
CDI BeanManager customer set

### ISSUE THREAD

**Issue by yyq2013** [omnifaces/omnifaces#221]
in this class: org.omnifaces.config.BeanManager
It will throw error if no found beanManager, but my beanManager is initialized later and doesn't follow the standard, so IS it possible just warn it and then developer can set it in proper time?

if (beanManager == null) {
			throw new IllegalStateException(ERROR_CDI_IMPL_UNAVAILABLE);
		}

**Comment by BalusC** [comment]
Sorry, CDI is required to perform OmniFaces initialization during startup.

The check built into OmniFaces application listener is just a proactive central check to avoid a lot of different possible exceptions at a later point.
