### ISSUE TITLE
Please update link in DefaultCache javadoc

### ISSUE THREAD

**Issue by dmaidaniuk** [omnifaces/omnifaces#229]
Could you please update a link from `org.omnifaces.component.output.cache.DefaultCache` javadoc to point user to new URL from [GitHub](https://github.com/ben-manes/concurrentlinkedhashmap)?
Also found same outdated link in `org.omnifaces.component.output.cache.DefaultCacheProvider`.

**Comment by BalusC** [comment]
Thank you for reporting!
