### ISSUE TITLE
Documentation of o:tree, o:treeNode, ...

### ISSUE THREAD

**Issue by EJP286CRSKW** [omnifaces/omnifaces#230]
Bauke, I spent some hours trying to figure out o:tree and I don't think the documentation is clear enough. It should state clearly that o:treeNodeItem enumerates the *children* of the current o:treeNode, and that o:treeInsertChildren inserts its grandchildren.

**Comment by BalusC** [comment]
Agreed, documentation can be clearer. I made an attempt with removing all remarks related to JSF component tree structure and improving details on TreeModel parent/child relationships.

Here's the new version: http://omnifaces.org/docs/javadoc/current/org/omnifaces/component/tree/Tree.html
Compare the old version: http://omnifaces.org/docs/javadoc/2.3/org/omnifaces/component/tree/Tree.html

Let me know if this is OK or needs more improvement (if so, which/how exactly).

**Comment by EJP286CRSKW** [comment]
Bauke
 
Thanks, that seems a bit better. Another question if I may, I noticed
that the <o:tree value=> attribute is only processed in phase 1, which
doesn't play with trees that need to be updated or re-rendered. I can
see how this might be necessary if o:tree isn't a UIComponent but again
it needs to be documented. Or else I am crazy ;-)
 
EJP

  _____

**Comment by BalusC** [comment]
As per Tree#getModel() logic it's processed in phase 6 or when lazy initialization hasn't taken place.

o:tree is certainly an UI component, but is just doesn't render HTML. 

Any problems in flavor of MCVE are more than welcome.
