### ISSUE TITLE
NullPointerException with ListIndexConverter

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#231]
While experimenting with the [ListIndexConverter](http://showcase.omnifaces.org/converters/ListIndexConverter) I got `NullPointerException`s when the backing list contains `null`-elements:

    FullAjaxExceptionHandler: An exception occurred during rendering JSF ajax response. Error page '/errorpages/error.xhtml' will be shown.: java.lang.NullPointerException
    	at org.omnifaces.converter.ListIndexConverter.getAsString(ListIndexConverter.java:78)
    	at org.omnifaces.taghandler.Converter$1.getAsString(Converter.java:114)
    	at com.sun.faces.renderkit.html_basic.HtmlBasicRenderer.getFormattedValue(HtmlBasicRenderer.java:521)
    	at com.sun.faces.renderkit.html_basic.MenuRenderer.renderOption(MenuRenderer.java:534)
    	at com.sun.faces.renderkit.html_basic.MenuRenderer.renderOptions(MenuRenderer.java:794)

The reason is quite clear: the converter executes

    if (list.get(i).equals(value)) {

which is not null-save.

I'm not sure if `null`-elements in the list are valid, but it is nowhere mentioned, that it wouldn't be. So if it is valid, this is a bug and should be fixed. If it is not valid to have `null`-values in the list, please mention it in the documentation.

BTW, I'm using OmniFaces 2.1 but the code didn't change till at least 2.3.

Oh, and the actual reason I put a `null`-value in the list was, because I wanted to add a noSelectionOption, which was not possible. So when working at it, please consider this as well.

**Comment by BalusC** [comment]
`null` items in model are indeed unexpected, you should be using a separate f:selectItem for this. But based on stack trace you're actually using ListIndexConverter on <h:selectOneMenu>? The ListIndexConverter is not designed for components taking f:selectItem(s) as available items. The ListIndexConverter is designed for components taking List<T> as available items.

You need SelectItemsConverter or SelectItemsIndexConverter instead. Give it a try.

**Comment by matinh** [comment]
It really seems I misunderstood when to use the ListIndexConverter. I was actually using a `<rich:pickList>` which accepts `<f:selectItms(s)>`, so I really should be using `SelectItemsConverter` instead.

However, the NPE was unexpected for me and not mentioned anywhere in the documentation, that `null`-elements are not allowed. So maybe you could still update the documentation or add support by doing a null-safe compare in the converter.

Thanks anyway.

**Comment by BalusC** [comment]
Let's wait for a real world problem :)

Having `null` among available item values in model is in first place wrong. If a "please select" placeholder item is intented, it belongs in view, not in model.
