### ISSUE TITLE
Filter to exclude url patterns from faces servlet

### ISSUE THREAD

**Issue by feverdog** [omnifaces/omnifaces#233]
Greetings Bauke, first of all, bravo for Omnifaces and all of your work in the community.

I had an idea for a new Omnifaces feature that would be to create a filter to exclude url-patterns from the FacesServlet mapping. E.g. I want to map all my url's to the FacesServlet except my REST mapping path **/rest/**\* in order to avoid mapping it all with using prettyfaces.

An example of folder structure would be like this (took it from my Apache Shiro structure):

/login.xhml = authc
/app/*\* = user
/secure/*\* = ssl, user
/public/*\* = anon
/rest/*\* = authc, rest
/javax.faces.resource/*\* = anon

So I want to exclude my /rest/*\* path from FacesServlet to avoid any JSF lifecycle lookup.
Maybe I'm terribly wrong and missing something, if so, please accept my apologies.

Best Regards.

**Comment by BalusC** [comment]
Something like this? http://stackoverflow.com/q/3125296/157882

**Comment by feverdog** [comment]
Yes, it would be nice to have this feature already bundled with Omnifaces, maybe it would be useful for a lot of people.

**Comment by BalusC** [comment]
Sorry, above commit was for #223, I typo'ed the issue number.

**Comment by BalusC** [comment]
Coming back to the issue, what's the technical reason your FacesServlet is mapped on `/*` instead of eg `*.xhtml`?

**Comment by feverdog** [comment]
I was using ExtensionlessURLs filter and somehow had this idea that It would somehow affect application behavior - I haven't tested it because I decided have a separate REST service instead.. but thinking clearly, it should be fine using *.xhtml mapping with ExtensionlessURLs, shouldn't it?

I guess you should close this if it does hehe.

I am sorry for any inconvenience, thank you very much for your time, I do love your work.
Keep it up!

**Comment by BalusC** [comment]
Okay :)

I'm closing off as there's still not really a reasonable real world use case for this.
