### ISSUE TITLE
Change '+' to spaces in file name during file download

### ISSUE THREAD

**Issue by GithubJohn3031** [omnifaces/omnifaces#237]
If filenames have spaces during download the spaces are changed to "+". So if file name is "my picture.jpg" Firefox loads a file as "my+picture.jpg". I've seen this issue only in Firefox, but possibly it occured also in another browsers.
I've found 2 places for file download in Omnifaces. The solution can be replacement of "+" to "%20". Tested with Ie8, Ie11, Firefox, Chrome

FacesLocal.sendFile:
```java
		externalContext.setResponseHeader("Content-Disposition", String.format(SENDFILE_HEADER,
			(attachment ? "attachment" : "inline"), encodeURL(filename)));
```

to 

```java
		externalContext.setResponseHeader("Content-Disposition", String.format(SENDFILE_HEADER,
			(attachment ? "attachment" : "inline"), encodeURL(filename).replace("+", "%20")));
```

FileServlet.setContentHeaders 

	String filename = encodeURL(getAttachmentName(request, resource.file));

**Comment by BalusC** [comment]
Fix is available in today's [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).
