### ISSUE TITLE
JsfLabelMessageInterpolator is not called on @Param bean validation error

### ISSUE THREAD

**Issue by vanduynslagerp** [omnifaces/omnifaces#238]
The setting is as follow:
- `JsfLabelMessageInterpolator` configured as in [Showcase - JsfLabelMessageInterpolator](http://showcase.omnifaces.org/validators/JsfLabelMessageInterpolator) with same custom message for `@Size`
- `Messages` configured as [Showcase - Messages](http://showcase.omnifaces.org/utils/Messages) i.e. using `MessageFormat.format(message, params);`
- Managed Bean with an attribute annotated with `@Param` and `@Size(min = 5, max = 10)`

When the managed bean is called with a GET parameter value that doesn't match the validator constraint, [RequestParameterProducer](https://github.com/omnifaces/omnifaces/blob/master/src/main/java/org/omnifaces/cdi/param/RequestParameterProducer.java#L141) create a new JSF message.

The message `The size of {jsf.label} must be between 5 and 10 characters` ends up being processed by `MessageFormat.format(message, params);` and fail with `NumberFormatException` as the message still contains {jsf.label} while `MessageFormat` expect a number (i.e. {0}).

I was about to make a PR to modify [RequestParameterProducer](https://github.com/omnifaces/omnifaces/blob/master/src/main/java/org/omnifaces/cdi/param/RequestParameterProducer.java#L141) with `context.addMessage(component.getClientId(context), createError(violation.getMessage().replace("{jsf.label}", label)));` although the root cause of the issue might be the fact that `JsfLabelMessageInterpolator` is not called in that situation.

I would imagine in that situation `javax.faces.validator.BeanValidator.JsfAwareMessageInterpolator` should be called and delegate to `JsfLabelMessageInterpolator`. Not sure why it's not in that situation...

**Comment by vanduynslagerp** [comment]
Actually after some investigations, `JsfAwareMessageInterpolator` is called. But it's the method `interpolate(String messageTemplate, Context context)` that it is called rather than `interpolate(String messageTemplate, Context context, Locale locale)`.

It turns out that `interpolate(String messageTemplate, Context context)` doesn't replace `{jsf.label}`.

Is there a particular reason for that ?

**Comment by BalusC** [comment]
@arjantijms This was an oversight, I guess? The `JsfLabelMessageInterpolator#interpolate(String messageTemplate, Context context)` should instead of delegating to the wrapped delegate to `interpolate(String messageTemplate, Context context, Locale locale)` with `Faces#getLocale()`.

**Comment by arjantijms** [comment]
@BalusC most likely indeed so. It's been a while since I worked on this though.

**Comment by BalusC** [comment]
Fix is available in today's latest [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).

Thank you for reporting and improving OmniFaces!
