### ISSUE TITLE
Unable to locate BeanManager with Weld on plain Tomcat

### ISSUE THREAD

**Issue by michelepra** [omnifaces/omnifaces#243]
like this [mojarra issue](https://java.net/jira/browse/JAVASERVERFACES-3774) omnifaces is unable to locate BeanManager.
I made a patch to solve this issue that is like mojarra code in file com.sun.faces.util.Util.java accepted patch.

`Map<String, Object> applicationMap = facesContext.getExternalContext().getApplicationMap();`
`result = (BeanManager) applicationMap.get("org.jboss.weld.environment.servlet.javax.enterprise.inject.spi.BeanManager");`

**Comment by BalusC** [comment]
I will add this, but the correct solution, however, is to register bean manager in JNDI via `/META-INF/context.xml`.

**Comment by michelepra** [comment]
I agree with you that correct solution is register bean manager in JNDI, but sometimes (like mojarra issue say) JNDI fail to detect.
For example try with an empty maven project with all depedency required by omnifaces, set jetty-maven-plugin with correct configuration for using weld in particular set bean manager in JNDI (you can use listener or other jetty specific file configuration). Run goal jetty:run and you can see that bean manager is not retrived by JNDI, with jetty:run-war bean manager was correctly detected.
I don't know if this is only a jetty-maven-plugin (or tomcat) issue but there is a reason why developers of mojarra accepted this workaround as valid solution.

I hope you add this soon. Thanks

**Comment by arjantijms** [comment]
>I don't know if this is only a jetty-maven-plugin (or tomcat) issue but there is a reason why developers of mojarra accepted this workaround as valid solution.

Thanks for mentioning that. (btw we are also among the developers of Mojarra ;))

If possible, could you also try to address the issue with the developers of the jetty-maven-plugin? If it's also fixed there this would increase the chances of it working for anyone greatly. Thanks again!

**Comment by BalusC** [comment]
Same problem happens with Tomcat when you incorrectly use `tomcat:run` instead of `tomcat:run-war`. Moreover, CDI bean management and injection wouldn't work at all in many cases, resulting in `PropertyNotFoundException: Target unreachable` over all place.

**Comment by BalusC** [comment]
Implemented, OmniFaces does now not anymore require /META-INF/context.xml on Tomcat+Weld. 

Fix is available in today's [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).

**Comment by BalusC** [comment]
The alternate fix caused a deploy fail in WildFly as it violated a servlet spec "Programmatically added Listener is not allowed to programmatically register Filters/Servlets". The ApplicationListener is now back to `@WebListener`, but there will be no `FacesContext` available as it runs before JSF's own listener and then there will be also no `ServletContext` (which the alternate fix was relying on).

I will look back later.

**Comment by BalusC** [comment]
Today's latest [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT) with the fix works now in Tomcat/Payara/WildFly.
