### ISSUE TITLE
OmniFaces breaks FacesConverter contract

### ISSUE THREAD

**Issue by michaelom** [omnifaces/omnifaces#25]
Repost from googlecode:

Ever since FacesConverters have been made available as CDI InjectionTargets, one of our FacesConverters does not work as expected. The converter has a no-args Constructor (for partial state saving feature) plus a constructor with a Class<?> parameter.

```
public MyCoolConverter(Class<?> target) {
    this.clazz = target;
}
```

The FacesConverter's JavaDoc states:
"...If a converter has a single argument constructor that takes a Class instance and the Class of the data to be converted is known at converter instantiation time, this constructor must be used to instantiate the converter instead of the zero-argument version..."

Using plain Mojarra the Converter is instantiated as expected, using the aforementioned constructor. Since OmniFaces uses CDI to manage the instantiation (and lifecycle) of a FacesConverter-Bean I do not see how this can be achieved (in a clear manner).

Any advice on workarounds is appreciated.

**Comment by BalusC** [comment]
Noted should be that new JSF 2.3 `@FacesConverter(managed=true)` in its current form also doesn't support it.

**Comment by arjantijms** [comment]
Additionally it should be noted that the 2.3 `@FacesConverter(managed=true)` does not do any attempt to look up super classes or super interfaces. 

In other words, of the following list from the [Application#createConverter](https://docs.oracle.com/javaee/7/api/javax/faces/application/Application.html#createConverter-java.lang.Class-) javadoc:

* Locate a Converter registered for the target class itself.
* Locate a Converter registered for interfaces that are implemented by the target class (directly or indirectly).
* Locate a Converter registered for the superclass (if any) of the target class, recursively working up the inheritance hierarchy.

Only the first item it supported.

**Comment by BalusC** [comment]
Best I could do for now is to simply skip the coverter for CDI if it has no default c'tor or has a c'tor taking Class argument.
