### ISSUE TITLE
Numbers#formatThousandsUnit does not formats with maxfractions if number < base

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#251]
`of:formatThousandsUnit('2.3333333333333','W')` ends up as `2.3333333333333 W`, while `2.33 W`is expected.

**Comment by BalusC** [comment]
Fixed along with #252

**Comment by BalusC** [comment]
Initially, values lower than 1000 are unaffected, as documented. I however agree that this is not nice. Now values lower than 1000 are formatted too, including 999.999 which becomes 1k. Improvement is available in today's [2.4 snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT). Thank you for reporting and improving OmniFaces!

**Comment by jepsar** [comment]
Yeah, the original code was designed to handle bytes (integers), that's probably how this must have slipped in. Thanks for fixing!
