### ISSUE TITLE
Numbers#formatThousandsUnit returns false values

### ISSUE THREAD

**Issue by p-kp** [omnifaces/omnifaces#252]
Following numbers return wrong formated values:
`#{of:formatThousandsUnit(179945, 'm')}` -> 18 km
expected: 179,9 km
`#{of:formatThousandsUnit(280306, 'm')}` -> 28 km
expected: 280,3 km
`#{of:formatThousandsUnit(550297, 'm')}` -> 55 km
expected: 550,3 km

edit: I use Omnifaces v2.3

**Comment by BalusC** [comment]
That was embarrassing. Trailing zeroes were unintentionally stripped from non-fractional numbers as well. Fix is available in today's [2.4 snapshot](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).

Do note that the precision is 3, as documented. So the actual results are 180, 280 and 550.

**Comment by p-kp** [comment]
Thank you! I tested it and it works like expected.
