### ISSUE TITLE
Provide a way to use Collections.reverse(...) in el

### ISSUE THREAD

**Issue by xfr-dev** [omnifaces/omnifaces#257]
I think it would be useful to be able to use Collections.reverse(...) in el. Using directly a function or indirectly by converting to an array first.

**Comment by BalusC** [comment]
The view isn't supposed to manipulate the model, so Collections#reverse(), which would directly reflect changes back in the model, isn't a good idea. I have at least added of:reverseArray which returns a copy of the array, in reversed order. 

It's available in 2.4-SNAPSHOT.

**Comment by xfr-dev** [comment]
Ok, i agree with you statement and i will test this as soon as possible. Thank you.
