### ISSUE TITLE
Deployment Error with wildfly  10 development mode 

### ISSUE THREAD

**Issue by javanance** [omnifaces/omnifaces#260]
Environment: Wildfly 10.0, JSF 2.2.8, Omnifaces 2.3, Primefaces 5.3

**listings in  web.xml**

```
<context-param>
    <param-name>org.jboss.weld.development</param-name>
    <param-value>true</param-value>
  </context-param>
```

**Error Log** 

WELD-001504: Intercepted bean method [EnhancedAnnotatedMethodImpl] @SafeVarargs private final transient org.omnifaces.cdi.push.SocketChannelManager.register(Serializable, String, Map<String, String>, Map<String, String>[]) (intercepted by org.jboss.weld.probe.InvocationMonitor) cannot be declared final

Otherwise my war is deployed successfully in wildfly 10.0

thanks.

**Comment by BalusC** [comment]
If `final` is removed, then `@SafeVarargs` cannot be used. If it is removed, code will compile and run but only generate annoying "possible heap pollution" warnings which needed to be suppressed with `@SuppressWarnings`. 

I did so.

Fix is available in today's [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).
