### ISSUE TITLE
CombinedResourceHandle incompatibility between Omnifaces 2.3 and Primefaces 6.0

### ISSUE THREAD

**Issue by feverdog** [omnifaces/omnifaces#263]
Greetings,

Omnifaces 2.3 has an incompatibility issue with Primefaces 6.0.
Primefaces JS and CSS are no longer loaded if using the CombinedResourceHandler due to the fact that they were refactored and are no longer named `primefaces.css` and `primefaces.js.`

They are now named: `components.css`, `core.js` and `components.js`.

Is there an workaround for this? I have tried to exclude old resource names from the handler and add the new ones manually in the .xhtml master template.

Thank you very much for this great work!

**Comment by BalusC** [comment]
`CombinedResourceHandler` doesn't do any specific things with PrimeFaces resources. Moreover, the current snapshot showcase at http://snapshot.omnifaces.org uses PrimeFaces 6.0. What problems exactly are you facing? A reproducer would be helpful.

**Comment by feverdog** [comment]
Greetings,

I am so sorry for this issue, I dug a little deeper and found out it has to do with the custom primefaces theme that I am using.

Sorry for wasting your time and thank you very much.
See ya!
