### ISSUE TITLE
Videos served by FileServlet not playable in Chrome

### ISSUE THREAD

**Issue by alexeypolyakov** [omnifaces/omnifaces#269]
Chrome's video player (html5 video tag) requests file with Range: 0- by default.
Looks like it always expects Content-Range. 
FileServlet adds this header only if range length!=file length.
If I change FileServlet to always add Content-Range header (for all 206 responses) everything works fine.

Tested on Chrome 53.0.2767.4 (Official Build) dev (64-bit), on Ubuntu.

**Comment by BalusC** [comment]
Did you use 2.3 or 2.4-RC1? 

Related: https://github.com/alexeypolyakov/omnifaces/commit/b149204db8ce98db24a649488dc4c71627f1f2ed

**Comment by BalusC** [comment]
Fix is available in today's latest [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT). Let me know if that works out for you.
