### ISSUE TITLE
Cloudflare + CombinedResourceHandler cache

### ISSUE THREAD

**Issue by echer** [omnifaces/omnifaces#271]
Hello, i use cloudflare CDN for cache resources as css and js, but when it generated by CombinedResourceHandler this not cached. 
![selection_021](https://cloud.githubusercontent.com/assets/3532703/16206836/a2d4bc34-3700-11e6-8687-d219f2618e70.png)

Cloudflare say:

> If the Cache-Control header is set to "private", "no-store", "no-cache",  or "max-age=0", or if there is a cookie in the response, then CloudFlare will not cache the resource.

https://support.cloudflare.com/hc/en-us/articles/202775670-How-Do-I-Tell-CloudFlare-What-to-Cache-

How to remove this headers and maintain cache by cloudflare cdn? 

I understand that omnifaces generates resources and makes them accessible as a cdn, but I would like to take these requests from my server and move to the cloudflare cdn. Its correct?

**Comment by BalusC** [comment]
By default, the headers are all fine. I guess it's related to the session cookie. You'd best inspect the response headers if the cookie is there. I don't think there is much we can do from OmniFaces side.

**Comment by echer** [comment]
thanks for the reply, I'll check it out

**Comment by echer** [comment]
I removed the headers "no-store", "no-cache" generated by spring security, now its works.

**Comment by BalusC** [comment]
Great, thank you for the feedback.
