### ISSUE TITLE
Always make server-created cookies HttpOnly

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#272]
https://github.com/omnifaces/omnifaces/pull/232

It's considered bad practice when server-created cookies are modifiable in JavaScript. Instead, such cookies must be created by JavaScript itself.

Ideally, all server-created cookies must be HttpOnly, without exceptions. Currently, `Faces`, `FacesLocal` and `Servlets` utility classes doesn't take into account this.

**Comment by vanduynslagerp** [comment]
Updated #232 per recommendations in the PR comments.

**Comment by BalusC** [comment]
I will implement it once 2.4 has been released and branch is ready for 2.5.
