### ISSUE TITLE
FullAjaxExceptionHandler - exclude exceptions from logging

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#278]
I came across the same problem as there are already multiple questions at SO on how to not log a specific `Exception` like `ViewExpiredException` in `FullAjaxExceptionHandler`.

- http://stackoverflow.com/questions/18003309/silence-fullajaxexceptionhandler
- http://stackoverflow.com/questions/31491764/how-to-turn-off-severe-log-message-when-omnifaces-fullajaxexceptionhandler-handl?lq=1

What about declaring a comma separated list of exceptions in `web.xml` which shall not be logged, so we do not need to override the handler and factory.

	<context-param>
		<param-name>org.omnifaces.EXCEPTION_TYPES_IGNORE_LOG</param-name>
		<param-value>
			javax.faces.application.ViewExpiredException
		</param-value>
	</context-param>

**Comment by BalusC** [comment]
+1

**Comment by BalusC** [comment]
Enhancement is available in today's latest [2.5-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.5-SNAPSHOT).

Thank you for improving OmniFaces!
