### ISSUE TITLE
ValidateBean method forEachInputWithMatchingBase is not able to match base with base from valueReference for dynamic property with base as map object

### ISSUE THREAD

**Issue by vijpan** [omnifaces/omnifaces#280]
Similar to closed #227 - i tested the same reproducer with omnifaces 2.4 and found this issue: (i have made this comment in #227 also).

ValidateBean class - line # 334 - returns false.
Line 334 - `if (valueReference.getBase().equals(base)) {`

The value of "valueReference.getBase()" - comes out to be the "map" object while the value of "base" is the object in which map object is present - so they will never be the same.

i.e. "base" object = `#{testOFController.testOFBean}"`  while
valueReference.getBase() object = `#{testOFController.testOFBean.dataMap}"` 

The same reproducer from #227 can work - change will be omnifaces upgrade to 2.4.

**Comment by BalusC** [comment]
This is after all the same issue as https://github.com/omnifaces/omnifaces/issues/247

In a nutshell: detecting and updating nested properties is not trivial in EL. But will surely look at it, also for JSF 2.3.
