### ISSUE TITLE
Review all CDI related workarounds against currently available servers

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#281]
- `beans.xml` was for long only CDI 1.0 in order to be TomEE 1.7.x compatible. Now TomEE 7.x is out for some time, it can be updated to CDI 1.1 and give us the opportunity to reliably use `CDI.current()`.
- `WebXml` and `FacesConfigXml` enums have some awkward initialization workaround in order to be WebLogic 12.1 compatible. Check if it can be removed for WebLogic 12.2.
- Check if `@Inject InjectionPoint` workaround in all CDI producers can be removed in current OWB 1.6.3 version.
- Check if any `Beans#getReference()` call can be replaced by `@Inject` or `CDI.current().select()` and still work in all current servers.

**Comment by arjantijms** [comment]
>Check if @Inject InjectionPoint workaround in all CDI producers can be removed in current OWB 1.6.3 version.

If you mean the dynamic producers, then this was fixed in OWB, but unfortunately broke in Weld later again. See: https://issues.jboss.org/browse/CDI-610

**Comment by BalusC** [comment]
No, I didn't mean `InjectionPointGenerator`, I actually meant below construct as found in several producers such as `RequestCookieProducer`.

```
@Inject
private InjectionPoint injectionPoint; // Workaround for OWB not properly passing it as produce argument.

@Produces
@Cookie
public String produce(InjectionPoint injectionPoint) {
    // ...
}
```

**Comment by BalusC** [comment]
Also re-test all CDI functionality in multi-module EAR (two WARs in EAR) and update https://github.com/omnifaces/omnifaces/wiki/Known-Issues-(CDI)

**Comment by BalusC** [comment]
Important news: since Weld 2.3.5 (https://issues.jboss.org/browse/WELD-2143) there are no anymore issues when using OmniFaces in multiple WARs in multi-module EAR!

**Comment by BalusC** [comment]
Closing off as 2.5-RC1 has been released.
