### ISSUE TITLE
graphicImage 'id' doesnt render

### ISSUE THREAD

**Issue by danilomagrini** [omnifaces/omnifaces#294]
I'm trying to update a _oou:graphicImage_ from _Primefaces fileUpload_ but the graphicImage _'id'_ disappear on page load.

**Comment by BalusC** [comment]
This was an oversight. The fix is available in today's latest [2.5-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.5-SNAPSHOT/).

Thank you for reporting and improving OmniFaces!
