### ISSUE TITLE
Could Omnifaces 2.5 add JSF components for choose, when and otherwise which are taghandlers in JSF

### ISSUE THREAD

**Issue by vijpan** [omnifaces/omnifaces#296]

**Comment by BalusC** [comment]
Not necessary. The `rendered` attribute is sufficient for the task.

**Comment by vijpan** [comment]
I think in some scenarios it might come out handy.

If we have bunch of components that needed to be grouped together in
various logic scenario's - rendered attribute of when can help.

Else all these components will end up having duplicate rendered expression
and (not) rendered expression in otherwise.

In several places ui:fragment can help but that will get bloated (in
multiple when along with otherwise scenario)
