### ISSUE TITLE
Add "@global" to showMessageFor attribute of multiple field validators to add global message

### ISSUE THREAD

**Issue by julianomqs** [omnifaces/omnifaces#298]
I think it would be nice to have a option `@global` for `showMessageFor` attribute of multiple field validators.

This option will be used to add the error message as global, instead per component, to be shown in `h:messages`, `p:messages`, `p:growl` or similar.

Example:

```
<o:validateMultiple components="startMonth startYear endMonth endYear"
                    validator="#{myBean.validateMonthYearRange}"
                    message="The date ranges could not be the same."
                    showMessageFor="@global" />
```

What you think?

**Comment by julianomqs** [comment]
If you agree with the idea, I have the code ready, so I can make a pull request.
It worked well.

**Comment by BalusC** [comment]
Reasonable. Do the PR.
