### ISSUE TITLE
Add CDI support to composite backing / custom components

### ISSUE THREAD

**Issue by julianomqs** [omnifaces/omnifaces#302]
I need to inject some EJBs into a backing component of a composite component.

I did a PR to do that, can you evaluate?

P.S.: I did not put `public UIComponent createComponent(FacesContext context, Resource componentResource) overload`. I tried to put Resource as map key, but it didn't work.

**Comment by BalusC** [comment]
This is on the edge with "bad practice" and I'd prefer not to provide and implicitly advocate it from OmniFaces side on.

Just use normal managed beans for this and pass/call them in the composite. Related reading: 
- http://stackoverflow.com/q/37540190/157882
- http://stackoverflow.com/q/30232011/157882
