### ISSUE TITLE
Feature request: Components: reset input(s in form)

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#305]
I've created the code below to my project.  Maybe something to add to `Components`.

````
	/**
	 * Find the {@link UIForm} for the given event's component and
	 * {@link #resetFormInputs(javax.faces.component.UIForm) reset all inputs}.
	 *
	 * @param event
	 */
	public static void resetFormInputsActionListener(ActionEvent event)
	{
		UIForm form = Components.getClosestParent(event.getComponent(), UIForm.class);
		if (form != null) {
			resetFormInputs(form);
		}
	}


	/**
	 * Find all {@link UIInput} components in the given form and
	 * {@link #resetInput(javax.faces.component.UIInput) reset the input}.
	 *
	 * @param form
	 */
	public static void resetFormInputs(UIForm form)
	{
		for (UIInput input : Components.findComponentsInChildren(form, UIInput.class)) {
			resetInput(input);
		}
	}


	/**
	 * Reset the input to value {@code null} and not validated.
	 *
	 * @param input
	 */
	public static void resetInput(UIInput input)
	{
		input.setValue(null);
		input.setSubmittedValue(null);
		input.setLocalValueSet(false);
		input.setValid(true);
	}
````

**Comment by BalusC** [comment]
Makes sense.

**Comment by BalusC** [comment]
Added.

```
Components.resetInputs(event.getComponent());
```

I only did a tree visit instead of findComponentsInChildren() because the latter doesn't take into account all different states of the very same UIInput component when it's enclosed in a repeating component such as h:dataTable.

**Comment by jepsar** [comment]
OK, thanks! I also see I've managed to overlook `input.resetValue();`, thanks for that as well :-)

**Comment by jepsar** [comment]
What if you have a form component? Then you don't need to / cannot find a form in one of the parents. Maybe only check parents if `!(component instanceof UIForm)`?

**Comment by BalusC** [comment]
Reasonable. I improved it.

**Comment by jepsar** [comment]
Sorry, one last thing. I cannot get the tree visit to compile. I had to change `new Callback.WithArgument<UIInput>()` to `new Callback.WithArgument<UIComponent>()`. Is that because I'm using OmniFaces 2.4?

**Comment by BalusC** [comment]
It won't compile when `invoke()` method still takes `UIComponent`.

**Comment by jepsar** [comment]
Clear. Thank you for the prompt responses.

One other thing that came to mind though: for me getting the form and resetting its inputs is what I was going for. In other cases you might just want to reset a panel, subview, etc. Wouldn't it be better to simply reset the child inputs of the given component? If you need to reset a form you can simply get it yourself and use it when calling `resetInputs`.

**Comment by BalusC** [comment]
Makes sense. There's now resetForm() and resetInputs().
