### ISSUE TITLE
Does it make sense to introduce an attribute disable on converter tag handler?

### ISSUE THREAD

**Issue by jlerbsc** [omnifaces/omnifaces#308]
So we can use it on generic composite component and enable or disable it as appropriate by the use case.

**Comment by BalusC** [comment]
A changing converter suggests a changing model type. I.e. a property could randomly change between e.g. Integer and Date. This does in first place indeed not make sense.

Generally you just declare the converter in the client, exactly like as for standard inputs.

```
<your:composite>
    <f:someConverter ... />
</your:composite>
```

**Comment by jlerbsc** [comment]
Great. Thanks for your tip.

**Comment by jlerbsc** [comment]
In this case, how do you set the converterMessage attribute?
