### ISSUE TITLE
preRenderComponent and OmniViewHandler.validateComponentTreeStructure

### ISSUE THREAD

**Issue by canatoly** [omnifaces/omnifaces#309]
We have some initialization on preRenderComponent event for composite component, but now visiting tree for finding nested forms leads to empty "getters"

**Comment by BalusC** [comment]
Not exactly sure what you mean with empty getters and how that is causing a problem.

Composite initialization is by the way better done during PostAddtoView event. See also a.o. http://stackoverflow.com/q/21525669/157882

**Comment by canatoly** [comment]
Wrong event (preRenderComponent) for initialization was the real problem. With postAddToView event everithing is fine. Thank you for hinh and sorry for wasting your time
