### ISSUE TITLE
Provide support for <optgroup>

### ISSUE THREAD

**Issue by kalgon** [omnifaces/omnifaces#314]
Do you think it would be possible to implement option groups with something like this:

```
<h:selectOneMenu...>
    <o:selectGroup groupLabel="#{msgs.myGroupLabel}" groupDisabled="#{false}">
        <f:selectItems value="#{globalBean.items}" var="item" itemValue="#{item}" itemLabel="#{item.name}" />
    </o:selectGroup>
    <o:selectGroup...>...</o:selectGroup>
</h:selectOneMenu>
```

or

```
<h:selectOneMenu...>
    <o:selectGroups value="#{globalBean.groups}" var="group" groupLabel="#{group.name}" groupDisabled="#{group.disabled}">
        <f:selectItems value="#{group.items}" var="item" itemValue="#{item}" itemLabel="#{item.name}" />
    </o:selectGroups>
</h:selectOneMenu>
```

`o:selectGroup` would need to extend `f:selectItem` and wrap all children elements in a single `SelectItemGroup` while `o:selectGroups` would extend `f:selectItems` and create a list of `SelectItemGroup`s.

That does not sound too difficult to me but as I am no JSF expert, there may be complications I am not aware of.

**Comment by BalusC** [comment]
JSF already has `SelectItemGroup`: http://stackoverflow.com/q/31905878/157882 does that suit your needs?

**Comment by kalgon** [comment]
Hi, yes I know JSF supports `SelectItemGroup` but you need to create the groups in your model/managed bean, not in your view. I think it would be nice to have something like this in your model/managed bean:
```java
@ManagedBean
public class StoreBean {
    public List<Category> getCategories() { ... }
}
public class Category {
    public List<Product> getProducts() { ... } 
    public String getName() { ... }
}
public class Product {
    public String getName() { ... }
}
```
which is totally `SelectItemGroup`-agnostic and have the view automatically create the groups by doing something like:
```
<h:selectOneMenu>
    <o:selectGroups value="#{storeBean.categories}" var="category" groupLabel="#{category.name}">
        <f:selectItems value="#{category.products}" var="product" itemValue="#{product}" itemLabel="#{product.name}" />
    </o:selectGroups>
</h:selectOneMenu>
```
or
```
<h:selectOneMenu>
    <o:selectItems value="#{storeBean.categories}" var="category" groupLabel="#{category.name}" items="#{category.products}" itemVar="product" itemValue="#{product}" itemLabel="#{product.name}" />
</h:selectOneMenu>
```
What do you think?

**Comment by BalusC** [comment]
I do agree this is a missing feature in JSF. I will look at it.

**Comment by vanduynslagerp** [comment]
In support of this feature request, it's currently impossible with JSF to generate `<optgroup>` elements and use passthrough attributes.
As mentioned above the only option to generate `<optgroup>` elements is to use `SelectItemGroup ` and `<f:selectItems>`. The problem with `<f:selectItems>` is that passthrough attributes do not works (http://stackoverflow.com/a/29676353/2238351).

Ideally something like that should be possible:
```html
<c:forEach items="#{storeBean.categories}" var="category">
  <o:selectGroups  groupLabel="#{category.name}" pt:data-icon="#{category.icon}">
    <c:forEach items="#{category.products}" var="product">
      <f:selectItem itemValue="#{product}" itemLabel="#{product.name}" pt:data-icon="#{product.icon}" />
    </c:forEach>
  </o:selectGroups>
</c:forEach>
```
Or maybe something like that:
```html
<h:selectOneMenu>
    <o:selectItems value="#{storeBean.categories}" var="category" groupLabel="#{category.name}" items="#{category.products}" itemVar="product" itemValue="#{product}" itemLabel="#{product.name}" pt:data-icon="#{product.icon}" />
</h:selectOneMenu>

```
But in that 2nd case there wouldn't be any way to determine if `pt:data-icon="#{product.icon}"` applies to the `<optgroup>` or the `<option>`...

**Comment by BalusC** [comment]
Finally, `<o:selectItemGroups>` has been added.

Usage example:
```
<h:selectOneMenu value="#{bean.selectedProduct}" converter="omnifaces.SelectItemsConverter">
    <f:selectItem itemValue="#{null}" />
    <o:selectItemGroups value="#{bean.categories}" var="category" itemLabel="#{category.name}">
        <f:selectItems value="#{category.products}" var="product" itemLabel="#{product.name}" />
    </o:selectItemGroups>
</h:selectOneMenu>
```
