### ISSUE TITLE
o:inputFile required

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#315]
As pointed in http://stackoverflow.com/questions/39617729/oinputfile-optional-and-accept-validation?noredirect=1#comment66544309_39617729 I'm not able to use an inputFile and leave it blank if the accept field is not empty.

It happens in any browser (chrome and edge)

I'm providing a sample project

Myfaces 2.2.10, tomee

**Comment by cocorossello** [comment]
[example.zip](https://github.com/omnifaces/omnifaces/files/485328/example.zip)

**Comment by BalusC** [comment]
This is caused by MyFaces.

**Comment by BalusC** [comment]
o:inputFile will now by default always consider empty parts as null.
