### ISSUE TITLE
Log4j2 context param ignored if Omnifaces 2.x is used

### ISSUE THREAD

**Issue by jansohn** [omnifaces/omnifaces#316]
If I use Omnifaces together with log4j2 and an external configuration file specified in the `web.xml`, the context parameter specifying the location of the external log4j2 config file is being ignored. If I don't use Omnifaces the context parameter is properly read.

    <context-param>
    		<param-name>log4jConfiguration</param-name>
    		<param-value>file://${user.dir}/conf/custom_log4j2.xml</param-value>
    </context-param>

Reproducable webapp:
https://github.com/jansohn/log4j2OmnifacesWebapp

I've tried it with Java 8 and Tomcat 8.

**Comment by BalusC** [comment]
This is a bug in Tomcat. I reported it: https://bz.apache.org/bugzilla/show_bug.cgi?id=60164

Workaround: add `log4j-web*.jar` to `tomcat.util.scan.StandardJarScanFilter.jarsToScan` property of `conf/catalina.properties`.
