### ISSUE TITLE
Add Ajax.delete(clientId), Ajax.insertAfter(clientId, afterClientId) and Ajax.insertBefore(clientId, beforeClientId)

### ISSUE THREAD

**Issue by pvdlg** [omnifaces/omnifaces#320]
JSF Ajax APi (jsf.js) can handle insert after/before [(jsf.js)](https://github.com/javaserverfaces/mojarra/blob/master/jsf-api/src/main/resources/jsf.js#L1582) and delete [(jsf.js)](https://github.com/javaserverfaces/mojarra/blob/master/jsf-api/src/main/resources/jsf.js#L1571) directive in the partial XML response.

Although it seems these features are not used by any standard JSF component or methods.

Would it be possible to add the utility methods `Ajax.delete(clientId)`, `Ajax.insertAfter(clientId, afterClientId)` and `Ajax.insertBefore(clientId, beforeClientId)`, similar to [Ajax.update(String... clientIds)](https://github.com/omnifaces/omnifaces/blob/develop/src/main/java/org/omnifaces/util/Ajax.java#L133) ?

The main use case would be to delete / insert new entries in lists or tables without having to refresh the whole list/table.
It would be particularly useful in situation where you have javascript interaction on client side (such as expand/collapse a div in a list element)  and don't want to reload the whole table/list that would "erase" the visual modification done on client side.

**Comment by BalusC** [comment]
Idea is understood, but this is actually not that trivial to implement without interfering with update and creating duplicate elements with same ID. It's better to improve `Ajax.update()` to utilize those hidden features by detecting if a component has previously been rendered to HTML output or not. But this in turn is rather non-trivial and expensive to track.

**Comment by BalusC** [comment]
FYI: I played around it ~2y ago but in the end stumbled upon a roadblock when the datatable is backed by a custom DataModel such as PrimeFaces LazyDataModel. It wasn't possible to get it to work in a generic way without implementing impl/lib-specific hacks.

**Comment by BalusC** [comment]
Closing off because it's technically not possible. At least not in a impl/lib-independent way.
