### ISSUE TITLE
InputFile fails Javascript when I use maxSize

### ISSUE THREAD

**Issue by garcia-jj** [omnifaces/omnifaces#323]
I'm using `o:inputFile` tag like this:

```
<o:inputFile value="#{view.file}" accept="image/*" maxsize="1048576">
    <f:ajax listener="#{view.doUpload}" render="@form" />
</o:inputFile>
```
And when I select a file, I got a Javascript error in this line:
https://github.com/omnifaces/omnifaces/blob/develop/src/main/resources/META-INF/resources/omnifaces/inputfile.unminified.js#L41

The output HTML is:

```
OmniFaces.InputFile.validate(event,this,'globalMessages',1048576)
```

I think the error is because `globalMessages` exists in my XHTML (its a `o:messages` component), but since there are no messages to show in the page, the element doesn't exists.

Its possible to use a validation if this element is not null before call `innerHTML`?

About my environment: I'm using JSF 2.2 only with core implementation + Omnifaces. There are no Primefaces/Richfaces components. I'm also using JQuery 3 and some plugins.

Thank you

**Comment by BalusC** [comment]
I understand you're using `<o:messages var="...">`? This will by design indeed render nothing by itself. You're fully responsible for the generated markup. You could solve this specific problem by manually adding a `<div id="globalMessages">`.

```
<div id="globalMessages">
    <o:messages id="globalMessages" var="...">
        ...
    </o:messages>
</div>
```
