### ISSUE TITLE
o:messages Support for Iterating Components

### ISSUE THREAD

**Issue by matt328** [omnifaces/omnifaces#325]
It would be nice if `<o:messages>` could use `UIComponent.visitTree` when gathering messages from child components instead of `Components.findComponentsInChildren`.  I have a data table using `h:dataTable` with in-place editing of row data.  Rather than change the structure of the table and insert validation messages everywhere, I'd like to just display a list of validation messages below the table, and highlight the fields inside the table.

I realize there may not be many more use cases for this UI decision, but the data in my table is fairly simple, and so are the validation rules.

Edit: I have just seen issue #32, but it doesn't appear to be working anymore?

**Comment by BalusC** [comment]
#32 only deals with messages targeting an UIInput component directly. The findComponentsInChildren() is only used when target component isn't an UIInput.
