### ISSUE TITLE
2.5.1 - cdi injection in FacesConverter doesn't works

### ISSUE THREAD

**Issue by ssette** [omnifaces/omnifaces#331]
I'we tried to upgrade from 2.1 to 2.5.1 but there is an issue with cdi/ejb injection into faces converter (null pointer exception)

Glassfish 4.1.1
Mojarra jsf 2.2.12
PrimeFaces 6.0

The same code works fine with omnifaces 2.1 (changing the bean-discovery-mode to all in bean.xml)

**Comment by BalusC** [comment]
This is a bug in GlassFish 4.1.1. It works fine in Payara 4.1.1.x.

This is related to #281.

I recommend upgrading the server too. Else keep it to OmniFaces 2.4.
