### ISSUE TITLE
FullAjaxExceptionHandler ignoring the parameter org.omnifaces.EXCEPTION_TYPES_TO_UNWRAP

### ISSUE THREAD

**Issue by julianomqs** [omnifaces/omnifaces#333]
Hello,

I'm using `FullAjaxExceptionHandler` and I ran into a problem:

`FullAjaxExceptionHandler` ignoring the parameter `org.omnifaces.EXCEPTION_TYPES_TO_UNWRAP`.

This happens because line **333** of method **parseExceptionTypesParam**:

```java
@SuppressWarnings("unchecked")
	private static Class<? extends Throwable>[] parseExceptionTypesParam(ServletContext context, String paramName, Set<Class<? extends Throwable>> defaults) {
		Set<Class<? extends Throwable>> types = new HashSet<>();

		if (defaults != null) {
			types.addAll(defaults);
		}

               // Problem is the line below		
               String typesParam = context.getInitParameter(PARAM_NAME_EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING);

		if (!isEmpty(typesParam)) {
			for (String typeParam : typesParam.split("\\s*,\\s*")) {
				try {
					types.add((Class<? extends Throwable>) Class.forName(typeParam));
				}
				catch (ClassNotFoundException e) {
					throw new IllegalArgumentException(
						String.format(ERROR_INVALID_EXCEPTION_TYPES_PARAM_CLASS, paramName, typeParam), e);
				}
			}
		}

		return types.toArray(new Class[types.size()]);
	}
```

As you can see, the parameter `paramName` is being ignored and `PARAM_NAME_EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` is fixed.

I ran WildFly in debug mode, and checked `FullAjaxExceptionHandler` class, the `exceptionTypesToUnwrap` array always have the default values, `FacesException` and `ELException`.

I forked and made the change, tested and it solved the problem, so I created the PR #334.

Can you take a look, and if possible, make a hotfix release to solve this problem, please?

**Comment by BalusC** [comment]
Whoops, fixed, thank you for reporting!
