### ISSUE TITLE
Bug with o:validateBean and composite components

### ISSUE THREAD

**Issue by recentralized** [omnifaces/omnifaces#342]
Hi Bauke, I've opened pull request  #341 which solves a problem with o:validateBean when it's value attribute references a composite component attribute, e.g.:

  <o:validateBean value="#{cc.attrs.controller.entity}" .../>

Within the ValidateBean tag handler, the ValueExpression evaluation returns null, then ValidateBean continues down a path as if the value attribute was never specified.

My limited understanding is that UIComponent "visitation" needs to happen in order to resolve #{cc...} expressions.

**Comment by BalusC** [comment]
It's available in today's 2.6-SNAPSHOT.
