### ISSUE TITLE
o:skipValidators inside composite component issue

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#344]
I have a composite component which exposes some client behaviors through `cc:clientBehavior`. If, when using it, I attach to it an `o:skipValidators`, I get an IllegalStateException:
`Parent component of o:skipValidators must be an instance of UICommand or ClientBehaviorHolder.`
I can provide example xhtml if needed.

UPDATE:
I know binding my composite to an UINamingContainer which implements ClientBehaviorHolder could be the solution, but I'd prefer to be as DRY as possible, and if I implement ClientBehaviorHolder I'd have to correctly override the methods `getEventNames()` and `getDefaultEventName()` for every composite component, keeping java code synchronized with the xhtml...

**Comment by BalusC** [comment]
If you composite represents an input component, let your backing component extend from `UIInput`. It has already a basic implementation for `ClientBehaviorHolder`.
