### ISSUE TITLE
Minimal "what's new" and documentation for 1.1x versions?

### ISSUE THREAD

**Issue by mauromol** [omnifaces/omnifaces#345]
I understand the main development effort is on >=2.x, but it would be useful if a minimal "what's new" section were available on the website for 1.1x versions. As an example, I was using OmniFaces 1.10 and decided to try to update to 1.14, but it's something like a blind upgrade because I could not find any changelog, what's new or such in all the omnifaces.org website (please correct me if I'm wrong).

Also, the online Javadoc documentation seems to be available only for <=1.8 and >=2.0.

If you're wondering why I'm not upgrading to 2.x, it's because I'm using Spring and not CDI.

Thank you!

**Comment by BalusC** [comment]
2.x was continuously merged into 1.1x but *without* **new** <o:xxx> tags. All components/tags and utility classes which already existed in 1.x were continuously being merged (and therefore updated) in 1.1x, including new attributes which were only added in 2.x.

I however do agree that there should be VDL and API documentation for this. I'll generate VDL sooner or later. As to API, in the meanwhile you can just use javadoc.io for that which extracts the documentation from **-javadoc.jar files in Maven: http://javadoc.io/doc/org.omnifaces/omnifaces/1.14

**Comment by BalusC** [comment]
VDL and API docs have been added to homepage.
