### ISSUE TITLE
o:socket throws exception sometimes

### ISSUE THREAD

**Issue by Sniffie** [omnifaces/omnifaces#346]
Hi,
we are using the omnifaces socket tag with the following attributes in our master template:
<o:socket channel="userChannel" onmessage="onPushMessage" user="#{bean.userId}" />

Generally the socket is working fine, but once a day, the application server must be restarted because of the following exception:
java.lang.IllegalArgumentException: o:socket channel 'userChannel' is already registered on a different scope. Choose an unique channel name for a different channel (or shutdown all browsers and restart the server if you were just testing).

We are only using this socket tag in one master template.

Current version of omnifaces: 2.4
[exception.txt](https://github.com/omnifaces/omnifaces/files/729194/exception.txt)

**Comment by BalusC** [comment]
That can theoretically happen if `user` attribute ever evaluates to `null`.

I'll look at it, but for now, either don't render the socket if there is no user, or explicitly set `scope="session"`.

**Comment by Sniffie** [comment]
Thank you BalusC for the quick answer! Theoretically, the master template is only rendered, if the user is logged in and has a user id.
I will check the user id now first and set the scope to session explicitly! 👍
