### ISSUE TITLE
Bug with o:validateBean and composite components (again)

### ISSUE THREAD

**Issue by recentralized** [omnifaces/omnifaces#347]
Hi Bauke, in lieu of being able to reopen issue #342, I'm creating this new bug.

Turns out that my fix (that you had merged) only works if `h:form` is defined in the calling page.  Recently I moved `h:form` to be within the composite component and discovered that the `o:validateBean` `ValueExpression` was still evaluating to `null`.

Examples:

    The following worked after fixing issue #342:
    
      demo.xhml:
        <h:form>
          <foo:testDialog bean="#{controller.entity}"/>
        </h:form>
    
      resources/foo/testDialog.xhtml:
        <cc:implementation>
          <o:validateBean value="#{cc.attrs.bean}"/>
        </cc:implementation>
    
    However that fix did not work for the following:
    
      demo.xhtml:
        <foo:testDialog bean="#{controller.entity}"/>
    
      resources/foo/testDialog.xhtml:
        <cc:implementation>
          <h:form>
            <o:validateBean value="#{cc.attrs.bean}"/>
          </h:form>
        </cc:implementation>

**Comment by recentralized** [comment]
Fixed in pull request #348

**Comment by BalusC** [comment]
I fixed it in Components#forEachComponent() side and added two composite based cases to integration test. Today's latest 2.6-SNAPSHOT contains the fix, please let me know if that works for you too.

**Comment by recentralized** [comment]
> I fixed it in Components#forEachComponent() side and added two composite based cases to integration test. Today's latest 2.6-SNAPSHOT contains the fix, please let me know if that works for you too.

I tested the develop branch (at commit b2b749) and reviewed the recursive call you put in `Components.invoke` and confirmed the bug is fixed for my application.  Thanks!
