### ISSUE TITLE
HttpServletResponseOutputWrapper: missing overrides

### ISSUE THREAD

**Issue by joseflaviojr** [omnifaces/omnifaces#350]
At **org.omnifaces.servlet.HttpServletResponseOutputWrapper**, line 90, should override:
```
new ServletOutputStream() {
    ...
    public void setWriteListener( WriteListener listener )
    public boolean isReady()
    ...
}
```

**Comment by BalusC** [comment]
That method was added in Servlet 3.1. OmniFaces 2.x has a Servlet 3.0 dependency. In upcoming OmniFaces 3.0 I will add it.
