### ISSUE TITLE
omnifaces 2.6 cannot be used with java 1.7

### ISSUE THREAD

**Issue by blixon** [omnifaces/omnifaces#358]
Web application using omnifaces 2.6 and java 1.7 cannot be deployed: 

GRAVE: Critical error during deployment: 
java.lang.NoSuchMethodError: java.lang.reflect.Method.getParameterCount()I
	at org.omnifaces.el.FacesELResolver.<clinit>(FacesELResolver.java:57)

The method java.lang.reflect.Method.getParameterCount() exists in java 1.8, but not in java 1.7.

Using getParameterTypes().length to get the total number of parameters will fix this.

**Comment by BalusC** [comment]
That shouldn't have been possible with pom.xml set to 1.7. I will investigate this.

For now, it has been fixed in today's latest [2.6.1-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.6.1-SNAPSHOT/). If you confirm that it works, then I will release it.

**Comment by blixon** [comment]
Version 2.6.1-SNAPSHOT solves the problem. Deployment of my web app is now successfull.

By the way, BalusC, I would like to thank you for everything you do. You make my life much more comfortable.
