### ISSUE TITLE
Custom HeadRenderer for CombinedResourceHandler not working

### ISSUE THREAD

**Issue by julianomqs** [omnifaces/omnifaces#359]
The custom `HeadRenderer` mentioned in https://github.com/omnifaces/omnifaces/wiki/Combine-hardcoded-PrimeFaces-resources-using-CombinedResourceHandler is not working.

When that `HeadRenderer` is used in combination with `CombinedResourceHandler` the js file is not supplied.

It is not even in showcase anymore.

Test case in https://github.com/julianomqs/testcase2

**Comment by BalusC** [comment]
That wiki indeed needs an update. It's only valid until PrimeFaces 5.x. PrimeFaces 6.0 changed things here and there, but with bugs. I'm basically waiting for PrimeFaces 6.1 to see how it behaves. In the meanwhile, your best bet is putting back JSF impl's own `HeadRenderer`, e.g. when you're using Mojarra,

```
    <renderer>
        <component-family>javax.faces.Output</component-family>
        <renderer-type>javax.faces.Head</renderer-type>
        <renderer-class>com.sun.faces.renderkit.html_basic.HeadRenderer</renderer-class>
    </renderer>
```

and manually defining the PrimeFaces CSS/JS resources in some master template.

**Comment by BalusC** [comment]
The wiki has been updated.

Thanks for reporting!
