### ISSUE TITLE
o:inputHidden with label support

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#360]
Strangely h:inputHidden does not provides a label attribute.
I use h:inputHidden sometimes in cases it is bound to a client widget.

But it does not provides a label for required or validation messages which is not so user-friendly in that case.

**Comment by BalusC** [comment]
You could add it using `<f:attribute>`.

**Comment by djmj** [comment]
Did not knew that validation messages will still use it. Thank you.

**Comment by BalusC** [comment]
It's indeed undocumented, but as it extends from UIInput, it should just work. The f:attribute may be useful when your IDE considers it as an error when you specify an undocumented attribute and then annoyingly underlines it red..
