### ISSUE TITLE
Enhance ExceptionHandling

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#367]
Current JSF exception-handling is a too naive approach, thinking that a website is just a small application. It only allows to define one location in case a certain exception is thrown.

    <error-page>
        <exception-type>javax.faces.application.ViewExpiredException</exception-type>
        <location>/index.jsf</location>
    </error-page>

Big websites consist of multiple applications. The most simple example is a dedicated mobile website sitting in a sub-directory _/sites/mobile_.

What happens if an exception is thrown from this mobile navigation path? Maybe it its URL is rewritten and behind a proxy to make it available at _mobile.mydomain.com_.

**Enhancement:**

JSF should allow to define prefix-free rules, similar to URL rewriting:

    <error-page>
        <exception-type>javax.faces.application.ViewExpiredException</exception-type>
        <message detail="#{msg.errorViewExpired}" summary="#{msg.error}" target=":growl"/>
        <rule target="/sites/mobile*" location="/sites/mobile/error/expired.xhtml">
        <rule target="*" location="/sites/error/expired.xhtml">
    </error-page>

**Example:**

For our case we just want to go to main page, where user will automatically be logged in again (remember-me cookie available). To include-view-params since page is URL-rewritten is also necessary.
Also useful for multi-tenancy applications.

        <rule target="/sites/mobile/*" location="/sites/mobile/index.xhtml?includeViewParams=true">

**Message:**

If one could define a _FacesMessage_ in the config that will be pushed, the user could be informed about its expired view for example right after reload (like PrimeFaces growl).

Without such a solution everyone needs to hardcode those rules into their own exception-handler.
It is a little similar to OCPsoft rewrite module but far less complex, so i posted this feature here.

**Comment by BalusC** [comment]
This goes beyond OmniFaces' scope. 

If it were me I would in a servlet filter rethrow the exception as a more specific exception and declare another error page location for it. If I'd have more time, then I'd even go a step further back and just make use of responsive design so you can keep using a single URL for all types of clients.

**Comment by djmj** [comment]
Yes thats why i was not sure. But responsive design is not the solution. For the mobile / desktop problem yes. We serve multiple websites with different PrimeFaces themes depending on client. 

Client is identified as view param behind a reverse proxy and rewritten URL.

www.client1.de -> /sites/client.xhtml?id=1 -> Theme blue
www.client2.de -> /sites/client.xhtml?id=2 -> Theme red

They all get redirected to same error page if i don't catch and check from which url and params they came from.
