### ISSUE TITLE
Relative paths are broken by the CombinedResourceHandler

### ISSUE THREAD

**Issue by stephanrauh** [omnifaces/omnifaces#371]
Bootstrap uses relative paths to address the Glyphicons font. After combining the CSS resources with OmniFaces, the relative path points to the wrong folder (a parent folder instead of the Glyphicons folder). This is because the Bootstrap CSS file is in a subfolder, while the virtual CSS resource is located in the root folder.

I suppose this is a common problem. Bootstrap is just a special case. In general, you can fix this by modifying the CSS files manually, but in the case of BootsFaces this is not possible because it's meant to work with and without OmniFaces.

Is there a way to solve the problem?

Also see https://github.com/TheCoder4eu/BootsFaces-OSP/issues/688.

**Comment by stephanrauh** [comment]
It seems we've found a workaround for BootsFaces, but I think relative paths are a common problem.

**Comment by BryanV91** [comment]
Resources in JSF are a bit tricky at the beginning, you will have this problem with FontAwesome, Bootstrap, Glyphicons, etc. The only way to handle this, is using references in your static files (CSS).

From this:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('../fonts/glyphicons-halflings-regular.eot'); 
}
```

To this:

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url("#{resource['bootstrap:fonts/glyphicons-halflings-regular.eot']}");  
}
```

Tedious, if you ask me.

**Comment by tandraschko** [comment]
AFAIR relative paths were never supported directly therefor some years ago a addon resourcehandler was developed: http://myfaces.10567.n7.nabble.com/Advanced-JSF-2-ResourceHandler-for-MyFaces-commons-td16199.html

**Comment by BalusC** [comment]
Unfortunately this is a technical limitation. I've already brainstormed for long about this while working on `UnmappedResourceHandler`. There is no silver bullet. You should really prefer absolute paths over relative paths in JSF resources.

Related reading:
- http://stackoverflow.com/questions/6925733
- http://stackoverflow.com/questions/31434885
