### ISSUE TITLE
Add a check for `prependId="false"` to the NoAutoGeneratedIdViewHandler

### ISSUE THREAD

**Issue by kukel** [omnifaces/omnifaces#374]
Maybe it is an idea to add a check for `prependId="false"` to the http://showcase.omnifaces.org/viewhandlers/NoAutoGeneratedIdViewHandler so issues with using this and ajax are 'prevented' too

**Comment by BalusC** [comment]
A warning line will be logged. Throwing an exception is a bit on the edge in this stage. Perhaps later.
