### ISSUE TITLE
Omnifaces 1.13+ not entirely Java 1.6 compatible

### ISSUE THREAD

**Issue by 4a6f42** [omnifaces/omnifaces#378]
Being stuck at Java EE 6, I am grateful for the legacy branch. But while you state that "Legacy OmniFaces 1.x only requires Java 1.6" that's not quite the case. Since version 1.13 for example org.omnifaces.el.ExpressionInspector imports java.util.Objects which requires Java 1.7. And that may not be the only class with this problem. So far my workaround is to use 1.12, but further investigation and a fix would be nice :)

**Comment by 4a6f42** [comment]
@BalusC, could you take a look at this? It seems you introduced the JEE 7 dependency with [this commit](https://github.com/omnifaces/omnifaces/commit/53edffd4591d9bd8c3313dcd0e98a3de3c3a0b18).

**Comment by BalusC** [comment]
This problem has same grounds as https://github.com/omnifaces/omnifaces/issues/363

I'll have to bake an 1.14.1.

**Comment by BalusC** [comment]
1.14.1 has been baked. It will be in Maven central soon.

**Comment by 4a6f42** [comment]
Thanks!
