### ISSUE TITLE
Provide a <o:importClass type="..." />

### ISSUE THREAD

**Issue by kalgon** [omnifaces/omnifaces#381]
The current version of EL does not support the `instanceof` operator.

A possible workaround would be to import the `Class` in the request scope so that we could call `isInstance()`, `isAssignableFrom()` on it:

    <o:importClass type="eg.Customer" var="customerClass" />
    <ui:fragment rendered="#{customerClass.isInstance(currentObject)}">...</ui:fragment>

What do you think?

**Comment by BryanV91** [comment]
Workaround:

Create a request scoped bean, that contains this method:

```
@RequestScoped
@Named
public class UtilityBean implements Serializable {

public boolean compareClass(String className, Object obj) {
		try {
			return Class.forName(className).isInstance(obj);
		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		}
		return false;
	}

}
```

In your JSF page:

`<ui:fragment rendered="#{utilityBean.compareClass('eg.Customer',currentObject)}">...</ui:fragment>`

You will avoid having this:

```
<o:importClass type="eg.Customer" var="customerClass" />
<o:importClass type="eg.Car" var="carClass" />
<o:importClass type="eg.Boat" var="boatClass" />
<o:importClass type="eg.OtherClass" var="otherClass" />
...
<o:importClass type="eg.nthClass" var="nthClass" />
<ui:fragment rendered="#{customerClass.isInstance(currentObject)}">...</ui:fragment>
```

**Comment by kalgon** [comment]
Even better alternative:

    <o:importFunctions type="java.lang.Class" var="k" />
    <ui:fragment rendered="#{k:forName('eg.Customer').isInstance(currentObject)}">...</ui:fragment>

**Comment by BryanV91** [comment]
Really cool alternative.

**Comment by BalusC** [comment]
This is a bit on the edge. Here are alternatives: http://stackoverflow.com/q/10314214

**Comment by BalusC** [comment]
I added an `of:isInstance()` function. It'll be in today's latest 3.0-SNAPSHOT.
