### ISSUE TITLE
Feature request: of:coalesceString('', 'not empty')

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#382]
After writing a `#{empty someBean.someMethod ? 'default' : someBean.someMethod}` construct, I was wondering if I haven't seen a function in OmniFaces to dry this up. The function I remembered is `coalesce`. But, if the first object is not null, but an empty string, the first object is returned. Maybe you could add a string variant which checks if the first string is empty:

````
  public static String coalesceString(String first, String second) {
    return (first == null || first.isEmpty()) ? second : first;
  }
````

**Comment by BalusC** [comment]
Having an empty string instead of null is suspicious at best. What's the real world use case?

**Comment by jepsar** [comment]
You are right, suspicious, and probably a bug. I need to double check a few things when I'm at the office, it looks like I'm trying to fix the workaround.

**Comment by jepsar** [comment]
This could be useful when `javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL` is not set to `true`. I was working on an older project where this wasn't enabled.

I'm going to enable it and fix resulting issues though :-)
