### ISSUE TITLE
tag o:viewParam 2.6.2

### ISSUE THREAD

**Issue by thimor** [omnifaces/omnifaces#384]
Hi, i do having problem when i use the tag o:viewParam of 2.6.2 version and JSF 2.3.0 version.
is setting  null value on set method when url has no param.
i tested with 1.5 version and works fine.

**Comment by BalusC** [comment]
I'm not exactly sure if I understand the problem. Were you expecting an empty string instead of null?

**Comment by BalusC** [comment]
No feedback, closing off.
