### ISSUE TITLE
FullAjaxExceptionHandler can produce an endless loop

### ISSUE THREAD

**Issue by tnawrath** [omnifaces/omnifaces#386]
I am experiencing an endless loop in the FullAjaxExceptionHandler. 
I am using Omnifaces 2.6 with Primefaces 6 on Wildfly 10.1.0 Final I instrumented the FullAjaxExceptionHandler as precise as i could as it is recommended in the Showcase

My web.xml contains this:
```
<error-page>
    <error-code>500</error-code>
    <location>/error/java/defaulterror.jsf</location>
</error-page>
```
Now lets say a user sends an Ajax Request like this:

```
<p:commandButton value="Do something long" 
    action="#{bean.doSomethingLong()}" async="true"/>
```
Bean:

```
public void doSomethingLong() {
    try {
        Thread.sleep(30000);
    } catch (InterruptedException e) {
    }
}
```
And now lets say the user does not wait for the Request to complete but instead hits the logout button:

```
    <p:commandButton value="Logout" 
        action="#{bean.invalidateSession()}" />
```
Bean:

```
public void invalidateSession() {
    ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
    externalContext.invalidateSession();
}
```
When the first request finally completes its waiting time, it produces an endless (or very long) loop which looks in the log like this:

> at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.renderErrorPageView(FullAjaxExceptionHandler.java:541) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handleAjaxException(FullAjaxExceptionHandler.java:414) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handle(FullAjaxExceptionHandler.java:367) at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119) at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123) at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.renderErrorPageView(FullAjaxExceptionHandler.java:541) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handleAjaxException(FullAjaxExceptionHandler.java:414) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handle(FullAjaxExceptionHandler.java:367) at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119) at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123) at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.renderErrorPageView(FullAjaxExceptionHandler.java:541) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handleAjaxException(FullAjaxExceptionHandler.java:414) at org.omnifaces.exceptionhandler.FullAjaxExceptionHandler.handle(FullAjaxExceptionHandler.java:367) at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:119) at com.sun.faces.lifecycle.RestoreViewPhase.doPhase(RestoreViewPhase.java:123) at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)

In other cases, like invalidating the session before calling the long request or invalidating the request inside of the long request, or any other exception in an ajax request, the exception page will be shown just fine. The content of the errorpage itself does not seem to matter. For completeness:

defaulterror.xhtml:

```
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>ErrorPage</title>
    </h:head>
    <h:body>
        This is bad.
    </h:body>
</html>
```
Omnifaces 2.4 and earlyer shows the internal 'Ooops!' error message, Omnifaces 2.5 until today produces an endless loop. 

I also posted on Stackoverflow: https://stackoverflow.com/questions/44329126/omnifaces-fullajaxexceptionhandler-produces-endless-loop-config-issue-bug-or

**Comment by danilAREFY** [comment]
@tnawrath hi. I'm faced with a problem. As I understand it, the problem with Undertow. You can try to Wildfly 11.0.0.Alpha1. There should not be this problem.

**Comment by tnawrath** [comment]
Well, I think the behavoir in 2.4 was better, because it showed an internal error instead of causing an endless loop. Would it be an option to change the Method renderErrorPageView in the class FullAjaxExceptionHandler back to how it was in 2.4?

**Comment by tnawrath** [comment]
How it was in 2.4, causing an internal error: 
```
        Hacks.removeResourceDependencyState(context);

        try {
            ViewDeclarationLanguage vdl = viewHandler.getViewDeclarationLanguage(context, viewId);
            vdl.buildView(context, viewRoot);
            context.getApplication().publishEvent(context, PreRenderViewEvent.class, viewRoot);
            vdl.renderView(context, viewRoot);
            context.responseComplete();
        } catch (Exception e) {
```
how it is now since 2.5 causing an internal loop:

```
        try {
            context.setCurrentPhaseId(PhaseId.RENDER_RESPONSE);
            getLifecycle(context).render(context);
            context.responseComplete();
        } catch (Exception e) {
```

**Comment by BalusC** [comment]
Can you confirm if today's [2.6.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.6.4-SNAPSHOT/) works for you?

**Comment by tnawrath** [comment]
Yes, I confirm that 2.6.4-SNAPSHOT on Wildfly 10.1. will now show the internal Error Page instead of an endless loop. Thank you. 
At the moment, I can not work with Wildfly 11 to test the behavoir as suggested by @danilAREFY though.
