### ISSUE TITLE
Percent converter ignoring % character.

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#387]
JSF built in number converter requires a percentage number input including % character, which is just annoying for users to input the % sign. 

I extended the built-in _NumberConverter_ for this purpose. I was not sure if the % sign for all locales is the suffix. If yes the % could just be appended which makes this code even smaller.

What do you think?

**Converter**

	/**
	 * Basic {@link NumberConverter} which allows input of percentage numbers
	 * without % character.
	 */
	@FacesConverter("package.NumberPercentConverter")
	public class NumberPercentConverter extends NumberConverter
	{
		private static final BigDecimal PERCENT_MULTIPLIER = new BigDecimal(0.01);
	
		@Override
		public Object getAsObject(final FacesContext context, final UIComponent component, String value)
		{
			// 20.5
			if (value == null)
				return null;
	
			// .5 -> 0.5
			value = MathUtils.prefixZero(value, this.getLocale());

			// check if % sign is missing
			if (this.getType().equals("percent") && !value.contains("%"))
			{
				this.setType("number");
	
				// 20.5
				Number number = (Number) super.getAsObject(context, component, value);

				// 0.205 - convert to percentage range
				number = BigDecimal.valueOf(number.doubleValue()).multiply(NumberPercentConverter.PERCENT_MULTIPLIER);
	
				this.setType("percent");
	
				// "20.5%" - format number using converter attributes and locale
				value = super.getAsString(context, component, number);
			}
	
			return super.getAsObject(context, component, value);
		}
	}

**Form**

	<h:form>
		<p:messages/>

		<p:inputText value="#{testBean.number}">
			<f:validateLongRange minimum="0" maximum="1"/>
			<o:converter converterId="de.store24.web.jsf.converter.NumberPercentConverter"
				maxIntegerDigits="3" maxFractionDigits="4" type="percent"/>
		</p:inputText>

		<p:commandButton value="Save" update="@form"/>
	</h:form>

**Prefix missing Zero**

I also allowed input of `.5` using regular expression to prefix a missing 0 before the decimal separator of that locale. Its just more user-friendly. I can provide this function if necessary.

**Comment by BalusC** [comment]
Makes sense.

**Comment by BalusC** [comment]
I added `omnifaces.ImplicitNumberConverter` for 3.0. 

This not only covers percent formats but also currency formats. 

Only prefixing with zero wasn't necessary in my case. It works just fine for me in Java 1.8 (Oracle JDK 1.8.0_111).

Thanks for improving OmniFaces with this suggestion!
