### ISSUE TITLE
o:graphicImage with dataURI="true" don't work without cookies

### ISSUE THREAD

**Issue by mbto** [omnifaces/omnifaces#389]
o:graphicImage with dataURI="true" don't work if the browser blocks cookies or the browser visits the site for the first time.

Tested on Firefox 53 & Chrome 58
```
package local.jsfapp.pojo;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import java.io.IOException;
import java.io.Serializable;
import java.nio.file.Files;
import java.nio.file.Paths;

@Named
@ViewScoped
public class Pojo implements Serializable {
    private static final long serialVersionUID = 1L;

    private byte[] pic;

    @PostConstruct
    public void init() {
        try {
            pic = Files.readAllBytes(Paths.get("C:\\temp\\advert.jpg"));
        } catch (IOException ignored) { }
    }

    public byte[] getPic() {
        return pic;
    }
}
```

```
<h:body>
    <o:graphicImage value="#{pojo.pic}" dataURI="true"/>
</h:body>
```
![2017-06-11_21-41-51](https://user-images.githubusercontent.com/8545291/27013588-323e63be-4eef-11e7-86c8-13e721ad24b8.png)

**Comment by BalusC** [comment]
If you block cookies, then you basically block HTTP session, so servlet `HttpSession` will be recreated anew on every request, so `@SessionScoped` and `@ViewScoped` won't work and they will behave like `@RequestScoped`.

This is not a bug in OmniFaces.
