### ISSUE TITLE
How to define OmniMessages component for an environment that can't recognize @FacesComponent annotations 

### ISSUE THREAD

**Issue by vedmack** [omnifaces/omnifaces#390]
Hi, 

Since my environment can't recognize @FacesComponent annotations for libraries in WEB-INF/lib , I have to add the component manually to the `faces-config.xml` file, but it looks like I'm missing something

I have added the following

	<component>
		<component-type>org.omnifaces.component.messages.OmniMessages</component-type>
		<component-class>org.omnifaces.component.messages.OmniMessages</component-class>
	</component>

I guess its similar to the [following issue ](https://stackoverflow.com/questions/37529138/javax-faces-facesexception-expression-error-named-object-org-omnifaces-compon)

but I'm getting the following exception `renderer cannot be found for component type org.omnifaces.component.messages.OmniMessages and renderer type org.omnifaces.Messages`

**Comment by BalusC** [comment]
If `@FacesComponent` is not recognized, `@FacesRenderer` is likely also not recognized. The `<o:messages>` is one of very few components having an external renderer, the `MessagesRenderer`.

Add a `<renderer>` for `MessagesRenderer` as well.

```
<renderer>
    <component-family>javax.faces.Messages</component-family>
    <renderer-type>org.omnifaces.Messages</renderer-type>
    <renderer-class>org.omnifaces.renderer.MessagesRenderer</renderer-class>
</renderer>
```
