### ISSUE TITLE
Allow optional validation method / validator in o:validateBean

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#391]
`o:validateBean` creates a copy of the bean to be able to validate it. For validation it uses default validator factory which is not sufficient in all cases.

Validation factory can be extended to support custom validation method that may look into the database. A check for unique key combinations before saving is a general requirement.

This could be supported by `o:validateBean` if it allows to pass an optional validator / validation method / interface to leverage the validation. Some ideas:

	
	<o:validateBean value="#{bean.order}" validator="#{bean.orderCouponRemoteValidator}" />

	
	<o:validateBean value="#{bean.order}" validator="package.entityRemoteValidator" 
		validationGroups="package.OrderCoupon"/>

	
	<o:validateBean value="#{bean.order}" validationMethod="#{generalBean.validateEntityRemote}" 
		validationGroups="package.OrderCoupon"/>

**Use case example**

In our remote application server we use a `SessionConstraintValidator` that has access to hibernate database session. Database session validators and groups are added using xml annotations.

In this example the `@ValidOrder` validates the basic coupon information. The xml added `@ValidOrderCouponRemote` validates for example if the coupon was already used. 
In a wizard GUI for cash-out the user can get instance feedback why its coupon is invalid.

	@ValidOrder 
	// @ValidOrderCouponRemote(groups =  OrderCoupon.class ) defined by xml, to hide from client
	public class Order
	{
		@Valid
		private Coupon coupon;

		@NotNull
		private Date timeCreated;
	}

	<p:inputText id="coupon" value="#{bean.order.coupon}" converter="#{bean.remoteCouponConverter}">
		<p:ajax event="change" process="coupon" update="pnlCouponUpdate"/>
		<o:validateBean validationGroups="OrderCoupon" 
			validator="package.jsf.validator.entityRemoteValidator" />
	</p:inputText>

**Comment by BalusC** [comment]
I'm not sure I understand the concrete problem. It's not clear to me what exactly  `#{bean.orderCouponRemoteValidator}`, `package.entityRemoteValidator`, `#{generalBean.validateEntityRemote}` and `package.jsf.validator.entityRemoteValidator` classes/methods would represent and why that can't be done in the `ConstraintValidator` implementation as defined in `@Constraint(validatedBy)` attribute of `@ValidOrderCouponRemote`.

**Comment by BalusC** [comment]
Closing off as incomplete.
