### ISSUE TITLE
inputfile maxsize javascript

### ISSUE THREAD

**Issue by seb2803** [omnifaces/omnifaces#396]
In IE 11: changing dynamically the value of inputFile triggers the onchange again. This leads to unexpected behaviors.
In IE11/Edge: changing dynamically the enctype leads to JS error: Invalid Argument.
Obviously, according to [W3 counters]([https://www.w3counter.com/globalstats.php],) IE browsers are on the decline. But worth to note for your 3.0 release.

**Comment by BalusC** [comment]
Fixed. Thank you for reporting. Please let me know if today's 2.6.5-SNAPSHOT works for you.
