### ISSUE TITLE
Can Omifaces integrate with Oracle ADF?

### ISSUE THREAD

**Issue by tuyendev** [omnifaces/omnifaces#397]
I'm trying to integrate Omifaces with Oracle ADF. I have got confused because it seems don't work:
Here's my example code:
```
<af:selectOneChoice id="aTxtOrgLevel" simple="true"
                                contentStyle="width:100%"
                                autoSubmit="true" required="false"
                                valueChangeListener="#{pageFlowScope.dicOrgAddPageController.doCheckRender}"
                                value="#{pageFlowScope.dicOrgAddPageController.dicOrgNew.orgType}">
        <f:selectItems value="#{pageFlowScope.dicOrgAddPageController.lstSiUnitType}"/>
        <o:converter converterId="omnifaces.ListConverter" list="#{pageFlowScope.dicOrgAddPageController.lstSiUnitType}" />
</af:selectOneChoice>
```

And ADF Faces had said, " converter is not valid child of a Choice element ". So, Doesn't Omifaces support ADF Faces?
Thank you so much.

**Comment by BalusC** [comment]
That's a problem in JDeveloper, not in ADF Faces nor OmniFaces.

Ignore the error message, deploy and run it. You'll see that it works just fine. You have the following options:

1. Upgrade your IDE if possible.
2. Configure your IDE to not show that kind of error messages.
3. Replace your IDE by a different IDE.
