### ISSUE TITLE
Is this still necessary? try-with-resources statement

### ISSUE THREAD

**Issue by daniville1** [omnifaces/omnifaces#398]
https://github.com/omnifaces/omnifaces/blob/2ecec3f272d0c3cbc56f374cff09c15609c8ae5b/src/main/java/org/omnifaces/util/Utils.java#L449

Is this still necessary? It seems to me that they used it to close streams that are now implicitly closed because they are using the try-with-resources statement

**Comment by BalusC** [comment]
Yes this is still necessary. It allows you to close a resource without that an exception is thrown. The try-with-resources statement can't do that.
