### ISSUE TITLE
Use of validator attribute in o:validateMultiple fails with partial state saving

### ISSUE THREAD

**Issue by Mobe91** [omnifaces/omnifaces#400]
Contrary to the `validateMethod` attribute, the `validator` attribute is not part of the component state and is only set by the `org.omnifaces.component.validator.ValidateMultipleHandler`. For this reason, I encountered issues during view restore when partial state saving was used, resulting in the `validator` property being `null`.

Use of the `validateMethod` attribute did not work for me so I used the `validator` attribute with a MethodExpression as a workaround like this:
```xml
<o:validateMultiple components="c1 c2" validator="#{myValidator.validateValues}" message="Validation failed" showMessageFor="c1"/>
```
Possible solutions:

- Make the `validator` property part of the state
- Always set the `validateMethod` property in the handler and remove the validator property

**Comment by BalusC** [comment]
> the validator attribute is not part of the component state

This was a deliberate decision. JSF converter/validator instances are supposed to be designed as unserializable/applicationscoped and therefore not supposed to be saved in JSF state but just be re-referenced or recreated from scratch during view build time. `MethodExpression` instances in turn are just serializable as they basically just represent the literal expression string `#{foo.bar}`.

If in your specific case it returned null after restore view then it could only mean that the concrete instance is not available during view build time. Perhaps it's in turn being referenced in an iterator JSF component such as `<h:dataTable>`? In other words, the validator is a property of the model? This doesn't look good in first place. What exactly is the functional requirement you're trying to solve this way?

**Comment by Mobe91** [comment]
I understand the intention behind this design. For me, the issue only occurs with partial state saving. Maybe this is a bug in JSF (I use MyFaces) that fails to properly reinitialize the component instance.

My use case is to have a date range validation across two date input components. The validator basically checks if the date entered in field1 is before the date in field2. The validator instance is not part of the model, it is just a `@Named @ApplicationScoped` bean which I used to reference by name via EL like so:
```xml
<o:validateMultiple components="field1 field2" validator="#{myValidatorName}"/>
```

Give me a couple of days and I will dig up the stack trace of where the component is instantiated during restore along with the MyFaces version that I have been using.

**Comment by BalusC** [comment]
Thank you for the detail.

In the meanwhile, can't you just use `<o:validateOrder>` instead? http://showcase.omnifaces.org/validators/validateOrder

**Comment by BalusC** [comment]
Closing off as invalid (works as designed; bug is elsewhere).
