### ISSUE TITLE
commandScript onbegin, oncomplete could use examples

### ISSUE THREAD

**Issue by bobbotron** [omnifaces/omnifaces#403]
I've been quite enjoying the commandScript tag, it's a nice addition to the omnifaces library.  I had a suggestion for the javadoc/vdl/? documentation for the tag.  Both onbegin (http://omnifaces.org/docs/vdldoc/2.6/o/commandScript.html#onbegin) and oncomplete (http://omnifaces.org/docs/vdldoc/2.6/o/commandScript.html#oncomplete) could use an example of the expected javascript.  Some such callbacks expect it in the form:

`onbegin="aMethod"`
while other callbacks are in the form
`onbegin="aMethod()"`

From the existing documentation, it's not immediately clear which is required here or if both are valid.

**Comment by bobbotron** [comment]
It appears that only the second method is valid:
`onbegin="aMethod()"`

**Comment by BalusC** [comment]
It literally says "a script" which can be any JavaScript code.

It's true that the `onevent` and `onerror` of `<f:ajax>` deviate from this as they expect a function reference instead of "a script". But its doc already says "The name of the JavaScript function that will handle UI events.". This is primarily because arguments are to be passed in.

I'll look into improving the javadoc.

**Comment by bobbotron** [comment]
I'm sorry @BalusC, this is a picky issue, I almost didn't post it.  "The name of the JavaScript function that will handle UI events." doesn't quite work here though, as when I only wrote the following, which is the name of the JS method, the method wasn't called (on glassfish 4.1, omnifaces 2.6.3.)

`onbegin="aMethod"`

**Comment by BalusC** [comment]
I was referring to `onevent` and `onerror` of `<f:ajax>`.

**Comment by bobbotron** [comment]
Ah, sorry!

**Comment by BalusC** [comment]
<o:commandScript> is deprecated as per OmniFaces 3.0 because it has been moved to JSF 2.3 as <h:commandScript>. No efforts will be made.
