### ISSUE TITLE
Documentation: Combine hardcoded PrimeFaces resources using CombinedResourceHandler

### ISSUE THREAD

**Issue by mydeadlyvenoms** [omnifaces/omnifaces#409]
The wiki entry seems to have a small error, there are probably other ways to solve it but I did it using `FacesContext`.

```
@Override
public void processEvent(SystemEvent event) throws AbortProcessingException {
    //FacesContext context = event.getFacesContext();
    FacesContext context = FacesContext.getCurrentInstance();
    ProjectStage projectStage = context.getApplication().getProjectStage();
    PrimeConfiguration primeConfiguration = RequestContext.getCurrentInstance().getApplicationContext().getConfig();

    ...
```

**Comment by BalusC** [comment]
`event.getFacesContext()` is new since JSF 2.3. In older JSF versions you can indeed just grab it via `FacesContext.getCurrentInstance()`.

**Comment by mydeadlyvenoms** [comment]
Perfect - still waiting for Payara 5 final - no JSF 2.3 yet. :-)
The comment will help. Thank you!
