### ISSUE TITLE
SocketFacesListener should visit with SKIP_ITERATION

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#410]
We have problem with SocketFacesListener which search for `<o:connect>` components before render view phase. In our case, when `Components.forEachComponent` iterates over data inside nested `<ui:repeat>` component, an exception is thrown inside repeat's getValue() method (our code). May be the iteration should be initialized with VisitHint.SKIP_ITERATION or the problem is on our side. Please, close this issue, if the visitor context must not have SKIP_ITERATION.

**Comment by BalusC** [comment]
It looks like you're performing business logic in a getter method.

Can you confirm you understood everything of https://stackoverflow.com/q/2090033/157882?

**Comment by skybber** [comment]
Yes I do. In our case we had following structure (before socket):

```XML
<ui:fragment rendered="#{expr. evaluated to TRUE}">
    <ui:repeat value="#{fail}">
    <ui:repeat>
</ui:fragment>
```
when this structure is rendered, it does not fail since `ui:fragment` has `rendered=false`.

after `socket` addition:

```XML
<o:socket>
...
<ui:fragment rendered="#{expr. evaluated to TRUE}">
    <ui:repeat value="#{fail}">
    <ui:repeat>
</ui:fragment>
```
it starts to fail in pre-render since the render condition is not considered in visitor. I suppose the problem is on our side, but it looks weird for me that search for `<o:connect>` component iterates over data in iterable components. Unfortunately it is not possible to change this behaviour to easy fix all problems in our big project. The only way is to extend custom component as I did...

**Comment by BalusC** [comment]
> but it looks weird for me that search for `<o:socket>` component iterates over data in iterable components

It's not impossible that users want to use `<o:socket>` as below (even it's totally ineffective):

```
<ui:repeat value="#{bean.sockets}" var="socket">
    <o:socket connected="#{socket.connected}" />
</ui:repeat>
```

**Comment by BalusC** [comment]
> but it looks weird for me that search for `<o:socket>` component iterates over data in iterable components

Totally agree that.

**Comment by BalusC** [comment]
It's in today's latest [2.6.6-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.6.6-SNAPSHOT/).

**Comment by skybber** [comment]
Good ! Thanks.
