### ISSUE TITLE
o:validateMultiple - add the possibility to process disable components

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#411]
Consider a case like this:
```xhtml
<h:inputText id="input1"/>
<h:inputText id="input2"/>
<h:inputText id="input3" disabled="#{someBean.someProperty}"/>
<o:validateMultiple components="input1 input2 input3" validator="#{myMultipleValidator}"/>
```
where `myMultipleValidator` expects 3 components.
If `#{someBean.someProperty}` evaluates to false, `myMultipleValidator` will fail, because he won't receive the component `input3`.
I think it would be useful to add a property, e.g. `skipDisabledComponents`, which control the behavior: if it's false, disabled or readonly inputs will be processed too. Obviously it should default to true to keep consistency with the current behavior.

**Comment by BalusC** [comment]
There's another problem: HTML won't send values of disabled inputs to server in first place.

Better use hidden inputs.

**Comment by BalusC** [comment]
On second thought, this could be quite useful if the validator should just retrieve the model value.

**Comment by NicolaIsotta** [comment]
That's exactly my use case. Thanks @BalusC

**Comment by flange-ipb** [comment]
I came here facing the same issue, but we still use JSF 2.2 with OmniFaces 2.7.12. The fix made it only to the 3.x branch. @BalusC, is it possible to backport it to 2.x?

**Comment by BalusC** [comment]
It didn't made into 2.7.x because it's an API (javadoc) change and the root issue is work-aroundable.

Work around is to either use hidden inputs or use e.g. `disabled="#{bean.property and faces.renderResponse}"`.

**Comment by flange-ipb** [comment]
Thanks, that's indeed a nice workaround. The example of the OP would thus be the following:
```xml
<h:inputText id="input1"/>
<h:inputText id="input2"/>
<h:inputText id="input3" disabled="#{someBean.someProperty and faces.renderResponse}"/>
<o:validateMultiple components="input1 input2 input3" validator="#{myMultipleValidator}"/>
```
I observed the following in my validator implementation: The `values` list has 3 elements, but the 3rd (the value of input3) is null. You can use the corresponding component from the `components` list to get the right value, e.g. via `components.get(2).getValue()`.

Best regards,
Frank

PS: The "hidden inputs" method @BalusC was referring to can be found [here](https://stackoverflow.com/a/6282509).
