### ISSUE TITLE
TreeModel.remove() doesnt remove current node

### ISSUE THREAD

**Issue by Patrizia218** [omnifaces/omnifaces#414]
TreeModel.remove() doesnt remove current node as expected but always removes first node from parents children. 
I think its something with AbstractTreeModels equals method.
... L228 `return equals(getRoot(this), getRoot((AbstractTreeModel)object));` always returns true for the first entry of the list as it has the same parent/root as the current node I want to remove.

This issue came with update to omnifaces 2.6.5. With 2.6.4 TreeModel.remove() worked as expected

**Comment by BalusC** [comment]
That was a bad move. I have fixed it and added an unit test on it.

Thanks for reporting, it will be with next 2.6.6-SNAPSHOT.
