### ISSUE TITLE
o:url - deactivate bookmarkable url feature

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#416]
_<o:url>_ is a nice feature to create bookmarkable url's to reuse as a param. 

But it lacks support of simple url building for external urls like:

	<o:url var="varMapsSrc" href="https://www.google.com/maps/embed/v1/place">
		<o:param name="key" value="mykey"/>
		<o:param name="language" value="#{view.locale.language}"/>
		<o:param name="q" value="#{bean.address}" converter="#{addressConverter}/>
	</o:url>

	<iframe src="#{varMapsSrc}"></iframe>

I came across this requirement since i forgot to UTF-8 encode the params when creating url by concatenating dynamic params.

**Workaround:**

I extended my previously posted 'BookmarkableUrlConverter' in ticket #113 to allow external links using following function:

	<o:outputFormat var="varMapsSrc" value="https://www.google.com/maps/embed/v1/place" converter="BookmarkableUrlConverter">
		<o:param name="key" value="mykey"/>
		<o:param name="language" value="#{view.locale.language}"/>
		<o:param name="q" value="#{bean.address}" converter="#{addressConverter}/>
	</o:url>

	/**
	 * Appends the given parameters to the query string of the given uri
	 *
	 * @param uri
	 * @param params Optional query string parameters to add
	 *
	 * @return
	 */
	public static String BuildUri(final String uri, final Collection<ParamHolder> params)
	{
		Objects.requireNonNull(uri, "uri must not be null");

		final UriBuilder uriBuilder = UriBuilder.fromUri(uri);
		if (params != null)
		{
			for (final ParamHolder param : params)
			{
				final Object paramValue = param.getValue();
				if (paramValue != null)
					uriBuilder.queryParam(param.getName(), paramValue);
			}
		}

		return uriBuilder.build().toString();
	}

*Converter*

	if (component != null)
	{
		params = Components.getParams(component);

		// external link
		boolean isLink = FacesContextUtils.coerceToBoolean(context, component.getAttributes().get(BookmarkableUrlConverter.ATTRIBUTE_LINK));

		// external link
		if (isLink)
		{
			final String url = BookmarkableUrlConverter.BuildUri(value, params);
			return url;
		}

		// rest of code
	}

**Comment by BalusC** [comment]
Makes sense.

**Comment by BalusC** [comment]
Implemented in 3.0-SNAPSHOT.
