### ISSUE TITLE
FullAjaxExceptionHandler does not removes the exception from queue when 'shouldHandleExceptionRootCause' returns false

### ISSUE THREAD

**Issue by vijpan** [omnifaces/omnifaces#417]
Env: Liberty App Server 17.0.0.2 (JEE 7 compliant - MyFaces JSF 2.2 implementation), Primefaces 6.1, Omnifaces 2.6.6, Java 8
Alias: PrimeFaces - PF

FullAjaxExceptionHandler  - Looks like this [commit](https://github.com/omnifaces/omnifaces/commit/fa74dcd67d30fb80539746a0445347c1a1a2e5bb)  referred in this stackoverflow [question](https://stackoverflow.com/questions/34144536/customize-fullajaxexceptionhandler-to-show-only-a-faces-message-for-specific-exc) related to the removal of exception from the queue was reverted in this recent [commit](https://github.com/omnifaces/omnifaces/commit/39bf8ab91d4093a676f151eb71367bb1ed3c57a9)

This creates a problem as the wrapped handler (MyFaces internal handler) will find the exception in the queue and will navigate to error page (if available) and the navigation(any other specific page or stay on same page) which might have happened in 'shouldHandleExceptionRootCause' will be lost.

Should not the exception also be removed from the queue when 'shouldHandleExceptionRootCause' returns false.

What do you think?
Thanks

**Comment by BalusC** [comment]
That was unintended. I have fixed it.

**Comment by vijpan** [comment]
Great. Thanks!
