### ISSUE TITLE
Showcase is down?

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#418]
I am getting this...

![image](https://user-images.githubusercontent.com/4399574/32901561-22f1858a-cabe-11e7-89d0-2241f2f17d28.png)

**Comment by BalusC** [comment]
We're aware of this. This happened since move from OpenShift v2 to v3. Builds and deployments fail way too often. The showcase was supposed to be updated with 2.6.6, but for some reason the build is on status "pending" (for 8+ hours already).

**Comment by BalusC** [comment]
I have for now installed a server at home.
