### ISSUE TITLE
javax.faces.FacesException: Expression Error: Named Object: org.omnifaces.component.output.ConditionalComment not found

### ISSUE THREAD

**Issue by deelo55** [omnifaces/omnifaces#419]
I have upgraded from JSF 2.2.7 to 2.2.15 and I am now receiving the following error when running Jetty:
`javax.faces.FacesException: Expression Error: Named Object: org.omnifaces.component.output.ConditionalComment not found.`

I'm using omnifaces 1.14.1.

**Comment by BalusC** [comment]
Where is the OmniFaces JAR located? It must be in /WEB-INF/lib. Exception suggests that it's elsewhere. In Mojarra 2.2.9 a classloading bug related to this was fixed.

**Comment by BalusC** [comment]
Turns out this is a Jetty related issue: https://github.com/javaserverfaces/mojarra/issues/4013

> @manfredriem said:
> As of Servlet 3.0 a Servlet container is required to implement support for the ServletContainerInitializer API, the specific 2.2 version of Mojarra you are trying uses this API.
> 
> Please do not ask to restore this functionality on our side as the old implementation is NOT compatible with JavaSE 9. Which is why it was decided to use the ServletContainerInitializer API going forward, as it was expected a Servlet 3.0 and newer container would be implementing it correctly.
> 
> I am sorry that you hit the issue and if the Jetty engineers need some pointers I am happy to provide them.
> 
> See https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContainerInitializer.html

Closing off as wontfix. Best you could do is to report to Jetty guys and have them the to fix the JAR-provided ServletContainerInitializer being uninitalized on Jetty.
