### ISSUE TITLE
More protected methods are needed in FullAjaxExceptionHandler

### ISSUE THREAD

**Issue by ova2** [omnifaces/omnifaces#42]
We have overwritten the FullAjaxExceptionHandler.

```java
public class WebshopExceptionHandler extends FullAjaxExceptionHandler {
   ...
}
```

and want to use the following methods in WebshopExceptionHandler:

```java
private void resetResponse(FacesContext context);
private void renderErrorPageView(FacesContext context, final HttpServletRequest request, String errorPageLocation) throws IOException;
```

but they are __private__ and can not be called in the extended  class. Can you make them __protected__ please? Maybe in 1.8.2.

Also the constants 

```java
private static final String ATTRIBUTE_ERROR_EXCEPTION = "javax.servlet.error.exception";
private static final String ATTRIBUTE_ERROR_EXCEPTION_TYPE = "javax.servlet.error.exception_type";
private static final String ATTRIBUTE_ERROR_MESSAGE = "javax.servlet.error.message";
private static final String ATTRIBUTE_ERROR_REQUEST_URI = "javax.servlet.error.request_uri";
private static final String ATTRIBUTE_ERROR_STATUS_CODE = "javax.servlet.error.status_code";
private static final String ERROR_PAGE_ERROR = "...";
```

should be __protected__. Thanks.

**Comment by BalusC** [comment]
I wonder what exactly you'd like to do in `resetResponse()` and `renderErrorPageView()` instead as changing them would violate the purpose of `FullAjaxExceptionHandler` of showing an `<error-page>` exactly the same way as during a synchronous request.

Those constants are since OmniFaces 2.0 replaced by Servlet 3.0 ones.

**Comment by ova2** [comment]
I can not remember about resetResponse() (have to look into the project code), but ```renderErrorPageView``` is needed e.g. to show the error on the same page. We only show unexpected errors on a separate page. Business errors are shown on the same page by invoking ```navigate``` in the ```NavigationHandler``` with the outcome ```null```. Business errors are thrown across the whole web app and we don't need to change the view.

**Comment by BalusC** [comment]
Closing off as this actually defeats purpose of `FullAjaxExceptionHandler`. 

To implement the desired functionaliry, better override `shouldHandleExceptionRootCause()`.
```
protected boolean shouldHandleExceptionRootCause(FacesContext context, Throwable exception) {
    if (isContinuableBusinessException(exception)) { 
        return true;
    }
    else {
        // Do your specific thing here. Show a faces message?
        // ...
        return false;
    }
}
```

**Comment by meprabu** [comment]
Hi I tried the above logic to show my business exception on the same page but i dont the values that i set in the context in the xhtml. This is the response that i get.
<?xml version='1.0' encoding='UTF-8'?>
<partial-response id="j_id1"><error><error-name>class gov.ms.mdes.access.framework.exception.BaseRunTimeException</error-name><error-message><![CDATA[null]]></error-message></error></partial-response>

Please see the code here 
http://stackoverflow.com/questions/34144536/omnifaces-fullajaxexceptionhandler
