### ISSUE TITLE
Faces#sendFile(File file, boolean attachment) is slow

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#420]
````
Faces.sendFile(file, false);
````

is slow (as in multiple seconds), while

````
try (InputStream inputStream = new FileInputStream(file)) {
  Faces.sendFile(inputStream, file.getName(), false);
}
````

is fast. I've tested this with 2.6.6 on Payara 4.1.2.173 and it occurred on each request.

**Comment by BalusC** [comment]
Not reproducible.

Only technical difference is that former sets the content-length header while the latter doesn't. So in theory slowness could happen if server or proxy wants to cache the whole file.

**Comment by jepsar** [comment]
OK, thanks. I'll add a wrapper to our library.
