### ISSUE TITLE
InstanceOf function

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#421]
Since el _instanceof_ is still not implemented in JSF and its a very usefull feature omnifaces could add following function:

	/**
	 * Checks if the given objects is of the given class. Is a replacement 
	 *
	 * @param value
	 * @param className
	 *
	 * @return {@link Class#isInstance(Object)}
	 *
	 * @throws ClassNotFoundException
	 */
	public static boolean isInstanceOf(final Object value, final String className) throws ClassNotFoundException
	{
		Objects.requireNonNull(className, "className must not be null");
		return Class.forName(className).isInstance(value);
	}

**Comment by BalusC** [comment]
This is indeed not uncommon, but frankly this indicates a poor model. The model should have some discriminator column identifying the subtype, which is usually represented by an enum. This way you could just do #{mode.type eq 'FOO'} instead of #{of:isInstanceOf(model, 'com.example.model.Foo')}. This has also benefits in SQL/JPA side.

**Comment by djmj** [comment]
I don't think this indicates a poor model, it depends. If its a bad design why JSF reserved the _instanceof_ keyword?

## 1. Check entity type

Not all ORM frameworks allow mapping of discriminator column or need to map it explicitly twice. Discriminator is an anti-pattern, its only purpose is to select the correct table to save the data. 

When you hit the OO-layer you should check it using their class.

## 2. toggle editing components based on class

    class EntityReadDAO // read entities
    class EntityDAO extends EntityReadDAO // edit entities

in many composite components I toggle edit GUI components by following check. 

    <composite:attribute name="dao" type="package.EntityReadDAO" required="true"/>
    <ui:param name="isEditDAO" value="#{of:isInstanceOf(cc.attrs.dao, 'package.EntityDAO')"/>

Of cause an _editable_ attribute could be passed down the often complex markup tree. This needs to be  maintained in case of changes

## 3. Loose coupled tables

# a) I have a loose document table (pdf, image, excel, ...) with a surrogate key (id, type) to referencing tables / entities which implement a marker (empty) interface _DocumentEntityRef_. 

    class Document<T extends DocumentEntityRef> extends Entity
    {
        long refId;
        Class<T> refType;
        
        DocumentType type;
    }

    class Product extends Entity implements DocumentEntityRef { }

This approach saves a lot of time, boiler-plate associations / code and is very flexible to display documents such as a single or a sequence of images.

# b) Others entities have a direct reference to a document like a pdf using interface _DocumentEntity_

    class Foo implements DocumentEntity
    {
        // implement interface
        @Override
        public Document getDocument();
    }

# Composite

A simple example is a composite _comp:metaOgImageUrl_ which will just render the first image url for SEO purpose. 

    <composite:attribute name="entity" type="package.Entity" required="true"/>
    
    <meta property="og:image:url" value="#{of:isInstanceOf(cc.attrs.entity, 'package.DocumentEntityRef')
        ? bean.getFirstImageUrl(cc.attrs.entity)
        : of:isInstanceOf(cc.attrs.entity, 'package.DocumentEntity')
                ? bean.getImageUrl(cc.attrs.entity.file)
                : cc.attrs.default}"/>

We have a lot of entities that implement either one of the given types. It is not a 100% clean design but its time efficient programming and there are more important design questions then detecting the above cases.

**Comment by BalusC** [comment]
I was about to start implementing this in OmniFaces 3.0, it appears that there's already an `of:isInstance()` as result of #381 :o 

Closing off as duplicate.
