### ISSUE TITLE
OmniPartialResponseWriter does not write comments on ajax update

### ISSUE THREAD

**Issue by leomekenkamp** [omnifaces/omnifaces#425]
When a component writes a comment in its encodeBegin(FacesContext context) by calling context.getResponseWriter().writeComment(String), it is written to the inital html page. However, when the page is partially updated through an ajax request, I can see my debugger stepping through encodeBegin, but the comments are not written to the html stream anymore. writer.startElement and writer.endElement do work as expected. The OmniPartialResponseWriter appears as name of the writer class implementation.

Workaround: use writer.write("");

**Comment by BalusC** [comment]
OmniPartialResponseWriter does nothing special with comments. It just passes through all non-overridden methods to the wrapped writer. The writeComment() is one of them. In theory, you would still have the same problem when removing OmniFaces. Please reconfirm.

**Comment by BalusC** [comment]
Closing off as invalid.
