### ISSUE TITLE
onbeforeunload does immediately destroy @ViewScoped bean

### ISSUE THREAD

**Issue by mublu** [omnifaces/omnifaces#427]
One of the main reasons we started to use omnifaces is for the fact, that we need `@PreDestroy` to be triggered on Browser `unload ` event.

Now I want to detect if a user leaves a page with unsaved changes. Therefore I tried it with `window.onbeforeunload` and copied the example from the [showcase](http://showcase.omnifaces.org/cdi/ViewScoped). I use plain JS as noted in the showcase.

Afterwards I tried the functionality with a change of an input field:
```javascript
<p:inputText id="label"
    value="#{controller.label}"
    required="true">
    <f:validator binding="#{labelValidator}" />
    <p:ajax event="change" process="@this" update="@this"/>
</p:inputText>
```

The change is being detected and `$("body").data("unsavedchanges", true);` is triggered.

Next I try to leave the page without a submit. The browser (I tried it with IE 11, EDGE and FF52) shows the dialog, where the user can decide to leave the page or not. At the same time a POST of the `omnifaces.event:"unload"` is triggered and the method with the annotation @PreDestroy is fired in the bean. This event is not depended on my decision! Even in case I want to stay on the page, the backend bean is destroyed. If I try to do any further changes on the page, a `ViewExpiredException` is thrown.

I'm not sure whether this is a bug or I'm not using the concepts of `@PreDestroy`, `window.onbeforeunload` with ajax correctly.

**Comment by BalusC** [comment]
1. Which OmniFaces version are you using?
2. When exactly did you define window.onbeforeunload? Preferably you'd define it in `<h:outputScript>`

**Comment by mublu** [comment]
Dear BalusC,
thank you very much. Using `<h:outputScript>` did the trick. I had the code in `$(document).ready()`, as you suspected. Now it works as expected.
