### ISSUE TITLE
Updating widget inside of o:tree

### ISSUE THREAD

**Issue by JensPiegsa** [omnifaces/omnifaces#429]
I'm really impressed by the power of o:tree. Now I am facing a small problem:

I like to update the content of `a p:selectOneMenu` inside an `o:treeNodeItem`. Though the getter referenced via `f:selectItems` is called on the given event, the available options do not change. (But they change if I add new nodes)

Are there any known limitations regarding this use case? Do I have to alter the data in my `ListTreeModel` to make the change detectable?

**Comment by JensPiegsa** [comment]
PS: updating the whole `@form` works ...

**Comment by BalusC** [comment]
There should be no limitations. I'll have to reproduce this issue myself first so I can debug it.

**Comment by BalusC** [comment]
Sorry, works just fine for me. You'll have to come up with a reproducer.

```
<h:form>
	<o:tree value="#{bean.tree}" var="item">
		<o:treeNode>
			<ul>
				<o:treeNodeItem>
					<li>
						<p:selectOneMenu id="menu">
							<f:selectItems value="#{{1,2,3}}" var="i" itemLabel="#{i} #{now}" />
						</p:selectOneMenu>
						<p:commandButton value="Refresh menu" update="menu" />
						<o:treeInsertChildren />
					</li>
				</o:treeNodeItem>
			</ul>
		</o:treeNode>
	</o:tree>
</h:form>
```

**Comment by BalusC** [comment]
Closing off as not reproducible and no feedback.
