### ISSUE TITLE
Provide a SourceMapping ResourceHandler

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#430]
CSS, JS have source maps now. Mapping is commonly done via a special comment at the end of a file:

    /*# sourceMappingURL=sourcemaps/argus.css.map */

, but it's kinda hard to make it work with JSF due to mapping.

Thankfully, there is an alternative: the SourceMap header. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/SourceMap
OmniFaces could provide a ResourceHandler that fills this header with a proper JSF resource link. Maybe support some options like: source maps near their respective derivative files, or source maps in a separate directory. It should only fill the header, if a source map actually exists.

**Comment by BalusC** [comment]
> but it's kinda hard to make it work with JSF due to mapping.

You can use `#{resource['sourcemaps/argus.css.map']}` to print the correct URL.

> OmniFaces could provide a ResourceHandler that fills this header with a proper JSF resource link. Maybe support some options like: source maps near their respective derivative files, or source maps in a separate directory.

Reasonable.

**Comment by VsevolodGolovanov** [comment]
My CSS are generated (by libsass-maven-plugin), I can't edit them.

**Comment by BalusC** [comment]
I did a local experiment. It appears that the response header is ignored when `# sourceMappingURL` comment is present. So far now I think using `UnmappedResourceHandler` is your best bet.

**Comment by VsevolodGolovanov** [comment]
libsass-maven-plugin provides the `omitSourceMapingURL` option to disable adding the `# sourceMappingURL` comment.

**Comment by BalusC** [comment]
https://github.com/samaxes/minify-maven-plugin/issues/157

**Comment by BalusC** [comment]
It's in 3.1-SNAPSHOT. Let me know if it does the job for you.

**Comment by VsevolodGolovanov** [comment]
It'll probably take me a while, so I'm closing the issue. I'll report if there any problems. Thanks.
