### ISSUE TITLE
ExtensionlessURLs not working after 2.4 version

### ISSUE THREAD

**Issue by arunvc** [omnifaces/omnifaces#432]
Run the attached sample project [testurl.zip](https://github.com/omnifaces/omnifaces/files/1689524/testurl.zip)

```
<dependency>
      <groupId>org.omnifaces</groupId>
      <artifactId>omnifaces</artifactId>
      <version>3.0</version>
    </dependency>
```

This url does'nt work
localhost:8080/testurl/login?test=true

Change version no to 2.4 in pom.xml

```
<dependency>
      <groupId>org.omnifaces</groupId>
      <artifactId>omnifaces</artifactId>
      <version>2.4</version>
      <type>jar</type>
    </dependency>
```

This url works fine
localhost:8080/testurl/login?test=true

Java 8
Webserver = tomcat 9

**Comment by BalusC** [comment]
Works for me after I have cleaned up the project.

1. Remove com.sun.faces.config.ConfigureListener. It's already by default registered it only causes duplicate JSF applications.
2. Remove org.jboss.weld.environment.servlet.Listener. It's already by default registered it only causes duplicate CDI applications.
3. Fix welcome file from `/login` to `login`. The welcome file must represent the file not the path.
