### ISSUE TITLE
Socket not working on POST request

### ISSUE THREAD

**Issue by maucs5** [omnifaces/omnifaces#434]
In a JSF file with <o:socket>, making a POST request somehow removes it

<img width="812" alt="screen shot 2018-02-10 at 2 37 04 am" src="https://user-images.githubusercontent.com/1415703/36043818-8f522b5e-0e0b-11e8-8837-2adab8edce4e.png">

After making a POST request, it becomes this

<img width="819" alt="screen shot 2018-02-10 at 2 37 17 am" src="https://user-images.githubusercontent.com/1415703/36043830-9a2fb226-0e0b-11e8-99aa-9063f2eed68d.png">

**Comment by BalusC** [comment]
Happens only when it's not an ajax request or not performing a PRG.
