### ISSUE TITLE
Numbers#formatXxx breaks on negative values

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#435]
For example `Numbers.formatThousands(-12858)` breaks at https://github.com/omnifaces/omnifaces/blob/master/src/main/java/org/omnifaces/el/functions/Numbers.java#L259 caused by `maxfractions` also being negative.

**Comment by BalusC** [comment]
Fixed in 2.6.9.

**Comment by jepsar** [comment]
Thank you!
