### ISSUE TITLE
Change all the publicly-visible enum-singletons to factory methods

### ISSUE THREAD

**Issue by ogregoire** [omnifaces/omnifaces#441]
It's hard to test code containing `FacesConfigXml` without having a full blown Arquillian instance to fire up. Arquillian is nice for integration testing, but not all tests happen in integration tests. Some happen in unit-tests.

So it'd be nice to be able to mock `FacesConfigXml`, such as making an interface of it. This way you have the concurrency and serialization guarantees offered by the singleton-enum, and the flexibility of interfaces for testing.

Typical expected actions:

1. Rename `FacesConfigXml` to `ConcreteFacesConfigXml` and make it package-private.
2. Extract a public interface from `ConcreteFacesConfigXml` named `FacesConfigXml`.
3. Add a `static FacesConfigXml instance()` method returning `ConcreteFacesConfigXml.INSTANCE`.
4. Repeat this process for all the enum singletons.

**Comment by BalusC** [comment]
How would you mock the `instance()` method?

**Comment by ogregoire** [comment]
Well, that's a static factory method returning the singleton... It's not a business method: it doesn't need to be mocked. Meaning that when you mock, you simply `FacesConfigXml facesConfigXml = mock(FacesConfigXml.class)` and when you access the real instance (through a `@Provider`, for instance), you `FacesConfigXml facesConfigXml = FacesConfigXml.instance()`.

**Comment by BalusC** [comment]
Okay, makes sense.

**Comment by ogregoire** [comment]
Of course, this is omnifaces, so I guess there's a slight possibility to have `FacesConfigXml` automagically produced directly as a singleton instead of having to declare the full producer ourselves? But that'd be a nice cherry on top: the main request here is to decouple the mandatory initialization from the interface.

**Comment by BalusC** [comment]
It's available in today's latest 3.1-SNAPSHOT.

CDI producers have been added as well.

**Comment by ogregoire** [comment]
Thanks for the fast handling of this request! Nice trick on the deprecated instances ;-)
