### ISSUE TITLE
Namespace not found Netbeans 8.2 / omnifaces 3.0

### ISSUE THREAD

**Issue by fdellwing** [omnifaces/omnifaces#442]
Hello,

we would like to update our application to omnifaces 3.0, after deploying everything works fine, but Netbeans is unable to find library for the namespace leaving us unable to use autocomplete in xhtmls.

Having this problem with our own application, I tried it with the omnifaces showcase application, but the problem is present here as well.

![omnifaces](https://user-images.githubusercontent.com/22813377/37516222-b3724d6c-290d-11e8-9619-32b64097931e.png)

Greetings
Fabian

**Comment by BalusC** [comment]
Upgrade Netbeans to a version with JSF 2.3 support.

**Comment by fdellwing** [comment]
Thats the current stable version, sadly.
