### ISSUE TITLE
Pass generic type parameter to ValueChangeConverter

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#443]
Since JSF 2.3 supports typed converters _Converter<T>_ the generic type parameter should be passed to _ValueChangeConverter_.

We use generic converters and interfaces that extend Converter which will not compile anymore. So we musst remove the usage of _ValueChangeConverter_

_The interface Converter cannot be implemented more than once with different arguments: Converter<Object> and Converter<T>_

**Comment by BalusC** [comment]
That was an oversight. Fixed now.

Thanks for reporting!
