### ISSUE TITLE
Pass generic type parameter of Converter to Param

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#445]
Param provides Converter functionality and it should be generic.

Related to: https://github.com/omnifaces/omnifaces/issues/443

**Comment by BalusC** [comment]
Not sure I understand the problem.

Are you referring to `converterClass` attribute?

**Comment by djmj** [comment]
Sorry for not being clear. I referred to https://github.com/omnifaces/omnifaces/blob/3.0/src/main/java/org/omnifaces/component/output/Param.java 

This class should be generic:

	public class Param<T> extends UIParameter implements ParamHolder
	{
		Converter<T> converter;

		public Converter<T> getConverter()
	}

Basically the _getLocalValue_ getter is also bound to T, since the _value_ is obtained by the converter.

	public T getLocalValue()

**Comment by BalusC** [comment]
Ah, the `<o:param>`. 

How would you specify the generic type from XHTML on?

**Comment by djmj** [comment]
Not sure but is this required during runtime, or could _o:param_ not just use _Object_ as _T_ internal? 

I have used generic composite component's with generic methods which have worked.

**Comment by BalusC** [comment]
I made following adjustments:

1. `ParamHolder` is now `ParamHolder<T>`
2. `Object getLocalValue()` is now `T getLocalValue()`
3. `Object getValue()` is now `String getValue()`

It's in today's latest 3.1-SNAPSHOT. Let me know if everything's still fine in your end.

**Comment by djmj** [comment]
I will test it out later.

**Comment by djmj** [comment]
Did a quick migration and test and looks good. I just had to wrap _Component.getParams(...)_ into a wildcard collection to be able to pass it to other functions. 

    Collection<ParmaHolder<?>> params = new HashSet<ParamHolder<?>>(Components.getParams(component))

Object as generic param is very often to strict since casting is not possible. Like if you have _Collection<ParamHolder<String>>_ it cannot be cast to _Collection<ParamHolder<Object>>_.

**Comment by BalusC** [comment]
Ah, overlooked this one before releasing 3.1. I'll fix it.
