### ISSUE TITLE
Remove deprecation of GenericEnumConverter

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#450]
Generic enum converter is still required in case value attribute of component has no bean binding. In this case runtime class of enum is lost and the selection is converted to an array of Strings.

This case is used in PrimeFaces custom filters in datatable in combination with a many menu:

	<p:column filter="#{foo.state}>
		<f:facet name="filter">

		<p:selectCheckboxMenu label="#{msg.filters_u}" converter="omnifaces.GenericEnumConverter"
			onchange="PF('#{tblWidgetVar}').filter();">
		<f:selectItems itemLabel="#{varEnum}" itemValue="#{varEnum}"
			value="#{FooState.values()}/>
		</p:selectCheckboxMenu>

		</f:facet>
	</p:column>

**Comment by BalusC** [comment]
Makes sense.
