### ISSUE TITLE
Reevaluate deprecation of o:importConstants

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#453]
I see a problem with upcoming removal of _o:importConstants_.

Quote from omnifaces page: 

> <o:importConstants> has been deprecated as it's now moved into JSF 2.3 as <f:importConstants> with the only difference that <f:importConstants> requires being placed in <f:metadata>

The new _f:importConstants_ must be placed in _f:metadata_ which is only available once in root view. So the root-view must know which import's are required by any child include / composite / or taglib component. 

Currently i use _o:importConstants_ whereever i need in my components. No need for the root view to know what i need a particular import in my composite.

**Comment by BalusC** [comment]
Point taken.
