### ISSUE TITLE
Feature: MapConverter

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#454]
We had the request to persist current shopping-cart items and quantity into cookies. So i created following reusable map converter to persist this map (key = item, value = quantity) into a cookie in the cart bean. 

If you find it usefull, you can add it to OmniFaces.

This could be enhanced so by default the key and value converters could use a simple dummy _StringConverter_. I returned a _LinkedHashMap_ to preserve insertion order. This is similar to _ToCollectionConverter_.

	/**
	 * JSF converter to convert a Map to a String using specific key and value
	 * converters.
	 */
	public class MapConverter<K, V> extends ValueChangeConverter<Map<K, V>> implements Serializable
	{
		private static final long serialVersionUID = 8844023735130746057L;
	
		private static final String MAP_DELIMITER = ",";
		private static String ENTRY_DELIMITER = "=";
	
		/**
		 * converter for map keys
		 */
		private final Converter<K> keyConverter;
	
		/**
		 * converter for value keys
		 */
		private final Converter<V> valueConverter;
	
		/*
		 * constructor
		 */
	
		/**
		 * Creates a new map converter using given key and value converter
		 *
		 * @param keyConverter
		 * @param valueConverter
		 */
		public MapConverter(final Converter<K> keyConverter, final Converter<V> valueConverter)
		{
			Objects.requireNonNull(keyConverter, "keyConverter must not be null");
			Objects.requireNonNull(valueConverter, "valueConverter must not be null");
	
			this.keyConverter = keyConverter;
			this.valueConverter = valueConverter;
		}
	
		@Override
		public String getAsString(final FacesContext context, final UIComponent component, final Map<K, V> value)
		{
			if (value == null)
				return "";
	
			final List<String> strEntries = new ArrayList<>(value.size());
	
			for (final Entry<K, V> entry : value.entrySet())
			{
				final String strKey = this.keyConverter.getAsString(context, component, entry.getKey());
				final String strValue = this.valueConverter.getAsString(context, component, entry.getValue());
	
				final String strEntry = Utils.decodeURL(strKey) + MapConverter.ENTRY_DELIMITER + Utils.decodeURL(strValue);
	
				strEntries.add(strEntry.trim());
			}
	
			return String.join(MapConverter.MAP_DELIMITER, strEntries);
		}
	
		@Override
		public Map<K, V> getAsChangedObject(final FacesContext context, final UIComponent component, final String value)
		{
						if (StringUtils.isBlank(value))
				return null;
	
			final List<String> strEntries = Arrays.asList(value.split(MapConverter.MAP_DELIMITER));
	
			final Map<K, V> map = new LinkedHashMap<>();
	
			for (final String strEntry : strEntries)
			{
				if (StringUtils.isBlank(strEntry))
					continue;
	
				final String[] keyValue = strEntry.split(MapConverter.ENTRY_DELIMITER);
	
				// key
				final String strKey = Utils.encodeURL(keyValue[0].trim());
				final K oKey = this.keyConverter.getAsObject(context, component, strKey);
				if (oKey == null)
					continue;
	
				// value - check length since user could change cookie manual
				final String strValue = keyValue.length > 1 ? Utils.encodeURL(keyValue[1].trim()) : null;
				final V oValue = this.valueConverter.getAsObject(context, component, strValue);
	
				map.put(oKey, oValue);
			}
	
			return map;
		}
	
	}

**Comment by BalusC** [comment]
Unsure how to use it from the view side on. It seems to be only useful when called programmatically. In that case one would prefer just using one of the many available JSON parsers/formatters to convert a Java Map to/from a JSON string.
