### ISSUE TITLE
Memory leak at SocketSessionManager.socketSessions

### ISSUE THREAD

**Issue by THKDev** [omnifaces/omnifaces#456]
After a test over two days [SocketSessionManager.socketSessions](https://github.com/omnifaces/omnifaces/blob/2.x/src/main/java/org/omnifaces/cdi/push/SocketSessionManager.java#L76) contains over 100000 entries. It seems that this Map will never be cleared. 
All user specific sockets are hold until server will be restarted.
> <o:socket channel="userchannel" user="#{Bean.userIdentifierer}"/>

Maybe it is also possible to adjust memory footprint of ConcurrentHashMap regarding [this suggestion](https://ria101.wordpress.com/2011/12/12/concurrenthashmap-avoid-a-common-misuse/).

Thank you and kind regards
Thomas

**Comment by BalusC** [comment]
They are only removed when a socket is closed. 

How exactly did you test it?

**Comment by BalusC** [comment]
The counterpart is [deregister](https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/cdi/push/SocketSessionManager.java#L235). This is invoked when user session is destroyed.

**Comment by BalusC** [comment]
Fixed in both 2.6.10-SNAPSHOT and 3.2-SNAPSHOT. Once the IT has passed, you can get them from Sonatype. Can you retry and let me know?

**Comment by THKDev** [comment]
First test looks good. Thanks for your fast response! Is there any release date for 2.6.10 ?

**Comment by BalusC** [comment]
Not definitive. Usually we release about every 3 months. Sometimes longer sometimes shorter. 2.6.9 has been released only previous week.
