### ISSUE TITLE
Random unload events and ViewExpiredExceptions

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#459]
Hi, 

I'm writing this more as a question than as a bug. 

I have an application with omnifaces 2.6.9 and myfaces 2.2.12. I have a few omnifaces @ViewScoped beans (just in backoffice pages).

The problem is that I'm getting totally random unload events (post with a request parameter omnifaces.event = unload) in the frontoffice, where I'm not using any Omnifaces @ViewScoped.

I'm not able to reproduce it locally, it happens from time to time and only in production servers, so I think  it must be a concurrency issue. 

Very strange, because it doesn't even happen in our CI environment, where we have about 180 selenium concurrent tests, few of them using those viewScoped

I have removed all omnifaces @ViewScoped and now it's not happening any more. 

I'm not able to tell when this issue started, I just detected it first a few days ago after I upgraded primefaces-extensions to 6.2.4, but it doesn't make sense at all. Do you have a clue of where can I look at? Can it be related to a recent upgrade of primefaces-extensions? (I upgraded from 6.2.3 to 6.2.4). 

Related to JSF I'm using myfaces 2.2.12, omnifaces 2.6.9, primefaces 6.2, primefaces-extensions 6.2.4

Thanks in advance.

**Comment by cocorossello** [comment]
I can reproduce with a page that has a very long ajax (10-30 seconds) and an ajax poll every second updating some progress status. The ajax poll gets a random unload event and then the view is lost

**Comment by BalusC** [comment]
> getting totally random unload events [...], where I'm not using any Omnifaces @viewscoped.

Perhaps `<h:form>` generated incorrect URLs. Try using `<o:form useRequestURI="true">` instead.

> The ajax poll gets a random unload event

This suggests that the ajax poll itself is broken.

> Do you have a clue of where can I look at? 

Put a breakpoint in unload JS event listener and inspect the stack to find out the trigger.

**Comment by BalusC** [comment]
Any progress?

**Comment by cocorossello** [comment]
Hi, 

I haven't used ViewScoped in production since then and I'm not able to reproduce it locally (or in CI). Since I removed it, it didn't happen again.

I'll close the issue and reopen if I'm able to get more information.
