### ISSUE TITLE
Myfaces 2.3.1 and omnifaces 3.1 minor bug

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#464]
Hi,

There is a minor error with myfaces 2.3.1 and CombinedResourceHandler. I'm not sure if it's myfaces error or omnifaces.

I have in my configuration (or in web.xml, it doesn't matter):
            servletContextEvent.getServletContext().setInitParameter("org.omnifaces.COMBINED_RESOURCE_HANDLER_DISABLED", "true");

Then CombinedResourceHandler fails with: 
java.lang.ClassCastException: java.base/java.lang.String cannot be cast to [C

The problem is in CombinedResourceHandler:309:
String.valueOf(evaluateExpressionGet(disabledParam)))

If it's changed to:
evaluateExpressionGet(disabledParam).toString())

it works (but it also should take care of null).

Workaround is as simple as use some dynamic property  or subclass the CombinedResource class
servletContextEvent.getServletContext().setInitParameter("org.omnifaces.COMBINED_RESOURCE_HANDLER_DISABLED", "#{myBean.shouldDisableCominer}");

**Comment by BalusC** [comment]
Fixed in 2.7-SNAPSHOT and 3.2-SNAPSHOT
