### ISSUE TITLE
<o:validateBean> should use locale of current request

### ISSUE THREAD

**Issue by hwellmann** [omnifaces/omnifaces#466]
## Scenario

I have a form which combines field-level validations (using `javax.validation` annotations on a CDI managed bean) with cross-field validation via `<o:validateBean>`.

## Expected Behaviour

All constraint violation message use the locale of the current request (ultimately derived from browser language settings).

## Actual Behaviour

The field-level violation messages use the request locale (German in my case), whereas the cross-field violation messages use the server default locale (English in my case).

## Notes

Tested on WildFly 12.0.0.Final with Omnifaces 2.6.8 and 3.1, using Oracle JDK 1.8.0_162.

It seems that Omnifaces does not use the `javax.faces.validator.BeanValidator` which adds a `JsfAwareMessageInterpolator` to the validation context.

**Comment by BalusC** [comment]
Fixed in 2.7-SNAPSHOT.

Thank you for reporting and improving OmniFaces!
