### ISSUE TITLE
Undeprecate includeViewParams and includeRequestParams of <o:form>

### ISSUE THREAD

**Issue by skuntsel** [omnifaces/omnifaces#468]
It seems that `includeViewParams` and `includeRequestParams` of `<o:form>` might still be helpful when the application server is accessed via a reverse proxy.

In case the proxy rewrites the URL (e.g. inserts `/path` to the initial URL path), and the request is later forwarded (e.g. removes back the `/path`) the action of the generated form element of `<o:form useRequestURI="true" ... />` will be incorrect.

In case a view handler is properly configured to correctly handle the proxied requests the right URLs could be generated via `<o:form useRequestURI="false" includeRequestParams="true" ... />`, thus making a valid use case for the aforementioned attributes.

In fact, it could make sense to take into account the proxied requests with a correctly configured view handler and modify the first line of `Form.ActionURLDecoratorViewHandler#getActionURL` method from

    String actionURL = form.isUseRequestURI() ? getActionURL(context) : getWrapped().getActionURL(context, viewId);

to

    Map<String, String> requestHeaderMap = context.getExternalContext().getRequestHeaderMap();
    boolean proxied = requestHeaderMap.containsKey("Forwarded") || requestHeaderMap.containsKey("X-Forwarded-For");
    String actionURL = form.isUseRequestURI() && !proxied ? getActionURL(context) : getWrapped().getActionURL(context, viewId);

**Comment by BalusC** [comment]
Understood, but not all proxies manipulate the request URI.

I've undeprecated the `includeRequestParams` and made its default behavior to set `useRequestURI` to `false`.

    <o:form includeRequestParams="true">

should do it for you.
