### ISSUE TITLE
Feature: change the user of the socket component on demand with JavaScript

### ISSUE THREAD

**Issue by fkjaekel** [omnifaces/omnifaces#472]
Since PrimeFaces push is going to be discontinued, I started to migrate to OmniFaces push. For notification purposes it's all working as expected, but I have a chat application where I'm missing one thing in OmniFaces:

Change the user of the socket on demand. I require this for private conversations. On PrimeFaces I used to create a channel for each two people conversation based on the participants users ids, and I passed it to the connect method of their socket component. 

With OmniFaces I would use this custom id as the user of the channel, and both participants of the conversation would connect on it. 

I tried to place the socket component inside a PrimeFaces output panel, bind the user property to a view scoped bean, update the panel on a ajax request and on the oncomplete event call OmniFaces.Push.open('channelName'), but I can see on the SocketObserver class(from the showcase) that the user has not been updated. 

As a workaround I created the channel using only the logged user id as user and send the message to the list of the users in the conversation (same way it's described at the showcase), but if someone different from the person that he is talking at the moment sends a message, I ignore it at the JavaScript callback instead of appending it. 

Could consider something like OmniFaces.Push.setUser() for a future release?

Thanks

**Comment by BalusC** [comment]
I'm not exactly understanding the concrete problem.

You could just send the ID of the other chat particpiant as part of `PushContext#send()` payload and have the UI append it to the correct chat box when present.

**Comment by fkjaekel** [comment]
Yes I did this way, sorry for the confuse text. 

I was actually more worried about a costumer support app I have. It has dozens of simultaneous conversations, but reviewing the code, since a costumer can open only one conversation at time, I think I could change the logic and have one channel with the ckerk id and the other with the costumer id, instead of having the channel with the attendance id like I did in PrimeFaces.

But still that would be a big refactor. So I don't see this anymore as a limitation, but as a migration helper. If I could change the user dynamically it would simplify a lot the migration from PrimeFaces for me, and I guess other people too, since push is not working in PF 6.2(https://github.com/primefaces/primefaces/issues/3138) and will be removed in PF 6.3.

Thanks

**Comment by BalusC** [comment]
It's now in 3.2-SNAPSHOT. Any changes in `<o:socket user="#{...}">` will now be taken into account across ajax requests, like as already implemented on `connected` attribute.

Also a new `@SocketEvent.Switched` has been added which you can observe. The physical socket itself won't be closed/reopened.
