### ISSUE TITLE
Enhance of:formatBytes() to format in either SI units or IEC units

### ISSUE THREAD

**Issue by pholding** [omnifaces/omnifaces#473]
Could the `of:formatBytes()` function be enhanced to provide the option of formatting in either SI or IEC units rather than just IEC units?

Ideally `#{of:formatBytes(500000,'SI')}` would return "500 kB" and `#{of:formatBytes(500000,'IEC')}` would return "488.3 KiB"

**Comment by BalusC** [comment]
Use `#{of:formatThousandsUnit(500000, 'B')}`
