### ISSUE TITLE
<o:tagAttribute> not (always) working

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#475]
In short: I found a usecase, where the propagation of the id-attribute is not working as expected.

The issue is described in detail at [this StackOverflow article](https://stackoverflow.com/questions/51247880/omnifaces-otagattribute-not-working-under-some-circumstances).

**Comment by BalusC** [comment]
This is fixed in 2.6.9 but overlooked in "what's new?" notes.

Please retry with 2.6.9.

**Comment by matinh** [comment]
Ok, it seems already fixed in 2.6.9. Thanks.
