### ISSUE TITLE
Issue with TagAttribute

### ISSUE THREAD

**Issue by andrewscode** [omnifaces/omnifaces#478]
Omnifaces: 2.7
Wildfly 13.0  (JSF: 2.2.13.SP5)

The latest changes to TagAttribute  in 2.6.9 and 2.7 has caused some weird issue with id when extra attributes are added to a tag.

formGroup.xhtml
```
<o:tagAttribute name="id" />

<br/>formGroupId: #{id}
    
<ui:insert />
```

formRow.xhtml:
```
    <o:tagAttribute name="id" />

    <br/>formRowId: #{id}
```

test1.xhtml:
```
        <jt:formGroup>
            <jt:formRow></jt:formRow>
        </jt:formGroup>
```
Yields: (expected)
```
formGroupId: j_ido-1420978802_5143a44a 
formRowId: j_ido-1859022143_73cd9e71
```

test2.xhtml: (adding an extra random attribute)
```
        <jt:formGroup>
            <jt:formRow test="asd"></jt:formRow>
        </jt:formGroup>
```
Yields: (incorrect duplicate id)
```
formGroupId: j_ido-1420978802_5143a44a 
formRowId: j_ido-1420978802_5143a44a
```

**Comment by Rapster** [comment]
I don't think the id is the problem, sounds like related to #475 (which looks closed)

**Comment by BalusC** [comment]
Nasty. Thanks for reporting.

**Comment by andrewscode** [comment]
I tested out the changes and experienced a similar error:

`
<jt:formGroup id="test">
        <jt:formRow>
        </jt:formRow>
    </jt:formGroup>
`

Produces:
`
formGroupId: test
formRowId: test
`
