### ISSUE TITLE
html 'p' component

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#480]
JSF should have a component for html paragraph _p_ tag. 
Best solution would be a _tag_ attribute at _outputText_ which will render a _p_ instead of _span_ like: 

    <h:outputText tag="p" value="#{msg.myText}" rendered="#{bean.show}"/>

Or a separate _p_ component since its just boilerplate to have markup like.

	<ui:fragment rendered="#{bean.show}">
		<p><h:outputText value="#{msg.myText}" escape="false"/></p>
	</ui:fragment>

**Comment by BalusC** [comment]
You can use `<p jsf:rendered="#{bean.show}">`.

**Comment by djmj** [comment]
Ah i forgot that this is possible. Thank you.
