### ISSUE TITLE
Provide configuration for UnmappedResourceHandler

### ISSUE THREAD

**Issue by EugenFischer** [omnifaces/omnifaces#481]
Please provide configuration (with meaningful default setting) for resources handled by the UnmappedResourceHandler.
Currently does handle each resource.

**Comment by BalusC** [comment]
Just adjust the `<url-pattern>` in `web.xml` accordingly.

**Comment by BalusC** [comment]
Which problem exactly are you trying to solve this way?

**Comment by EugenFischer** [comment]
On configure Faces Servlet using prefix mapping /javax.faces.resource/* **each** request started with that prefix get handeled by UnmappedResourceHandler. Also composite components which normaly locaed under resources folder. 
I've try to filter out resouce request for composite components and delegate to the wrapped ResourceHandle, but mix of prefix, suffix handling for Faces Servlet is not expected by default resource handler.

**Comment by BalusC** [comment]
Yes, I understood that part. But what is the underlying problem you tried to solve this way? It should in first place not cause any problems with composite components.

**Comment by EugenFischer** [comment]
It provides access to each artifact located in "resources" folder, also composite components (if you have the knowledge that they exits).
This is not a really security relevant, but expose internal resources.

**Comment by BalusC** [comment]
Even without UnmappedResourceHandler these are still accessible. So it's not related to the UnmappedResourceHandler. The normal solutions to this problem are listed in https://stackoverflow.com/q/13861612/157882

Do you have a different problem with UnmappedResourceHandler?

**Comment by EugenFischer** [comment]
Thanks for the hint.

May i did something wrong, but without usage UnmappedResourceHandler the request to internal composite components retrieve empty response. By configure the UnmappedResourceHandler as resource handler, the source of composite component will be retrieved.
