### ISSUE TITLE
@org.omnifaces.cdi.ViewScoped not working correctly with multiple tabs

### ISSUE THREAD

**Issue by wilhei** [omnifaces/omnifaces#483]
Hello everyone,

I found a problem working with @org.omnifaces.cdi.ViewScoped:

I have a link in TestPage.xhtml that opens another page (ShowValuePage.xhtml) with a request parameter "someValue". If I open this link 10 times in a new tab and navigate away in the first opened tab, PostConstruct will be called again instead of just navigating away.

Same happens if I navigate back from ShowValuePage to TestPage multiple times. (To test this, we must click the links "Show Value" and "Home" multiple times).

This only happens if more tabs are opened than defined in the web.xml values "numberOfLogicalViews" and "numberOfViewsInSession".

I've set up a small project that shows this problem. The exact description of the procedure can be found in the readme.txt.

https://github.com/wilhei/jsfMultipleTabs

Is there a workaround for this?

Thank you and best regards
Heinrich

**Comment by kukel** [comment]
Why do you think this is a bug instead of 'as designed'.

**Comment by BalusC** [comment]
Fixed, but only for modern browsers which use [navigator.sendBeacon](https://caniuse.com/#feat=beacon) during unload instead of legacy synchronous XMLHttpRequest.
