### ISSUE TITLE
EL function for checking presence of a component in component-tree

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#484]
I would like to see an EL function in OmniFaces that allows to check if a component with a given ID is contained in the component-tree. There is `<o:resolveComponent>` which is similar, but throws an exception if the specified component is not found. There is also PrimeFaces' `#{p:resolveClientId()}` which is even more similar to what I want. But it also throws an exception if specified component is not found.

The use-case I have for this function is for AJAX updates of component which are within a <c:if> tag and are thus not included in the component tree.

Currently I use this code:

    <p:commandLink id="someLink" value="click me" 
                   update="#{component.findComponent(':myForm:myConditionalComp') != null ? ':myForm:myConditionalComp' : ''} />

But I'd like to have something more explicit and shorter like

    <p:commandLink id="someLink" value="click me"
                   update="#{of:componentExists(':myForm:myConditionalComp') ? ':myForm:myConditionalComp' : ''} />

or much shorter

    <p:commandLink id="someLink" value="click me"
                   update="#{of:ifComponentExists(':myForm:myConditionalComp')} />

The latter would be a function that returns the components ID if it is found, or an empty string (or null?) if it is not found.

What do you think? Is this worth an OmniFaces function?

**Comment by BalusC** [comment]
So far, I haven't stumbled upon real world use cases whereby I missed this function. Closing off.
