### ISSUE TITLE
Support for <p:pickList> in ValidateMultipleFields

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#488]
OmniFaces provides validators that validate multiple fields at a time, like `<o:validateAll>`, `<o:validateMultiple>`, etc. These validators won't work with PrimeFaces' `pickList` components, due to the lack of support for the `DualListModel` used by this component.

The problem for `validateAll` is in the method [`isEmpty()`](https://github.com/omnifaces/omnifaces/blob/3.2/src/main/java/org/omnifaces/util/Utils.java#L136) from the `Utils` class. Other component do validation different.

Adding another `instanceof` statement in this method would solve the problem for the `validateAll` component, but introduce a dependency to PrimeFaces, which is probably unwanted. Maybe there is a more elegant solution for this?

**Comment by BalusC** [comment]
You could work around the `<o:validateAll>` issue with a custom `DualListModel` which implements `Collection` and delegates to `DualListModel#getTarget()`.

E.g.

```
public class CustomDualListModel<T> extends DualListModel<T> implements Collection {

	public CustomDualListModel(List<T> source, List<T> target) {
		super(source, target);
	}

	@Override
	public boolean isEmpty() {
		return getTarget().isEmpty();
	}

	@Override
	public int size() {
		return getTarget().size();
	}

	@Override
	public boolean contains(Object o) {
		return getTarget().contains(o);
	}

	// Etc ...
}
```

**Comment by matinh** [comment]
Thank's for the hint with implementing `Collection`. However, this doesn't work out of the box, as PrimeFaces' `PickListRenderer` has a `getConvertedValue()` method which looks something like this:

            // ...
            String[][] value = (String[][]) submittedValue;
            String[] sourceValue = value[0];
            String[] targetValue = value[1];
            DualListModel model = new DualListModel();   // <--- problematic

            pickList.populateModel(context, sourceValue, model.getSource());
            pickList.populateModel(context, targetValue, model.getTarget());

            return model;

Thus, for your suggestion to work, one would have to implement a custom renderer that overrides `getConvertedValue()` and uses the `CustomDualListModel` from above instead of `DualListModel`.
For the renderer to be used by JSF you have to add the following lines to your `faces-config.xml`:

    <render-kit>
      <renderer>
        <component-family>org.primefaces.component</component-family>
        <renderer-type>org.primefaces.component.PickListRenderer</renderer-type>
        <renderer-class>my.company.MyPickListRenderer</renderer-class>
      </renderer>
    </render-kit>

See [this StackOverflow answer](https://stackoverflow.com/questions/8076625/) for details on how to use your own renderer.

However, once the custom renderer is used, the `CustomDualListModel` workaround works just fine. Thanks!

**Comment by matinh** [comment]
For the records: there seems to be some other bug (maybe a PrimeFaces bug?) that might get triggered by `<o:validateAll>`. Details can be found on [StackOverflow](https://stackoverflow.com/questions/54826563/).

**Comment by matinh** [comment]
It turned out, that the PrimeFaces issue [#4756](https://github.com/primefaces/primefaces/issues/4756) seems to be a Mojarra bug: [#4398](https://github.com/javaserverfaces/mojarra/issues/4398).
