### ISSUE TITLE
No library found for namespace http://omnifaces.org/ui in NetBeans 8.2/9.0

### ISSUE THREAD

**Issue by johbor** [omnifaces/omnifaces#489]
With OmniFace 3.2 you get an error message in a facelet 
`No library found for namespace http://omnifaces.org/ui`

With NetBeans 8.2 en 9.0 you can only have the 8.2 JEE plugins.
You can actually make JSF2.3 work but adding OmniFaces to a facelet then renders the error.

I managed to get rid of the error  by unpacking the omnifaces-3.2.jar to a directory and add that directory to the libraries of the project and remove the omnifaces-3.2.jar from the libraries.
After that I changed the XML tag facelet-taglib to a signature as used in mojarra_ext.taglib.xml of javax.faces-2.3.7.jar the error is going away from the facelet.
I saw a closed issue about a namespace not found in NetBeans 8.2 and I have the same problem.

[https://github.com/omnifaces/omnifaces/issues/442](url) 

I think the NetBeans webproject is not able to see the new signature of the omnifaces-ui.taglib.xml version 2.3.
The NetBeans IDE is making a transition to Apache and until Feb. 2019 there will not any renewal on the Jakarta EE plugins for NetBeans supporting JSF 2.3

[https://cwiki.apache.org/confluence/display/NETBEANS/Apache+NetBeans+Release+Roadmap](url)

So what I did was to uncheck the package checkbox of the changed directory in the library settings and in the web build/packaging to add the omnifaces-3.2.jar.
Actually I think it is a NetBeans problem but until feb. 2019 no updates on Jakarta EE to expect from there.

A picture of 2 projects, 1 with problem and the second with solved problem of the index.xhtml
![screen shot 2018-10-22 at 15 56 02](https://user-images.githubusercontent.com/9353297/47298773-eab3a100-d618-11e8-849e-627e6507ee97.png)

A picture of the library settings of the second project
![screen shot 2018-10-22 at 16 22 19](https://user-images.githubusercontent.com/9353297/47298855-19317c00-d619-11e8-9211-c4ba9491176e.png)

A picture of the build/packaging settings of the second project
![screen shot 2018-10-22 at 16 22 34](https://user-images.githubusercontent.com/9353297/47298898-3bc39500-d619-11e8-867f-3f0309f2f850.png)

**Comment by BalusC** [comment]
Thank you for describing the work around, but this is really a bug/issue in Netbeans itself, not in OmniFaces. If I would downgrade the OmniFaces taglib file, then future IDEs which actually support JSF 2.3 may not cope well with it.

The Netbeans guys could better make their JSF version detection a bit less explicit. E.g. let it support a higher version and treat it as the last known one.
