### ISSUE TITLE
ImportFunctionsMapper takes only one of several methods into account

### ISSUE THREAD

**Issue by mahairod** [omnifaces/omnifaces#490]
ImportFunctionsMapper takes only one of several methods into account. For example if we have several methods with same name and parameter count (`java.utils.Arrays.toString(smth[])`) then mapper collects only last of them, and sometimes it may be not the method a was looking for.
[`ImportFunctions`](https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/ImportFunctions.java#L198)

**Comment by BalusC** [comment]
This is a technical limitation induced by EL: https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/ImportFunctions.java#L59
