### ISSUE TITLE
CacheControlFilter doesn't work on CSS background images

### ISSUE THREAD

**Issue by banifou** [omnifaces/omnifaces#491]
I'm using OmniFace 2.7 and Primefaces 6. I set with CacheControlFilter an expire time of 365d for all image types (*.jpg|*.jpeg|*.png|*.gif|*.ico).
This browser caching settings seem not to apply to CSS background images that get an url like:

> ".../playground/javax.faces.resource/images/smiley.jpg.xhtml"

Same apply to the combined resource files (CSS and JS) that have an url like:

> .../javax.faces.resource/LONG-HASH.js.jsf?ln=omnifaces.combined&v=1544138175000

Do you have any idea how to solve this issue? Thanks

**Comment by BalusC** [comment]
As mentioned in [javadoc](http://omnifaces.org/docs/javadoc/2.7/org/omnifaces/filter/CacheControlFilter.html), `CacheControlFilter` explicitly skips JSF resources because they have their own context param setting to configure expire time.
