### ISSUE TITLE
Omnifaces Viewscoped Unload Javascript on transient Views

### ISSUE THREAD

**Issue by neXus1987** [omnifaces/omnifaces#492]
Hi Team,

is it possible to avoid the rendering of the Omnifaces.Unload script for transient views?

Thanks
Phil

**Comment by BalusC** [comment]
That's already implemented. It will log a warning line instead. https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/cdi/viewscope/ViewScopeManager.java#L188

Which version are you using?

**Comment by neXus1987** [comment]
Hi Balus,

i´m using 	
<dependency>
<groupId>org.omnifaces</groupId>
<artifactId>omnifaces</artifactId>
<version>3.2</version>
</dependency>


Ok, i will investigate why the root view isn´t transient. 
Thanks!

**Comment by neXus1987** [comment]
Ok if i use the f:view transient="true" in the template, the root view won´t be transient. If i use f:view on the xhtml page which uses the template, then the rootview is transient.

**Comment by BalusC** [comment]
No problem!
