### ISSUE TITLE
<o:socket> auto-reconnect doesn't work on server restart

### ISSUE THREAD

**Issue by jasonex7** [omnifaces/omnifaces#494]
I'm testing the auto-reconnect feature of `<o:socket>` component in case of server restart, but it fails. It doesn't work on server restart in application and session scope `<o:socket>`. I had to do a page refresh and a new connection was established successfully. The test was performed with WildFly 10.1 + JDK 8u191 + JSF 2.2 + OmniFaces 2.7.

I also try to do an ajax update of the `<o:socket>` component via `onclose` property in case of close code 1000 (which occurs on server restart), but after the component was rendered successfully I've got 1008 error code. I review this case and think the problem is because a new random UUID  is generated for the same channel, but the variable `sockets` of the JavaScript object `OmniFaces.Push` keeps record of the former UUID and doesn't refresh itself on `init` method.

https://github.com/omnifaces/omnifaces/blob/acd5a47591128da9085044a88a0d0e54c9da4bac/src/main/resources/META-INF/resources/omnifaces/push.unminified.js#L154

I'm very happy with <o:socket> component, thank you very much for adding to the JSF 2.2 version of OmniFaces.

**Comment by BalusC** [comment]
Javadoc has been improved. Also took opportunity to describe how to correctly use push in a cluster.
