### ISSUE TITLE
FacesExceptionFilter and FullAjaxExceptionHandler

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#495]
I apologize for the question but I am working on new project with these libraries:
**OminFaces 3.2**
**MyFaces 2.3**
**PrimeFaces 6.2**

I am using FullAjaxExceptionHandler and FacesExceptionFilter to map errors to an error page called common/error.jsf.

When I get an error caught by the FacesExceptionFilter I get this in the log and it properly shows me my full error page.

> FacesExceptionFilter: An exception occurred during processing servlet request. Error page '/common/error.jsf' will be shown.

![non-ajax-error](https://user-images.githubusercontent.com/4399574/51411145-cf333600-1b34-11e9-91b7-860cbcf11ce8.jpg)

However when I get an AJAX error the FullAjaxExceptionhandler is catching the error and routing to my error.jsf page.  I can see the full HTML in the Ajax request.  However, the page is not being displayed correctly.  It looks like this...

> FullAjaxExceptionHandler: An exception occurred during processing JSF ajax request. Error page '/common/error.jsf' will be shown.

![ajax-error](https://user-images.githubusercontent.com/4399574/51411151-d2c6bd00-1b34-11e9-82ad-610b72ec0fcb.jpg)

Was hoping you could shed some light on what I am doing wrong or what might be happening that the Ajax request is not rendering my error page properly.

**Comment by BalusC** [comment]
Most probably you've stylesheets specific to the error page in the head of the error page itself instead or in a shared template. Ajax responses by default doesn't update the head.

**Comment by melloware** [comment]
Ahhh OK let me try and figure it out.  That does make sense.

**Comment by melloware** [comment]
OK I can see the CSS in the HEAD of the main page before the error is thrown and when I inspect the HTML of the error.jsf both in Ajax and non Ajax it has that StyleSheet in the head.  But for some reason the browser is not seeing it.

```html
<head id="j_id_3">
<meta http-equiv="X-UA-Compatible" content="IE=edge"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"><meta name="apple-mobile-web-app-capable" content="yes"><link href="/javax.faces.resource/images/favicon.ico.jsf" rel="shortcut icon" type="image/x-icon"><link type="text/css" rel="stylesheet" href="/javax.faces.resource/theme.css.jsf?ln=primefaces-babylon-bluegrey-accent"><link type="text/css" rel="stylesheet" href="/javax.faces.resource/fa/font-awesome.css.jsf?ln=primefaces&amp;v=6.2.13"><link rel="stylesheet" type="text/css" href="/javax.faces.resource/components.css.jsf?ln=primefaces&amp;v=6.2.13"><script type="text/javascript" src="/javax.faces.resource/jquery/jquery.js.jsf?ln=primefaces&amp;v=6.2.13"></script><script type="text/javascript" src="/javax.faces.resource/core.js.jsf?ln=primefaces&amp;v=6.2.13"></script><script type="text/javascript" src="/javax.faces.resource/components.js.jsf?ln=primefaces&amp;v=6.2.13"></script><link rel="stylesheet" type="text/css" href="/javax.faces.resource/css/nanoscroller.css.jsf?ln=babylon-layout"><link rel="stylesheet" type="text/css" href="/javax.faces.resource/css/primeflex.css.jsf?ln=babylon-layout"><link rel="stylesheet" type="text/css" href="/javax.faces.resource/css/layout-bluegrey.css.jsf?ln=babylon-layout"><link rel="stylesheet" type="text/css" href="/javax.faces.resource/inventory-manager.css.jsf?ln=css"><script type="text/javascript">if(window.PrimeFaces){PrimeFaces.settings.locale='en_US';PrimeFaces.settings.projectStage='Development';}</script>
<title>Inventory Manager - Error</title></head>
```

This is really strange.

**Comment by melloware** [comment]
Looks like it is the same issue as this guy is having: https://stackoverflow.com/questions/53400252/houtputstylesheet-not-inserted-when-using-fullajaxexceptionhandler

**Comment by melloware** [comment]
My apologies. Your exact solution was here:  https://stackoverflow.com/questions/43224613/hbody-not-rerendered-when-using-fullajaxexceptionhandler

I was styling the body class which I see now is now allowed.

**Comment by kawoolutions** [comment]
I cannot see the solution here or it doesn't work for our project:

https://stackoverflow.com/questions/58032100/omnifaces-fullajaxexceptionhandler-exception-on-ajax-request-results-in-renderi
