### ISSUE TITLE
Provide a default JSF viewhandler to support generated URL's

### ISSUE THREAD

**Issue by adam-waldenberg** [omnifaces/omnifaces#496]
Filters are great. However, they completely break the JSF lifecycle whenever you use them to generate virtual URL's (with `servletContext.getRequestDispatcher(DESTINATION).forward()` specifiaclly).

The default view handler generates action URL's that point to the forwarded page by default. When generating URL's this often points to a hidden document inside `WEB-INF/` - resulting in the request failing.

I'm proposing OmniFaces could include a filter-friendly forward view handler that does something like this;

```
public class ForwardedViewHandler extends ViewHandlerWrapper {
	public final static String FORWARDED_PATH = "org.omnifaces.viewhandler.FORWARDED_PATH";
        private final ViewHandler wrappped;

        public ForwardedViewHandler(ViewHandler wrappped) {
                super();
                this.wrappped = wrappped;
        }

        @Override
        public ViewHandler getWrapped() {
                return wrappped;
        }

        @Override
        public String getActionURL(FacesContext context, String viewId) {
		final String originalViewId = getRequestAttribute(context, FORWARDED_PATH);

		if (originalViewId != null) {
			final String contextPath = context.getExternalContext().getRequestContextPath();
			return String.format("%s/%s", StringUtils.removeEnd(contextPath, "/"), originalViewId);
		}

		return super.getActionURL(context, viewId);
        }
 }
```

If we then provide a new utility class `Filter` together with a `Filter.forward()` method that automatically sets the above request attribute this would allow us to easily create forwarding filters that don´t break the action URL generated in JSF.

If you like the idea, I can create a PR. But I thought it could be an idea to open this up for discussion first.

**Comment by BalusC** [comment]
I'm not exactly sure if I understand the problem.

OmniFaces has several solutions built in for this issue. Primarily, the `Faces#getRequestXxx()` and `Servlets#getRequestXxx()` utility methods support forwarded URLs. These are in turn used by among others `<o:form>` and `FacesViews`. So they transparently support forwarded URLs as well.

**Comment by adam-waldenberg** [comment]
Thanks @BalusC. You are understanding it perfectly. I had no idea this was already supported! Looks like it's time to move to "o:form" for all the pages accesed via a filter! :+1: I tried the above and it's working exactly as intended - so I'm closing this issue :) .
