### ISSUE TITLE
It's been a while, any plans for a 3.3 release?

### ISSUE THREAD

**Issue by exsilium** [omnifaces/omnifaces#509]
Firstly, thank you for all the hard work and effort that goes into maintaining Omnifaces! :bowing_man: As the issue indicates. there are some nice workarounds and fixes done in 3.x branch. Any plans or indication of one for a minor release? Cheers! :smiley: :trophy: :beers:

**Comment by BalusC** [comment]
I wanted to finish up a few weeks ago but I couldn't reproduce #503 and it seemed serious enough to investigate for next version. I'm grabbing a Windows laptop this weekend.

**Comment by codylerum** [comment]
@BalusC Thanks. I've been running on 3.3-Snapshot for the last 6 months https://github.com/eclipse-ee4j/mojarra/issues/4500 and it would be great to get on a stable release.

**Comment by BalusC** [comment]
http://central.maven.org/maven2/org/omnifaces/omnifaces/3.3/
