### ISSUE TITLE
Add onerror to <o:socket>

### ISSUE THREAD

**Issue by kmahlmann** [omnifaces/omnifaces#512]
We would like to react to network/server problems (e.g. notify the user).

Alternatively having access to the WebSocket objects in OmniFaces.Push would be fine.
As a workaround we will now grab the WebSocket from the first MessageEvent received.

Thanks...

**Comment by kmahlmann** [comment]
That didn't work. It's only called, when the server is up again and the connection can't be reestablished.
(Using the WebSocket's onerror didn't work either.)

Thanks anyway... I'll look for a different approach

**Comment by BalusC** [comment]
Ah, I'm getting you.

Yes this can be added.

**Comment by BalusC** [comment]
It's in 3.4-SNAPSHOT now.

**Comment by kmahlmann** [comment]
Works great, as far as I've tested it.
Much appreciated...

**Comment by ravihariharan** [comment]
@BalusC  can this fix also be made available for version 2.x ?
