### ISSUE TITLE
converterAttributes not working in Param annotation with convert-id reference

### ISSUE THREAD

**Issue by parysto** [omnifaces/omnifaces#513]
In my application, I'm using the `@Param` annotation to convert and inject a GET-parameter. I want this converter to be configurable. 
According to the JavaDoc of the annotation, attributes can be set on the converter instance using `Param#converterAttributes()`. However, I'm experiencing issues when I reference the converter with `Param#converter()` or `Param@converterClass()`:

- With `Param#converter()`, attributes are **not** set, but EJBs are injected in converter
- With  `Param@converterClass()`, attributes are set, but EJBs are **not** injected in converter

I'm running Omnifaces 3.3 on Payara 5.191.

### Named and ViewScoped CDI bean

    Named("test")
    @ViewScoped
    public class TestBean implements Serializable {

        @Inject
        @Param(
                converter = "testConverter",
                converterAttributes = {
                    @Attribute(name = "testAttr", value = "Value for TestAttr")}
        )

        String test;
        @Inject
        @Param(
                name = "test",
                converterClass = TestConverter.class,
                converterAttributes = {
                    @Attribute(name = "testAttr", value = "Value for TestAttr")}
        )
        String testClass;

    }

### Converter

    @FacesConverter(value = "testConverter", managed = true)
    public class TestConverter implements Converter<String> {

        @Inject
        SomeEjb someEjb;

        String testAttr;

        public String getTestAttr() {
            return testAttr;
        }

        public void setTestAttr(String testAttr) {
            this.testAttr = testAttr;
        }

        @Override
        public String getAsObject(FacesContext context, UIComponent component, String value) {
            System.out.println("!!!TestAttr: " + testAttr);
            System.out.println("!!!Ejb: " + someEjb);
            return "Object---" + value;
        }

        @Override
        public String getAsString(FacesContext context, UIComponent component, String value) {
            System.out.println("!!!TestAttr: " + testAttr);
            System.out.println("!!!Ejb: " + someEjb);
            return "String---" + value;
        }

    }

**Comment by BalusC** [comment]
Fixed in today's 2.7.2-SNAPSHOT and 3.4-SNAPSHOT.

Thank you for reporting!
