### ISSUE TITLE
o:validator not serializable

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#514]
It's quite ok that o:validator (org.omnifaces.taghandler.Validator) is not Serializable, since it is tag handler. But it creates anonymous class `new DefferedValidator()`

https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/Validator.java#L136

which internally references outer Validator class, which is not Serializable. 

Fix suggestion: 
1. make DeferredClass not anonymous class with flds validator, attributes, disabled, message 
2. make DeferredAttributes Serializable

**Comment by skybber** [comment]
Look at:
https://stackoverflow.com/questions/17804704/notserializableexception-on-anonymous-class

`Inner classes should not implement Serializable. They use ...`

**Comment by BalusC** [comment]
Awkward. I've fixed it. Retry with today's 3.4-SNAPSHOT and let me know.

**Comment by skybber** [comment]
According me the `org.omnifaces.taghandle.Validator` should implement Serializable as well, since it creates serializable anonymous class extended from DeferredValidator so enclosing class must be Serializable.

```
Usually, the problem seen when serializing anonymous class is that the enclosing class is not serializable (and the author failed to realize that serializing an anonymous class involves serializing its enclosing class).
```

**Comment by BalusC** [comment]
I'm failing to understand the problem.

Are you binding the component tree to a view/session scoped bean? A reproducer of your problem would be helpful.

**Comment by skybber** [comment]
May be I'm wrong...  but anonymous class created at this point:

https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/Validator.java#L136

is declared as Serializable but it is actually not Serializable since enclosing class `org.omnifaces.taghandle.Validator` is not Serializable.
