### ISSUE TITLE
Upgraded from OmniFaces 3.2 -> 3.3 EAR won't deploy

### ISSUE THREAD

**Issue by NOTiFYcouk** [omnifaces/omnifaces#515]
Just upgraded my project to OmniFaces 3.3 which is powered by:

PrimeFace (Elite) 7.0.3
Java openjdk 11.0.2
Kotlin 1.3.31

JBoss WildFly 16.0.0.FINAL
Undertow 2.0.19.Final
Mojarra 2.3.9.SP01 

Google Chrome Version 74.0.3729.157 (Official Build) (64-bit)
Safari 12.1 (14607.1.40.1.4)
macOS Mojave 10.14.5

and when I deploy my EAR I get:

> 22:28:05,790 INFO  [org.primefaces.webapp.PostConstructApplicationEventListener] (ServerService Thread Pool -- 86) Running on PrimeFaces 7.0.3
> 22:28:05,791 INFO  [org.primefaces.webapp.PostConstructApplicationEventListener] (ServerService Thread Pool -- 86) Running on PrimeFaces 7.0.3
> 22:28:05,791 SEVERE [org.omnifaces.ApplicationProcessor] (ServerService Thread Pool -- 86) OmniFaces failed to initialize! Report an issue to OmniFaces.: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.checkDuplicateResourceHandler(ApplicationProcessor.java:88)
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.processEvent(ApplicationProcessor.java:72)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.event.SystemEvent.processListener(SystemEvent.java:123)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:115)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:553)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:264)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
> 
> 22:28:05,792 SEVERE [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 86) Critical error during deployment: : java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.checkDuplicateResourceHandler(ApplicationProcessor.java:88)
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.processEvent(ApplicationProcessor.java:72)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.event.SystemEvent.processListener(SystemEvent.java:123)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:115)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:553)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:264)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
> 
> 22:28:05,793 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 86) MSC000001: Failed to start service jboss.deployment.subunit."GoStopHandle.ear"."GoStopHandleWAR.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."GoStopHandle.ear"."GoStopHandleWAR.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 	at org.jboss.threads@2.3.3.Final//org.jboss.threads.JBossThread.run(JBossThread.java:485)
> Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
> 	... 8 more
> Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:283)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:216)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:185)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at org.wildfly.extension.undertow@16.0.0.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1502)
> 	at io.undertow.servlet@2.0.19.Final//io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:250)
> 	... 10 more
> Caused by: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.checkDuplicateResourceHandler(ApplicationProcessor.java:88)
> 	at deployment.GoStopHandle.ear.GoStopHandleWAR.war//org.omnifaces.ApplicationProcessor.processEvent(ApplicationProcessor.java:72)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.event.SystemEvent.processListener(SystemEvent.java:123)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.processListeners(Events.java:253)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.invokeListenersFor(Events.java:231)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.applicationimpl.Events.publishEvent(Events.java:115)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.application.ApplicationImpl.publishEvent(ApplicationImpl.java:127)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at javax.faces.api@2.3.9.SP01//javax.faces.application.ApplicationWrapper.publishEvent(ApplicationWrapper.java:788)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigManager.publishPostConfigEvent(ConfigManager.java:553)
> 	at com.sun.jsf-impl@2.3.9.SP01//com.sun.faces.config.ConfigureListener.contextInitialized(ConfigureListener.java:264)
> 	... 22 more
> 
> 22:28:05,796 ERROR [org.jboss.as.controller.management-operation] (External Management Request Threads -- 1) WFLYCTL0013: Operation ("add") failed - address: ([("deployment" => "GoStopHandle.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"GoStopHandle.ear\".\"GoStopHandleWAR.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files."}}
> 22:28:05,798 ERROR [org.jboss.as.server] (External Management Request Threads -- 1) WFLYSRV0021: Deploy of deployment "GoStopHandle.ear" was rolled back with the following failure message: 
> {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"GoStopHandle.ear\".\"GoStopHandleWAR.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.RuntimeException: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.
>     Caused by: java.lang.IllegalStateException: Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files."}}
>

**Comment by NOTiFYcouk** [comment]
BTW - I have a single WAR.

**Comment by BalusC** [comment]
The error message is:
> Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated. This will result in erratic resource handling behavior. Please check your faces-config.xml files, also in web fragment JAR files.

You have duplicate copies of PrimeResourceHandler in your build. Have you also checked your build configuration?

**Comment by NOTiFYcouk** [comment]
I've had no prior issues when I was using OmniFaces 3.2. The error started when I upgrade from 3.2 to 3.3 in my Gradle build:

`compile group: 'org.omnifaces', name: 'omnifaces', version: '3.3'`

I cleaned my  Gradle cache:

`./gradlew build --refresh-dependencies`

Rebuilt and got the 'duplicate' errors.

**Comment by melloware** [comment]
And if you revert back to 3.2 you do not get the errors correct?

**Comment by BalusC** [comment]
This change was indeed implemented in OmniFaces 3.3.

But this actually indicates an underlying problem of:
- you have multiple PrimeFaces JAR files in your classpath
- or, you have multiple declarations of PrimeResourceHandler in all your faces-config.xml files together

**Comment by NOTiFYcouk** [comment]
If I revert back to OmniFaces 3.2:

`compile group: 'org.omnifaces', name: 'omnifaces', version: '3.2'`

It builds and **deploys the EAR**. 

What do you mean by "This change was indeed implemented in OmniFaces 3.3" ?

I only have the PrimeFaces 7.0.3 in my EAR:

`task GoStopHandleEAR(type: Ear) {`
```
...
 dependencies {
     earlib group: 'org.primefaces', name: 'primefaces', version: '7.0.3', ext: 'jar'

**Comment by NOTiFYcouk** [comment]
@BalusC Yes, I had two PrimeFaces (7.0.3) JAR in my WAR & also in my EAR. 

In OmniFaces 3.2 this didn't cause an issue and everything worked. But it did with 3.3, I was getting the "Resource handler class org.primefaces.application.resource.PrimeResourceHandler is duplicated".

When I remove the duplicate PrimeFaces I'm now getting another issue when calling my Controller which calls my EJB and get a null pointer issue. This wasn't there before and my List was being populated. 

Please close the issue.

**Comment by BalusC** [comment]
WAR-targeted libraries indeed don't belong in EAR itself. Glad you sorted it out.
