### ISSUE TITLE
ViewScope not working with MyFaces 3.x

### ISSUE THREAD

**Issue by rmpestano** [omnifaces/omnifaces#516]
OmniFaces uses the following reflective call to retrieve `getSessionViewStorageFactory`:

https://github.com/omnifaces/omnifaces/blob/f5651a42ee11c94951f60264160668eb0799489f/src/main/java/org/omnifaces/util/Hacks.java#L216

The problem is that the method was removed in myfaces trunk in following commit:
https://github.com/apache/myfaces/commit/b27eb9644e5c7b8fd7758a9304c780cd54a36f48#diff-3ce67104eb93e341411b43c4d56d65eb

(cc @tandraschko)

This makes the OmniFaces viewScope unusable in MyFaces 3.x, whenever user left a view it gets a NPE:

```
java.lang.IllegalStateException: Cannot invoke method 'getSessionViewStorageFactory' of class 'class org.apache.myfaces.application.viewstate.ServerSideStateCacheImpl' with arguments [].
        at org.omnifaces.util.Reflection.invokeMethod(Reflection.java:345)
        at org.omnifaces.util.Hacks.removeViewState(Hacks.java:216)
        at org.omnifaces.viewhandler.OmniViewHandler.unloadView(OmniViewHandler.java:137)
        at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:99)
        at org.apache.myfaces.lifecycle.RestoreViewExecutor.execute(RestoreViewExecutor.java:171)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:164)
...
Caused by: java.lang.NullPointerException
        at org.omnifaces.util.Reflection.invokeMethod(Reflection.java:340)
        ... 50 more


```

**Comment by rmpestano** [comment]
Adding the method back into `ServerSideStateCacheImpl` fixes the issue but I don't know if that's a problem to MyFaces team (which is mainly @tandraschko)

**Comment by tandraschko** [comment]
thats the problem with "Hacks.java" :D
readded it, it doesn't hurt

**Comment by rmpestano** [comment]
Thank you @tandraschko (https://github.com/apache/myfaces/commit/956b4292f7bb4ae006ff06f4462c6c0145999466)

Just tested and it works!

Now we just need #517 merged to enable OmniFaces ViewScope in Quarkus :punch:

![Screenshot from 2019-06-04 08-28-52](https://user-images.githubusercontent.com/1592273/58875728-b0c47600-86a2-11e9-807f-1cc9a67d3b36.png)

**Comment by BalusC** [comment]
> thats the problem with "Hacks.java" :D
> readded it, it doesn't hurt

Ha!

Would be nicer if there was a standard JSF API method for exactly this situation. I've ever proposed this to be added to JSF 2.3, but it unfortunately didn't make it due to difficulties with support for portlets and client windows.
