### ISSUE TITLE
Make bean passivation configurable in BeanStorage

### ISSUE THREAD

**Issue by rmpestano** [omnifaces/omnifaces#517]
Currently BeanStorage assumes [all beans are passivation capable](https://github.com/omnifaces/omnifaces/blob/f5651a42ee11c94951f60264160668eb0799489f/src/main/java/org/omnifaces/cdi/BeanStorage.java#L63), this is not true in Quarkus which doesn't support bean passivation, see Quarkus [limitations here](https://quarkus.io/guides/cdi-reference#limitations).

So it would be nice if bean passivation in BeanStorage could be configurable via init parameters.

**Comment by tandraschko** [comment]
Also see: https://github.com/apache/myfaces/commit/2d2e1cf342151e9b21b02044366303a1345c6d3f

**Comment by rmpestano** [comment]
Yea, I've tested MyFaces viewScoped and it also works great on Quarkus, my main motivation here is to help people that already uses OmniFaces ViewScope (our case here at the company) to run/migrate their application on/to Quarkus.

**Comment by melloware** [comment]
@rmpestano I applaud that because my clients use OmniFaces ViewScoped heavily and have for years.

**Comment by BalusC** [comment]
I checked your changes, but I'm not sure why context param would need to be preferred over `type instanceof PassivationCapable`? Can you explain this? Not familiar with Quarkus btw.

**Comment by tandraschko** [comment]
the MyFaces impl also requires to change #getBean which normally returns a key instead the contextual

**Comment by rmpestano** [comment]
>  It should work equally well when Quarkus doesn't actually let the type implement PassivationCapable and that saves yet another context param.

Yea, it also works with instance of just tested, if you prefer I can remove the param.

**Comment by tandraschko** [comment]
@rmpestano can you also check if it works in MyFaces without the param?
i had no luck when after 20 postbacks

**Comment by rmpestano** [comment]
Sure @tandraschko, ping you back here to tell the result.

**Comment by rmpestano** [comment]
Hi again @tandraschko, it looks like @BalusC idea also works for MyFaces but as I'm not so familiar with the codebase I don't know if it has any side effects, see changes [here](https://github.com/rmpestano/myfaces/commit/ab91fca7cbda95501fb7ada677753617e21bfee4) 

I've tested more than 15 views and saw the older views got destroyed as expected because `NUMBER_OF_VIEWS_IN_SESSION` is set to 15: 

![Screenshot from 2019-06-04 21-09-41](https://user-images.githubusercontent.com/1592273/58921448-2b29e000-870d-11e9-954e-b52f702387d8.png)

One thing I'm not sure is [this line](https://github.com/rmpestano/myfaces/blob/ab91fca7cbda95501fb7ada677753617e21bfee4/impl/src/main/java/org/apache/myfaces/cdi/view/ViewScopeContextualStorage.java#L124).

I can open a PR and discuss on myfaces to not polute this issue...

**Comment by tandraschko** [comment]
yep i see
i think i introduced the config to make the the IllegalStateException optional

not sure how essential the check is for normal environments...

**Comment by tandraschko** [comment]
I like this fix:

https://github.com/apache/myfaces/commit/1297baf736f194cc5c22ecde84f562bb91410f15

Please also see:
https://github.com/quarkusio/quarkus/issues/2721
