### ISSUE TITLE
IndexOutOfBoundsException using ListConverter with p:picklist on select event

### ISSUE THREAD

**Issue by rbetjes** [omnifaces/omnifaces#519]
I've been trying to track down a problem with primefaces picklist but I'm starting to think the problem is the combination with omnifaces.ListConverter.
Primefaces 7.0
Omnifaces 2.7.1
Mojarra 2.2.7

I've got a primefaces picklist and feed it a list of pojos as source using the ListConverter. 
The picklist has it's select event wired to a listener. But when one of the items in de picklist is selected then an IndexOutOfBoundsException is thrown because the picklist source seems to be an empty list. 

This does not happen when converting by hand without using ListConverter. 
But it also does not happen in primefaces 6.2, just in 7.0. 

I've created a testcase using the primefaces-test project: https://github.com/rbetjes/primefaces-test

**Comment by rbetjes** [comment]
Looks like the getAsObject method in ListConverter compares a (somewhat) escaped with an unescaped version of the object as string: 
value= TestPojo [id&#x3D;1, name&#x3D;One] 
convertedListValue= TestPojo [id=1, name=One]

That should not be possible, should it?

**Comment by mores** [comment]
I think this is related to  https://forum.primefaces.org/viewtopic.php?f=3&t=58460

**Comment by mores** [comment]
The ListConverter utilizes toString() of the Pojo....
In my case:
`return String.format( "%s[id=%d]", getClass().getSimpleName(), getId() );`

Primefaces 7.0 and greater is now converting from
`[id=3942]`
to
`[id&#x3D;3942]`

which causes the Picklist to stop working if the ListConverter was used.

**Comment by melloware** [comment]
@mores can you try it  by setting the picklist to esape="false" and escapeValue="false" ? I just want to see if that is what is causing the issue.

**Comment by mores** [comment]
@melloware - when setting escape="false" and escapeValue="false" on the picklist - everything seems to work fine.

**Comment by melloware** [comment]
OK can you now narrow it down and set escapeValue="true" ?  let's see which of the two flags causes the issue.  Once we know I can update the PrimeFaces docs to add a warning about using OmniFaces ListConverter.

**Comment by rbetjes** [comment]
I have worked around this issue by changing the toString of the pojo's to not need escaping (changed all equals signs to a colon). 
However, escape="false" seems to fix it also. escapeValue="false" does not. 
But using escape="false" would leave the view with the picklist vulnerable to XSS?

**Comment by melloware** [comment]
Correct escape was added to prevent XSS which introduce this issue.  So I feel like Primefaces is doing the right thing and OmniFaces is not doing anything wrong either, its understanding how to make a good toString for your POJO that doesn't need to be escaped.  I am inclined to have you close this OmniFaces issue?

**Comment by BalusC** [comment]
This is a bug in script behind `<p:pickList>`. It's unnecessarily escaping the submitted value instead of only the presented value (the label).
