### ISSUE TITLE
WebXml.instance() fail when called inside method which Observes initialization of servletcontext (@Observes @Initialized(ApplicationScoped.class) ServletContext servletContext)

### ISSUE THREAD

**Issue by dhaalves** [omnifaces/omnifaces#522]
Hello,

I have been trying to update my ecosystem from java EE 7 + JDK 8 to java EE 8 + JDK 11 and found this issue while updating omnifaces from 2.7.1 to 3.3

#### Working code with omnifaces 2.7.1
```java
     private void registerWebFilter(@Observes @Initialized(ApplicationScoped.class) ServletContext servletContext) {
        FilterRegistration fr = servletContext.addFilter("KeycloakLoginFilter", KeycloakLoginFilter.class);
        WebXml webXml = WebXml.INSTANCE.init(servletContext);
        Map<String, Set<String>> securityConstraints = webXml.getSecurityConstraints();
        fr.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST),
                true, securityConstraints.keySet().toArray(new String[0]));
    }
```

#### Faling  code with omnifaces 3.3, I get org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
```java
    private void registerWebFilter(@Observes @Initialized(ApplicationScoped.class) ServletContext servletContext) {
        FilterRegistration fr = servletContext.addFilter("KeycloakLoginFilter", KeycloakLoginFilter.class);
        WebXml webXml = WebXml.instance();
        Map<String, Set<String>> securityConstraints = webXml.getSecurityConstraints();
        fr.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST),
                true, securityConstraints.keySet().toArray(new String[0]));
    }
```

**Comment by ogregoire** [comment]
You removed the `.init(servletContext)` in the second call.

You should use 

    WebXml webXml = WebXml.instance();
    webXml.init(servletContext);

**Comment by dhaalves** [comment]
.init(servletContext) written deprecated and return Singleton instance.

**Comment by dhaalves** [comment]
.init(servletContext) written deprecated and return Singleton instance.

**Comment by BalusC** [comment]
Weld apparently only places `ServletContext` in CDI scope *after* `@Observes @Initialized(ApplicationScoped.class)`.

Try performing the job in `ServletContextListener#contextInitialized()` instead or in `@PostConstruct` of an `@Eager @ApplicationScoped`.

**Comment by BalusC** [comment]
Any luck with `ServletContextListener`?

**Comment by dhaalves** [comment]
Hello. I had same behavior when I use `ServletContextListener#contextInitialized()`

I had to implement my own `getSecurityConstraints(ServletContext context)` passing servletcontext

**Comment by BalusC** [comment]
OK, I reproduced it, debugged it and fixed it.

Can you retry with 3.4.1-SNAPSHOT?
