### ISSUE TITLE
ValidateOne / Check for emptyness with selectOneMenu and noSelectionOption

### ISSUE THREAD

**Issue by realdognose** [omnifaces/omnifaces#526]
Seen with Omnifaces 2.3: 

The validateOne checks for emptyness of the submitted value: 

          `for (Object value : values) {
			if (!isEmpty(value)) {
				if (hasValue) {
					return false;
				}

				hasValue = true;
			}
		}`

When using 2 selectOneMenus with a custom noSelectionOption, the validator considers both fields filled out. So, In case of the selectOneMenu, the validator should check if the value that IS existing equals the noSelectionOption - then consider it as "no value" as well.

**Comment by realdognose** [comment]
Example to reproduce: 

      <h:form>
    Favourite Color: 
	<p:selectOneMenu id="color">
	  	<f:selectItem noSelectionOption="true" itemValue="NO_PREFERENCE" itemLabel="No Preference"/>
	  	<f:selectItem itemValue="red"/>
	  	<f:selectItem itemValue="blue" />
	  	<f:selectItem itemValue="green" />
	</p:selectOneMenu>

	Favourite Burger: 
	<p:selectOneMenu id="burger">
	  	<f:selectItem noSelectionOption="true" itemValue="NO_PREFERENCE" itemLabel="No Preference"/>
	  	<f:selectItem itemValue="cheeseburger"/>
	  	<f:selectItem itemValue="hamburger" />
	  	<f:selectItem itemValue="chiliburger" />
	</p:selectOneMenu>
	
	<o:validateOne components="color burger" />
	
	<p:commandButton ajax="true" action="start" value="ok">
	
	</p:commandButton>
      </h:form>

results in: 

> j_idt585:j_idt586:j_idt588:color, j_idt585:j_idt586:j_idt588:burger: Please fill out only one of those fields

**Comment by realdognose** [comment]
I extended the "ValidateOne", and modified the code as required. (I only took care for the itemValue, but maybe this can be a part of the solution)

ps.: I expect that the other validators have the same issue - also with other selectmenues available. 

```
@Override
public boolean validateValues(FacesContext context, List<UIInput> inputs, List<Object> values) {
	boolean hasValue = false;

	/**
	 * In Case the input in question is a SelectOneMenu, the noSelectOption should be considered as noValue as well.
	 */

	int i = 0;
	for (Object value : values) {
		UIInput relatedInput = inputs.get(i++);
		Object noSelectValue = null;

		if (relatedInput instanceof HtmlSelectOneMenu) {
			for (UIComponent child : ((HtmlSelectOneMenu) relatedInput).getChildren()) {
				if (child instanceof UISelectItem) {
					if (((UISelectItem) child).isNoSelectionOption()) {
						noSelectValue = ((UISelectItem) child).getItemValue();
						break;
					}
				}
			}

			if (!isEmpty(value) && ((noSelectValue != null) && !noSelectValue.equals(value))) {
				if (hasValue) {
					return false;
				}

				hasValue = true;
			}
		}
	}
	return hasValue;
}
```

**Comment by BalusC** [comment]
This is not the correct usage of `noSelectionOption`. This does not mean that it's an unselectable/default option. This works only in combination with `hideNoSelectionOption="true"` on the parent `UISelect` component, if supported by that component. The `<p:selectOneMenu>` doesn't support it. The `<h:selectOneMenu>` supports it.

```
<h:selectOneMenu hideNoSelectionOption="true">
    ...
    <f:selectItem noSelectionOption="true" ... />
    ....
</h:selectOneMenu>
```

When *another* option is selected during page load, then the one with `noSelectionOption` will behave as `rendered="false"`, i.e. it will not at all be rendered.

You should actually be using `itemValue="#{null}"` instead.

```
 <f:selectItem itemValue="#{null}" itemLabel="No Preference"/>
```

See also https://stackoverflow.com/q/11360030/157882
