### ISSUE TITLE
Omnifaces should not exclude packages with components  in beans.xml

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#528]
MyFaces's parameter `org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING` could improve startup time using CDI's annotation scanner but Omnifaces uses exclusion for all packages with JSF annotated classes in beans.xml.

**Comment by Hint10** [comment]
The exclude org.omnifaces.event should also be removed, in this package some NamedEvents exists.

**Comment by BalusC** [comment]
Good point.
