### ISSUE TITLE
Resource Handler & Progressive Web App 

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#532]
It would be nice to automatically create the serviceworker.js file for the progressive web app standard based on the resources found on the login page. 

This Vaadin blog article is useful:
https://vaadin.com/blog/progressive-web-apps-in-java

This is also related to the notification API feature request.
Maybe we need a bean called ManifestModel to hold all the informations
of the PWA ...

**Comment by BalusC** [comment]
I've as first step just added a `WebAppManifestResourceHandler` for 3.6.

**Comment by BalusC** [comment]
I've just added an offline-aware service worker. The `WebAppManifest` got two new protected properties `getCacheableViewIds()` and `getOfflineViewId()` wherein you can optionally specify the "cacheable view IDs" and "offline view ID". See javadoc for detail.

Chrome's Lighthouse tool is satisfied with this.
