### ISSUE TITLE
Quarkus OmniFaces

### ISSUE THREAD

**Issue by rmpestano** [omnifaces/omnifaces#536]
Guys, I have a working Quarkus extension which enables OmniFaces and some of its features: https://github.com/rmpestano/quarkus-omnifaces

To make OmniFaces boot, the extension first registers some omnifaces beans needed on app startup, [see here](https://github.com/rmpestano/quarkus-omnifaces/blob/77892125e562695eae0292e5b63ba07825924567/deployment/src/main/java/io/quarkus/myfaces/deployment/OmniFacesProcessor.java#L28-L32).

Then it registers the view scope as a [quarkus scope here](https://github.com/rmpestano/quarkus-omnifaces/blob/77892125e562695eae0292e5b63ba07825924567/deployment/src/main/java/io/quarkus/myfaces/deployment/OmniFacesProcessor.java#L59).

Also in dev mode (quakus:dev) it disables combined resource handler, [see here](https://github.com/rmpestano/quarkus-omnifaces/blob/77892125e562695eae0292e5b63ba07825924567/deployment/src/main/java/io/quarkus/myfaces/deployment/OmniFacesProcessor.java#L68).

Obviously the extension doesn't support all omnifaces features, I just implemented the ones I use in AdminFaces project ([quarkus-admin-showcase](https://github.com/adminfaces/quarkus-admin-showcase) and [quarkus-admin-starter](https://github.com/adminfaces/quarkus-admin-starter)).

So the question is, would you like to mantain the extension? if so I can donate the repository.

Let me know if you have interest!

Happy new year!

**Comment by melloware** [comment]
Nice work @rmpestano  I think Quarkus might be the future for EE as platform.

**Comment by arjantijms** [comment]
That sounds incredibly cool @rmpestano! I will take a deeper look as soon as I can.

**Comment by melloware** [comment]
Any progress on this?  Would be great if this was a first class citizen of OmniFaces.  My client is seriously considering moving to Quarkus and we heavily rely on OmniFaces.

**Comment by melloware** [comment]
@rmpestano can you review issue https://github.com/omnifaces/omnifaces/issues/556 and PR https://github.com/omnifaces/omnifaces/pull/557

**Comment by rmpestano** [comment]
Hi @melloware, I cannot approve the PR but what I'll do is to update the quarkus-omnifaces extensions to latest quarkus and myfaces and try using your omnifaces branch on top of that. 

I'll come back here as soon I have something, thank you!

**Comment by melloware** [comment]
Thank you!

**Comment by rmpestano** [comment]
Hey guys JFYI, I've moved the extension to [this repo](https://github.com/adminfaces/quarkus-omnifaces), updated to latest MyFaces and released to maven central.

Hopefully a happy new year to you all!

**Comment by BalusC** [comment]
Sorry for the late response, I expected Arjan would take a closer look at it.

> So the question is, would you like to mantain the extension?

I don't have hands-on experience with Quarkus, so I'd rather not for now.

> Any progress on this? Would be great if this was a first class citizen of OmniFaces.

I do agree that it would be great if we can move it into a new repository below OmniFaces umbrella, but I'd rather leave maintenance up to someone else more proficient in Quarkus who we can then add as a new member of the group.

**Comment by rmpestano** [comment]
Hey BalusC, thanks for the reply.

Maybe for now we can leave the extension there and see how much interest from the community it will have and then see if it worth moving it to Omnifaces org.

If you agree then we can close this issue.

**Comment by melloware** [comment]
Can be closed as its been moved to Quarkiverse: https://github.com/quarkiverse/quarkus-omnifaces

**Comment by melloware** [comment]
Official release is now in Maven Central:
```xml
        <dependency>
            <groupId>io.quarkiverse.omnifaces</groupId>
            <artifactId>quarkus-omnifaces</artifactId>
            <version>3.0.0</version>
        </dependency>
```
