### ISSUE TITLE
FullAjaxExceptionHandler uncomplete error page rendering

### ISSUE THREAD

**Issue by mazen-khalil** [omnifaces/omnifaces#539]
Hello, I am suspecting an issue with FullAjaxExceptionHandler error page rendering.

The rendered error page differs when sending Ajax request / Non Ajax request - Missing scripts and style classes - which causes issues displaying the error page.
In my case I use ui:param in the error page to apply style class on body tag, but its not happening in case of Ajax request.

I found different implementations for Ajax Exception handling, but the unique thing with Omnifaces is displaying the error page without page redirection. +1

It seems same issue is happening on the showcases site, page source is different and page style does not match:
http://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler

--> Click on **`throw runtime exception on ajax request`** button and see page source
![image](https://user-images.githubusercontent.com/21160900/72982254-bae0e380-3def-11ea-96c5-459a8973df00.png)

Click on **`throw runtime exception on normal request`** button and see page source
![image](https://user-images.githubusercontent.com/21160900/72982287-ca602c80-3def-11ea-8c1a-b577874a074d.png)

Thank you!

**Comment by mazen-khalil** [comment]
To be more specific, the partial response is correct, but its not getting rendered correctly.

**Comment by melloware** [comment]
I think your issue was the same as mine: https://github.com/omnifaces/omnifaces/issues/495

See the solution provided.

**Comment by BalusC** [comment]
This is JSF Ajax specific not OmniFaces specific. We can do little, sorry! You can find alternatives/workarounds in https://stackoverflow.com/q/43224613/157882
