### ISSUE TITLE
problems downloading omnifaces

### ISSUE THREAD

**Issue by Johanna0630** [omnifaces/omnifaces#542]
When I add the dependency of omnifaces in maven I get the following error message:  **Failed to read artifact descriptor for org.omnifaces:omnifaces:jar:1.8.1: Could not transfer artifact org.omnifaces:omnifaces:pom:1.8.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/omnifaces/omnifaces/1.8.1/omnifaces-1.8.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. -> [Help 1]**.

Similarly when I want to download the omnifaces .jar file directly from the omnifaces website the link does not work.

Maybe the same thing happened to someone? how do I solve it

**Comment by arjantijms** [comment]
Maybe use https instead of http?

**Comment by BalusC** [comment]
Indeed. Also https://central.maven.org has been migrated to a new domain https://repo.maven.apache.org. This indeed caused all download links in homepage to be broken.

Thank you for reporting this!
