### ISSUE TITLE
Warning when deploying to Wildfly 18.0.1 (OpenJDK 11): Illegal reflective access by org.jboss.as.server.deployment.reflect.ClassReflectionIndex

### ISSUE THREAD

**Issue by f-matt** [omnifaces/omnifaces#546]
When deploying a simple webapp to Wildfly 18 (OpenJDK 11), I'm getting the following warnings:

``` 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jboss.as.server.deployment.reflect.ClassReflectionIndex (jar:file:/var/wildfly/modules/system/layers/base/org/jboss/as/server/main/wildfly-server-10.0.3.Final.jar!/) to field java.util.Date.gcal
WARNING: Please consider reporting this to the maintainers of org.jboss.as.server.deployment.reflect.ClassReflectionIndex
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

The only maven dependency is Omnifaces 3.5, removing this dependency also removes the warnings:

```
<!-- OmniFaces -->
<dependency>
  <groupId>org.omnifaces</groupId>
  <artifactId>omnifaces</artifactId>
  <version>3.5</version>
</dependency>`
```

It might be related to [this issue](https://developer.jboss.org/message/990456?et=watches.email.thread#990456) (reported on jboss) and [this issue](https://github.com/TheCoder4eu/BootsFaces-OSP/issues/1089) (reported on bootsfaces). Maybe something with the ["now" managed bean](http://showcase.omnifaces.org/managedbeans/now)?

**Comment by BalusC** [comment]
Reasonable. I've replaced them by CDI producers.
