### ISSUE TITLE
Same Files are being download from a JSF backing bean

### ISSUE THREAD

**Issue by chsreedhar** [omnifaces/omnifaces#552]
#### Below commandButton is inside `<p:dataTable>`'s footer
This commandButton is updated on `rowSelect` & `rowUnselect` events of `<p:ajax>`

    <p:commandButton id="pdfVwBtn" value="View PDF Doc." icon="pi pi-file-pdf "  action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'" ajax="false"  >
    <f:param name="id" value="#{sid}" />
    <f:param name="type" value="#{type}" />
    </p:commandButton>

#### CDI Bean 
    public void viewPDF() throws IOException {
	        String fileName = Faces.getRequestParameter("id");
    	String fileType = Faces.getRequestParameter("type");
    	File pdffile = new File(getFilePath(), fileName);
    	Faces.sendFile(pdffile, false);
	}

### Issue:
On first time `rowSelect` event, able to dowonload the required file and this same file is being downloaded even different `rowSelect` of `<p:dataTable>` selected.

### Environment
TomEE 7.1.2 with JSF 2.2.20
PrimeFaces 8.0
OmniFaces 2.7.4

**Comment by BalusC** [comment]
Most probably these are agressively cached. Try installing the http://showcase.omnifaces.org/filters/CacheControlFilter as per the `noCache` example. Let me know if that works out.

**Comment by chsreedhar** [comment]
Throws `error-page 404` in new window

**Comment by BalusC** [comment]
Apparently the file is not found. Debug the `fileName`.

**Comment by chsreedhar** [comment]
Yes you are right, `error-page 404` was because of file path issue. Sorry.

#### `noCache` filter added as below to `web.xml`
```
<filter>
    <filter-name>noCache</filter-name>
    <filter-class>org.omnifaces.filter.CacheControlFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>noCache</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
```
#### View
```
<h:form>
   <p:commandButton value="View HE10107" action="#{pdfView.viewPDF}" ajax="false" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10107R2.pdf" />
      <f:param name="type" value="PRS" />
   </p:commandButton>
   <p:commandButton value="View HE10119" action="#{pdfView.viewPDF}" ajax="false" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10119R1.pdf" />
      <f:param name="type" value="PRS" />
   </p:commandButton>
   <h:commandButton value="View HE10107" action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10107R2.pdf" />
      <f:param name="type" value="PRS" />
   </h:commandButton>
   <h:commandButton value="View HE10119" action="#{pdfView.viewPDF}" onclick="this.form.target='_blank'">
      <f:param name="id" value="BP-HE10119R1.pdf" />
      <f:param name="type" value="PRS" />
   </h:commandButton>
</h:form>
```
`<h:commandButton>`s are working as expected. But incase of `<p:commandButton>` problem repeats.

**Comment by BalusC** [comment]
Ok, not an OmniFaces issue then.
