### ISSUE TITLE
Tree component not loading on showcase

### ISSUE THREAD

**Issue by chaseven** [omnifaces/omnifaces#554]
Hi guys, just came across this when I was trying to see some example of the tree component (not sure if this should be posted here but I don't have another way to reach you.

http://showcase.omnifaces.org/components/tree

Error

    Date/time: 2020-05-22 02:32:20
    User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
    User IP: 34.99.4.246
    Request URI: /components/tree
    Ajax request: No
    Status code: 500
    Exception type: class javax.servlet.ServletException
    Exception message: java.lang.StackOverflowError
    Stack trace: 

Got the same error on: Firefox/ Chrome/ IE

**Comment by BalusC** [comment]
Fixed and 3.6.1 has been released. Thanks for reporting.
