### ISSUE TITLE
Quarkus web.xml location

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#556]
It looks like some Quarkus apps use /META-INF/web.xml a location for web.xml.

See:  https://github.com/quarkusio/quarkus/issues/3457

So I think this location should be added to web.xml parser similar to PrimeFaces: https://github.com/primefaces/primefaces/issues/5968

**Comment by BalusC** [comment]
I'm confused. This isn't specified in servlet spec. The servlet spec only specifies META-INF/web-fragment.xml.

I've never used Quarkus, but is it trying to deviate from servlet spec or?

**Comment by melloware** [comment]
I believe it is because Quarkus can be packaged as a single runnable JAR with Undertow running as the embedded servlet engine you can put configuration resources in different places.   So its not a WAR file its a runnable JAR similar to Spring Boot.

See the Undertow Quarkus configuration doc: https://quarkus.io/guides/http-reference#web-xml

_7.3. web.xml
If you are using a web.xml file as your configuration file, you can place it in the src/main/resources/META-INF directory._
