### ISSUE TITLE
Make Servlets#prepareRedirectURL public

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#563]
I was adding `public void openInNewWindow(final String url)` to a project and I had hoped I could use `Servlets#prepareRedirectURL(...)`.

**Comment by BalusC** [comment]
Makes sense but why is this issue closed?

**Comment by jepsar** [comment]
After some thinking I decided to remove `openInNewWindow` (which send a JS statement to open a new window) from my backend. I don't like opening new windows... I'll rework my UI to solve that. Then I couldn't think of other uses for the `prepareRedirectURL` method. But, if you think it might help others, please do make it public.
