### ISSUE TITLE
o:validateBean not respecting javax.faces.validator.BeanValidator.MESSAGE

### ISSUE THREAD

**Issue by blutorange** [omnifaces/omnifaces#564]
I have `javax.faces.validator.BeanValidator.MESSAGE` set to `{1}: {0}` so that the label is added before the error message. When I use `<o:validateBean showMessageFor="@violating" />`, it adds the error messages to the correct components, but without the label.

The `javax.faces.validator.BeanValidator` and also the  new [`WholeBeanValidator`](https://github.com/eclipse-ee4j/mojarra/blob/master/impl/src/main/java/com/sun/faces/ext/component/WholeBeanValidator.java#L115) use `javax.faces.validator.BeanValidator.MESSAGE` with the constraint violations message and the component label to create the final error message.

Looking at the source code of omnifaces ( [Platform#114](https://github.com/omnifaces/omnifaces/blob/1d2bd4a401ee6f39bfae002fd80c77043054696b/src/main/java/org/omnifaces/util/Platform.java#L114), [Platform#134](https://github.com/omnifaces/omnifaces/blob/1d2bd4a401ee6f39bfae002fd80c77043054696b/src/main/java/org/omnifaces/util/Platform.java#L135), [ValidateBean#416](https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L416), [ValidateBean#495](https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L495) ) it seems `o:validateBean` does not perform that step.

So I guess I have two question: Am I missing something and is this supposed to work? If not, is there any chance the behavior could be changed to respect `javax.faces.validator.BeanValidator.MESSAGE` ?

**Comment by BalusC** [comment]
Right, an oversight! Fixed for 3.8. Also added to ValidateBeanIT.
