### ISSUE TITLE
String function dataURL using base64 encoding

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#569]
Feature request:
I have an application where I send HTML emails. I want to show a preview which should not be affected by application's style sheet, so I want to add an iframe with a data URI.

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs

**Comment by jepsar** [comment]
Probably just having a EL base64 encode will be fine

**Comment by BalusC** [comment]
I've added `of:encodeBase64()` :+1:
