### ISSUE TITLE
Add onerror to <o:socket> - Fix for Omnifaces 2

### ISSUE THREAD

**Issue by ravihariharan** [omnifaces/omnifaces#570]
Hi @BalusC 

Can we have the feature for https://github.com/omnifaces/omnifaces/issues/512 in OmniFaces 2.x (for JSF 2.2 application) ?

Thanks
Ravi

**Comment by BalusC** [comment]
Technically speaking it was a new feature and not a fix and therefore it was not added to 2.x.

I can add it but it'll remain undocumented.

**Comment by ravihariharan** [comment]
Thanks @BalusC
