### ISSUE TITLE
omnifaces + myfaces-next on quarkus: @FacesConverter(managed=false) causes problem with @ResourceDependencies

### ISSUE THREAD

**Issue by 38leinaD** [omnifaces/omnifaces#572]
I still might not have a deep enough understanding of the issue, so please apologize if you don't think this should be reported as an issue here. This is a very special combination. Anyway, maybe this conversation can help me understand the problem better and thus also my options.
I am using myfaces (latest myfaces-next-M3 build) + omnifaces on Quarkus.
I have a @FacesConverter with @ResourceDependencies: https://github.com/38leinaD/jsf-reproducer/blob/master/src/main/java/org/acme/EncryptConverter.java; (managed is not set; so, implicitly set to "false").

Reproduce:
- git clone https://github.com/38leinaD/jsf-reproducer
-  mvn quarkus:dev
- Open localhost:8080/index.xhtml; it should print "crypt library embeeded!!!"  to the browser console (the crypt.js @ResourceDependency is added)
- Refresh the browser

Actual:
- "crypt library embeeded!!!" is not printed because the crypt.js is not embeeded into the HTML this time

Expected
- ""crypt library embeeded!!!" should be printed again / embeeded into the HTML.

Analysis:
I have traced it back to this:
https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/application/OmniApplication.java#L82

The createConverter method intercepts and caches the converter instance; thus, only calling super.createConverter (https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/application/OmniApplication.java#L90) the first time the page is loaded. According to a myfaces contributor, this is problematic in a JSF 2.3 environment because JS resources from the@ResourceDependencies will only be analysis by myfaces when the super.createConverter method is called.

I can set managed=true and it seems to solve the issue; but, ideally, I would like to keep the managed=false on the @FacesConverter because the converter is in a lib that is compiled against JavaEE 7 apis; so, it does not know about the "managed" attribute. Also, i would like to understand the problem better.

Can you help me understand the issue better. How come I cannot use managed=false? I was encouraged by a myfaces committer to report this here but to be honest, I am still trying to understand if this is an issue that is specific to the combination with Quarkus or also applies to Java EE 8 / JSF 2.3 appservers; and if it does not apply there: Why?

Below, please find the full conversation with Thomas from the myfaces team in case I might have misunderstood some of his statements:
> Thomas Andraschko: i think you need to talk with omnifaces guys why they cache it - thats actually up to the JSF impl to create CDI managed converters
> Thomas Andraschko: IMO it should not be active when JSF 2.3 is used: https://github.com/omnifaces/omnifaces/blob/4.x/src/main/java/org/omnifaces/cdi/converter/ConverterManager.java#L59
> Thomas Andraschko: in general managed=true enabled injection, so omnifaces doesnt need that code anymore
> Daniel Platz: @Thomas Andraschko Well, we compile against JSF 2.2, so don't have the managed attribute. So, effectively, managed is false for us.
> Also seeing this:
> 
> JavaDoc: JSF 2.3 compatibility
>  OmniFaces 3.0 continued to work fine with regard to managed converters which are initially developed for JSF 2.2.
>  However, JSF 2.3 introduced two new features for converters: parameterized converters and managed converters.
>  When the converter is parameterized as in <code>implements Converter&lt;T&gt;</code>, then you need to use
>  at least OmniFaces 3.1 wherein the incompatibility was fixed. When the converter is managed with the new JSF 2.3
>  <code>managed=true</code> attribute set on the {@link FacesConverter} annotation, then the converter won't be
>  managed by OmniFaces and will continue to work fine for JSF. But the &lt;o:converter&gt; tag won't be able to
>  set attributes on it.
>
> I think omnifaces is doing nothing wrong: just staying backwards compatible. If managed=true, they do not manage the converter and it would work.
> (actually, i dont see where in the code they make the distinction; i only read this from the comment. did you find it?)
> think in the end the problem is with our combination of compiling against JSF 2.2, running on a myfaces implementation that is JSF >=2.3 and omnifaces.
> Would be interested in your final opinion before filing an issue just to get a clear understanding of the situation.
> 
> Daniel Platz: @Thomas Andraschko Has there been some change in myfaces how the converts and annotation processing is handled with myfaces 2.3 next? I am wondering and just like to understand. Because the same version of omnifaces plays nice on websphere liberty, which comes with myfaces 2.2 to my knowledge...
> 
> Thomas Andraschko: No, that doesnt matter
> createConverter triggers that logic, also in older Versions
> And If omnifaces prevents this, thats a bug on their side
> Omnifaces wraps createConverter to support injection, which is only required in pre JSF2.3
> To it duplicates logic for 2.3 runtime and introduces a Cache, which introduces the Bug, that ResourceDepedency isnt handlew

**Comment by 38leinaD** [comment]
Additional comment: I did not use the omnifaces quarkus extension by @rmpestano, but I assume it should not make a difference in regards to my issue in JVM mode in my setup; just directly added the library as a dependency.
If someone sees this differently, I can give it a try as well.

**Comment by rmpestano** [comment]
Hi @38leinaD, I don't think quarkus-omnifaces extension will make a difference because it only registers OmniFaces ViewScope and also a few beans needed to boot OmniFaces. 
About your issue maybe we can do something regarding this on the extension, maybe we can veto some OmniFaces beans which are causing the issue and add other/alternative implementation which may solve the issue, just thinking out loud.

**Comment by 38leinaD** [comment]
@rmpestano yes, sounds like an idea.
But to be honest, i am not at the point yet that i have fully understood the problem. I still would like to test it on a Websphere Liberty with Java EE 8 (containing myfaces 2.3). Maybe that helps me understand why the problem is happening in quarkus and if it is also happening there.
If someone has a more deeper understanding and could shed some light on it, that would be helpful.
It might be that the CDI implementation in Quarkus handles the converts differently.
In Java EE 8 / JSF 2.3: Is a @FacesConverter(managed=false) also a CDI bean? I assume not...? Because, for Quarkus, by default, @FacesConverter might be seen as a bean-defining annotation...

**Comment by tandraschko** [comment]
the problem is quite simple:
OmniFaces overwrites and intercepts the #createConverter calls and caches the result. As MyFaces #createConverter handles the ResourceDependencies, your ResourceDependency isnt always processed.
I dont know when exactly OmniFaces caches the result - but if it happens, @ResourceDependencies are ignored.

**Comment by tandraschko** [comment]
It may be possible that something related to quarkus makes the OmniFaces cache always active (maybe all FacesConverters are always beans?) but the root problem is clear: the result of createConverter shouldnt be cached AND JSF 2.3 already has injection for converters/validators, so why there is no JSF2.3 only version of OmniFaces which removes the injection stuff OmniFaces?

**Comment by 38leinaD** [comment]
@tandraschko for the bug title: you mean "The bugtitle could also be: OmniFaces prevents @ResourceDepdenceny to work with @FacesConverter(managed=FALSE)", right?
Because with managed=true all works fine.

**Comment by tandraschko** [comment]
not sure, i dindt check the code in detail. Depends on when converterManager returns null or not.

**Comment by 38leinaD** [comment]
I did debug it. That is whyi am saying the title should be "OmniFaces prevents @ResourceDepdenceny to work with @FacesConverter(managed=false)"

managed=false
-> converterManager.createConverter returns null the first time; for subsequent pageloads, it returns a non-null value.

managed=true
 -> converterManager.createConverter returns null always

**Comment by tandraschko** [comment]
yep, ok. i see

**Comment by BalusC** [comment]
OmniFaces does not cache concrete `javax.faces.convert.Converter` instances. It only caches the `javax.enterprise.inject.spi.Bean<Converter>` instances. This is perfectly fine.

I'll have to investigate what exactly is happening here.

**Comment by BalusC** [comment]
Okay, it appears that resource dependencies are applied during creating the converter rather than during calling its getAsObject().

**Comment by BalusC** [comment]
I've locally fixed it but the integration tests in TomEE 8.0.4 (MyFaces 2.3.6) throw NPE on FacesConverterCDIWrapper#getAsString() because its delegate unexpectedly returned null. I'll have to analyze that.

**Comment by BalusC** [comment]
Okay, everything is fixed. The IT fail on TomEE was caused because it was a `Converter<String>` instead of `Converter<Object>`. As this wasn't an OmniFaces-specific concern, I've adjusted the IT nonetheless.

The fix is available in OmniFaces 3.8-SNAPSHOT.

**Comment by 38leinaD** [comment]
Thanks for fixing this so quickly @BalusC 
I have one further question: Do you think a backport to Omnifaces 2 would be possible/easy?
Let me explain: We are currently migrating a rather large JSF application to Quarkus and are currently still compiling against Java EE 7 apis because we still want to run on Java EE 7 appservers for some time. Until we can lift this restriction, we still compile against JSF 2.2 and bundle with omnifaces 2.7.6.
Due to this, it would be best if we can use the same omnifaces version on all platforms.
I know that this is a setup where it could be argued to use omnifaces 3 because Quarkus is using myfaces with JSF 2.3, but I would like to get your opinion.
The alternative is to compile against omnifaces 2.7.6 but on quarkus actually run wit omnifaces 3. Do you see any problems in this? 

Thanks,
Daniel

**Comment by melloware** [comment]
@38leinaD is that even possible seeing as Quarkus relies on MyFaces NEXT which is already JSF 2.3 EE8?  I assumed you would have to use OmiFaces 3 when using Quarkus but @rmpestano knows better than I do.

**Comment by 38leinaD** [comment]
@melloware Well, on the surface it works except for what i reported on this issue.
Note though, that I am currently not using the ominifaces quarkus extension but just the plain omnifaces dependency.
