### ISSUE TITLE
ValidateBean throws NullPointerException when validating Beans with properties of type java.util.Calendar

### ISSUE THREAD

**Issue by stefanpr** [omnifaces/omnifaces#577]
This occurs when ValidateBean reads all nested properties before creating a copy of the specified Bean for validation (`method="validateCopy"`).
In the case of Calendar this fails for the nested property `actualMinimum` (and possibly others). The Exception is thrown in `org.omnifaces.util.Reflection.getBeanProperty(Object, PropertyDescriptor)` since no read method for the nested property can be inferred. I assume this is due to the mandatory parameter of the read method: `java.util.Calendar.getActualMinimum(int)`.

An easy solution would be to exclude `java.util.Calendar` from the property types needed for recursion in `org.omnifaces.util.Reflection.isNeedsFurtherRecursion(Class<?>)` like `java.util.Date` and `java.time.temporal.Temporal`.

**Comment by BalusC** [comment]
Thank you for improving OmniFaces!
