### ISSUE TITLE
Faces/FacesLocal sendFile : add Path support and customFileName

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#580]
Hi, I think there could be some useful additions to Faces/FacesLocal sendFile methods:

- add support for `java.nio.file.Path`

- let the user provide a custom file name. This would be especially useful when sending files created by [File.createTempFile](https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createTempFile-java.lang.String-java.lang.String-) which usually have a long random number in the name

**Comment by BalusC** [comment]
> add support for java.nio.file.Path

Makes sense.

> let the user provide a custom file name.

Gotcha.

**Comment by BalusC** [comment]
It'll come in 3.9.
