### ISSUE TITLE
Tree: Support PreValidateEvent and PostValidateEvent

### ISSUE THREAD

**Issue by fanste** [omnifaces/omnifaces#582]
OmniFaces: 2.7.8

I implemented a validator for `o:tree` based on the code of `o:validateUniqueColumn`. That validator should be a direct children of the `o:tree` which is currently not possible, because `TreeFamily#processValidators` does not fire the events `PreValidationEvent` and `PostValidationEvent`.

Would it be possible to add those events?

Currently I moved my validator to `o:treeNode` but then the validator executes multiple times (once per level, as the treenode is reused).

**Comment by BalusC** [comment]
Makes sense.

**Comment by BalusC** [comment]
Can you test it with today's latest 2.7.9-SNAPSHOT and let me know if it works for you?

**Comment by fanste** [comment]
Thanks for the implementation. But sadly it is not working. I have commented your changes where I think the mistake lies.

**Comment by BalusC** [comment]
Probably I misunderstood how you implemented the validator. Can you post a minimal example of it?

**Comment by fanste** [comment]
You understood it correctly. But you used a anonymous class as the parameter of your `process` method. Inside that class you invoke `publishEvent` with `this` as the third parameter, which references the anonymous class. If I understood it correctly, the third parameter of `publishEvent` should be the component instance which should receive the event - which is `Tree.this` instead of `this`.

I've seen that it is possible to overwrite components (component types) with own implementations. I did this with the following code for the `Tree` and it is working:
```java
public class TreeWithValidationEvents extends Tree {

	@Override
	public void processValidators(FacesContext context) {
	    Application app = context.getApplication();
	    app.publishEvent(context, PreValidateEvent.class, this);
            super.processValidators(context);
	    app.publishEvent(context, PostValidateEvent.class, this);
	}
}
```

**Comment by BalusC** [comment]
Right. Fixed now.
