### ISSUE TITLE
Websocket tag throws JS error after ajax refresh

### ISSUE THREAD

**Issue by luisnegrete-vungle** [omnifaces/omnifaces#583]
I'm getting a JavaScript exception after an `o:socket` tag is rendered via an ajax refresh. 

`<h:form id="mainForm">
                <o:socket id="testSocket" channel="testSocketChannel" scope="view">
<f:ajax event="updateEvent"/>
</o:socket>
                <h:commandButton id="refreshButton" styleClass="hidden">
                    <f:ajax render="@form"/>
                </h:commandButton>
            </h:form>`

After performing a click event on the refreshButton, the websocket in the page seems to break and the following JavaScript exception is performed when a new message is tried to be sent to the websocket in the page:

`jsf.js?ln=javax.faces&stage=Development:2484 Uncaught TypeError: Cannot read property 'name' of null
    at Object.request (jsf.js?ln=javax.faces&stage=Development:2484)
    at Object.ab (jsf.js?ln=javax.faces&stage=Development:3737)
    at Array.OmniFaces.Push.init.updateEvent (assetManager.xhtml:196)
    at WebSocket.c.readyState.c.onmessage (omnifaces.js?ln=omnifaces&v=3.8:12)`

The issue can be reproduced using Omnifaces version 3.8

**Comment by Rapster** [comment]
Same problem here, either it's because o:socket does not generate HTML or something has changed recently in `#request` function lately. Problem reproduced with OmniFaces 3.8.1 & Mojarra 2.3.9

**Comment by Rapster** [comment]
Same problem. Turns out, whether I'm using `o:socket` or `f:websocket` I end up with the same issue (OmniFaces 3.8.1 or /and Mojarra 2.3.9). To make it work, I used the alternative which is to combine socket and commandScript

**Comment by BalusC** [comment]
I'll analyze, but why are you ajax-refreshing a web socket in first place? Seems unnecessary.

**Comment by BalusC** [comment]
Hmm, I can't reproduce it with OmniFaces 3.8.1 on a minimal project deployed to WildFly 21.0.0 (Mojarra 2.3.14.SP01).
- `FacesServlet` mapped on URL pattern of `*.xhtml`
- `org.omnifaces.SOCKET_ENDPOINT_ENABLED=true` 
-  `javax.faces.PROJECT_STAGE=Development`
- empty `beans.xml`
- minimal Facelet with exactly the `<h:form id="mainForm">` which you have posted, no beans, no other things

Is there more into the actual use case?

**Comment by BalusC** [comment]
Nevermind, it happens when pushing the exact message `updateEvent` back to the socket after it's been ajax-refreshed, I've indeed reproduced that. Happens already from OmniFaces 2.6 on (the first version this feature was introduced). I'll analyze.

**Comment by BalusC** [comment]
Technical problem was that JSF couldn't find an element with the `id` of the `<o:socket>` in the document. This was because it was rendered as `id` of a `<script>` element. However, by default JSF strips all `<script>` elements from Ajax response and evaluates them individually without putting them in the DOM.

The solution was to let the `<o:socket>` render its `id` as a `<input type="hidden">`. The fix will be available in 2.7.9 / 3.9.

Thank you for reporting and improving OmniFaces!

**Comment by Rapster** [comment]
Thanks a lot BalusC! Maybe I should report this very same issue on mojarra?
