### ISSUE TITLE
Sitemap.xml components

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#584]
For SEO a sitemap in TXT or XML format is a good tool to improve and speed up google bot indexing time and we have following options right now:

- https://www.sitemaps.org/protocol.html
- https://support.google.com/webmasters/answer/183668

**Option generator**

Use a sitemap generator, that traverses the link hierarchy of the website and upload this with disadvantages to be refreshed when there are changes and no priority for page crawling. This is also overhead for small to medium pages.

Could be done using a `@Schedule` bean that regenerates and reads attributes `lastmod`, `changefreq` and `priority` from some hidden meta fields in the html head of each URL and saves the file to the server.

**Option JSF Java**

My first idea is creating this sitemap programmaticaly using a JSF bean and getting the bookmarkable URLs. This is also not optimal since all XHTML markup links need to regenerated in java code. With `outcome`, `params` and `param converters`. I always try to keep view data out of java.

**Idea**

Instead of outputting xhtml we could output xml and use a new link component to generate those url for the sitemap. This way the links are only duplicate within markup, what i can live with.

_File: sitemap.xml_

``` 
<?xml version="1.0" encoding="UTF-8"?>
<o:sitemapUrlSet var="varPoduct" value="#{sitemapBean.products}">
   <o:sitemapUrl outome="/sites/index.xhtml" absolute="true"
       lastMod="#{product.lastUpdated}" changefreq="weekly" priority="1.0">
      <o:param name="product" value="#{varProduct}" converter="productConverter"/>
   </o:sitemapUrl>
</o:urlSet>
``` 

Instead of `o:sitemapUrl` the existing `o:url` could change its render output if inside `o:sitemapUrlSet`.

_This renders output_

``` 
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
   <url>
      <loc>https://www.example.com/Product/1243/Coca-Cola</loc>
      <lastmod>2020-01-01</lastmod>
      <changefreq>weekly</changefreq>
      <priority>1.0</priority>
   </url>
</urlset> 
``` 

Since these are technical components it suits OmniFaces i think.

**Comment by BalusC** [comment]
This is indeed a repeatable problem.

In our recent projects we've just used plain JSP for this, but this can indeed be solved/simplified with JSF.

**Comment by djmj** [comment]
If you are interested, is it possible to get a quote/pay for this?

**Comment by BalusC** [comment]
Send an email to balusc@gmail.com to discuss.

**Comment by BalusC** [comment]
Summarized, a `ViewResourceHandler` has been added which reads out `org.omnifaces.VIEW_RESOURCE_HANDLER_URIS` context param as a commaseparated string of context-relative paths to non-XHTML files which should be interpreted as JSF view resources, such as `/sitemap.xml, /robots.txt` and ultimately allows you to use JSF components and EL expressions in these files.

A new component `<o:sitemapUrl>` has been added which renders a `<url><loc/><lastmod/><changefreq/><priority/></url>` entry for `<urlset>` of sitemap.xml.

**Comment by melloware** [comment]
Excellent work @BalusC !!

**Comment by djmj** [comment]
@BalusC  Great thanks for your work on this, your help for my solution and quick responses.
