### ISSUE TITLE
[Feature request] Create share private URL

### ISSUE THREAD

**Issue by karlkilden** [omnifaces/omnifaces#59]
Hello,

Many, many public sites offers you a way to share your content with anyone by generating a direct link. The url will not be indexed by search engines and is impossible to guess for mortal men and women.

Dropbox, Google docs, Skydrive are notable examples.

I really like this flow control because it makes it easy to envolve people who lack a proper account. 

`<o:shareLink value="Share private" />` : All view params included, outcome will be current page

`<o:shareLink value="Share private" params="daterange id locale"  outcome="/privateurl"/>` :The specified view params will be included, outcome will be specified servlet in this case.

the resulting link:

mysite/privateurl?l=kasdkka-993a93akask-da

Then some clever way to decode it again. Also maybe some way to differentiate between params that can be in plain text. I was thinking a sevlet that decoded and then redirected but some viewAction smartness might be awesome as well.

The usual converter / validator stuff might be useful to have in combination. maybe f:param children instead of the render syntax

**Comment by BalusC** [comment]
Idea is sound, but I feel it's beyond scope of OmniFaces as it doesn't solve a general JSF API problem.

Theoretical solution would be:

```
<h:link outcome="some">
    <f:param name="share.key" value="#{util:collectViewParamsAndEncrypt(view)}" />
</h:link>
```

And then a servlet filter with a `HttpServletRequestWrapper` which creates a (internally) modifiable request parameter map. And then in view handler during restore view, lookup that parameter and decrypt the individual params into that modifiable request parameter map.

Both the parameter name and encryption key must be configurable via e.g. context param.
