### ISSUE TITLE
ViewExpiredExceptionHandlerFactory functionality loss

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#592]
The following functionality is not available vs. the original version:
`org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` context paremeter in `web.xml` doesn't work with PrimeFaces exception handler, or without `FullAjaxExceptionHandlerFactory` handler

**Comment by BalusC** [comment]
Are you referring to the loss of `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` functionality in `FacesExceptionFilter` once the `ViewExpiredExceptionHandler` is activated?

**Comment by lprimak** [comment]
I don't use `FacesExceptionFilter` in my applications. I supposed I could. Didn't even know it handled the same thing.
Obviously it needs testing.

**Comment by BalusC** [comment]
Sorry, I'm really confused.

Are you saying that you expected that `ViewExpiredExceptionHandler` should also log other exceptions?

**Comment by lprimak** [comment]
No. when using `ViewExpiredExceptionHandler` alone, or with PrimeFaces,
`org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` stops working.

I am not using `FacesExceptionFilter` *currently* in my applications, so perhaps starting to use it  *could* resolve this, 
but it needs testing

**Comment by lprimak** [comment]
Oh, I see where you may be confused:
is `FacesExceptionFilter` activated automatically? via `@WebFilter` perhaps?
Perhaps there is an issue in my test then...

**Comment by lprimak** [comment]
Never mind, I just looked at the source code and it isn't, unless I am missing something,
it needs to be manually added

**Comment by lprimak** [comment]
Re-reading this from the docs:

> Noted should be that this filter won't run on exceptions thrown during ajax requests. To handle them using web.xml configured error pages, use FullAjaxExceptionHandler.

Should I even bother testing `FacesExceptionFilter` or do you think exception filtering won't work for Ajax requests w/o `FullAjaxExceptionHandlerFactory`?

**Comment by BalusC** [comment]
Sorry, I'm really confused. You said:

> No. when using ViewExpiredExceptionHandler alone, or with PrimeFaces,
`org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` stops working.

Where exactly are you using it?

Are you using it in `FullAjaxExceptionHandler` or in `FacesExceptionHandler`? These are the only two places in OmniFaces where exceptions are logged and where the API documentation says that the param is being consulted to ignore specific exception types in logging.

In your first comment you're implying that you're not using `FullAjaxExceptionHandler`, so I inferred that you was using `FacesExceptionFilter`. But in a later comment you said that you also don't use it. So I'm really confused.


Differently put, you're implying that when you remove `ViewExpiredExceptionHandler`, then the `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` starts working again. But who exactly is using it?

**Comment by lprimak** [comment]
Please try to look at it from the application developer's perspective.

Here are the requirements:
- Use the new `ViewExpiredExceptionHandler` to avoid all propagation of `ViewExpiredException` to users and logs
- Use PrimeFaces Ajax exception handler (https://www.primefaces.org/showcase/ui/misc/exceptionHandler.xhtml) which precludes the usage of `FullAjaxExceptionHandler`
- remove certain exceptions from the log, via `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING`
- Have this functionality in Ajax requests (where `FacesExceptionFilter` does not apply)

To accomplish these requirements, *my original* implementation of `ViewExpiredExceptionHandler` checks for absence of `FullAjaxExceptionHandler`. If it's absent, it calls `FullAjaxExceptionHandler.getExceptionTypesToIgnoreInLogging(Faces.getServletContext());` directly and processes
these 'ignored' exception by itself.

In the new OmniFaces implementation of `ViewExpiredExceptionHandler` this functionality is absent, so there is *no way* to use `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` and have it function as documented with the new implementation of `ViewExpiredExceptionHandler`

Do you understand this now or are you still confused?

Thanks for all your help and patience.

**Comment by lprimak** [comment]
No. when using ViewExpiredExceptionHandler alone, or with PrimeFaces,
org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING stops working.
> Where exactly are you using it?

That's the whole point. There is no longer a place for me to use it correctly, it's missing, hence the title of the issue :)

**Comment by BalusC** [comment]
But the `ViewExpiredExcepitonHandler` doesn't at all log the other exceptions?

So far the `FullAjaxExceptionHandler` and `FacesExceptionHandler` are the only ones which logs exceptions. The first one does that for execptions on ajax requests and the second one for exceptions on non-ajax requests.

**Comment by lprimak** [comment]
My original implementation did, because there is no other way to do this for Ajax without `FullAjaxExceptionHandler` which I can't use because it's mutually exclusive with PrimeFaces one which I want to use.

The issue is that the new implementation is missing that part of my implementation of `ViewExpiredExcepitonHandler`

**Comment by lprimak** [comment]
This code is missing:
```
 // now add ignored logging instances
        if (!isIgnoreLoggingAlreadyHandled(wrapped, FullAjaxExceptionHandlerFactory.class)) {
            for (Class<? extends Throwable> cls : getTypesToIgnore()) {
                addToStreamBuilderIfNew(handlerStreamBuilder, existingClasses, cls, ignored);
            }
        }
```
```
    static boolean isIgnoreLoggingAlreadyHandled(ExceptionHandlerFactory wrapped, Class<?> target) {
        boolean matched = false;
        while (wrapped != null && !matched) {
            matched = target.isInstance(wrapped);
            wrapped = wrapped.getWrapped();
        }
        return matched;
    }
```
```
  static Class<? extends Throwable>[] getTypesToIgnore() {
        return FullAjaxExceptionHandler.getExceptionTypesToIgnoreInLogging(Faces.getServletContext());
    }
```
```
  private static void addToStreamBuilderIfNew(
            Builder<Map.Entry<Class<?>, Function<ExceptionQueuedEvent, Boolean>>> handlerStreamBuilder,
            Set<Class<?>> existing, Class<?> cls, Function<ExceptionQueuedEvent, Boolean> fn) {
        if (!existing.contains(cls)) {
            existing.add(cls);
            handlerStreamBuilder.add(new AbstractMap.SimpleEntry<>(cls, fn));
        }
    }
```

**Comment by BalusC** [comment]
Why exactly would this be the responsibility of something called "ViewExpiredExceptionHandler"?

It looks more and more like that you just need a secondary exception handler whose sole task is to completely suppress a specific set of exceptions configureable as a context parameter for which you initially just reused the existing `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` context parameter of OmniFaces (originally intended for a different purpose) instead of coming up with your own.

**Comment by lprimak** [comment]
I suppose you can think of it that way... I was hoping not to have to introduce three exception handlers.

Basically, what you are suggesting is this:
for OmniFaces exception handling:
- ViewExpiredExceptionHandler
- FullAjaxExceptionHandler

for PrimeFaces exception handling:
- ViewExpiredExceptionHandler
- PrimeFaces exception handler
- Logging suppression exception handler

My only issue with this is the number of exception handlers necessary.
I would prefer that there would only be one for OmniFaces use case, and two for PrimeFaces,
instead of two or three.

**Comment by lprimak** [comment]
If you feel that the above is not enough of a justification, feel free to close this issue

**Comment by lprimak** [comment]
If the above justification isn't enough to sway you to integrate log suppression into ViewExpiredExceptionHandler, 
another way to resolve this issue would be to create a new `LogingSuppressionHandler` in OmniFaces

**Comment by BalusC** [comment]
I don't agree the tight-coupling, no.

OmniFaces is a public library which is used by hundredthousands of users, not a private library.

Decouple the concerns and make them individually reusable. This makes the API more sane, clear-cut and useful.

> LogingSuppressionHandler 

The exception handler you had in mind has nothing to do with suppressing logging. You're essentially trying to completely suppress the exceptions themselves. Try coming up with a more matching name for such an exception handler.

**Comment by melloware** [comment]
I am also not sure why you are using PrimeFaces and Omnifaces exception handlers? The PrimeFaces one is a stripped down version of the OmniFaces ones?  The OmniFaces ones are more feature complete. 

I would like to hear your use case of using both?

**Comment by lprimak** [comment]
@melloware I don't want to use both, I just want to continue to use the PrimeFaces exception handler, for one reason or another not under my control.

I want to use PF Ajax exception handler and OmniFaces for everything else

**Comment by lprimak** [comment]
@BalusC 
 > LogingSuppressionHandler

 I was trying to make it consistent with the rest of OmniFaces, i.e. `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING` and not introduce new terminology.

> Decouple the concerns and make them individually reusable. This makes the API more sane, clear-cut and useful.
The exception handler you had in mind has nothing to do with suppressing logging. You're essentially trying to completely suppress the exceptions themselves. Try coming up with a more matching name for such an exception handler.

**Comment by BalusC** [comment]
No. Your private exception handler suppresses specific exceptions. That param only suppresses logging of specific exceptions (but the exception itself is still thrown and the user still retrieves HTTP 500 error -as it should).
