### ISSUE TITLE
ExceptionSuppressor - why new / different configuration variable?

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#596]
From the user's perspective, the new configuration variable `org.omnifaces.EXCEPTION_TYPES_TO_SUPPRESS` is causing confusion. Why not just use the existing `org.omnifaces.EXCEPTION_TYPES_TO_IGNORE_IN_LOGGING`?
It makes zero difference from the app developer / user perspective IMHO

**Comment by BalusC** [comment]
The first one declares types to suppress by `ExceptionSuppressor`.

The second one declares types to ignore in logging by `FullAjaxExcepitonHandler` and `FacesExceptionFilter`.

These are not interchangeable. The `ExceptionSuppressor` suppresses the exceptions, but the `FullAjaxExceptionHandler` and `FacesExecptionFilter` don't suppress exceptions, these will show an error page.

Endusers might still want to continue to show an error page for specific exceptions but not log them. For example `ViewExpiredException`. And they'll want to be able to suppress others such as `ClosedByInterruptException`.
