### ISSUE TITLE
o:validateBean: Recursive property collection fails due to bean spec violations in object graph

### ISSUE THREAD

**Issue by iwesg** [omnifaces/omnifaces#598]
Using `o:validateBean` with the `validateCopy` method (the default) triggers recursive property collection, which in turn fails when encountering an object that does not adhere to the beans spec with regards to getters and setters.

In our case, we ran into a NullPointerException in `org.omnifaces.util.Reflection.getBeanProperty(Object, PropertyDescriptor)`, since one of the objects in the object graph declared a setter without a corresponding getter (`propertyDescriptor.getReadMethod()` returned `null`). All of this happens during `org.omnifaces.util.Reflection.getBaseBeanPropertyPaths(Object)`, so before any actual copying or validation is performed.

Other than using `validateActual`, we couldn't find any obvious way to exclude paths from the property collection or to turn off cascading validation altogether. Since we cannot universally guarantee that all objects reachable from validated beans are bean spec compliant (nor that invoking their getters is safe with regards to side-effects), we currently cannot use it as intended.

I'm no expert in bean validation, so maybe I'm missing something obvious, but I think that this needs more fine-grained control, such as maybe only following properties annotated with `javax.validation.Valid`. Alternatively, it could ignore non-compliant beans or provide a way to disable cascading validation.

**Comment by BalusC** [comment]
> since one of the objects in the object graph declared a setter without a corresponding getter (propertyDescriptor.getReadMethod() returned null)

I've just committed an adjustment which filters out them. These should indeed never have been collected in first place.

> Other than using validateActual, we couldn't find any obvious way to exclude paths from the property collection or to turn off cascading validation altogether. Since we cannot universally guarantee that all objects reachable from validated beans are bean spec compliant (nor that invoking their getters is safe with regards to side-effects), we currently cannot use it as intended.

Another way would be to provide the bean validator a real bean and then map it back after submit, or to provide a custom copier whereby you only map the properties of interest.

> I'm no expert in bean validation, so maybe I'm missing something obvious, but I think that this needs more fine-grained control, such as maybe only following properties annotated with javax.validation.Valid. Alternatively, it could ignore non-compliant beans or provide a way to disable cascading validation.

Agreed. I'll look at way to skip properties or to disable cascading.

**Comment by iwesg** [comment]
> I've just committed an adjustment which filters out them. These should indeed never have been collected in first place.

Thank you!

> [...] provide a custom copier whereby you only map the properties of interest.

We actually have one, but we didn't get that far due to the issue above.

> Agreed. I'll look at way to skip properties or to disable cascading.

Thanks a lot, this would be very helpful.

**Comment by BalusC** [comment]
In hindsight, after reading the bean validation spec, it should actually only have followed properties annotated with `@Valid`. So I'll for now go this path.

**Comment by BalusC** [comment]
Done now. The o:validateBean will now only recurse nested properties explicitly annotated with `@Valid`.

**Comment by melloware** [comment]
@BalusC That is correct we use this a lot and it will only follow nested with `@Valid` so this is a good fix.
