### ISSUE TITLE
Not an issue, do you have any resources to make work JSF on G. AppEngine?

### ISSUE THREAD

**Issue by gavelez** [omnifaces/omnifaces#599]
Not an Issue, but couldn't realize how to ask directly this...

**Comment by melloware** [comment]
Seems like there are some issues with GAE and JSF: https://stackoverflow.com/questions/41786164/how-do-i-set-up-a-google-appengine-webapp-with-jsf-2-2-jpa-2-0-and-dependency-i

**Comment by melloware** [comment]
Actually here is a better one: https://stackoverflow.com/questions/60147893/how-to-implement-jsf-2-3-on-google-app-engine-project

https://sites.google.com/a/wildstartech.com/adventures-in-java/Java-Platform-Enterprise-Edition/JavaServer-Faces/javaserver-faces-22/configuring-jsf-22-to-run-on-the-google-app-engine-using-eclipse
