### ISSUE TITLE
Extract ConstraintViolationException

### ISSUE THREAD

**Issue by mzeibig** [omnifaces/omnifaces#602]
In addition to `Exceptions.is(e, ConstraintViolationException.class)` there should be a method to extract an nested exception of a given type.
e.g. `ConstraintViolationException cve = Exceptions.extract(e, ConstraintViolationException.class)`

**Comment by BalusC** [comment]
Use `Exceptions#unwrap()`.

```
ConstraintViolationException cve = Exceptions.unwrap(e, ConstraintViolationException.class);
```

**Comment by mzeibig** [comment]
Thank you. So your documentation is a little bit missleading. 
`Unwrap the nested causes of given exception as long as until it is not an instance of the given types and then return it. If the given exception is already not an instance of the given types, then it will directly be returned. `
For me it reads like 'return the first exception, that is not a ConstraintViolationException'

And for my use case it would be nice to have a method like:
`public static <T extends Throwable> T unwrap(Throwable exception, Class<T> type)`

**Comment by mzeibig** [comment]
It does not work as expected:
`        
    ConstraintViolationException e = new ConstraintViolationException(new HashSet<>());
    EJBException e2 = new EJBException(e);
    ConstraintViolationException unwrap = (ConstraintViolationException) Exceptions.unwrap(e2, 
    ConstraintViolationException.class);
`
results in:
`java.lang.ClassCastException: class javax.ejb.EJBException cannot be cast to class javax.validation.ConstraintViolationException`

**Comment by BalusC** [comment]
Right. I initially misinterpreted it the other way round.
