### ISSUE TITLE
o:url - value URL not rewritten - call encodeResourceURL

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#603]
I tried to use _o:url_ with an `sitemap.xml` file that is registered using _ViewResourceHandler_.

`<o:url var="varLink" value="/sites/foo/sitemap.xml" />Sitemap: #{varLink}`

The URL is not rewritten and i compared the _o:url_ source with _h:outputLink_ and this part seems to be missing in _o:url_ renderer.
`href = context.getExternalContext().encodeResourceURL(href)` explicit states that the URL will be rewritten.

**Comment by BalusC** [comment]
Fixed now.
