### ISSUE TITLE
Feature request: Faces / Servlets   getReferer

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#607]
[HTTP referer](https://en.wikipedia.org/wiki/HTTP_referer)

`public static String getReferer() { return Faces.getRequest().getHeader("referer"); }`

**Comment by BalusC** [comment]
Wondering if I should fix or keep the legendary typo :P

**Comment by pizzi80** [comment]
:D 

I don't remember if it works both with one and two 'r'  (:

thanks a lot

**Comment by BalusC** [comment]
The header name itself is really with one `r`, this typo is already set in stone. 

I guess I'll just use `Faces/Servlets#getReferrer()`, with the typo fixed in method name.
