### ISSUE TITLE
OmniFaces 4.0-M6 omnifaces.util.* package missing

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#610]

**Comment by BalusC** [comment]
There's more missing in that JAR as well :( Looks like Maven build went astray for unclear reason.

**Comment by BalusC** [comment]
I've just re-run the maven deploy with 4.0-M7. It's not in central yet, but the local JAR looks good.

**Comment by BalusC** [comment]
Ah it's there already: https://repo.maven.apache.org/maven2/org/omnifaces/omnifaces/4.0-M7/

**Comment by pizzi80** [comment]
It works! thanks ;)
