### ISSUE TITLE
Versions starting with 3.9 cause some strange ClassCastExceptions during WAR-deployment

### ISSUE THREAD

**Issue by AndrewG10i** [omnifaces/omnifaces#612]
First of all I would like to start with saying what a great library OmniFaces and thank you so much for supporting JSF/JavaEE/JakartaEE-community with a such great stuff! It has already saved us a lot of efforts by providing shortcuts for the things which do not work smooth in plain JSF.

As per the issue: it seems that versions staring with 3.9 (3.9, 3.10, 3.10.1) causing some strange ClassCastExceptions during WAR deployment on the Payara Server Full 5.2020.7
![image](https://user-images.githubusercontent.com/16522951/106985114-cce7b700-67a3-11eb-9313-f15b00258f75.png)

But in case of v3.8 (or 3.8.1) - all work fine (without changing any other piece of code, only the pom.xml version of omnifaces).

Environment:
Windows 10 (same issues were noticed on CentOS Linux as well)
Java: (Zulu 8.50.0.21-CA-win64) (build 1.8.0_272-b17)
NetBeans 12.1
Payara Server Full 5.2020.7

Let me know please in case any other information is required to be provided for better root cause investigation. I am still trying to figure out whether it is related to my environment or not and will update this issue in case of new findings.

Thank you!

**Comment by BalusC** [comment]
Do you have a stack trace?

**Comment by BalusC** [comment]
Hmm, research on similar errors suggest an incompatibility between the Java compiler used to create the (OmniFaces) JAR and the Java runtime used by the target environment. I indeed remember to have upgraded my JDK about around the time before the 3.9 release. It was released 19 December and I have done a full OS reinstall of my development machine at 7 November. I have just picked the latest JDK 1.8 that date (I don't exactly remember which one and I'm not at home atm so I cannot verify, I can do at earliest Sunday).

Have you tried a different JRE/JDK?

**Comment by AndrewG10i** [comment]
Here is stack-trace for v 3.9, 3.10, 3.10.1 (somehow it was not always shown):
```
  Exception while visiting org/omnifaces/validator/RequiredCheckboxValidator.class of size 2760
java.lang.ClassCastException: org.glassfish.hk2.classmodel.reflect.impl.InterfaceModelImpl cannot be cast to org.glassfish.hk2.classmodel.reflect.impl.AnnotationTypeImpl
	at org.glassfish.hk2.classmodel.reflect.impl.ModelClassVisitor.visitAnnotation(ModelClassVisitor.java:183)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:582)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.glassfish.hk2.classmodel.reflect.Parser$5.on(Parser.java:336)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.handleEntry(ReadableArchiveScannerAdapter.java:165)
	at com.sun.enterprise.v3.server.ReadableArchiveScannerAdapter.onSelectedEntries(ReadableArchiveScannerAdapter.java:127)
	at org.glassfish.hk2.classmodel.reflect.Parser.doJob(Parser.java:321)
	at org.glassfish.hk2.classmodel.reflect.Parser.access$300(Parser.java:44)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:280)
	at org.glassfish.hk2.classmodel.reflect.Parser$3.call(Parser.java:269)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
|#]
  Exception while visiting javax.faces.validator.FacesValidator|#]
```

Re trying running on the different JRE/JDK - didn't think about such test, but will do this shortly and provide feedback asap.

**Comment by BalusC** [comment]
The exact exception was reported here: https://github.com/payara/Payara/issues/4952

Looks like it's already fixed and will make into next community version yet to come.

**Comment by AndrewG10i** [comment]
Just tried to deploy WAR containing v3.10.1 on Payara running under Oracle jdk-8u281-windows-x64 - result the same (same exception popped-up).

Yep, thanks for giving the ref to the reported issue in Payara - will wait for the new release and see how it goes there.

**Comment by BalusC** [comment]
Curious. This problem is not happening during integration testing against Payara 5.2020.7. Most recent one: https://travis-ci.org/github/omnifaces/omnifaces/jobs/755991773

```
$ java -Xmx32m -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~16.04-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_252

...

[INFO] Configured Artifact: fish.payara.distributions:payara-web:5.2020.7:zip
[INFO] Unpacking /home/travis/.m2/repository/fish/payara/distributions/payara-web/5.2020.7/payara-web-5.2020.7.zip to /home/travis/build/omnifaces/omnifaces/target with includes "" and excludes ""

...

[INFO] Results:
[INFO] 
[INFO] Tests run: 91, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:2.22.1:verify (default) @ omnifaces ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by BalusC** [comment]
For the record, this is my JDK, which is being used to build the final releases (the one in Travis is only used to build the snapshots):
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

While at it .. can you please try version 3.10.2-SNAPSHOT and see it if works in your Payara? (via OSS own snapshot repo). Then we can exclude the one or other.

**Comment by AndrewG10i** [comment]
Good news: just tried on Payara 5.2021.1 - issue gone! All good, thanks for the great library once again! )
