### ISSUE TITLE
CombinedResourceHandler: Not honoring the h:outputStylesheet media attribute

### ISSUE THREAD

**Issue by klaros-testmanagement** [omnifaces/omnifaces#613]
I converted my Primefaces/JSF project to use the OmniFaces `CombinedResourceHandler`.

Overall this is working great so far with one exception:

One of my `h:outputStylesheet` elements is containing a `media="print"` attribute.

Without using the resource handler this stylesheet is only applied to printer output.
When using the `CombinedResourceHandler` the styleshhet is also applied to the screen output.

I got this working by excluding the resource via `org.omnifaces.COMBINED_RESOURCE_HANDLER_EXCLUDED_RESOURCES`, yet I still wonder if this is a bug worth reporting.

Any thoughts on this?

I am using OmniFaces 3.10.1 with PrimeFaces 8 and Mojarra 2.3.

**Comment by BalusC** [comment]
Makes totally sense to auto-exclude them.

I've previously never stumbled upon this situation because normally CSS `@media` rules are used instead in my projects.
