### ISSUE TITLE
Stylesheets not rendered in FullAjaxExceptionHandler

### ISSUE THREAD

**Issue by chrisselwyn** [omnifaces/omnifaces#630]
I am experiencing a very similar problem that was asked about on StackOverflow in case [https://stackoverflow.com/questions/53400252](https://stackoverflow.com/questions/53400252)

The problem is that h:outputStylesheet components are not getting rendered when rendering a page from FullAjaxExceptionHandler.

I have done a bunch of diagnosis and I think I have found why the problem is happening. The stylesheet renderer (com.sun.faces.renderkit.html_basic.ScriptStyleBaseRenderer) prevents the stylesheet from being reoutput if it has already been output with the lines
```        // Ensure this resource is not rendered more than once per request.
        ResourceHandler resourceHandler = context.getApplication().getResourceHandler();
        if (resourceHandler.isResourceRendered(context, name, library)) {
            return;
        }
```
where isResourceRendered() is implemented in javax.faces.application.ResourceHandler as follows
```
    public boolean isResourceRendered(FacesContext context, String resourceName, String libraryName) {
        String resourceIdentifier = libraryName + ":" + resourceName;
        Set<String> resourceIdentifiers = (Set<String>) context.getAttributes().get(RESOURCE_IDENTIFIER);
        return resourceIdentifiers != null && resourceIdentifiers.contains(resourceIdentifier);
    }
```
The purpose of FullAjaxExceptionHandler, as far as I understand it, is to render a whole brand new page but deliver it as an Ajax response.
The stylesheet was already rendered previously in the page that errored because it is in my site JSF template, but then it doesn't get rendered again in the error page.

I can see that there is already an attempt at clearing information about previously rendered resources in OmniFaces's Hacks class with the code 
```
	public static void removeResourceDependencyState(FacesContext context) {
		// MyFaces remembers processed resource dependencies in a map which it doesn't clear on change of view.
		context.getAttributes().keySet().removeAll(MYFACES_RESOURCE_DEPENDENCY_KEYS);

		// PrimeFaces puts "namelibrary=true" for every processed resource dependency.
		// NOTE: This may possibly conflict with other keys with value=true. So far tested, this is harmless.
		context.getAttributes().values().removeAll(Collections.singleton(true));
 	}
```
but it feels to me that it is incomplete.

Maybe the Hacks class should be augmented with something like.
```
        Set<String> resourceIdentifiers = (Set<String>)context.getAttributes().get(ResourceHandler.RESOURCE_IDENTIFIER);
        if (renderedResources != null) {
            renderedResources.clear();
        }
```

I am using OmniFaces 3.11 and Mojarra (jakarta.faces) 2.3.14.payara-p2 on Payara 5.2020.7.

**Comment by BalusC** [comment]
This has been reported in https://github.com/omnifaces/omnifaces/issues/627 and fixed 15 days ago.

Can you retry with current snapshot?

**Comment by chrisselwyn** [comment]
I have just tried using the 3.11.1-SNAPSHOT build of 09/May/2021 and it looks as though it does not fully resolve the problem.

The problem that I see is that PrimeFaces' components.css resource is not being rendered.

In the Hacks class I can see the code...
```
		if (context.getRenderResponse()) {
			// Mojarra 2.3+ rendered @ResourceDependency/<h:outputScript>/<h:outputStylesheet>
			context.getAttributes().keySet().remove(ResourceHandler.RESOURCE_IDENTIFIER);
		}
```

The documentation for getRenderResponse() says "Return true if the renderResponse() method has been called for the current request."

In my particular test case, the exception is being thrown in the Ajax listener method. So that means that the  renderResponse() method has not yet been called. That, in turn, means that the RESOURCE_IDENTIFIER set is not being removed and, hence, the CSS resources don't get rerendered.

Could I ask why the removal of the RESOURCE_IDENTIFIER set is protected by the test on context.getRenderResponse()?

Chris

**Comment by BalusC** [comment]
Because it otherwise added a duplicate when it was explicitly declared via <h:outputStylesheet>. 

I'll try improving the IT and cover PrimeFaces-specific case.

**Comment by BalusC** [comment]
Sorted out now. 

In the end, your problem was only reproducible when ajax request was fired by PrimeFaces component (e.g. `<p:commandButton>`) instead of standard JSF component (e.g. `<h:commandButton><f:ajax>`). This is because PrimeFaces internal ajax script clears out the entire `<head>` instead of appending non-existing CSS/JS elements to it. 

Thanks for reporting.

**Comment by chrisselwyn** [comment]
I'm glad you got to the bottom of it.
Thanks for all your work.

Chris

**Comment by melloware** [comment]
I just ran into this too and verified this fixes our issue.  Any chance we can get a 3.11.1 release to central?

**Comment by BalusC** [comment]
2.7.12 / 3.11.1 / 4.0-M9 have just been deployed.

**Comment by melloware** [comment]
Thank you very much!
