### ISSUE TITLE
Add validateJoined

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#631]
So you can, for example, validate multiple email address separated with `,` (actual separator should be an attribute, as well as the validatorId).

So `foo@bar.com, bar@@foo` would lead to validation failed, and `foo@bar.com, bar@foo.com` would pass.

**Comment by jepsar** [comment]
.. or a `joinedConverter` to convert to a list and a `validateList`

**Comment by BalusC** [comment]
Better use `List<String>` instead of `String` in combination with https://showcase.omnifaces.org/converters/ToCollectionConverter. Then you can use validators the usual way.
