### ISSUE TITLE
SelectItemsConverter tag

### ISSUE THREAD

**Issue by fcorneli** [omnifaces/omnifaces#633]
Right now you have to use the SelectItemsConverter as follows:
```xml
<p:selectOneMenu value="#{whatever}" converter="omnifaces.SelectItemsConverter">
    <f:selectItems value="#{whatever}"/>
</p:selectOneMenu>
```
It would be nice if you could do something like:
```xml
<p:selectOneMenu value="#{whatever}">
    <o:selectItemsConverter/>
    <f:selectItems value="#{whatever}"/>
</p:selectOneMenu>
```
to make it more in-line with our other converters that do have a custom tag.
All this requires is to add:
```xml
<tag>
        <tag-name>selectItemsConverter</tag-name>
        <converter>
            <converter-id>omnifaces.SelectItemsConverter</converter-id>
        </converter>
</tag>
```
to the omnifaces taglib descriptor.
Same remark for all the other converters.

**Comment by BalusC** [comment]
Okay. Will add new converter/validator tags to next OmniFaces version.

**Comment by fcorneli** [comment]
Thanks.
