### ISSUE TITLE
Feature request: FacesConverter using the OWASP Java HTML Sanitizer

### ISSUE THREAD

**Issue by flange-ipb** [omnifaces/omnifaces#636]
Hi folks!

My colleagues and me frequently find ourself implementing a converter that sanitizes HTML for security reasons in different JSF projects, especially when using PrimeFaces' p:textEditor component(*) and rendering its results via h:outputText with escape="false". We typically use [OWASP Java HTML Sanitizer's](https://github.com/OWASP/java-html-sanitizer) PolicyFactory for sanitization. It would be great to have such a converter shipped with OmniFaces.

Examples from one of our projects:
- [RichTextConverter](https://github.com/ipb-halle/CRIMSy/blob/master/ui/src/main/java/de/ipb_halle/lbac/util/RichTextConverter.java) for use with p:textEditor
- [InputConverter](https://github.com/ipb-halle/CRIMSy/blob/master/ui/src/main/java/de/ipb_halle/lbac/util/InputConverter.java): Sometimes we see that `PolicyFactory.sanitize(String)` also escapes some characters, so we additionally apply `Encoding.decodeHtml(String)`, which is also part of the OWASP HTML Sanitizer library.

Discussion/Ideas:
- Configure the converter by passing in a PolicyFactory object.

(*) I just discovered that PF [takes care for some XSS issues exactly there](https://github.com/primefaces/primefaces/issues/7484). Unfortunately, we're using a super-old PF version where no sanitization happens.

**Comment by BalusC** [comment]
This is unfortunately not a general shortcoming in JSF API itself and it adds a 3rd party dependency and it is therefore beyond the scope of OmniFaces. I recommend pinging [PrimeFaces Extensions](https://github.com/primefaces-extensions/primefaces-extensions) for this, it fits exactly in their scope.

cc: @melloware

**Comment by melloware** [comment]
Yes @flange-ipb if interested open this same ticket over at PrimeFaces Extensions we would be happy to discuss and add. This seems like a good idea.  And @BalusC is right it fits more the PF Extensions use cases.

See:  https://github.com/primefaces-extensions/primefaces-extensions/issues

**Comment by jepsar** [comment]
I'm not sure if you can end up with something that's reusable. The need / config will differ per project or even instance.

**Comment by BalusC** [comment]
The config can be supplied as converter attribute taking an argument of `PolicyFactory` type.

E.g.
```
<x:convertWithHtmlSanitizer policyFactory="#{yourApplicationScopedBean.desiredPolicyFactory}" />
```

**Comment by melloware** [comment]
This will be in PFE 10.0.5. Code is here for review: https://github.com/primefaces-extensions/primefaces-extensions/commit/35758681ebf4dcdf7a7f0749986915b7a52a3729
