### ISSUE TITLE
Omnifaces Multiviews break Websocket support when Welcome Files are enabled (Fixed in 3.11.1)

### ISSUE THREAD

**Issue by treo** [omnifaces/omnifaces#637]
I've written all of the below, and just before submitting it, noticed that there is a new minor version of Omnifaces (3.11.1), so I updated the reproducer with it and the bug went away. **I updated my application to use 3.11.1 and it works now**, too. 

As there is no mention of this being fixed on the What's New page, I guess fixing this bug was a side effect of something else. 

I'm posting this issue anyway, in case someone looks for a solution later on.

Edit: Turns out I was blind: https://showcase.omnifaces.org/whatsnew#fixed_2_7_12
* 3f87300 - MultiViews "excluded pages" failed in OpenLiberty
* fbdfe7d - MultiViews welcome file path info was missing in OpenLiberty

---

I'm using the MultiViews functionality, and recently had to add server push via websockets to a project again. I've spent a long time to try and figure out why things aren't working, even though it works in a different project.

Turns out that having welcome files enabled and multi views at the same time will break websockets support. That is for both the  support built into JSF as well as custom Endpoints defined with `@ServerEndpoint`. 

Excluding the paths from being considered with the following also doesn't help:
```xml
    <context-param>
        <param-name>org.omnifaces.FACES_VIEWS_SCAN_PATHS</param-name>
        <param-value>/*.xhtml/*,!/ws,!/omnifaces.push</param-value>
    </context-param>
```

This project reproduces the behavior:
https://github.com/treo/omnifaces-websockets-multiviews-broken/tree/0bb4f7f6f62c49203a26d44140d71457434b1b7a

Run it with `mvn liberty:dev`. At http://127.0.0.1:9080/index is a very simple JSF application. It has a button, that when clicked will trigger a message on a websocket which itself triggers an alert when websockets actually work. 

I think the reason is still the same as in https://github.com/omnifaces/omnifaces/issues/402.

**Comment by BalusC** [comment]
Thank you very much for the report nonetheless!

Background info for those two ticketless issue fixes related to MultiViews in Liberty: OpenLiberty has been added to set of test servers in the integration tests for the first time in OmniFaces 4.0 and then those two issues were discovered and then backported for 3.x.
