### ISSUE TITLE
The OmniFaces showcase is not working

### ISSUE THREAD

**Issue by anuragnz** [omnifaces/omnifaces#639]
Could you please check, its coming up as below:
![image](https://user-images.githubusercontent.com/3331466/133738725-8754f711-226c-402f-9146-8be345165c5c.png)

**Comment by BalusC** [comment]
Interesting. This appeared to be the effect when the SSL certificate was expired and the PWA serviceworker couldn't fetch it.

I've updated the SSL certificate. It's back online again. Thank you for the report!
