### ISSUE TITLE
validateMultiple: Tag position changes type of passed values

### ISSUE THREAD

**Issue by Rawi01** [omnifaces/omnifaces#642]
According to the comment in `ValidateMultipleFields` the tag can be placed before or after the validated inputs which should only change the validation order. I tried it to work around a different problem but it seems like changing the position also affects the type of the values that gets passed to the validator. If the tag is placed before the inputs it always passes string instead of converted values, even if the conversion is impossible. If the tag is placed after the inputs it passes the converted values or doesn't call the validator if one of the fields contain a value that can not be converted. This is actually quite confusing and I think it is not intended. I have not checked the code in detail but as far as I could figure out the conversion should take place in the Apply Requests phase and validation in the later Process Validation phase so the converted values should be available somewhere.

**Demo:**
```html
<!DOCTYPE html>
<html lang="de" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:o="http://omnifaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core">
	<h:form>
		<o:validateMultiple id="pre" components="foo bar" validator="#{validateMultipleImpl}" message="Pre" />
	
		<h:panelGrid columns="3">
			<h:inputText id="foo" value="#{validateMultipleBean.foo}" />
	
			<h:inputText id="bar" value="#{validateMultipleBean.bar}" />
	
			<h:panelGroup />
			<h:commandButton value="submit">
				<f:ajax execute="@form" render="@form" />
			</h:commandButton>
		</h:panelGrid>
		
		<h:messages />
		
		<o:validateMultiple id="post" components="foo bar" validator="#{validateMultipleImpl}" message="Post" />
	</h:form>
</html>
```
```java
package org.omnifaces.showcase.validators;

import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.component.UIInput;
import javax.faces.context.FacesContext;
import javax.inject.Named;

import org.omnifaces.util.Messages;
import org.omnifaces.validator.MultiFieldValidator;

@Named
@ApplicationScoped
public class ValidateMultipleImpl implements MultiFieldValidator {
	@Override
	public boolean validateValues(FacesContext context, List<UIInput> components, List<Object> values) {
		Messages.addGlobalInfo(values.get(0).getClass().getName() + " " + values.get(0).getClass().getName());
		return true;
	}
}
```
**Valid values:**
![img](https://user-images.githubusercontent.com/5850477/134487309-cb613f45-f03a-419e-a097-73d47b968172.png)
**Invalid values:**
![img](https://user-images.githubusercontent.com/5850477/134487422-1e3fe7d5-ebad-48e4-9458-5954f00e4202.png)

**Comment by BalusC** [comment]
Sorry, the JSF lifecycle really specifies that conversion runs during the process validations phase. So the observed behavior is correct.


```
JSF phases/lifecycle cheatsheet

fc = FacesContext
vh = ViewHandler
in = UIInput
rq = HttpServletRequest
id = in.getClientId(fc);

1 RESTORE_VIEW
String viewId = rq.getServletPath();
fc.setViewRoot(vh.createView(fc, viewId));

2 APPLY_REQUEST_VALUES
in.setSubmittedValue(rq.getParameter(id));

3 PROCESS_VALIDATIONS
Object value = in.getSubmittedValue();
try {
   value = in.getConvertedValue(fc, value);
   for (Validator v : in.getValidators())
      v.validate(fc, in, value);
   }
   in.setSubmittedValue(null);
   in.setValue(value);
} catch (ConverterException | ValidatorException e) {
   fc.addMessage(id, e.getFacesMessage());
   fc.validationFailed(); // Skips phases 4+5.
   in.setValid(false);
}

4 UPDATE_MODEL_VALUES
bean.setProperty(in.getValue());

5 INVOKE_APPLICATION
bean.submit();

6 RENDER_RESPONSE
vh.renderView(fc, fc.getViewRoot());
```

**Comment by BalusC** [comment]
I've at least clarified the javadoc.

**Comment by Rawi01** [comment]
Thanks a lot for the fast and detailed response (that's a great cheatsheet) and for updating the javadoc.
