### ISSUE TITLE
ExpressionInspector.getMethodRefernce stops working with tomcat-jasper-el 9.0.54

### ISSUE THREAD

**Issue by thomaswoeckinger** [omnifaces/omnifaces#646]
Used omnifaces 3.11.1
When upgrading to Tomcat 9.0.54 `ExpressionInspector.getMethodRefernce` can not resolve `MethodRefrences` of form

```
#{Foo.create(Bar.selected)}
```
The returned type of `Bar.selected` is `Baz`

`org.apache.el.parser.AstValue.getMethodInfo(EvaluationContext, Class[])` calls `getParameters` also on the parameters,
see https://github.com/apache/tomcat/commit/2d05397132e8e803781a0c73c72e8e7d825da1d1 for details.

This will lead to wrong outcome at line 201 of the internal inspectorElContext.
The base object changed to `Baz` instead of `Foo`

**Comment by BalusC** [comment]
Nailed and fixed. Thank you very much for reporting this issue!

**Comment by thomaswoeckinger** [comment]
I think the fix will be included in version 3.11.3, so when do you plan the next release?
Thx for your fast response!!

**Comment by BalusC** [comment]
3.11.3 has moved to 3.12. There are no strict release plans. I can release 3.12 today if you prefer.

**Comment by thomaswoeckinger** [comment]
> 3.11.3 has moved to 3.12. There are no strict release plans. I can release 3.12 today if you prefer.

That would be great, thx

**Comment by BalusC** [comment]
There you go: https://repo.maven.apache.org/maven2/org/omnifaces/omnifaces/3.12/
