### ISSUE TITLE
Combination of UnmappedResourceHandler with ExtensionlessURLs gives broken links

### ISSUE THREAD

**Issue by astappiev** [omnifaces/omnifaces#651]
When using `ExtensionlessURLs` and `UnmappedResourceHandler` my page doesn't show icons.  And surprisingly it happens when I just added a new page and no other changes (spoiler: later I found a reason, it's a HashMap returned by `servletRegistration.getMappings()`).

So, the problem is that links inside resources rendered incorrectly, with unnecessary prefix, e.g.:
```
@font-face{font-family:'primeicons';font-display:block;src:url("/imprint/jakarta.faces.resource/primeicons/primeicons.eot?ln=primefaces&v=11.0.0-RC2");
```
In the code above, `/imprint` shouldn't be there.

I started to dig into the problem and found that it happens because wrong mapping is used from [getFacesServletMapping](https://github.com/apache/myfaces/blob/3.0.x/shared/src/main/java/org/apache/myfaces/shared/resource/BaseResourceHandlerSupport.java#L174) and in particular because [this method](https://github.com/apache/myfaces/blob/3.0.x/shared/src/main/java/org/apache/myfaces/shared/application/FacesServletMappingUtils.java#L272) just uses the last mapper when it iterates over HashMap of all mappers of a Servlet. With some amount of pages, my `imprint` page went to last position and started causing the problem. Before, all `ExtensionlessURLs` mappings had position before `/jakarta.faces.resource/*` mapper, but because it's HashMap, we can't set a position.

Of course, I think it's more an issues of MyFaces or JSF in general, but without `UnmappedResourceHandler` it works fine because there is no need for full resource path. Maybe for "unmapped" resources, we can check `_requestPath` and remove prefix if there is something before `/jakarta.faces.resource/*`.

I can create an example project if needed.

**Comment by BalusC** [comment]
> it happens when I just added a new page and no other changes

So after redeploying the project or restarting the server, everything works again?

Have you also checked if it also happens in Mojarra?

**Comment by astappiev** [comment]
> Have you also checked if it also happens in Mojarra?

Had a chance to check with Mojarra and no, there is no such issue. The affected version is MyFaces 3.0.

Until now, the issue was fixed with such a weird wrapper. The important part is `fixContextPath` method.
It checks whether resource path contains `RESOURCE_IDENTIFIER` not on the first position and if so, removes the prefix and adds double `RESOURCE_IDENTIFIER` prefix (this is required, otherwise doesn't work).
```java
import static org.omnifaces.util.Faces.*;

import jakarta.faces.application.Resource;
import jakarta.faces.application.ResourceHandler;

import org.omnifaces.resourcehandler.RemappedResource;

public class UnmappedResourceHandler extends org.omnifaces.resourcehandler.UnmappedResourceHandler {
    /**
     * Creates a new instance of this unmapped resource handler which wraps the given resource handler.
     *
     * @param wrapped The resource handler to be wrapped.
     */
    public UnmappedResourceHandler(final ResourceHandler wrapped) {
        super(wrapped);
    }

    // Actions --------------------------------------------------------------------------------------------------------

    /**
     * If the given resource is not <code>null</code>, then decorate it as an unmapped resource.
     */
    @Override
    public Resource decorateResource(Resource resource) {
        if (resource == null) {
            return resource;
        }

        String path = fixContextPath(resource.getRequestPath());
        return isResourceRequest(path) ? new RemappedResource(resource, unmapRequestPath(path)) : resource;
    }

    private static String fixContextPath(String path) {
        if (!path.startsWith(getRequestContextPath() + RESOURCE_IDENTIFIER)) {
            return getRequestContextPath() + RESOURCE_IDENTIFIER + path.substring(path.indexOf(RESOURCE_IDENTIFIER));
        }
        return path;
    }

    private static boolean isResourceRequest(String path) {
        return path.startsWith(getRequestContextPath() + RESOURCE_IDENTIFIER);
    }

    private static String unmapRequestPath(String path) {
        String mapping = getMapping();

        if (isPrefixMapping(mapping)) {
            return path.replaceFirst(mapping, "");
        } else if (path.contains("?")) {
            return path.replace(mapping + "?", "?");
        } else if (path.endsWith(mapping)) {
            return path.substring(0, path.length() - mapping.length());
        } else {
            return path;
        }
    }
}
```

**Comment by astappiev** [comment]
> So after redeploying the project or restarting the server, everything works again?

No, restarting the server doesn't help. But adding or removing views changes the mappings HashMap.
In some cases, the resources mapping will appear on expected position and everything works. But adding a new view, results into new order of the map and it doesn't work anymore. Adding a few more pages may solve the issue, or not.

**Comment by BalusC** [comment]
Ok, reproduced, happens only when MultiViews is enabled as well. I.e. e.g. `/*.xhtml/*` configuration is used instead of `/*.xhtml`. This bit of information was missing in original report.
