### ISSUE TITLE
@Param in quarkus

### ISSUE THREAD

**Issue by RobiVeho** [omnifaces/omnifaces#658]
I'm trying to port the JSF app to quarkus. I use @Param in my beans, it works OK in WildFly. I am able to compile it, however  during the startup  I am getting "[1] Unsatisfied dependency for type java.lang.Integer and qualifiers [@Param]".

**Comment by arjantijms** [comment]
Interesting. We should probably add Quarkus as a test target. @BalusC ?

**Comment by BalusC** [comment]
That would basically mean that we should merge/implement something like https://github.com/adminfaces/quarkus-omnifaces into OmniFaces itself, right?

**Comment by melloware** [comment]
@BalusC Yes I would think that is what it means.  Quarkus cannot be used currently with OmniFaces without that bridge.  It would be much preferred it that was part of the OmniFaces ecosystem and built as part of OmniFaces.

**Comment by arjantijms** [comment]
I'm not super up to date with Quarkus, but I think something like the `OmniFacesProcessor` is the build-time version of the CDI extension OmniFaces uses. Probably for EE 10 (or 11, depending on how it goes), we could convert it to CDI-Lite.

**Comment by BalusC** [comment]
Then I can for the time being only recommend to use https://github.com/adminfaces/quarkus-omnifaces and implement/fix `@Param` support over there and then await for CDI-Lite to be available before backporting it for OmniFaces-native Quarkus compatibility.

**Comment by melloware** [comment]
@RobiVeho Yes I would report it over there on Quarkus Omnifaces for now and have @rmpestano add it there.

**Comment by melloware** [comment]
OK I am working on the Quarkiverse OmniFaces official extension and I know why `@Param` does not work.

See: https://github.com/quarkiverse/quarkus-omnifaces/issues/3

**Comment by melloware** [comment]
This is fixed in Quarkus OmniFaces 4.5.1.1 when released.
