### ISSUE TITLE
o:inputFile accept media type (with + char) validation

### ISSUE THREAD

**Issue by areal-amlr** [omnifaces/omnifaces#661]
Mojarra 2.3.14 SP04
Omnifaces 3.12
Wildfly 26.0.0
OpenJDK 11.0.13+8

Hi,

I found an unexpected behaviour while using accept attribute on `o:inputFile.`

`<o:inputFile id="uploadedFile" value="#{myBean.uploadedFile}" accept="image/svg+xml" required="true" requiredMessage="Value is required"/>`

I debuged `org.omnifaces.component.input.InputFile` method:

	private void validatePart(FacesContext context, Part part, String accept, Long maxsize) {
		String fileName = getSubmittedFileName(part);
		String message = null;
		String param = null;

		if (accept != null) {
			String contentType = isEmpty(fileName) ? part.getContentType() : getMimeType(context, fileName.toLowerCase(getLocale()));

			if (contentType == null || !contentType.matches(accept.trim().replace("*", ".*").replaceAll("\\s*,\\s*", "|"))) {
				message = getAcceptMessage();
				param = accept;
			}
		}

		if (message == null && maxsize != null && part.getSize() > maxsize) {
			message = getMaxsizeMessage();
			param = formatBytes(maxsize);
		}

		if (message != null) {
			addError(getClientId(context), message, Components.getLabel(this), fileName, param);
			setValid(false);
		}
	}

and found out that the validation fails on

`!contentType.matches(accept.trim().replace("*", ".*").replaceAll("\\s*,\\s*", "|"))`

This is caused by the regular expression being evaluated having a quantifier(+) char.
If I change the accept attribute of my inputFile to `image/svg\\+xml`, then the validation is successfull, however with this change the svg file extension is not recognized in the browser dialog.

I'm not really sure if this is an issue, or if this is the expected behaviour. Anyway, is there a workaround so I can have the built-in validation along with browser dialog filter for mime types containing the + char?

**Comment by BalusC** [comment]
I've fixed it for 3.13 (and 2.7.15). 

Can you let me know if the latest 3.13-SNAPSHOT works for you? https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/3.13-SNAPSHOT/

Thank you very much for reporting this issue and improving OmniFaces!

**Comment by areal-amlr** [comment]
Hi,

It's works fine with only one entry on accept attribute.
If you test, for instance with `accept="image/png,image/svg+xml"` the test fails.
I think the reason is the split regex on `String[] parts = accept.replaceAll("\\s*", "").split("(?=[*,])");` in method `convertAcceptToRegex` on class `org.omnifaces.component.input.InputFile`

With that value on accept attribute, the parts array is returning `[image/png, ,image/svg+xml]`, when I think the expected return should be `[image/png, ,, image/svg+xml]`.

Thank you!

**Comment by BalusC** [comment]
Fixed, thanks!

**Comment by areal-amlr** [comment]
It's working great!
Are you planning to release final release or a patch on 3.12 with this fix?
Thank you!
