### ISSUE TITLE
Support for o:validate* parent component ID

### ISSUE THREAD

**Issue by semrola** [omnifaces/omnifaces#662]
I often have the form fields in `ui:repeat` or `c:forEach` and it's really annoying to construct a string of component IDs that need to be validated for `o:validate` tag `components` attribute.
Add support for inserting a parent component ID to `components` attribute of `o:validate` which would validate all children inputs. This way you can easily validate all inputs by passing a single ID.

**Comment by BalusC** [comment]
Point taken.

**Comment by BalusC** [comment]
Implemented for 3.13. Thank you for creating this issue and improving OmniFaces!

**Comment by semrola** [comment]
Is it not going to be merged to v2 library?

**Comment by BalusC** [comment]
Nope, 2.x is in bugfix mode since 3.x release (i.e. only bugfixes will get there). It won't get API changes unless required by the bugfix.
