### ISSUE TITLE
Add Faces#isSessionExpired

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#663]
https://stackoverflow.com/questions/11206817/how-to-detect-session-has-been-invalidated-in-jsf-2

```java
return request.getRequestedSessionId() != null && !request.isRequestedSessionIdValid();
```

Would be great to use on a component on the login page like `rendered="#{faces.sessionExpired}"` instead of `rendered="#{not empty request.requestedSessionId and not request.requestedSessionIdValid}"`

**Comment by BalusC** [comment]
`Faces#isRequestedSessionExpired()`, `FacesLocal#isRequestedSessionExpired(FacesContext)` and `#{faces.requestedSessionExpired}` have been added for 3.13.

Thank you for improving OmniFaces!

**Comment by BalusC** [comment]
Turns out this already existed since OmniFaces 1.1 as `Faces#hasSessionTimedOut()` :o I'll deprecate that one in favor of the current one because the `has` prefix isn't entirely natural.
