### ISSUE TITLE
Stylesheets not rendered in FullAjaxExceptionHandler when using p:ajax

### ISSUE THREAD

**Issue by paulthomson78** [omnifaces/omnifaces#664]
Hello,

This follows on from the previous issue reported under #627 / #630, i.e. that stylesheets were not being rendered on error pages generated via FullAjaxExceptionHandler.  The fix provided for that (commit 3552b12b4cfac19d162d17d647bd0bd187aa34ea) is working nicely for exceptions thrown in the actionListeners of PrimeFaces components, thank you.

However, I see the problem still occurring when the PrimeFaces ajax request is triggered using p:ajax within a regular JSF component, e.g.:

```
<h:commandButton value="Click me">
    <p:ajax listener="#{myBean.myMethod}"/>
</h:commandButton>
```

This may be down to how Hacks#isPrimeFacesAjaxRequest was implemented, i.e. testing:

```
actionSource.getClass().getPackage().getName().startsWith(PRIMEFACES_PACKAGE_PREFIX);
```

In the h:commandButton example above, the actionSource's package is javax.faces.component.html rather than org.primefaces.component.commandbutton, so this isn't recognised as being a PrimeFaces ajax request.

Is this scenario something you'd be able to support too please?

I'm running using:
- Omnifaces 3.12.
- PrimeFaces 8.0
- Java 8
- WildFly 19.1.0, which is using jsf-impl-2.3.9.SP08.jar.

Thanks, Paul.

**Comment by BalusC** [comment]
Fixed, thank you very much for improving OmniFaces!

**Comment by paulthomson78** [comment]
That's fantastic, thank you very much!
