### ISSUE TITLE
ViewScoped broken with myfaces 2.3-next or 3.0

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#666]
I believe Omnifaces ViewScoped is broken with myfaces 2.3-next and up.

In Hacks.java:

`	private static final String MYFACES_SERIALIZED_VIEWS = "org.apache.myfaces.application.viewstate.ServerSideStateCacheImpl.SERIALIZED_VIEW";
`

But this class was split in a refactor in myfaces 2.3-next. See https://github.com/apache/myfaces/commit/337102e8aa5f72c0fde2803b7b5457b1e8755e91#diff-4dcfe4aebbad521c946ca0958570c01d305853e99198bac8ed11f32267373380

So the key should be org.apache.myfaces.application.viewstate.StateCacheServerSide.SERIALIZED_VIEW

Maybe omnifaces should try both keys?

**Comment by melloware** [comment]
Good catch!

**Comment by BalusC** [comment]
I've fixed it. 

I also wanted to move `tomcat-myfaces` IT config to 2.3-next-M6, but relatively a lot of tests failed with 
```
org.jboss.arquillian.graphene.request.RequestGuardException: Request type 'XHR' was expected, but type 'NONE' was done instead
```
39 of 109 failed. 

Most of those failing cases were in some way related to performing a second ajax submit after already having performed an ajax submit on same page beforehand. I.e. most probably a JS error popped up after the 1st ajax submit causing the 2nd ajax submit to behave as a non-ajax submit.

Probably something for MyFaces to look at?

I've for now left the IT config at Myfaces 2.3.9.

**Comment by melloware** [comment]
CC @tandraschko

**Comment by tandraschko** [comment]
if you can provide me a simple primefaces-test reproducer + description, i can have a look at
