### ISSUE TITLE
ViewParam - ignore default value in getStringValueFromModel

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#668]
We are using _o:viewParam_ to define and pass default parameters to our bean. Like pagination page number or size:

    <o:viewParam name="page" default="1"/>
    <o:viewParam name="pageSize" default="20"/>

There is a drawback that any generated bookmarkable URL will include those parameters since they are not null in the model leading to unnecessary duplicate URLs and even potential problems like a non identical meta refresh of the main page tag to keep the session alive or other unwanted "duplicate URLs" bots like google will start to crawl, just to realize the defined canonical wasting performance. 

    <meta http-equiv="refresh" content="3600;url=?page=1&pageSize=20&foo=false">

Instead of extending my own view handler from _MultiViewHandler_ and ignoring those when building the bookmarkable / action URLs i naively thought about dynamically obtaining them via _ ViewMetadata.getViewParameters(root)_ and  replacing them afterwards which works, but of cause not for rewritten URLs with parameters like _/page/1_.

https://github.com/eclipse-ee4j/mojarra/blob/ea2783c4cfbef8f6a8e171be1b9ef2e87a930b8f/impl/src/main/java/com/sun/faces/application/view/MultiViewHandler.java#L562

**ViewParam.getStringValueFromModel**

Before extending the view handler another option could be returning null in _getStringValueFromModel_ if the string value matches the default?

https://github.com/omnifaces/omnifaces/blob/505c688750e678fe0b96e604f500df43ec924a3c/src/main/java/org/omnifaces/component/input/ViewParam.java#L141

The only reference i found to this method is in the _MultiViewHandler_ and i think this would be a clean solution?

**Comment by BalusC** [comment]
Makes sense.

**Comment by djmj** [comment]
Thanks for the update!
