### ISSUE TITLE
Feature Request | Faces.validationError

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#669]
```
public static void validationError(String message,Object... params) {
  throw new ValidatorException(Messages.createError(message,params));
}
```

or if a more extended support for FacesMessege Level is needed 

```
public static void validationError(String message,Object... params) {
  throw new ValidatorException(Messages.createError(message,params));
}

public static void validationInfo(String message,Object... params) {
  throw new ValidatorException(Messages.createInfo(message,params));
}

public static void validationWarn(String message,Object... params) {
  throw new ValidatorException(Messages.createWarn(message,params));
}
```

**Comment by jepsar** [comment]
I'd say `Messages.throwValidatorException(String message, Object... params)`

**Comment by BalusC** [comment]
Indeed, those are already handled via `Messages` utility class: https://showcase.omnifaces.org/utils/Messages

**Comment by pizzi80** [comment]
Oops, sorry is the first example! :open_mouth: 

I find this just a little counterintuitive, 
but I understand the philosophy behind.

Probably it was the only way to unify those jsf api ............

@BalusC any chance that Faces will incorporate Omnifaces ?

or viceversa you could fork Mojarra + include all actual Omnifaces implementations
ad create a super efficient and better JSF implementation :smiley:

**Comment by arjantijms** [comment]
> or viceversa you could fork Mojarra + include all actual Omnifaces implementations

Technically we wouldn't have to fork Mojarra as the OmniFaces committers are also Mojarra committers ;)

**Comment by pizzi80** [comment]
Even better, after Mojarra v4 it could be a good idea 
to elevate OmniFaces to a Faces implementation and unify Mojarra 4 and Omnifaces 4

OmniFaces it's also a better name for a "Faces" implementation ;)
( similar to MyFaces )
