### ISSUE TITLE
Snapshots not available in maven central

### ISSUE THREAD

**Issue by skwirking** [omnifaces/omnifaces#67]
It looks like the SNAPSHOT versions are not being deployed to Maven Central.

The omnifaces homepage suggests the following maven configuration:

```xml
<dependency>
    <groupId>org.omnifaces</groupId>
    <artifactId>omnifaces</artifactId>
    <version>1.8.1</version> <!-- Or 2.0-SNAPSHOT or 1.10-SNAPSHOT -->
</dependency>
```

But Maven can't find the SNAPSHOT dependencies:
> Could not find artifact org.omnifaces:omnifaces:jar:1.10-SNAPSHOT

When I look in Maven Central for [all the versions of omnifaces](http://search.maven.org/#search|gav|1|g%3A%22org.omnifaces%22%20AND%20a%3A%22omnifaces%22), there are no SNAPSHOT versions listed.

My workaround at the moment is to download the jar manually and then manually install it into my local repo.

**Comment by BalusC** [comment]
Added link to homepage.
