### ISSUE TITLE
Socket - security and performance question

### ISSUE THREAD

**Issue by kozeljko** [omnifaces/omnifaces#670]
We are currently exploring the Omnifaces socket component for displaying live data to our users. More specifically, if some data enters our system, it should be displayed to users of the group that has ownership of said data. We are using OmniFaces version 2.6.4.

We implemented a small demo similarly to how it is proposed on the documentation page (https://showcase.omnifaces.org/push/socket). We have a class that receives data in the back end and sends an event about it:

```java
...

@Inject
private Event<EventData> sendingEvent;

...

public void sendEvent(Data data) {
    sendingEvent.fire(new EventData(data));
}

```

We have an ApplicationScoped class that observes for these events and sends them to a socket.

```java

@ApplicationScoped
public class DataEventHandler {

    @Inject
    @Push(channel = "someChannel")
    private PushContext pushContext;
    
    public void handleData(@Observes EventData eventData) {
        Long groupId = 1L; // Some random compay for test
        pushContext.send(eventData.getData(), groupId);
    }
}

```

And some markup to listen to the socket. Component listens on channel "someChannel" with the user's groupId as "user":

```xhtml
        <script>
            function socketListener(message) {
                console.log(message);
            }
        </script>

        <o:socket id="main" channel="someChannel" onmessage="socketListener" user="#{user.groupId}"/>

```

And this works. What my concern is that I'm not sure how secure this is. With this markup, the user would get only data for their group, but I don' think anything prevents the user from connecting to the socket manually and selecting an arbitrary value for the "user" field.

I would like to add that any user of the application should be able to connect to the socket. But certain messages should go only to certain users.

**Question 1:**
So my question is, is it possible to completely secure this flow and prevent an arbitrary user to connect to web socket he wasn't meant to? What are my options here?

One option, that is also seen in the documentation, is that the socket should only push notifications of a new message and then the web page needs to ask the back end for an update manually. This requires some more work from the back end, but it will work. What I'm unsure about is the quantity of messages, that may arrive on the socket. If a message arrives while the update for the previous one is still happening, what will happen?

**Question 2:**
So my question is, if there is a considerable amount of messages, can this block the front end and make it unresponsive? What happens if an update is being made for the previous message and a new one arrives?

Thanks

**Comment by BalusC** [comment]
1. It's secure already.
2. Yes it can. It's your responsibility to queue the calls to `PushContext#send()`. It was considered beyond the responsiblity of the o:socket because there are too many options to implement this task.

**Comment by kozeljko** [comment]
Thank you
