### ISSUE TITLE
importConstants: identical name gets resolved with ancestor field

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#672]
OF 3.13.
Have
```
public class Bean {

	public static final String VALUE = "Bean value";

}

public class ChildBean extends Bean {

	public static final String VALUE = "ChildBean value";

}
```
Importing ChildBean.VALUE
```
<o:importConstants type="Bean" />
Imported Bean.VALUE=#{Bean.VALUE}
<br />
<o:importConstants type="ChildBean" />
Imported ChildBean.VALUE=#{ChildBean.VALUE}
```
gets resolved to the values of Bean.VALUE, not ChildBean.VALUE. It should resolve to ChildBean.VALUE.
![image](https://user-images.githubusercontent.com/8070317/154301044-dddeb236-1896-46de-aa01-7d91801ec873.png)
At least that's how it is with openjdk-11.0.11_9 on windows. It's not guaranteed behavior - looking at ImportConstants it depends on getFields implementation.
[omnifaces-importconstants-name-clashes-resolved-by-ancestor.zip](https://github.com/omnifaces/omnifaces/files/8081246/omnifaces-importconstants-name-clashes-resolved-by-ancestor.zip)

**Comment by VsevolodGolovanov** [comment]
PrimeFaces' p:importConstants doesn't seem to have this problem. But it seems to rely on getFields result order, so it's not strictly correct either:
![image](https://user-images.githubusercontent.com/8070317/154301721-9d931924-7f3c-4b3a-a3c5-e1f60e0b218f.png)

**Comment by BalusC** [comment]
Fixed. I've used `getDeclaredFields()` instead of `getFields()`.

Thank you for improving OmniFaces!
