### ISSUE TITLE
o:viewParam - required if present

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#678]
For view param _required_ validation there is a logic difference if the value is optional and a converter is attached.

The request param could have a string value but the converter may not find corresponding data which maybe represents a 404 error since the data is really not available anymore or has moved or someone is trying to access resources he has no permission too like a bot or just guessing id's for example.

We could throw an exception inside the converter but for reusability we are using a generic converter that just returns _null_ if it cannot find the data.

Basically we need an attribute like  _requiredIfPresent_ for this case and the current solution we use is:

		<o:viewParam name="product" value="#{bean.product}" converter="#{productConverter}">
			<f:validateRequired disabled="#{empty param['product']}"/>
			<o:viewParamValidationFailed sendError="404" />
		</o:viewParam>

Maybe could be simplified using:

		<o:viewParam name="product" value="#{bean.product}" converter="#{productConverter}" requiredIfPresent="true"/>
		

		<o:viewParamValidationFailed sendError="404" />

Its nothing big but would save some lines of code and make it more readable.

**Comment by BalusC** [comment]
The `required` attribute supports EL and the following ought to be possible:
```
<o:viewParam name="foo" ... required="#{not empty param.foo}" />
```
```
<o:viewParam name="foo" ... required="#{not empty param[component.name]}" />
```
```
<o:viewParam name="foo" ... required="#{not empty component.submittedValue}" />
```

**Comment by djmj** [comment]
Ah, how could i not have tested this. Thank you!
