### ISSUE TITLE
o:validateBean clone copier isAccessible fails

### ISSUE THREAD

**Issue by areal-amlr** [omnifaces/omnifaces#680]
Mojarra 2.3.14 SP04
Omnifaces 3.13
Wildfly 26.0.1
OpenJDK 11.0.13+8

Hi,

I'm using o:validateBean and after upgrading to omnifaces 3.13 I was getting NPE on my custom validator.
e.g.
`<o:validateBean value="#{myBean}" validationGroups="MyValidationGroup"/>`

After debugging, I found that the `clone` method on MyBean was not being invoked.
Then I verified that the reason was issue #659. It's fails on additional validation
`if (!method.isAccessible()) {
throw new IllegalStateException(format(ERROR_INACCESSIBLE_METHOD, object.getClass()));
		}`
even though I override clone method to public
`	@Override
	public Object clone() throws CloneNotSupportedException`

I managed to workaround this issue by creating a custom copier based on the omnifaces one.
The only change is `if (!method.canAccess(object))` instead of `if (!method.isAccessible())`.

I understand that this cannot be used on current 3.x because this is only available since Java9 (replacing `method.isAccessible()` wich is deprecated).
I checked the current 4.x branch and it is still using the deprecated method.

Is it possible to fix this for 3.x and making the change for 4.x ?

Thanks!

**Comment by BalusC** [comment]
You're completely right. Fixed now and added an unit test to be sure. Thank you for reporting this issue and improving OmniFaces!
