### ISSUE TITLE
Regression: VersionedResourceHandler broken since 3.13.1

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#688]
This is a regression introduced due to a fix for #676 

I believe that the resource handler chain is no longer preserved in `VersionedResourceHandler` since this commit:
https://github.com/omnifaces/omnifaces/commit/349b6769a556b593866b58c9ab2e969b9e359a4e
hence the regression.

Broken test:
https://jenkins.hope.nyc.ny.us/blue/organizations/jenkins/flowlogix-org-repo%2Fflowlogix/detail/dependabot%2Fmaven%2Forg.omnifaces-omnifaces-3.13.2/1/tests

Disclosure: I did not have much time to investigate the failure, but what I am seeing from the commit makes sence.
Prior to this commit, `wrapped` was being passed to the inner class, and currently it's ignored in `RemappedResource` thus 
the handler chain is broken.

Thank you!

**Comment by BalusC** [comment]
> and currently it's ignored in `RemappedResource`

Can you be a bit more specific. I'm not seeing where it is ignored.

**Comment by lprimak** [comment]
https://github.com/omnifaces/omnifaces/blob/349b6769a556b593866b58c9ab2e969b9e359a4e/src/main/java/org/omnifaces/resourcehandler/VersionedResourceHandler.java#L99

`wrapped` is not passed in here, thus the handler chain is broken

**Comment by BalusC** [comment]
Sorry, still not understanding why it should be passed there.

**Comment by lprimak** [comment]
Because it breaks the handler chain. It gives no chance to another handler to work on the resource path.
Let's say have multiple handlers installed. Then the `VersionedResourceHandler` operates on the resource path.
In the previous iteration, another handler can also rewrite the path after the versioned handler has done its work.
WIth the new iteration, `VersionedResourceHandler` is the 'last' handler and it doesn't go further down the handler chain because it breaks said chain.

Hope this helps. If you look at the failing test it illustrates the situation quite well

**Comment by lprimak** [comment]
The failed test has both `VersionedResourceHandler` and `MinimizedHandler` and the latter does not run with the latest OmniFaces

**Comment by BalusC** [comment]
I get that, but the passed-in `resource` argument is supposed to be already obtained from `wrapped` handler.

I will take a closer look later.

**Comment by lprimak** [comment]
Thanks. As I said before in the disclaimer this is an educated guess but this is the most likely point of failure. IT tests proved lifesaver yet again :)

**Comment by svenhaag** [comment]
@lprimak maybe you can PR some of your tests?

**Comment by BalusC** [comment]
Sorry, norepro with https://github.com/omnifaces/omnifaces/commit/f64c045cb85ec2a02e833bfa8c2df26dd5dda9b0

Can you please show me the source of your `MinimizedHandler`? A wild guess would be that it doesn't implement all of the three `createResource()` methods.

**Comment by lprimak** [comment]
Here is the minimized handler (it’s tiny): 
And available for contribution into OmniFaces 

https://github.com/flowlogix/flowlogix/blob/master/jakarta-ee/flowlogix-jee/src/main/java/com/flowlogix/ui/MinimizedHandler.java

and the IT test: 
https://github.com/flowlogix/flowlogix/tree/master/jakarta-ee/jee-examples

https://github.com/flowlogix/flowlogix/blob/master/jakarta-ee/jee-examples/src/test/java/com/flowlogix/examples/ExceptionPageIT.java

**Comment by BalusC** [comment]
```
    @Override
    public Resource decorateResource(Resource resource) {
        if (resource != null && !Faces.isDevelopment() && resource.getLibraryName() == null) {
            resource.setResourceName(toMinimized(resource.getResourceName()));
        }
        return resource;
    }
```
The `setResourceName()` call there was unexpected and uncovered a bug in `RemappedResource` which I've fixed.

Let me know if your IT runs then I'll release 3.13.3.

**Comment by lprimak** [comment]
@BalusC Success! Tests are now running properly.
Thanks for your help!

**Comment by BalusC** [comment]
3.13.3 has been released.
