### ISSUE TITLE
Event Driven Updates

### ISSUE THREAD

**Issue by schulzp** [omnifaces/omnifaces#69]
We recently released [Event Driven Updates](https://github.com/encoway/edu), a JSF library to decouple components of AJAX heavy UIs. It takes search expressions (`@this`, `@parent`, `@(...)`) a step further to allow for an **event-driven** approach instead of referencing components directly.

Instead of maintaining EDU as a separate project I'd love to contribute to OmniFaces. Please let me know what you think.

**Comment by schulzp** [comment]
Hi, thanks for an awesome 2.0 release. Now that it's out, are you still interested in adding [Event Driven Updates](https://github.com/encoway/edu) as feature? Please let me know where you'd like it integrated.

**Comment by BalusC** [comment]
Let's do it in `org.omnifaces.ajax` package.

Utility (if absent) can be added to existing `org.omnifaces.util.Components` and `Ajax` classes.

**Comment by schulzp** [comment]
Alright, thanks. I'll try to come up with a pull request these days.

**Comment by ova2** [comment]
Guys, this is a very good idea, I like it. But I would use the keyword `@` as prefix to be conform with PrimeFaces :-). Maybe as `render="@event(something-changed something-else-changed)"` The value in `@event(...)` is a comma or space separated list.

**Comment by schulzp** [comment]
Hi @ova2, thanks for your comment. I like that Idea. Let's see what I can do.

**Comment by BalusC** [comment]
JSF 2.3's new [Search Expression Framework](http://arjan-tijms.omnifaces.org/p/jsf-23.html#1238) could make this very easy.

**Comment by melloware** [comment]
This will be in PrimeFaces 9.0:
https://github.com/primefaces/primefaces/issues/5509

Example usage:
https://github.com/primefaces-extensions/primefaces-integration-tests/commit/e6f58f1c40c599340f54e0d14d59b0bb852143a4

**Comment by BalusC** [comment]
Excellent!

Let's not reinvent this :) 

I would personally only use `@observes(...)` instead of `@obs(...)`.
