### ISSUE TITLE
Documentation clarification regarding GenericEnumConverter

### ISSUE THREAD

**Issue by commodis** [omnifaces/omnifaces#691]
On the showcase of the [GenericEnumConverter](https://showcase.omnifaces.org/converters/GenericEnumConverter) the following sentence was written down:

> However, when you're having a valueless input component, then this converter may be still useful.

But I do not see the difference between both examples

![image](https://user-images.githubusercontent.com/48327141/168564714-878d464c-c51c-44f6-b2a3-a801e59f414c.png)

What is a `valueless input component`, when both examples look identical and both example interactions work?

**Comment by BalusC** [comment]
Is this more clear?

> However, when you're having an input component without a `value` attribute, and thus the exact type cannot be automatically determined by simply inspecting the return type of the associated getter method, then this converter may be still useful.

**Comment by commodis** [comment]
Yes! This makes much more sense - thank you 🤗
