### ISSUE TITLE
#{now} has a wrong timezone?

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#696]
Faces 4
Weld 5
Java 17

**Result**
```
Date/time OmniFaces now: 2022-06-16 15:37:44    <-- wrong
Date/time OmniFaces now.zoned: 2022-06-16 15:37:44  <-- wrong
Date/time LocalDateTime: 2022-06-16 17:37:44 <-- correct
Date/time java.util.Date: 2022-06-16 17:37:44  <-- correct
```

**xhtml**
```
<!DOCTYPE html>
<html lang="en"
      xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html"
      xmlns:ui="jakarta.faces.facelets"
      xmlns:of="http://omnifaces.org/functions">
<f:view transient="true"> 
    <h:head id="head">
        <title>Hello JSF</title>
    </h:head>
    <h:body>        
        <ul>
            <li>Date/time OmniFaces now: #{of:formatDate(now, 'yyyy-MM-dd HH:mm:ss')}</li>
            <li>Date/time OmniFaces now.zoned: #{of:formatDate(now.zonedDateTime, 'yyyy-MM-dd HH:mm:ss')}</li>
            <li>Date/time LocalDateTime: #{of:formatDate(currentDatetime, 'yyyy-MM-dd HH:mm:ss')}</li>
            <li>Date/time java.util.Date: #{of:formatDate(currentDatetime2, 'yyyy-MM-dd HH:mm:ss')}</li>
        </ul>
    </h:body>
</f:view>
</html>
```

**java**

```
@Produces @Named @RequestScoped
public Date getCurrentDatetime() {
    return Date.from(LocalDateTime.now().atZone(ZoneId.systemDefault()).toInstant());
}

@Produces @Named @RequestScoped
public Date getCurrentDatetime2() {
    return new Date();
}
```

**Comment by BalusC** [comment]
This is expected. Java time API is ISO 8601 based.

But I agree that this is a regression as compared to the original behavior in OmniFaces 1.x/2.x/3.x and that it's better to retain the original behavior.

Noted should be that `getCurrentDatetime()` example is not entirely correct for demonstration purposes as it uses `Date#from()` instead of returning `Instant` directly. When returning it directly, you'll see that the zone is still "incorrect".

**Comment by BalusC** [comment]
Currently `#{now}` and `#{now.zonedDateTime}` will have the system default zone.
The `#{now.instant}` will remain at UTC.

**Comment by pizzi80** [comment]
thanks for your clarifications, always super helpful!

so basically during migration from old versions, to have the same output, 
#{now} should be replaced with #{now.instant}  :ok_hand: 

also related to: https://github.com/omnifaces/omnifaces/issues/549

only as a reminder: The showcase still says that #{now} it's a java.util.Date

**Comment by BalusC** [comment]
#{now} can remain to be used as #{now}.

Showcase runs 3.x not 4.x.
