### ISSUE TITLE
Form.ts line 42  is trying to retrieve faces.request.ajax.arguments 

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#699]
this is not compatible with js strict mode 

```
const params = faces.ajax.request.arguments;
```

I am creating a PR for mojarra's faces.js
and my PR will break it

I would like to know your thoughts on this

1) Is there a way to fix this in Form.ts?
2) port partialSubmit to Faces 
3) remove the strict mode from faces.js only for this

**Comment by BalusC** [comment]
Just add new property to API such as `faces.ajax.request.params`.

**Comment by pizzi80** [comment]
In the meantime I'm trying to test the `o:form` partialSubmit 
but it doesn't seems to work as expected 
(does it should work like PrimeFaces partialSubmit?)

with Faces 4 / Omnifaces 4 the following form creates a full form ajax submit

```
<o:form id="partial" partialSubmit="true">
    <h:inputText id="name" value="#{testBean.name}" />
    <h:inputText id="foo" />
    <h:inputText id="foo2" />
    <h:inputText id="foo3" />
    <h:commandButton id="action" value="submit" action="#{testBean.action}" >
        <f:ajax execute="name" />
    </h:commandButton>
</o:form>
```
![Schermata da 2022-06-22 15-34-43](https://user-images.githubusercontent.com/17908214/175042410-8b886452-e046-405b-8b12-3afc8eb7e601.png)

**Comment by BalusC** [comment]
Crap, it regressed during https://github.com/omnifaces/omnifaces/commit/ee76f788c6ae2b43e619627a257be21930dc845b. I'll have to fix it and add an IT.

**Comment by pizzi80** [comment]
wow, I didn't think you would fix the bug right away, so in the meantime I was working on it ...  :D

I'm trying to introduce the partial submit directly inside faces.js and I think 
that the final place is inside faces.ajax.getViewState 
... but it should be approved first ... at the moment I'll keep it in my fork ...

the main question is: "Why partial submit is not the default and only algorithm?"

**Comment by BalusC** [comment]
It has to be specified in API first. But in Mojarra impl for example you can keep it experimental and by default disabled.

Note that the InputHiddenIT has failed since the bugfix. I still need to look at these when I have time. Basically the algorithm needs to be fixed in such way that any non-namingcontainer child also needs to be included.

**Comment by BalusC** [comment]
InputHiddenIT has been fixed.

Coming back to the original question, I'll have to take back my first comment. This is in hindsight not that trivial. Your best bet is to change the signature of the `faces.getViewState(form)` function to support a second argument representing `options.execute`. This will also give the actual implementation (be it Mojarra or MyFaces) the opportunity to correctly perform the "partial submit" feature even when merely experimental.

**Comment by BalusC** [comment]
I've solved it by simply also monkeypatching the jsf/faces.ajax.request itself.

**Comment by pizzi80** [comment]
> InputHiddenIT has been fixed.
> 
> Coming back to the original question, I'll have to take back my first comment. This is in hindsight not that trivial. Your best bet is to change the signature of the `faces.getViewState(form)` function to support a second argument representing `options.execute`. This will also give the actual implementation (be it Mojarra or MyFaces) the opportunity to correctly perform the "partial submit" feature even when merely experimental.

today I was working on it and I came to same conclusion!! 😅

![DSC_8912](https://user-images.githubusercontent.com/17908214/175503754-e8d94001-6e48-4d4d-bdb0-d4dcd720ea53.JPG)
