### ISSUE TITLE
Intermittent deadlock in JNDIObjectLocator

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#700]
I will be working on a fix soon. It's very rare (1/1000 times under CI failure stress tests)
and only under a failure path (happy path works 100%)

Here are the details
https://github.com/flowlogix/flowlogix/issues/230

**Comment by lprimak** [comment]
tests successfully ran 50k times when previously it would fail around 1k

**Comment by lprimak** [comment]
@BalusC Any chance of releasing a new OmniFaces version that includes this fix? I had a couple of more instances of tests failing due to this :)  Thank you!

**Comment by BalusC** [comment]
It's most likely going to be the next weekend.
