### ISSUE TITLE
FacesExceptionFilter ignoring org.omnifaces.EXCEPTION_TYPES_TO_UNWRAP while logging exceptions

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#702]
In the [documentation](https://showcase.omnifaces.org/exceptionhandlers/FullAjaxExceptionHandler) to FullAjaxExceptionHandler you find;

> By default only FacesException and ELException are unwrapped. You can supply a context parameter "org.omnifaces.EXCEPTION_TYPES_TO_UNWRAP" to specify additional exception types to unwrap.
> [...]
> This context parameter will also be read and used by **FacesExceptionFilter**.

Also the [JavaDoc to `FullAjaxExceptionHandler.html#PARAM_NAME_EXCEPTION`](https://omnifaces.org/docs/javadoc/3.13/org/omnifaces/exceptionhandler/FullAjaxExceptionHandler.html#PARAM_NAME_EXCEPTION_TYPES_TO_UNWRAP) says:

> The context parameter name to specify additional exception types to unwrap by both FullAjaxExceptionHandler and **FacesExceptionFilter**.

However, the [`FacesExceptionFilter.logException()`](https://github.com/omnifaces/omnifaces/blob/4adf54baefe98549b2ce39457fdeb72906a24290/src/main/java/org/omnifaces/filter/FacesExceptionFilter.java#L160) method seems not to respect this parameter. It only checks if the exception itself should be ignored, not the unwrapped cause.

However, note that the parameter is read by the FacesExceptionFilter and used elsewhere inside this class. So maybe I just misinterpreted the documentation?

**Comment by BalusC** [comment]
> However, the [FacesExceptionFilter.logException()](https://github.com/omnifaces/omnifaces/blob/4adf54baefe98549b2ce39457fdeb72906a24290/src/main/java/org/omnifaces/filter/FacesExceptionFilter.java#L160) method seems not to respect this parameter. It only checks if the exception itself should be ignored, not the unwrapped cause.

By default, the `exception` argument passed to the `logException()` method is **already** unwrapped.

And now I'm a bit confused why you created this issue. Are you creating this issue because you've extended the `FacesExceptionFilter` with a custom version wherein you've observed a problem? If not, can you please describe/create a reproducer.

**Comment by BalusC** [comment]
Oh wait, I'm only now noticing that this doesn't happen when the caught exception is not a `ServletException` .. This is indeed a bug which needs to be fixed.

**Comment by BalusC** [comment]
Fixed, let me know if it works for you. It's available in 3.13.4-SNAPSHOT.

**Comment by matinh** [comment]
Thank's for the quick fix. I tested 3.13.4-SNAPSHOT and it's working now as expected.
