### ISSUE TITLE
Ajax#updateRow broken since #692?

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#705]
@BalusC   
In our application, we upgraded from version 3.13.3 to 3.13.4 and now the updateRow function does not work anymore.   
I tried to run 3.13.4 with a snapshot from PrimeFaces from the 23.06.2022 and with one from the 25.08.2022 and it is still the same.

renderIds with version 3.13.3 (working correctly)
- edit:batchtable:1:libraryPooledrequiredField
renderIds with version 3.13.4:
- edit:j_idt630:batchtable:1:libraryPooledrequiredField

![omnifaces_3_13_3](https://user-images.githubusercontent.com/60141928/186767471-6cdc3e0d-c6fe-4d0c-9224-59a4602ccff3.png)
![omnifaces_3_13_4](https://user-images.githubusercontent.com/60141928/186767476-75af88cd-05df-4c9a-a8ad-eaacd9ef16c0.png)

Is this probably due to https://github.com/omnifaces/omnifaces/commit/dc0315e34aaf36b5c5bf6230c766cd0855d7d344?

_Originally posted by @MatthiasScherrerFGCZ in https://github.com/omnifaces/omnifaces/issues/692#issuecomment-1227759149_

**Comment by BalusC** [comment]
Norepro in https://showcase.omnifaces.org/utils/Ajax

Can you please provide the smallest possible reproducer for this? Just providing self-containing contents of `<h:body>` as XHTML code and a CDI managed bean class as Java code is sufficient.

**Comment by BalusC** [comment]
I took a second look at the code and realized that this will indeed break when the parent of the table is not a naming container.

**Comment by MatthiasScherrerFGCZ** [comment]
> I took a second look at the code and realized that this will indeed break when the parent of the table is not a naming container.

Thanks for fixing it. When will this fix be released for version 3.13.4?

**Comment by BalusC** [comment]
3.13.4 is already released. The next version will be 3.14.
