### ISSUE TITLE
ServiceWorker breaks ViewScope

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#707]
Hi, I'm testing OmniFaces PWA functions. I discovered a strange behavior: the service worker causes the ViewScope to break.
What happens: I have a faceletes page which references a bean annotated with @ViewScoped . I fire an Ajax event on the page. Then:

- if the service worker is not on the page, the post construct method is **not** called (correct behaviour)
- if the service worker is on the page, the postconstruct is called and a new instance of the bean is created

I checked with developer tools and this is what happens after firing the ajax event without service worker:
![without-serviceworker](https://user-images.githubusercontent.com/18428155/189941477-de701c1e-6f25-4ae2-8f6c-1a5b5755c55f.jpg)
and with serviceworker:
![with-serviceworker](https://user-images.githubusercontent.com/18428155/189941495-308e41d7-a98a-48b1-81f0-45b6beb898c9.jpg)

The webapp uses Mojarra 3.0.2 with Omnifaces 4.0-M17 and runs on Tomcat 10.0.16 and Java 11
Let me know if I can provide additional informations.

**Comment by BalusC** [comment]
Norepro.

Do you have any non-default context params in web.xml?

**Comment by BalusC** [comment]
I've added an integration test for this use case.

**Comment by NicolaIsotta** [comment]
I'll try to create a reproducer

**Comment by BalusC** [comment]
How's it progressing?

**Comment by NicolaIsotta** [comment]
Hi, here's the sources of a reproducing project:
[test-view-scope.zip](https://github.com/omnifaces/omnifaces/files/10269354/test-view-scope.zip)
To reproduce, build with maven and deploy the war to Tomcat 10+ (I use 10.1.2)
The navigate to `/test-view-scope/test` and change the select value: every time an ajax request is made, a new bean is created (check the system out logs)

I've not tested with other AS since we only use Tomcat, but I try to create a jetty profile if needed.

**Comment by BalusC** [comment]
I see what you're getting at. Technically speaking, the view scope is not broken. 

Adjust your `Test` bean as follows:
```
@Named
@ViewScoped
public class Test implements Serializable {

	private String value;

	@PostConstruct
	public void postConstruct() {
		System.out.println("postConstruct: " + hashCode() + ", referrer: " + Faces.getReferrer());
	}
	
	public String getValue() {
		return value;
	}
	
	public void setValue(String value) {
		System.out.println("setValue: " + hashCode());
		this.value = value;
	}

}
```
And adjust your test form as follows:
```
<h:form id="form1">
	<p:selectOneMenu id="myMenu" value="#{test.value}">
		<f:selectItem itemValue="A" itemLabel="A"/>
		<f:selectItem itemValue="B" itemLabel="B"/>
		<p:ajax update="@form" />
	</p:selectOneMenu>
	#{test.hashCode()}
</h:form>
```
You'll see that the same view scoped bean instance (hashcode) is being reused across postbacks from the test page.

Another instance of the view scoped bean is only recreated during GET requests from sw.js which merely check if it's online or offline. This can in turn indeed be improved. It shouldn't have been necessary at all to build and render the view including all associated beans. I'll improve the sw.js on this.

**Comment by BalusC** [comment]
I've fixed it. Thank you very much for reporting this issue and making your issue clear with the reproducer.
