### ISSUE TITLE
Enhancement: Case-insensitive URLs with FacesViews

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#712]
Hi,

I think it would be good to have case-sensitivity removed from URLs:
ex: `https://xxx.org/MyWebSite` would map to `/mywebsite.xhtml`

What do you think?

**Comment by BalusC** [comment]
Not by default (violates URL spec and triggers SEO penalization), but definitely doable as configuration option.

**Comment by lprimak** [comment]
Ok thanks, config option would be great. The use case is to have camel case file names but not necessary the URLs. Actually urls could be all lower case in my specific use case.

**Comment by BalusC** [comment]
> Actually urls could be all lower case in my specific use case

This makes actually much more sense.

**Comment by BalusC** [comment]
I added a `org.omnifaces.FACES_VIEWS_LOWERCASED_REQUEST_URI` boolean context param to enable this.

**Comment by lprimak** [comment]
thank you!!!
