### ISSUE TITLE
SelectItemsIndexConverter: Update list in request

### ISSUE THREAD

**Issue by Rawi01** [omnifaces/omnifaces#713]
If I use SelectItemsIndexConverter together with a PrimeFaces SelectOneMenu and update the list in an action the converter cannot convert the new items in the first request.

I tried to figure out why this happens and I think it is related to the cache used in the converter. PrimeFaces calls the `getAsString` in an early phase which fills the cache with the old values. During rendering these values are still in the cache and it returns an empty string for new list values. I think that this can be fixed by adding the phase id to the cache key or cleaning it up somehow. The problem does not occur if I use a normal `h:selectOneMenu`.

**Demo:**
```html
<!DOCTYPE html>
<html lang="de" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:o="http://omnifaces.org/ui" xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:p="http://primefaces.org/ui">
	<h:head />
	<h:body>
		<h:form>
			<p:selectOneMenu converter="omnifaces.SelectItemsIndexConverter" value="#{converterTest.value}">
				<f:selectItems value="#{converterTest.values}" var="v" itemLabel="#{v}" />
			</p:selectOneMenu>
		
			<h:commandButton value="submit" action="#{converterTest.submit()}">
				<f:ajax execute="@form" render="@form" />
			</h:commandButton>
			
			<h:messages />
		</h:form>
	</h:body>
</html>
```
```java
@ViewScoped
@Named
@Getter
@Setter
public class ConverterTest implements Serializable {
	private List<String> values;
	private String value;
	
	@PostConstruct
	public void init() {
		values = List.of("A", "B", "C");
	}
	
	public void submit() {
		values = List.of("D", "E", "F");
		Messages.addGlobalInfo("Value = {0}", value);
	}
}

```
After load:
![grafik](https://user-images.githubusercontent.com/5850477/192552685-31f37219-4836-421f-929f-c67867ab0b78.png)
After first submit:
![grafik](https://user-images.githubusercontent.com/5850477/192552764-9c9c6785-98a5-418f-8076-f25d61ed6c2c.png)
![grafik](https://user-images.githubusercontent.com/5850477/192553580-292b20e6-4f08-4040-af50-44bfbeba556f.png)
After second submit:
![grafik](https://user-images.githubusercontent.com/5850477/192552834-287c7bcb-b8ce-48fd-98b1-464a195ae0f0.png)
After third submit:
![grafik](https://user-images.githubusercontent.com/5850477/192552884-08682c0f-ef9c-42be-99d5-f18a63163db2.png)

**Comment by BalusC** [comment]
> I think that this can be fixed by adding the phase id to the cache key

Makes total sense.
