### ISSUE TITLE
lower case request URI is broken with the latest commit

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#714]
Hi,

Unfortunately https://github.com/omnifaces/omnifaces/commit/ba438f5c019bb8e82c48ed1c5e1c43dcbabddc49 broke things in #712 :)

Currently if the xhtml file is already lower-case, it is inaccessible.

i.e. `src/main/webapp/mypage.xhtml` is not accessible via `https://site.com/app/mypage` (or at all)
however, if I rename it to `src/main/webapp/myPage.xhtml`, it's accessible

Thank you

**Comment by BalusC** [comment]
Ay. That slipped through badly. Will take a look later.
