### ISSUE TITLE
"Failed to find a valid digest in the 'integrity' attribute"

### ISSUE THREAD

**Issue by seinecle** [omnifaces/omnifaces#717]
JSF 12.0.0, Omnifaces 4.0

Console message when loading the page of a JSF app:

test.nocodefunctions.com/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'https://test.nocodefunctions.com/jakarta.faces.resource/eNorKMrMTU1LTE4ttkrOzy3Iz0vNKynWSy4urilAyBQnF-Xn5BQk5qXm6COxwcqAWD-5tLgkPxfEBQD_ZR_W.css.html?ln=omnifaces.combined&v=1668520920100' with computed SHA-384 integrity 'Buwu71xC8HXqxJZgUtZq8f3qNxY9ZLZnZaDloRIFjM4ZrbVS1cD9sl3AB/plpwC0'. The resource has been blocked.

I see [another issue](https://github.com/omnifaces/omnifaces/issues/660) that seems to discuss a related manner. I hope this report helps.

**Comment by BalusC** [comment]
JSF 12.0.0 doesn't exist. Did you mean to say PrimeFaces? If so, does it work without PrimeFaces?

The "another issue" link isn't a bug but a feature request to get this implemented.

A minimal reproducer is helpful.

**Comment by melloware** [comment]
@stolp ran into something similar even though I am using this feature in production just fine.

To solve it you can turn off `SRI` for now with this in your web.xml

```xml
<context-param>
        <param-name>org.omnifaces.COMBINED_RESOURCE_HANDLER_CROSSORIGIN</param-name>
        <param-value>use-credentials</param-value>
    </context-param>
```

But a reproducer would be helpful so we can debug.

**Comment by BalusC** [comment]
It can theoretically happen if something else between writing the response body and the receiving in the client side has modified the response body in such way that the SRI gets invalidated. E.g. trimming or changing the whitespace via a servlet filter or even via proxy/server itself. This problem is in turn beyond reach of OmniFaces.

**Comment by seinecle** [comment]
I meant PF 12.0.0 indeed. As I had issues with the css of my page, this error / warning msg was the only trace visible in the console so I reported it here. Turns out there is no relation.

**Comment by klaros-testmanagement** [comment]
@melloware Thanks for pointing me here.
@BalusC Thanks for the explanation, this at least gives a hook to start searching. In my case I can rule out proxies, yet there a plenty of filters to look for.

Am I getting that right, that the combined resources handler thus effectively forbids manipulation of the response body in filters? Would that include adding/changing header parameters?

**Comment by stolp** [comment]
Sorry for the change of persona - wrong account.

@melloware Thanks for pointing me here.
@BalusC Thanks for the explanation, this at least gives a hook to start searching. In my case I can rule out proxies, yet there a plenty of filters to look for.

Am I getting that right, that the combined ressources handler thus effectively forbids manipulation of the response body in filters? Would that include adding/changing header parameters?

**Comment by BalusC** [comment]
> Am I getting that right, that the combined ressources handler thus effectively forbids manipulation of the response body in filters?

No. It's the SRI who forbids that.

**Comment by melloware** [comment]
@stolp once the integrity hash is calculated if you change even 1 byte of the JS or CSS that the hash was calculated for the integrity is violated and the browser assumes a "man in the middle" attack has changed the code in between your server and the client.

**Comment by klaros-testmanagement** [comment]
Ok. So my understanding is, that in this case only a non-JSF related filter entry in web.xml might be causing this.

**Comment by melloware** [comment]
@seinecle i think this ticket is safe to close right?

**Comment by seinecle** [comment]
Yes indeed, thx !
