### ISSUE TITLE
Numbers.formatBytes() ignores Locale

### ISSUE THREAD

**Issue by matinh** [omnifaces/omnifaces#721]
According [to its JavaDoc ](https://omnifaces.org/docs/javadoc/4.0/org/omnifaces/el/functions/Numbers.html#formatBytes(java.lang.Long)) the method `Numbers.formatBytes()` should use the Locale obtained from `Faces.getLocale()`:

> The format locale will be set to the one as obtained by [Faces.getLocale()](https://omnifaces.org/docs/javadoc/4.0/org/omnifaces/util/Faces.html#getLocale()).

This is actually done in
https://github.com/omnifaces/omnifaces/blob/54c3bfa12bb8244bdc075ecf8b8183e5b85efa8b/src/main/java/org/omnifaces/el/functions/Numbers.java#L255-L260
However, the formatter is only used for parsing, not for formatting!

The actual formatting happens a few lines below via `toString()`  https://github.com/omnifaces/omnifaces/blob/54c3bfa12bb8244bdc075ecf8b8183e5b85efa8b/src/main/java/org/omnifaces/el/functions/Numbers.java#L273-L274

So while `formatNumber()` correctly respects Locale, `formatBytes()` ignores it. On a facelet using these functions, this would result in the following output with locale "de_DE":

```
formatBytes(): 1.5 KiB
formatNumber(): 1567,00 
```

I tested this all with OmniFaces 3.13.4 but it seems the code is still identical in trunk.

**Comment by BalusC** [comment]
Improved the unit test, fixed it and while at it also spotted an existing bug that formatBytes(1023) incorrectly returned "1023.0 B" in contrary to what the Javadoc says, it must be "1023 B".

Thank you very much for reporting the issue and improving OmniFaces!
