### ISSUE TITLE
UnmappedResourceHandler broken in Jakarta EE 10 (Regression)

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#722]
Hi,

I just tried to upgrade my app from EE 8 to EE 10 and without `UnmappedResourceHandler` everything works (except for bits that depend on `UnmappedResourceHandler` but when I add it back into faces.xml, none of the resources load, I get 404 not found errors.

**Comment by lprimak** [comment]
For now, I don't have any more information, just noticed this while trying my app.

**Comment by BalusC** [comment]
Did you edit the mapping URL pattern in web.xml as documented?

**Comment by lprimak** [comment]
Ah no :). Will try that

**Comment by lprimak** [comment]
Compiler was pulling in `javax.*` at compile time instead of runtime :) 
Thanks for the help!
