### ISSUE TITLE
Utils.fromTemporalToZonedDateTime not working today with YearMonth.of(2023, 2)

### ISSUE THREAD

**Issue by jllado** [omnifaces/omnifaces#723]
Hi,

Today we are suffering an issue with of:formatDate when yearhMonth value is YearMonth.of(2023, 2):
#{of:formatDate(yearMonth,"MMM yyyy")}

Checking Utils.fromTemporalToZonedDateTime, I see you are using now.getDayOfMonth() for temporals without DAY_OF_MONTH.

And today the method is throwing a java.time.DateTimeException: Invalid date 'February 29' as '2023' is not a leap year

Thanks

**Comment by BalusC** [comment]
Fixed, thank you very much for reporting!
