### ISSUE TITLE
Support ETag in Faces.sendFile

### ISSUE THREAD

**Issue by fabrii** [omnifaces/omnifaces#724]
Hi! Long time user of OmniFaces. Thanks for this amazing library.

I wanted to know if it is possible to support ETag (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) when downloading files, so we can use the browser cache without firing the download every time. This is useful for files that do not change often.

Thanks!

**Comment by BalusC** [comment]
Point taken but that does unfortunately not help because sendFile is invoked by POST.

You might want to consider FileServlet instead if your application logic allows the file to be downloaded by GET: https://showcase.omnifaces.org/servlets/FileServlet

**Comment by fabrii** [comment]
The problem with FileServlet is security right? Anyone can trigger the download of protected files.

Thanks for your response.

**Comment by BalusC** [comment]
You can set its url pattern to the already restricted folder, or to add its url pattern to the web.xml security constraints, or to the set of restricted urls, depending on how you authenticate users.

E.g. if your app already restricts access to `/private/*` then set its url pattern to e.g. `/private/downloads/*`, or if you want to map it to `/downloads/*`, then just add `/downloads/*` to where you already have configured `/private/*`.
