### ISSUE TITLE
o:inputHidden allow readonly and still validate

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#730]
Based on this question: https://stackoverflow.com/questions/17625239/why-is-inputhidden-readonly-attribute-not-in-jsf-documentation

**Proposal**

Hidden input component that performs validation on submit but does not need a setter (or wont invoke it). Its more a validation of static data to remove the manual need to validate this data in the java code.

	<h:inputHidden label="Bank account" value="#{bean.bankAccount.id}" readonly="true" required="true"/>

or even more usefull in case validation data is nested:

	<h:inputHidden label="Bank account" value="#{bean.bankAccount eq null ? null : bean.bankAccount.id}" readonly="true" required="true"/>

**Use case**

In our order wizard UI the user can select different payment methods. Certain payment methods need additional data which is independent of the current order such as user bank account, address or confirmed direct debit mandate. This data is more related to the user profile data and in the order process its just a usability shortcut.

**Why use `h:inputHidden`?** 

PrimeFaces wizard automatically validates all input fields if user clicks next to advance to next step and on failure user stays on the current step which is very useful. Else we need to do this in the java code `flow process` method:

- validate
- post `FacesMessage`
- prevent next step

**Current workaround**

_Bean_

	/* check if user saved bank account */
	public Boolean getBankAccountValid()
	{
		return this.bankAccount != null and this.bankAccount.getId() != null ? true : null;
	}

	/* dummy setter ... */
	public void setBankAccountValid(final Boolean bankAccountValid)
	{

	}

_Markup in wizard_

	<h:inputHidden id="bankAccountValid" label="Bank account" value="#{bean.bankAcountValid}" required="true"/>
	
		 		
	<p:button id="btnDialog"/>

_Related RequiredCheckboxValidator_

In this example i needed a nullable `Boolean` to enforce the `required` in the markup. I thought about using omnifaces `RequiredCheckboxValidator` but this is strict only for `UISelectBoolean` but could have been used in this case aswell.

**Comment by BalusC** [comment]
Makes sense.

**Comment by djmj** [comment]
Thanks for the implementation. Looking forward to use it since lately we had a few other cases for this:

- use `p:dataTable` to select data and use a hidden input on selection count property to make selection required
- a property which is populated automatically from bean and just shown as a readonly input. But if its missing it indicates a "wrong configuration" and user cannot proceed.

**Comment by djmj** [comment]
Hi Balus,

is there a chance you port this to _3.14.x_ branch? We are still at java 8.

best regards
Marco

**Comment by BalusC** [comment]
It's a new attribute so it should basically end up in 3.15. 
Since release of 4.0 the 3.x went into maintenance mode.
