### ISSUE TITLE
Beans.getInstance(String name) fails with NPE if bean is not found / misspelled

### ISSUE THREAD

**Issue by lprimak** [omnifaces/omnifaces#734]
I believe it should return `null` instead of at least throw a proper exception

Version 3.14.1 stack trace:
```
java.lang.NullPointerException: Cannot invoke "javax.enterprise.inject.spi.Bean.getScope()" because "bean" is null
	at org.omnifaces.util.BeansLocal.getInstance(BeansLocal.java:128)
	at org.omnifaces.util.BeansLocal.getInstance(BeansLocal.java:145)
	at org.omnifaces.util.Beans.getInstance(Beans.java:243)
```

**Comment by BalusC** [comment]
Makes sense.

**Comment by jepsar** [comment]
Hmm.. why return `null`? This will just move the NPE. The user should be aware that `null` can be returned and deal with that. An `Optional` would be better IMO. As that will be a breaking change I'm +1 on a better exception (message).

**Comment by BalusC** [comment]
Other `getInstance()` methods already return `null` if bean couldn't be found. This one was overlooked.

**Comment by BalusC** [comment]
If you want Optional, I can always add `findXxx()` methods delegating to `getXxx()`.

**Comment by lprimak** [comment]
Null is fine with me!  It's consistent with what other methods are doing.
Thank you
