### ISSUE TITLE
web app manifest should use .webmanifest extension

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#736]
Currently, the web manifest generated extending `WebAppManifest` can be reached using .json extension: `#{resource['omnifaces:manifest.json']}`
[According to W3C](https://w3c.github.io/manifest/#media-type-registration), the recommended extension is .webmanifest
I can provide a PR if needed.

**Comment by melloware** [comment]
I would submit a PR to review against the lowest branch you want this fix in.  Then they can decide to merge it and they will handle promoting it up the chain !

**Comment by BalusC** [comment]
True but do 4.x when the change is not backwards compatible. Else you'll need to support both.

**Comment by NicolaIsotta** [comment]
I was trying to build 3.x locally but it fails because of MultiViews IT:
```
Failures: 
  MultiViewsIT.testSubfolder:82->verify200:164 expected: <subfolder/MultiViewsIT> but was: <MultiViewsIT>
```
Is this caused by something wrong in my setup? My JDK is Adoptium jdk-8.0.322.6-hotspot

**Comment by BalusC** [comment]
No idea. Works fine for me and in [CI](https://github.com/omnifaces/omnifaces/actions). Do `-Dmaven.test.skip=true` for now.

**Comment by BalusC** [comment]
I added it to 4.2.
