### ISSUE TITLE
ValidateBean: Support for when a component's value expressions is bound to a container of the violated property

### ISSUE THREAD

**Issue by blutorange** [omnifaces/omnifaces#737]
### Problem

`o:validateBean` now supports nested properties (#247), which is great. This is done by inspecting the property nodes returned by the call to the bean validator in order to resolve the base object and the property being accessed on that base. Then, `o:validateBean` looks in the component tree for an `UIInput` with a value expression binding that matches the base and the property.
 
Recently, somebody added a piece of code to our code base where this behavior is still not quite enough. When the value expression of a component does not bind to a leaf node in the object graph to validate, but to some container object, the current approach cannot find the `UIInput`, as it only looks for the last property.

### Example

This might sound a bit cryptic, so let me explain with an example (simplified, but from a real world use-case, where `MyBean` actually has a `List<Model>`):

Java

```java
public class Descriptor {
  public Descriptor() {}
  public Descriptor(String type, String name) { this.type = type; this.name = name; }
  @NotEmpty private String name;
  @NotEmpty private String type;
  // getters and setters
}

public class Model {
  @Valid @NotNull private Descriptor descriptor = new Descriptor("json", null); 
  @NotEmpty private String lhs;
  @NotEmpty private String operator;
  @NotEmpty private String rhs;
  // getters and setters
}

@ViewScoped @Named
public class MyBean {
  @Valid private Model model;
  // getters and setters
  public List<Descriptor> findDescriptors(String query) {
    // some logic to find a list of available options...
    return List.of(new Descriptor("foobar", query));
  }
}

// For illustration, this uses simple string concatenation
@FacesConverter(forClass = Descriptor.class, value = "DescriptorConverter")
public class DescriptorConverter implements Converter<Descriptor> {
  @Override
  public Descriptor getAsObject(FacesContext context, UIComponent component, String value) {
    var index = value != null ? value.indexOf("_") : -1;
    // Default to type="json" when the user entered a value manually instead of selecting an existing one
    return index >= 0 ? new Descriptor(value.substring(0, i), value.substring(i+1)) : new Descriptor("json", value);
  }

  @Override
  public String getAsString(FacesContext context, UIComponent component, Descriptor value) {
    return value != null ? value.getType() + "_" + value.getName() : null;
  }
}
```
View:

```xml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:o="http://omnifaces.org/ui" xmlns:p="http://primefaces.org/ui">

<h:form>
  <xi:validateBean value="#{myBean.model}" showMessageFor="@violating" method="validateActual"/>

  <p:autoComplete id="input" forceSelection="false"
	value="#{myBean.model.descriptor}"
        var="desc"
	itemValue="#{desc}"
	itemLabel="#{desc.name}"
        converter="DescriptorConverter"
        dropdown="true"
	queryDelay="1000"
	autoHighlight="true"
	completeMethod="#{myBean.findDescriptors}">
    <p:column>
        <div>
            <i class="icon-#{desc.type}"></i>
            <span>#{desc.name}</span>
        <div>
    </p:column>
  </p:autoComplete>

  <!-- More UI that makes use of myBean.model.lhs etc. -->

</h:form>
</ui:composition>
```

The important bit here is the value expression for the PrimeFaces AutoComplete component: `"#{myBean.model.desc}"`. The user does not need to select an existing autocomplete option, they can enter the name manually. When they leave the name empty, bean validation fails as expected, producing a `ConstraintViolation` with the property path 

> [model, descriptor, name]

`o:validateBean` now [looks for](https://github.com/omnifaces/omnifaces/blob/b0fd8acfbbb79758e732c91b6c6e0ce86f4f8aad/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L605) a `UIInput` with a `value=#{some.thing.descriptor.name}` binding, with a `Descriptor` instance as the base. But it does not find one, the autocomplete is bound to the `descriptor` property of `Model`, where `Model` is the base. So in the example above, the validation error is not shown on the autocomplete component.

### Possible solution

One solution I can think of: Instead of looking only at the base and the final property from the violation, when no matching input is found, also look for `UIInput`s bound to non-final properties.

E.g. if the property path from the constraint violation is

> [p1, p2, p3, ..., p(n-1), pn]

Currently, [the code](https://github.com/omnifaces/omnifaces/blob/b0fd8acfbbb79758e732c91b6c6e0ce86f4f8aad/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L600-L612) resolves `base=p(n-1)` and `property=pn`, and then looks for an input with that base and property. If none is found, it could also look for `base=p(n-2)` and `property=p(n-1)` etc. At least in our case I could verify that this approach works well and `validateBean` finds the corresponding `UIInput`.

I also think this could be done in a performant manner, `Validators.resolveViolatedBase` already traverses all intermediate values, so if performance is an issue, this would only have to be done once; and then it might be possible to only traverse the component tree once as well.

**Comment by BalusC** [comment]
Implemented with IT.

**Comment by BalusC** [comment]
https://github.com/omnifaces/omnifaces/actions/runs/4271090600/jobs/7435315227

It's failing with BVal in TomEE. I'll have to look closer later.
