### ISSUE TITLE
NullPointer Exception on startup after upgrade from 3.6 to 3.14.1

### ISSUE THREAD

**Issue by crichtonibm** [omnifaces/omnifaces#738]
ApplicationInitializer.onStartup changed to use Platform.getDefaultFacesServletMapping(servletContext); over the past few years:  https://github.com/omnifaces/omnifaces/commit/3a61214f6e8295203147d00772e114f59e14607b

https://github.com/omnifaces/omnifaces/blob/3.x/src/main/java/org/omnifaces/util/Platform.java

That in turn will call getFacesServletRegistration, which gets an error in an old app I support which does NOT specify a servlet class (yup, jsp-file in web.xml). 

Anyway, the check in getFacesServletRegistration is done against registration.getClassName(), which is null in that case. 
A simple flopping of the equals check would fix this 

```
	public static ServletRegistration getFacesServletRegistration(ServletContext servletContext) {
		ServletRegistration facesServletRegistration = null;

		for (ServletRegistration registration : servletContext.getServletRegistrations().values()) {
			if (registration.getClassName().equals(FacesServlet.class.getName())) {
				facesServletRegistration = registration;
				break;
			}
		}
		return facesServletRegistration;
	}
```
Any fixes being done against 3.x stream?

**Update**: I did add `<servlet-class></servlet-class>`, after the jsp-file value, and while I got validation errors, it did set an empty string class, so side stepped the issue. Works for Liberty anyway.

**Comment by BalusC** [comment]
Fixed in 2.x and onwards. Thank you for improving OmniFaces!

**Comment by melloware** [comment]
@BalusC any chance we can get OmniFaces release soon?  Lots of fixes have been made the last few months!

**Comment by BalusC** [comment]
It's indeed about time.
