### ISSUE TITLE
Can't use new line as delimiter for omnifaces.ToCollectionConverter

### ISSUE THREAD

**Issue by dangnhdev** [omnifaces/omnifaces#739]
Please check the [ToCollectionConverter.java](
https://github.com/omnifaces/omnifaces/blob/4.x/src/main/java/org/omnifaces/converter/ToCollectionConverter.java#L119) file in the omnifaces repository, specifically to line 119 of the code. The current implementation use `.trim()` method at this line is causing an issue, as it is not allowing the use of a new line as a delimiter for the ToCollectionConverter.

The use of a new line as a delimiter is particularly useful in cases where the user's input has been copied from a spreadsheet or entered into a text area, where each line represents a distinct value. Therefore, it is recommended that the .trim() method be modified to allow for the use of new lines as delimiters.

**Comment by BalusC** [comment]
You're right. The delimiter itself should not be trimmed. Fixed now.

Thank you for reporting the issue and improving OmniFaces!
