### ISSUE TITLE
Feature - add UIParameter/Param utility function

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#74]
I am using following function to add a new parameter to a component. Maybe its usefull for others. 

**Use cases**

Creating primefaces menu programmatically. They have no distinction between markup and java and so each param must be added programmatically to dynamic menues.

**Code**

A version with `ParamHolder` as argument is also a good idea.

	/**
	 * Adds a new parameter to the given component using the provided name and value.
	 *
	 * If <code>converter</code> is provided and converted value differs from provided <code>value</code> a omnifaces {@link Param} is used, else JSF {@link UIParameter} is used.
	 *
	 * @param component Component to add the parameter to.
	 * @param name Name of the parameter
	 * @param value Value of the parameter
	 * @param converter Optional converter to add.
	 */
	public static void addParam(final UIComponent component, final String name, final Object value,
		final Converter converter)
	{
		if (component == null)
			throw new IllegalArgumentException("Component must not be null.");

		if (name == null || name.trim() == "" || value == null)
			return;

		UIParameter parameter = null;

		if (converter != null)
		{
			// JSF mojarra bug - jsf appends null query parameters
			final Object convertedObj = converter.getAsString(FacesContext.getCurrentInstance(), component, value);
			if (convertedObj == null)
				return;

			// check if converter necessary
			if (!value.equals(convertedObj))
			{
				final Param param = new Param();
				param.setConverter(converter);
				parameter = param;
			}
		}

		if (parameter == null)
			parameter = new UIParameter();

		parameter.setName(name);
		parameter.setValue(value);
		component.getChildren().add(parameter);
	}

I was not sure if method should return on `value == null`, maybe for strange reasons someone want to convert `null` to something meaningful.
Also not sure wether the optimization `if (!value.equals(convertedObj))` is not just too much.

**Comment by BalusC** [comment]
I'd rather not let OmniFaces advocate programmatic component creation. Use XHTML instead.

**Comment by djmj** [comment]
I prefer XHTML also, but primefaces menu-model lacks binding support why programmatic workarounds are needed. 

I see your point to reject this.
