### ISSUE TITLE
Improve primefaces ajax request detection to support component inheritance

### ISSUE THREAD

**Issue by didiez** [omnifaces/omnifaces#742]
Related issues #664, #627, #630

The current approach to detect whether a request is a PrimeFaces ajax request does not work when the component triggering the request is a custom component extending a primefaces component, as it only checks the `org.primefaces` package namespace matches the package of the component class.

```java
package es.didiez.component;

public class CustomCommandButton extends org.primefaces.component.commandbutton.CommandButton {
  ...
}
```

It would be great if the following method could cover also this case (component inheritance)
https://github.com/omnifaces/omnifaces/blob/37136eadecae37e06831df4d2972f20173c2eb38/src/main/java/org/omnifaces/util/Hacks.java#L392

**Comment by BalusC** [comment]
Thank you. I wanted it in 2.x and 3.x too, so I've fixed it in 2.x via https://github.com/omnifaces/omnifaces/commit/5ecf5d5772bda3be9328aa379ffe0a060391dd1a and then merged onwards into 3.x and 4.x.
