### ISSUE TITLE
Manifest not detected in Quarkus-Omnifaces extension

### ISSUE THREAD

**Issue by felipelx07** [omnifaces/omnifaces#749]
I've configured the PWAResourceHandler on my Quarkus + Myfaces Application but the manifest.json can't be detected. 
I debug the code and see the manifest generating the file.  But the manifest is not recognized. 
<img width="958" alt="image" src="https://user-images.githubusercontent.com/5168904/233116496-6e5235ac-6bdb-4dbc-9596-7a80dc649a4b.png">

Quarkus: 2.16.3.Final
Quarkus-Omnifaces: 3.14.3 

Someone can help ?

**Comment by felipelx07** [comment]
Quarkus Omnifaces is a extension from QuarkiVerse and it has some included libs like (Omnifaces, Myfaces and some others): 
https://quarkus.io/extensions/io.quarkiverse.omnifaces/quarkus-omnifaces

**Comment by melloware** [comment]
Yep I will look.

**Comment by felipelx07** [comment]
Thanks @melloware! I forgot to specified but i'm using Java 19.

**Comment by melloware** [comment]
I think I fixed it on the Quarkus side so you can close this ticket once you verify my fix works.

**Comment by felipelx07** [comment]
Its work! Thank you
