### ISSUE TITLE
PWA: No CacheableViewIds should log warning

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#751]
Attached is reproducer run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

If for some reason your have NO `<welcome-list>` files or anyt other reason is generates the manifest but NOT a Sevriceworker sw.js link on the page.  I have a project that has no welcome files and I was stumped why the sw.js was not being added to the page until I debugged.

I think a warning like "No cacheable view ids found so ServiceWorker will not be used." or something like that so a user knows why the sw.js is not on the page.   I debugged this longer than I should have. 😄 

```java
	@Override
	public Collection<String> getCacheableViewIds() {
		return Collections.emptyList();
	}
```

Reproducer: 
[o751.zip](https://github.com/omnifaces/omnifaces/files/11333399/o751.zip)

**Comment by BalusC** [comment]
Fixed for 3.14.3 and 4.2, thank you very much for reporting!
