### ISSUE TITLE
PWA: Invalid CacheableViewId should log error or throw error

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#752]
Attached is reproducer run `mvn clean jetty:run` and navigate to http://localhost:8080/primefaces-test/

I accidentally had `index.html` instead of `index.xhtml` which was subtle and the sw.js was throwing a 404 Not Found and I could not figure out why and I wasn't seeing any errors in the log.

![image](https://user-images.githubusercontent.com/4399574/234593777-4ca7c400-9b34-4bc7-a0b2-58f8ff2a3f27.png)

I was using Jboss EAP 7.4 and found no errors in the logs although Jetty is sending `java.lang.IllegalStateException: cannot set buffer size after response is in committed state` which didn't tell me what the issue was.

```java
	@Override
	public Collection<String> getCacheableViewIds() {
		return Arrays.asList("invalid-file.xxx");
	}
```

Reproducer: 
[O752.zip](https://github.com/omnifaces/omnifaces/files/11333496/O752.zip)

**Comment by BalusC** [comment]
Fixed for 3.14.3 and 4.2, thank you very much for reporting!
