### ISSUE TITLE
Adding @Param to a Quarkus 3 project fails with jakarta.enterprise.inject.UnsatisfiedResolutionException 

### ISSUE THREAD

**Issue by zeppelinux** [omnifaces/omnifaces#753]
Adding @Param (any type) to a bean in Quarkus 3 project fails with:

Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.lang.String and qualifiers [@Param]
        - java member: com.diligesoft.collarclub.jsf.view.CreateAccountWizard#step
        - declared on CLASS bean [types=[java.io.Serializable, com.diligesoft.collarclub.jsf.view.CreateAccountWizard, java.lang.Object], qualifiers=[@Default, @Any, @Named("createAccountWizard")], target=com.diligesoft.collarclub.jsf.view.CreateAccountWizard]
        The following beans match by type, but none have matching qualifiers:
                - Bean [class=java.lang.String, qualifiers=[@Cookie, @Any]]
                - Bean [class=java.lang.String, qualifiers=[@ConfigProperty, @Any]]
                - Bean [class=java.lang.String, qualifiers=[@Any, @Claim("")]]
                - Bean [class=java.lang.String, qualifiers=[@Any, @ContextParam]]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:482)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:564)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:293)
        ... 13 more

To reproduce:

1. Check out https://github.com/melloware/quarkus-faces
2. Add @Param to any of the beans
3. mvn clean compile

**Comment by melloware** [comment]
@zeppelinux already explained right here why it won't work: https://github.com/quarkiverse/quarkus-omnifaces/issues/3

I would subscribe to that ticket and close this one.

**Comment by zeppelinux** [comment]
@melloware I missed that one, makes sense. Thanks!

**Comment by melloware** [comment]
This is fixed in Quarkus OmniFaces 4.5.1.1 when released.
