### ISSUE TITLE
Upgrade from 4.0.1 to 4.1 does not work

### ISSUE THREAD

**Issue by tuerker** [omnifaces/omnifaces#756]
Upgrading the omnifaces dependency from 4.0.1 to 4.1 in my PrimeFaces 13.0.0.-SNAPSHOT based web application breaks with the following output:

```
[2023-05-15T13:42:26.297+0200] [Payara 6.2023.3] [SEVERE] [] [javax.enterprise.system.core] [tid: _ThreadID=222 _ThreadName=admin-thread-pool::admin-listener(6)] [timeMillis: 1684150946297] [levelValue: 1000] [[
  Exception while loading the app : CDI deployment failure:WELD-000163: Non-unique bean deployment identifier detected: 
  - BeanDeployment [beanDeploymentArchiveId=root_xxx-1.0-SNAPSHOT.war],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war/WEB-INF/lib/omnifaces],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war/WEB-INF/lib/omnifaces] -- WELD-000163: Non-unique bean deployment identifier detected: 
  - BeanDeployment [beanDeploymentArchiveId=root_xxx-1.0-SNAPSHOT.war],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war/WEB-INF/lib/omnifaces],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war],
  - BeanDeployment [beanDeploymentArchiveId=xxx-1.0-SNAPSHOT.war/WEB-INF/lib/omnifaces]]]
```

I am running Payara 6.2023.3. I did several mvn clean installs and artefacts rebuilds. Undeployed the previous and redeployed several times. No success.

I am aware that it might be difficult to guess the problem with the given little input. My hope is that you nevertheless have an idea why the upgrade fails? Many thanks in advance.

**Comment by BalusC** [comment]
Hard-delete Payara's deploy, temp and/or cache folders. The previous version is apparently lingering there.

Not an OmniFaces problem, so closing off.

**Comment by melloware** [comment]
Payara = Nightmares.... 😄

**Comment by tuerker** [comment]
> 

> Hard-delete Payara's deploy, temp and/or cache folders. The previous version is apparently lingering there.

That worked. I could have come to this idea, too. Sorry, for this simple question and many thanks for your quick response. Best regards.
