### ISSUE TITLE
Omnifaces 4.1: "Unescaped" ]]> in jsf.js included in AJAX Partial Response when using Omnifaces ViewScoped bean causing eval issue

### ISSUE THREAD

**Issue by crichtonibm** [omnifaces/omnifaces#758]
I am using an Omnifaces ViewScoped bean. Omnifaces calls registerUnloadScript (ViewScopeManager), which in turn calls addFacesScriptResource. Since this is an Ajax request, it is being included as an <eval> script inlined with the ajax response. Unfortunately, the jsf.js has an embedded string with ]]> which is messing things up on the browser side. Tried it with both FF and Chrome and both end up with incomplete code parsing when trying to evaluate the script. The section of the jsf.js code that is failing is shown below

T=D._Lang.hitch(V,V.indexOf),W=T(""),X=T("<[CDATA["),R=T("]]><![CDATA[]]]]><![CDATA[>");if(P(W,U,X,R)){return true;}return W<=U&&X<=R;}  **... continues**

This is where it ends, right at the ]]> which is in the string:

T=D._Lang.hitch(V,V.indexOf),W=T(""),X=T("<[CDATA["),R=T("

This is occurring for me using a fairly recent OpenLiberty with webProfile9.1 (2023-02)

Any suggestion to sidestep?

*FLASH* this is actually an error case, as there was no proper viewstate. I am converting to JSF 3.0 and had previously used @BalusC workaround described here: https://balusc.omnifaces.org/2011/09/communication-in-jsf-20.html#AutomaticallyFixMissingJSFViewStateAfterAjaxRendering
Once I fixed this namspace issue, it was working again.

**Comment by BalusC** [comment]
> had previously used @BalusC workaround described here: https://balusc.omnifaces.org/2011/09/communication-in-jsf-20.html#AutomaticallyFixMissingJSFViewStateAfterAjaxRendering

This work around is not anymore necessary since JSF 2.3. It should work as good without it (the blog has in the meanwhile been clarified on this).

I'll look closer at the script loading error tho, this should not happen.

**Comment by crichtonibm** [comment]
Intersting, as it seems that the viewstate is still not being included in MYFACES JSF 3.0.x as the "hasViewState" check from your workaround is returning false (so not finding the viewstate in the form), and was getting the failure on the postback before I fixed the namespace to be jakarta rather than javax on the viewstate. this is using openliberty feature webProfile-9.1, which is using feature faces-3.0

**Comment by BalusC** [comment]
Hmm, ok that's then probably a bug in MyFaces.

**Comment by melloware** [comment]
Yes @crichtonibm please report to MyFaces here: https://issues.apache.org/jira/projects/MYFACES/issues/MYFACES-4604?filter=allopenissues

**Comment by melloware** [comment]
MyFaces Issue opened: https://issues.apache.org/jira/browse/MYFACES-4605

It looks like it might be fixed in 2.2 and in 4.0 just not in 2.3 or 3.0 they are investigating.

**Comment by BalusC** [comment]
Okay.
