### ISSUE TITLE
Feature request: optional composite component action method expression

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#759]
If you have a composite component with a method attribute:
```
<cc:attribute name="okAction" method-signature="java.lang.String action()"
...
<p:commandButton id="ok" action="#{cc.attrs.okAction}"
```
Then trying to use this component without specifying the `okAction` results in the exception:
`javax.faces.FacesException: Unable to resolve composite component from using page using EL expression '#{cc.attrs.okAction}'`

Perhaps OmniFaces could help here somehow?

https://stackoverflow.com/questions/15420081/jsf2-0-composite-component-with-optional-method-expression

**Comment by BalusC** [comment]
It works for me in Mojarra 2.3.19+ when I just add `default="null"` to the `<cc:attribute>` of the action.
