### ISSUE TITLE
MyFaces ViewState is not removed if <servlet-mapping><url-pattern>*.jsf</url-pattern><..> is used for Faces servlet.

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#762]
`ViewHandlerImpl` in MyFaces converts viewId from request using:
```
String calculatedViewId = getViewHandlerSupport(context).calculateViewId(context, viewId);
```

In my case method `calculateViewId()` converts `hello.jsf` to `hello.xhtml`.  Then the `calculatedViewId=hello.xhtml` is used in for the key of ViewState. 

But the OF's method `Hacks.removeViewState`  gets `viewId` from request (e.g. `hello.jsf'), and it does not convert it using `calculateViewId()`, it uses invalid key and finally it does not destroy the view state.

**Comment by BalusC** [comment]
Fixed. Thank you very much for reporting this issue and improving OmniFaces!
