### ISSUE TITLE
Implement @WindowScoped

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#763]
It would be great to have @WindowScoped in the similar way how it is done in DeltaSpike, with unload feature how it is in OF's @ViewScoped. @WindowScoped beans can be easily shared between iframes, may be even between TABs (with shared=true URL param).

**Comment by melloware** [comment]
@skybber isn't this `@ClientWindowScoped` in Faces 4?

**Comment by skybber** [comment]
Does the spec have function autoclose on TAB close?

**Comment by melloware** [comment]
Not sure. See: https://github.com/jakartaee/faces/issues/1509  they implemented based on delta spike though...

**Comment by skybber** [comment]
Deltaspike implementation does not have autoclose of @WindowScope, however there is some quota restriction in DS. Btw I'm using a trick with OF @ViewScoped bean to close @WindowScoped in DS...

**Comment by melloware** [comment]
The maybe you can make a request to jakarta faces spec to implement your ehanced features since `@ClientWindowScoped` is now part of the spec.

**Comment by melloware** [comment]
Or Maybe @BalusC can just hook in on ViewScoped unload here if using ClientWindowScoped I will leave it up to him!

**Comment by BalusC** [comment]
We can count how many views were created referencing the bean and decrement during unloads and destroy the bean when the count reaches 0. But this essentially makes the URL unreusable when it's referenced in a link of a page which does not directly reference the bean, and this defeats the purpose of this scope.

Personally I've never seen much value in @(Client)WindowScoped and I've also never used these in production. In case of iframes, there are better ways to reference a @ViewScoped bean in parent page of the iframe (commandScript/remoteCommand). Iframes are de-facto deprecated as well.

**Comment by BalusC** [comment]
Closing off. This isn't going to be a winner combination because this will basically leave behind broken links. For the iframe case, use a separate @ViewScoped.
