### ISSUE TITLE
The link to the showcase is broken

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#766]
go to 

https://omnifaces.org/

click on "showcase"

**Comment by BalusC** [comment]
mmm redirect from http to https is broken somehow?

**Comment by BalusC** [comment]
Links have been fixed but leaving ticket open for later investigation because http should really autoredirect to https.

**Comment by pizzi80** [comment]
anyway now it works ;)

**Comment by BalusC** [comment]
http://showcase.omnifaces.org works now. There was a typo in port forwarding rule in depths of iptables. Took a while to figure out :woozy_face:
