### ISSUE TITLE
Components.getCurrentForm and Mojarra 

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#767]
I've found a strange thing about OmniFaces and/or Mojarra (4.1-snapshot) 
which uses the new `faces.js` (which is mine implementation... LOL)

looking at the OmniFaces `Components.getCurrentForm` 
algorithm I'm a bit surprised about the implementation

I'd expect somethings like:

```
return Components.getClosestParent( Components.getCurrentComponent() , UIForm.class );
```

I've debugged a bit and:

with the new `faces.js` the OmniFaces `Components.getCurrentForm` returns null

with the old one (4.0.2) returns the correct UIForm

with `<o:form partialSubmit="true" .. ` it returns the correct form

so basically it's all based on the current form id 
always passed in the xhr payload that in 
the new `faces.js` I'm not passing anymore ...

The questions are: 
1) do I have to pass the current form id even with partial submit from an action with execute="@this" ?
    for example:
```
<h:commandButton action="#{testViewAction.action}" value="Action" >
    <f:ajax execute="@this" />
</h:commandButton>
```

2) why not reimplement the `Components.getCurrentForm` using the " getParent until a UIForm is found?
    In this way it's always possible to find the current form event if the ID it's not in the payload

I hope it's clear enough ...

**Comment by BalusC** [comment]
> the new faces.js I'm not passing anymore ...
> 
> do I have to pass the current form id even with partial submit from an action with execute="@this" ?

Absolutely. This will set among others `UIForm#isSubmitted()` which is part of the public API. I'm surprised there's apparently no TCK for that?

Please fix it in Mojarra side before next release.

> why not reimplement the Components.getCurrentForm using the " getParent until a UIForm is found?
In this way it's always possible to find the current form event if the ID it's not in the payload

I'm not understanding this quesiton. That's already implemented as fallback.

**Comment by pizzi80** [comment]
> Absolutely. This will set among others UIForm#isSubmitted() which is part of the public API. I'm surprised there's apparently no TCK for that?

I run the ajax tests in the past after a review of @arjantijms  

... but now it's not possible to run the test anymore 
because selenium fails to find chrome v114 ... 

> Please fix it in Mojarra side before next release.

Absolutely ;)

> I'm not understanding this quesiton. That's already implemented as fallback.

ok, apparently the fallback does not work if the form ID 
it's not included in the payload...
but it's a non-standard situation like you said, so we can ignore it I think

**Comment by pizzi80** [comment]
I made a new test with **Mojarra 4.0.2** and **OmniFaces 4.2** both **official release** 
and with the following code `Components.getCurrentForm` return null

If you remember our "partialSubmit" implementations are really close ... 
so we both have to add the form.id in the viewState query string :D


```
<o:form id="partial" partialSubmit="true">
  <h:commandButton id="submit" action="#{testViewAction.testPartialSubmit}" value="Test partial submit" >
    <f:ajax execute="@this" />
  </h:commandButton>
</o:form>
```

```
@Named
@ViewScoped
public class TestViewAction implements Serializable {

    @Serial private static final long serialVersionUID = -8320082942764680795L;

    private static final Logger log = Logger.getLogger(MethodHandles.lookup().getClass().getName());

    public void testPartialSubmit() {
        UIComponent currentComponent = Components.getCurrentComponent();
        UIForm currentForm = Components.getCurrentForm();
        UIForm closestParentForm = Components.getClosestParent( currentComponent , UIForm.class );
        info( "component {0} - form {1} - parent form {2}" , currentComponent , currentForm , closestParentForm );
    }

    static void info( Object o , Object... params ) {
        String message = o == null ? "" : Objects.toString(o);
        if ( message.isBlank() || params == null || params.length == 0 ) log.info(message);
        else log.info(MessageFormat.format( message , params ));
    }

}
```

**Produces the following payload**

```
jakarta.faces.ViewState: 3445594619897062262:7739332117527197449
jakarta.faces.source: partial:submit
jakarta.faces.partial.event: click
jakarta.faces.partial.execute: partial:submit
jakarta.faces.behavior.event: action
jakarta.faces.partial.ajax: true
```

**Comment by BalusC** [comment]
Closing off. Was not a problem in OmniFaces.
