### ISSUE TITLE
Suggestion: Add loader attribute to importFunctions and importConstants

### ISSUE THREAD

**Issue by blutorange** [omnifaces/omnifaces#769]
We have an application that allows plugins to be installed, and some plugins can provide custom XHMTML UI pages. Since plugins have a separate class loader, they can't use `<o:importFunctions/>`, `<o:importConstants/>`, `<f:loadBundle>` etc.

As a solution, we created our own tag handlers that add a new optional attribute called `loader`, which allows for a custom class loader to be specified. Can be either a `Class` / `ClassLoader` instance or some other object, in which case the class loader of the object's class is used. This allows plugins to use XHTML code like this:

```xhtml
	<f:metadata>
		<xi:loadBundle var="myBundle" basename="WEB-INF/i18n/messages" loader="#{myPluginBean}" />
	</f:metadata>
```

Perhaps it would be useful additional to add such an attribute to the OmniFaces implementations directly?

**Comment by BalusC** [comment]
Great suggestion. I took the opportunity to also add a new <o:loadBundle> taghandler.

**Comment by blutorange** [comment]
Thanks, that's sounds great, now we can get rid of our own implementation : )
