### ISSUE TITLE
Reset component subtree state

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#770]
Not to be confused with resetting input state.

Consider (PrimeFaces):
```
<p:dialog>
	<h:form>
		<p:tabView>
```
I want to open this dialog in its pristine initial condition every time. But if the user switched to a different tab (and submitted the form) then the active tab index will be saved by TabView:
```
public void setActiveIndex(int _activeIndex) {
	getStateHelper().put(PropertyKeys.activeIndex, _activeIndex);
}
```
Rerendering the dialog is not enough here. Of course, I could bind `activeIndex` to a value, and reset it that way, but could there be a general solution to this, that I could put in my own general dialog component? A solution to reset component subtree state for all their properties.
`UIData#rowStatePreserved` seems to be a precedent for providing a way to affect state handling behavior, kind of like what my case needs. Kind of... :)

See also: https://stackoverflow.com/questions/54368936/how-to-reset-pdialog-together-with-the-disable-state-of-the-contained-component

**Comment by VsevolodGolovanov** [comment]
The problem with resetting is that there are not only component properties, but also internal facelet properties. Resetting everything leads to problems, like a duplicate ids exception because composite component facets' contents get duplicated.

In my dialog component's case I went with saving initial state when its gets restored during a dialog's first contentLoad. And then reusing it on subsequent restores for contentLoads of the same dialog.

**Comment by BalusC** [comment]
Point taken but this is not trivial to implement without basically a Faces API change to add a new method therefor. You'd then just utilize it right away.

**Comment by BalusC** [comment]
I gave it a second thought but sorry this is really not trivial outside control of Faces impl. I strongly recommend a Faces spec change/improvement.
