### ISSUE TITLE
OmniViewHandler: posible error with tomcat 9.0.80 and unloadView

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#771]
Hi,

We've been using omnifaces @ViewScoped without problems. This morning we have upgraded to tomcat 9.0.80 and I can see this error stack:

```
java.lang.NullPointerException: Cannot invoke "javax.faces.component.UIViewRoot.getViewId()" because "view" is null
	at org.omnifaces.viewhandler.OmniViewHandler.restoreViewRootState(OmniViewHandler.java:186)
	at org.omnifaces.viewhandler.OmniViewHandler.unloadView(OmniViewHandler.java:165)
	at org.omnifaces.viewhandler.OmniViewHandler.restoreView(OmniViewHandler.java:110)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:98)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:98)
	at javax.faces.application.ViewHandlerWrapper.restoreView(ViewHandlerWrapper.java:98)

```
The error happens when a reload is performed in any page, in the onload request. This page is protected by a login, with auth-method FORM used

There is something strange because Faces.getRequestURLWithQueryString() returns something like
http://localhostfaces.efaces.e
But the url in the browser is http://localhost/admin/

I believe that somehow is an error with tomcat, but I don't know how to start with this

**Comment by cocorossello** [comment]
The error happens when the session is new, so maybe in unloadView there is no need to try to restore the view if the session is new

**Comment by BalusC** [comment]
Which OmniFaces version exactly are you using? 
And you upgraded to Tomcat 9.0.80 from which Tomcat version exactly?

**Comment by BalusC** [comment]
I cannot reproduce the described issue in a minimal project with Mojarra 2.3.20 + OmniFaces 3.14.3 and as much as possible defaults (FacesServlet on `*.xhtml`, security constraint on `/*`, no filters, no context params) deployed to Tomcat 9.0.80 with test users in tomcat-users.xml. The `OmniViewHandler#restoreView()` isn't even hit because it's blocked by security constraint and redirected to login page (as expected).

Can you perhaps boil down a reproducer?

**Comment by cocorossello** [comment]
Sorry, I opened the issue too quickly.

I'm not being able to provide a minimal reproducer, but I'm realising that there are more things involved.

* The request is /admin/
* /admin/* is a secured request.
* There is a Rewrite (https://github.com/ocpsoft/rewrite ) rule that applies:
     `                .addRule(Join.path("/admin/").to("/admin/index.xhtml"))`


Versions are myfaces 2.3-next-M8, omnifaces 3.14.3 and I'm upgrading from tomcat 9.0.76 to 9.0.80.

I will try to provide one this week. Anyway the error is harmless, it's an onload request with a new session, so there is nothing to onload

**Comment by BalusC** [comment]
Sorry I still cannot reproduce it. 

1. open admin/index.xhtml which initializes a @ViewScoped
2. wait until session expires and invokes @PreDestroy of that @ViewScoped
3. reload page (just F5 in browser)
4. unload request hits security constraint, basically gets forwarded to login page and therefore never hits OmniViewHandler

Where/how exactly did you secure the /admin/* ? I understood it's secured by a `<security-constraint>` in web.xml but so far it sounds like it isn't.

**Comment by cocorossello** [comment]
Sorry for the delay, I downgraded and tried to upgrade recently.

I finally solved this changing a couple of rewrites (from [rewrite servlet](https://www.ocpsoft.org/rewrite/)). I'm unable to provide a reproducer so I think this issue should be closed.

This might have been related to my rewrite configuration, but I'm unable to see why. In the end I changed:

 ```
                .addRule(Join.path("/api/").to("/api/index.xhtml"))
                .addRule(Join.path("/admin/").to("/admin/index.xhtml"))
```

to 

```
                .addRule().when(Path.matches("/api/")).perform(Forward.to("/api/index.xhtml"))
                .addRule().when(Path.matches("/admin/")).perform(Forward.to("/admin/index.xhtml"))

```
And the issue was gone. 

Thanks for your help.
