### ISSUE TITLE
'Unknown channel: undefined' thrown when connection to web socket is lost. (Push js module badly migrated to TypeScript)

### ISSUE THREAD

**Issue by nemanjajovanovicgit** [omnifaces/omnifaces#774]
When connection is lost to web socket, Socket.socket.onclose triggers and in some cases Socket.open function is called asynchronously via setTimeout(see Push.ts line 125 (tag 4.2)), in minified omnifaces.js wrong open function is called. Open from 'a.prototype' (a should be Socket if I am understanding everything correctly) should be called and not 'b' ('b' is open function that accepts channel as parameter).  This will cause Push.open with no parameters defined to be called and ultimately error 'Unknown channel: undefined' will be thrown. Also code executed by setTimeout() is called from an execution context separate from the function from which setTimeout was called, and even if right open function was called this would not work. (ref: https://stackoverflow.com/questions/2130241/pass-correct-this-context-to-settimeout-callback and https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#the_this_problem ). This bug was introduced during the migration to typescript as it seems. Solution would be that instance of Socket should be bind when open is asynchronously called (e.g. setTimeout(self.open.bind(self), RECONNECT_INTERVAL * self.reconnectAttempts++);). P.S. Keep in mind that I am not fluent in JS and TS, solution might be wrong. In my case I used proposed solution on minified omnifaces.js and served that instead of omnifaces.js from jar.

**Comment by BalusC** [comment]
You're right. This badly slipped through during the migration. Thank you very much for reporting the issue and improving OmniFaces!
