### ISSUE TITLE
Detect duplicate HTML or BODY elements

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#775]
Issue on PrimeFaces: https://github.com/primefaces/primefaces/issues/10790

PR: https://github.com/primefaces/primefaces/pull/10796

User was using 2 `<html>` tags throughout his Facelets and it went undetected until our MoveToBottom failed.  I am wondering if this should be added to Faces spec?  

I thought I would post here before the Faces spec group to get your thoughts.

cc @adam-waldenberg @tandraschko

**Comment by BalusC** [comment]
We could add a dev stage check like missing UIForm.

**Comment by melloware** [comment]
That would be great should I open a faces ticket?

**Comment by BalusC** [comment]
Sure. And also check for head/HtmlHead and body/HtmlBody.

**Comment by melloware** [comment]
Done: https://github.com/jakartaee/faces/issues/1853
