### ISSUE TITLE
`o:validateBean`: `showMessageFor="@violating"` handles only one input component

### ISSUE THREAD

**Issue by NicolaIsotta** [omnifaces/omnifaces#776]
I have a class-level ConstraintValidator which marks only some fields of the objects as invalid using this code:
```java
context.buildConstraintViolationWithTemplate(message)
                .addPropertyNode("property")
                .addPropertyNode("anotherProperty")
                .addConstraintViolation()
                .disableDefaultConstraintViolation();
```
It the jsf page, class-level bean validation is enabled this way:
```java
<o:validateBean showMessageFor="@violating"/>
```
However, only the first input component bound to an invalid field gets marked as invalid, the other does't, and it can confusing to the user.

Here's a reproducer based off primefaces-test:
[primefaces-test.zip](https://github.com/omnifaces/omnifaces/files/12930584/primefaces-test.zip)
The reproducer runs on jetty and uses Mojarra 2.3, Omnifaces 3 and Apache Bval 2, but I've encountered the same behavior with Tomcat 10.1, Mojarra 4, Omnifaces 4 e Hibernate Validator 8.

I did some quick debugging but no luck so far, I'll try again later.

**Comment by NicolaIsotta** [comment]
I may have found the cause.
First, look at the method `invalidateInputsByPropertyPathAndShowMessages` in class `ValidateBean`:
https://github.com/omnifaces/omnifaces/blob/310ee3ffe5f2fd10de717032606ba84215732c43/src/main/java/org/omnifaces/taghandler/ValidateBean.java#L604-L631
The `break` at line 620 has to be removed, because there may be multiple invalid fields to handle.

But this modification alone is not enough to fix the issue, because method `resolveViolatedBasesAndProperties` has definitely something wrong:
https://github.com/omnifaces/omnifaces/blob/310ee3ffe5f2fd10de717032606ba84215732c43/src/main/java/org/omnifaces/util/Validators.java#L174-L214
If I comment line 197 the issue seems to be fixed, but I'm not sure why it was put there in the first place.

**Comment by NicolaIsotta** [comment]
trying to build but I receive this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.3.1:jar (attach-javadocs) on project omnifaces: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - error: --add-modules ALL-MODULE-PATH can only be used when compiling the unnamed module
[ERROR]
[ERROR] Command line was: cmd.exe /X /C ""C:\Program Files\Eclipse Adoptium\jdk-11.0.20.101-hotspot\bin\javadoc.exe" @options @packages @argfile"
```
Something wrong in my setup?

**Comment by BalusC** [comment]
OmniFaces 3 requires JDK8 to build.

**Comment by NicolaIsotta** [comment]
> OmniFaces 3 requires JDK8 to build.

I was trying to build 4.x, but seems like it needs JDK > 13 (https://bugs.openjdk.org/browse/JDK-8220702).
Switched to 3.x, build fails because of #777 
Even with #777 fixed, all integration tests fail with this error:
```
org.omnifaces.test.cdi.eager.EagerIT  Time elapsed: 13.473 s  <<< ERROR!
java.lang.RuntimeException: Could not invoke deployment method: public static org.jboss.shrinkwrap.api.spec.WebArchive org.omnifaces.test.cdi.eager.EagerIT.createDeployment()
	at org.omnifaces.test.cdi.eager.EagerIT.createDeployment(EagerIT.java:57)
```
Any hint?

**Comment by BalusC** [comment]
4.x requires JDK11 to build. Latest OpenJDK 11.0.12 works fine for me (I use sdkman to manage multiple Java versions).

#777 has been merged.

IT error clue is in server logs which you can find in target. E.g. target/wildfly-xyz/standalone/log/server.log.

**Comment by BalusC** [comment]
Looking at it today and I noticed that `addPropertyNode(...)` actually doesn't do what you'd expect at first sight. Basically it adds a new property node to the existing property path. It doesn't add a separate bean property.

E.g. when you have `#{bean.nested.property}` then you'd do `addPropertyNode("nested").addPropertyNode("property")`. In other words, this approach isn't applicable when you want to mark 2 separate properties as violating. In your case it's basically trying to add the violation message to `#{bean.property.anotherProperty}` while you really want to add it to `#{bean.property}` and `#{bean.anotherProperty}`.

But your point is taken. I think you better add a nested bean property which holds exactly these 2 properties and then omit the template building. The violation message will simply be added to all properties of the nested bean.

**Comment by NicolaIsotta** [comment]
You're right, chaining `addPropertyNode` is not the correct way to invalidate multiple properties.
The solution is simple: add a ConstraintViolation for each invalid property.
The code snippet in my first message then becomes:
```java
context.disableDefaultConstraintViolation();
context.buildConstraintViolationWithTemplate(message).addPropertyNode("property").addConstraintViolation();
context.buildConstraintViolationWithTemplate(message).addPropertyNode("anotherProperty").addConstraintViolation();
```
Omnifaces's behavior is correct, so I'm closing this.

**Comment by BalusC** [comment]
Fab!
