### ISSUE TITLE
[Enhancement] getBookmarkableURL - ignore blank or null values

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#78]
I think it is a mojarra "bug" but it would be great if omnifaces itself would ignore blank or null values in its bookmarkableURL methods, since there is no need to add them to the view id.

**Comment by BalusC** [comment]
I can do that for the provided parameters, but not for the view parameters via includeViewParams=true as this job is done by JSF implementation itself. That part can be solved by using o:viewParam instead of f:viewParam as it would return null instead of empty string.

**Comment by BalusC** [comment]
Fix is available in today's snapshot. Let me know if it is satisfying.
