### ISSUE TITLE
Incompatibility with MyFaces 4 and CDI

### ISSUE THREAD

**Issue by mkomko** [omnifaces/omnifaces#780]
When using OmniFaces 4.2 or 4.3 in an application (EAR) deployed on WildFly 30 using MyFaces 4, the OmniFaces converters are not discovered correctly, which leads, for example, to the exception:
`jakarta.faces.FacesException: Could not find any registered converter-class by converterId : omnifaces.SelectItemsConverter`

As discussed in https://github.com/omnifaces/omnifaces/issues/744, both possible ways of discovery do not work in this environment:

1. The MyFaces default implementation _DefaultAnnotationProvider_ does not find the classes. Probably something is now different in WildFly, Jakarta or Java. This is probably a MyFaces problem and may not be workaroundable by OmniFaces, see https://issues.apache.org/jira/browse/MYFACES-4643?focusedCommentId=17789343&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17789343.
2. The CDI implementation _CdiAnnotationProviderExtension_ used when enabling `USE_CDI_FOR_ANNOTATION_SCANNING` does not find the classes, because they are not CDI beans and the OmniFaces _bean-discovery-mode_ was changed from _all_ to _annotated_.

I don't know if the same could apply for FacesComponent, FacesValidator etc.

Thank you!

**Comment by tandraschko** [comment]
1) might be also be broken because of EAR, this was always very special.

**Comment by BalusC** [comment]
EAR might be a thing, yes. I haven't been able to reproduce it with a WAR. The EAR structure is nonetheless discommended since introduction of CDI in Java EE 6.

But how exactly did you install MyFaces in WildFly? There are different instructions on the web, including manually meddling around in WF's modules/system/layers/base subfolder.

I used these instructions: https://jasondl.ee/2023/myfaces-4-on-wildfly (Jason is one of developers of WildFly)

- Download and unzip Galleon into `~/Java` https://github.com/wildfly/galleon/releases
- Download and unzip WildFly into `~/Java` https://www.wildfly.org/downloads/
- Run `$ ~/Java/galleon-5.2.2.Final/bin/galleon.sh install org.wildfly:wildfly-myfaces-feature-pack:2.0.0.Final --dir=~/Java/wildfly-30.0.0.Final --config=standalone.xml --layers=myfaces`
- That's all

WF startup log:

```
10:21:24,246 INFO  [org.jboss.as] (MSC service thread 1-1) WFLYSRV0049: WildFly MyFaces feature pack 30.0.0.Final (WildFly Core 22.0.1.Final) starting
...
10:21:27,194 INFO  [org.apache.myfaces.webapp.FacesInitializerImpl] (ServerService Thread Pool -- 87) MyFaces Core has started, it took [234] ms.
```
[This testcase](https://github.com/omnifaces/omnifaces/commit/ca26e5049d79fbc1f304212ce6152528cb87e14b) with the `omnifaces.SelectItemsConverter` of OmniFaces 4.3 worked for me irrespective of the `org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING` context param.

**Comment by mkomko** [comment]
> The EAR structure is nonetheless discommended since introduction of CDI in Java EE 6.

I didn't know that. Although slightly off topic, do you have any more information about that or the recommended way?

> But how exactly did you install MyFaces in WildFly? There are different instructions on the web, including manually meddling around in WF's modules/system/layers/base subfolder.

Well, it's complicated. We have been using MyFaces 4 since WildFly 27, when there were not a lot of instructions and no Galleon feature packs. So we did it by scraping together information from various sources and of course manually creating modules in the modules folder (not system/layers/base though, that should stay untouched). We did it mostly like melloware did it in his Galleon feature pack: https://github.com/melloware/wildfly-myfaces-galleon-pack. But that's a bit outdated now.

When migrating to WildFly 30 I did try with Jason Lee's Galleon feature pack, but ran into problems:
https://github.com/wildfly-extras/wildfly-myfaces-feature-pack/issues/6
https://github.com/wildfly-extras/wildfly-myfaces-feature-pack/issues/7

Anyhow, I don't think our MyFaces integration into WildFly is the problem, we have been using it for a while.

> [This testcase](https://github.com/omnifaces/omnifaces/commit/ca26e5049d79fbc1f304212ce6152528cb87e14b) with the omnifaces.SelectItemsConverter of OmniFaces 4.3 worked for me irrespective of the org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING context param.

I don't see how it's possible that CDI could find your FacesConverter classes if they are not annotated with CDI annotations? Can you set a breakpoint in MyFaces CdiAnnotationProviderExtension#processAnnotatedType and see if that's even called?

**Comment by mkomko** [comment]
By the way, you don't even need to do all that if you want to reproduce the CDI part of the issue. I created a [simpler reproducer](https://issues.apache.org/jira/secure/attachment/13064651/primefaces-test.zip) for the [MyFaces ticket](https://issues.apache.org/jira/browse/MYFACES-4643). Just download it and run it using `mvn clean jetty:run -Pmyfaces40`.

The non-CDI part of the issue might be related to EAR deployment then.

**Comment by BalusC** [comment]
> *I don't see how it's possible that CDI could find your FacesConverter classes if they are not annotated with CDI annotations?*

Apparently WildFly's MyFaces feature pack takes care of that:
![image](https://github.com/omnifaces/omnifaces/assets/173372/5e6bd0f2-416c-4c38-b491-bd2249f8c58b)

> *When migrating to WildFly 30 I did try with Jason Lee's Galleon feature pack, but ran into problems*

You tried a month ago, at Oct 20. Both seem to be fixed. Note that I installed `org.wildfly:wildfly-myfaces-feature-pack:2.0.0.Final` as I figured out that was the latest available version released at Oct 31.

> *I didn't know that. Although slightly off topic, do you have any more information about that or the recommended way?*

The path towards loosely coupled applications ("microservices"). And, CDI doesn't support EAR format. Stick to WAR format. Root problem is elaborated in https://github.com/omnifaces/omnifaces/wiki/Known-Issues-(CDI) and summarized as follows:

> In a nutshell, a CDI extension which is enclosed in a JAR in a WAR in an EAR is not applied on a per-WAR basis, but only once on a per-EAR basis for only one WAR. This has the consequence that only one of the WARs can make use of the features offered by the CDI extension and other WARs can not.

**Comment by mkomko** [comment]
I wanted to test this myself, so I once again used the _wildfly-myfaces-feature-pack_ to create my WildFly instance. After deploying our application I am once again greeted with `java.lang.ClassNotFoundException: java.sql.ResultSet from [Module "jakarta.faces.impl:myfaces" version 4.0.1 from local module loader]`. So the fix to issue 6 didn't make it into version 2.0.0.Final of the _wildfly-myfaces-feature-pack_. After applying the relevant fix to the _myfaces-impl_ module, my application deployed successfully. Just to make sure I reproduced issue 7 as well, so it's still there. Jason Lee may be able to fix it if I provide a reproducer, but I didn't have time to create a simple deployable JSF application yet.

Then I updated our pom.xml to OmniFaces 4.3, made a clean build and restarted the server and deployed our EAR application. And indeed, the converters were available! Sadly we cannot use this solution because of issue 7 above.

Even so, my opinion is that OmniFaces should work with plain CDI and not rely on the application server to provide a special integration to make it work. Just take the primefaces-test project which uses Jetty and Weld (see my reproducer above). It doesn't work there either. If classes are supposed to be loaded by CDI (and they are when using this configuration, which may be the only configuration in the future. as hinted by tandraschko?), shouldn't they be CDI beans when using _bean-discovery-mode annotated_? I'll change the title of the issue to "Incompatibility with MyFaces 4 and CDI", because I don't see it as a problem just in combination with WildFly.
But that's just my opinion and I understand that you may have a different opinion and it's your library :smile:. 

> The path towards loosely coupled applications ("microservices"). And, CDI doesn't support EAR format. Stick to WAR format.

Our application consists of an EAR with a JAR (EJB module) and a WAR (WEB module). So I hope we shouldn't have too many problems, we didn't so far.
We're not going to split our monolithic web application into microservices, that's neither sensible nor feasible for us.

**Comment by mkomko** [comment]
Thank you very much for your efforts so far!

I wanted to test this myself, so I once again used the _wildfly-myfaces-feature-pack_ to create my WildFly instance. After deploying our application I am once again greeted with `java.lang.ClassNotFoundException: java.sql.ResultSet from [Module "jakarta.faces.impl:myfaces" version 4.0.1 from local module loader]`. So the fix to issue 6 didn't make it into version 2.0.0.Final of the _wildfly-myfaces-feature-pack_. After applying the relevant fix to the _myfaces-impl_ module, my application deployed successfully. Just to make sure I reproduced issue 7 as well, so it's still there. Jason Lee may be able to fix it if I provide a reproducer, but I didn't have time to create a simple deployable JSF application yet.

Then I updated our pom.xml to OmniFaces 4.3, made a clean build and restarted the server and deployed our EAR application. And indeed, the converters were available! Sadly we cannot use this solution because of issue 7 above.

Even so, my opinion is that OmniFaces should work with plain CDI and not rely on the application server to provide a special integration to make it work. Just take the primefaces-test project which uses Jetty and Weld (see my reproducer above). It doesn't work there either. If classes are supposed to be loaded by CDI (and they are when using this configuration, which may be the only configuration in the future. as hinted by tandraschko?), shouldn't they be CDI beans when using _bean-discovery-mode annotated_? I'll change the title of the issue to "Incompatibility with MyFaces 4 and CDI", because I don't see it as a problem just in combination with WildFly.
But that's just my opinion and I understand that you may have a different opinion and it's your library :smile:. Let me know what you think!

> The path towards loosely coupled applications ("microservices"). And, CDI doesn't support EAR format. Stick to WAR format.

Our application consists of an EAR with a JAR (EJB module) and a WAR (WEB module). So I hope we shouldn't have too many problems, we didn't so far.
We're not going to split our monolithic web application into microservices, that's neither sensible nor feasible for us.

Thank you!

**Comment by BalusC** [comment]
> *Even so, my opinion is that OmniFaces should work with plain CDI and not rely on the application server to provide a special integration to make it work*

It's in Faces 4.0 still the responsibility of the Faces impl to pick up annotated Faces artifacts. MyFaces should have found it by default (so, with `org.apache.myfaces.annotation.USE_CDI_FOR_ANNOTATION_SCANNING` param removed). Only as per the upcoming Faces 5.0 the impl isn't anymore required to manually find them and CDI can be used for that: https://github.com/jakartaee/faces/issues/1584

Your concrete problem is probably caused by bad integration of MyFaces in WildFly. When using MyFaces 4 in custom stack (Tomcat, Jetty, etc) or in JEE servers which by default use MyFaces as Faces impl (TomEE, Liberty, etc) it works just fine.

**Comment by mkomko** [comment]
To summarize:
* You don't plan to change anything in OmniFaces for Faces 4.0, correct?
* Should it work in Faces 5.0 in a plain CDI environment like Jetty & Weld?
* Is https://github.com/jakartaee/faces/issues/1584 already implemented in OmniFaces and/or Mojarra for Faces 5.0 or are there any plans on how it will be done?

Thank you!

**Comment by BalusC** [comment]
1. I don't think so as this is supposed to work out the box as per Faces 4 spec. If it doesn't work then it's an issue in either the Faces impl or in the Server integration. In your specific case, it was the server integration. MyFaces itself is working fine.
2. That's the plan yes. In Faces 4 the Faces-specific annotations are **not** CDI bean defining annotations.
3. OmniFaces it not a Faces impl. It's a Faces utility library. Mojarra and MyFaces are examples of Faces impls. As to the how, I'm not sure yet as that still needs to be discussed. One of the ways is to let Faces-specific annotations extend from an existing CDI bean defining annotation such as `@Dependent`. Another way is to introduce a new CDI scope specifically for these things. We'll see. Whatever way, it'll 'transparently' work in OmniFaces because the Faces impl is responsible for finding them.

**Comment by mkomko** [comment]
Thank you for your quick response and your information, we're looking forward to Faces 5.0 then 😉. In the meantime we'll try to get MyFaces fixed, get the wildfly-myfaces-feature-pack fixed or change your beans.xml manually 😉. I'll close the issue!
