### ISSUE TITLE
Components disableInputComponent ... or propose a change to Faces API ?

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#782]
I haven't found a way to disable
a generic `UIInput` component in jsf
so I wrote a utility method
which could be easily ported into _OmniFaces_ `Components` utility class ...

The question is: why doesn't the `UIInput` class have the `setDisabled` method?

```
public static void disableInputComponent( String id ) {
  UIInput input = Components.findComponent(id);
  switch (input) {
    case HtmlInputText text -> text.setDisabled(true);
    case HtmlInputTextarea area -> area.setDisabled(true);
    case HtmlSelectOneMenu menu -> menu.setDisabled(true);
    case HtmlSelectOneRadio radio -> radio.setDisabled(true);
    case HtmlSelectOneListbox box -> box.setDisabled(true);

    // default -> try with reflection ...
    default -> {
      try {
            // todo: use the internal OmniFaces Reflection utility
	    Method method = ReflectionUtils.getMethod(input.getClass(), "setDisabled", Boolean.class);
	    ReflectionUtils.invoke( method , input , true);
      } catch (Exception e) {
	    throw new RuntimeException(e);
      }
    }
  }
}
```

**Comment by NicolaIsotta** [comment]
h:inputHidden is a UIInput subclass and it does not have disabled attribute.
But I too agree a subclass or interface for inputs which can disabled would be useful (also for PF and other component frameworks).
I'm not sure what would be the best solution:

- add is/setDisabled to UIInput (and modify h:inputHidden accordingly)
- create new Disableable (?) interface
- new UIInput subclass, DisableableUIInput or something like that

**Comment by pizzi80** [comment]
> h:inputHidden is a UIInput subclass and it does not have disabled attribute. 

I don't know why h:inputHidden does not support the disabled attribute ...

is this a bug too :) ??

the html `input` element supports the "disabled" attribute

https://www.w3.org/TR/REC-html40/interact/forms.html#adef-disabled

the _"input hidden"_ it's an `input` with `type="hidden" `


> I'm not sure what would be the best solution:
> 
> add is/setDisabled to UIInput (and modify h:inputHidden accordingly)
> create new Disableable (?) interface
> new UIInput subclass, DisableableUIInput or something like that

:+1: :+1: 

cc: @arjantijms
cc: @BalusC 

what's your thoughts?

**Comment by NicolaIsotta** [comment]
There's [UIViewParameter](https://docs.oracle.com/javaee/7/api/javax/faces/component/UIViewParameter.html) (f:viewParam) too...

**Comment by BalusC** [comment]
> The question is: why doesn't the UIInput class have the setDisabled method?

Most likely because it's a superclass and `disabled` is a HTML attribute so it has to be declared on the `HtmlXyz` subclass.

> so I wrote a utility method

There's a simpler way.

```
input.getAttributes().put("disabled", true);
```

**Comment by pizzi80** [comment]
> There's a simpler way.
> 
> ```
> input.getAttributes().put("disabled", true);
> ```

:top: as usual, thanks

I'll use it on my jsf utils!

it would be nice to have it inside OmniFaces's Components utility

as @NicolaIsotta said it would be nice to have a common interface or abstract class
to share common attributes and/or methods to help developers and to improve Faces

**Comment by BalusC** [comment]
> I'll use it on my jsf utils!

You could open a PR to add to OmniFaces 4.x to create a win-win situation ;)

**Comment by BalusC** [comment]
Will be in 4.5.
