### ISSUE TITLE
PWAResourceHandler is not aware of VersionedResourceHandler

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#784]
Enabling the `VersionedResourceHandler` 
breaks the internal versioning algorithm of the `ImageResource` inner class
of the `WebAppManifest` class

the problematic line of code inside `WebAppManifest.class`  is 

```
requestPath = formatURLWithQueryString(requestPath, "v=" + connection.getLastModified());
```

because it adds the version query string without checking...

**Comment by pizzi80** [comment]
It's probably best to remove the PWA version control algorithm entirely
and if you need resource versioning, you need to enable `VersionedResourceHandler`

**Comment by BalusC** [comment]
Point taken, fixed now, thank you very much for improving OmniFaces!

**Comment by pizzi80** [comment]
During the last 2 weeks I have forked all the "stuff" regarding the PWA and made many improvements,
One day I'll try to do a PR on OmniFaces but probably
We need to synchronize a little on some assumptions.

It's OK for you?

Do I do a PR directly and then wait to your feedback?

Or you prefer to implement it by yourself ticket by ticket?

**Comment by BalusC** [comment]
A PR is totally fine. OmniFaces is not as strict as Faces/Mojarra ;)

**Comment by pizzi80** [comment]
ok! :smiley:
