### ISSUE TITLE
omnifaces ViewScoped bean not injectable in converter

### ISSUE THREAD

**Issue by JohannesProbst** [omnifaces/omnifaces#786]
We are using joinfaces 5.2.1 with omnifaces 4.3
and @BalusC's approach for omnifaces viewScope: https://balusc.omnifaces.org/2023/11/using-omnifaces-cdi-viewscoped-with.html

This leads us to the problem that viewscoped beans with no no-args constructor can't be injected anymore into facesConverter - it states:

> `WELD-001435: Normal scoped bean ... is not proxyable because it has no no-args constructor - Managed Bean [class ...] with qualifiers @Default @Any @Named].`

Possible solutions found so far WITHOUT switching injection to field or setter:
- use `com.sun.faces.cdi.CdiUtils` to get the viewScoped bean instance within the facesConverter
- use an interface on the viewScoped bean representing the methods needed in the converter and inject the interface into the facesConverter as the interface can be proxied by cdi

we tried to use the omnifaces utility for facesConverter: https://showcase.omnifaces.org/cdi/FacesConverter as we want to use the `o:converter` feature
but i think the example shown here is not working anymore as the shown message states `null` for the injected beans. 

2 Questions:
Can u confirm that the omnifaces converter managing approach is not working anymore?
Do u have another workaround?

An example project is found at: https://github.com/JohannesProbst/joinfaces-gradle-war-example

**Comment by BalusC** [comment]
Why do you want to inject a view scoped bean in a FacesConverter in first place? I've never come across such use case. Perhaps you need OmniFaces SelectItems(Index)Converter or List(Index)Converter instead?

As to the concrete problem, this is a limitation in CDI not in OmniFaces. You'd still have had exactly the same problem when using any other CDI scope such as standard `@RequestScoped` or even JSF own `@ViewScoped`. Either add a default c'tor or create a new interface and inject by interface instead. Related: https://stackoverflow.com/q/46543657

**Comment by JohannesProbst** [comment]
@BalusC  to your first Question: thx for the tipp - i will dig into it - possible resolving the needed injection at this point.

To my 2. Question: Am I misinterpreting your demo for [omnifaces facesConverter utility](https://showcase.omnifaces.org/cdi/FacesConverter#:~:text=attributes%20on%20it.-,Demo,-Submit%20the%20form) or is it not working anymore - as it shows for EJB and CDI injected beans `null` in the message.

**Comment by BalusC** [comment]
Demo has been [fixed](https://github.com/omnifaces/showcase/commit/043b262a63691e2b777f417b1130bccd99b26ed1). Interpretation of empty beans.xml file has changed in CDI 4.0. In order to continue with the original CDI configuration defaults the beans.xml has to be explicitly filled now. Retry now and you'll see it works again. Thanks for reporting, this was overlooked.
