### ISSUE TITLE
Missing list attribute in converter tag

### ISSUE THREAD

**Issue by aripddev** [omnifaces/omnifaces#788]
Missing `list` attribute in `converter` tag when using the `ListConverter`.

```xml
 <p:pickList ...>
    <o:converter converterId="omnifaces.ListConverter" list="#{view.source}"/>
```

**Comment by BalusC** [comment]
Sorry no. The sole goal of `<o:converter>` is to support *any* attribute possible. Registering one in the taglib would bring up the question why all possible others aren't registered. And there's technically speaking an infinite amount of them. So, no. See also https://github.com/omnifaces/omnifaces/issues/81 and https://showcase.omnifaces.org/taghandlers/converter
