### ISSUE TITLE
Feature - JSF tag for html link tag with parameter support for bookmarkable URL's

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#79]
Currently there is no JSF support for HTML `link` component to provide further meta data.

There are a few `rel` types which can benefit from bookmarkable URL's. 
Especially the `canonical` which is important for SEO marketing.

Currently I wrote myself a converter in combination with an ugly workaround: 

*The converter I can provide to omnifaces later if found usefull*

	htmlLinkRelHref=<link rel="{0}" href="{1}"/>

	<h:outputFormat value="#{msg.htmlLinkRelHref}" escape="false">
		<f:param value="canonical"/>
		<o:param>
			<h:outputText value="#{view.viewId}" converter="BookmarkableUrlConverter">
				<c:if test="#{bean.isProxyURL}">
					<f:attribute name="fqdn" value="http://www.example.com" />
				</c:if> 
				<f:attribute name="decode" value="true"/>
				<o:param name="foo" value="#{bean.foo}" converter="fooConverter"/>
				<o:param name="bar" value="#{bean.bar} converter="#{bean.barConverter}" disable="#{bean.foo eq null}"/>
			</h:outputText>
		</o:param>
	</h:outputFormat>

Relates to:

* http://stackoverflow.com/questions/8577194/houtputtext-inside-of-href-doesnt-work-in-jsf-2-0

**Comment by BalusC** [comment]
This goes overboard. You'd better not put markup in a resource bundle.

Here's a simplified form using `<o:outputFormat>`:

```
<o:outputFormat value="#{view.viewId}" converter="BookmarkableUrlConverter" var="linkHref">
    <c:if test="#{bean.isProxyURL}">
        <f:attribute name="fqdn" value="http://www.example.com" />
    </c:if> 
    <f:attribute name="decode" value="true"/>
    <o:param name="foo" value="#{bean.foo}" converter="fooConverter"/>
    <o:param name="bar" value="#{bean.bar}" converter="#{bean.barConverter}" disable="#{bean.foo eq null}" />
</o:outputFormat>

<link rel="canonical" href="#{linkHref}" />
```

**Comment by djmj** [comment]
Thank you, I did not knew about `<o:outputFormat>` yet.

Is this var attribute composite component safe?

I have a few other usages of small markup within resource bundles.
