### ISSUE TITLE
idea: why not rename the OmniFaces' @ViewScoped => @PageScoped ?

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#796]
at the moment it's very confusing 
and the only way is to include the fully qualified name ...

```
@org.omnifaces.cdi.ViewScoped
```

**Comment by melloware** [comment]
Yeah in our company code we call it PageScoped.  We override it with our own annotation.

```java
import static java.lang.annotation.ElementType.FIELD;
import static java.lang.annotation.ElementType.METHOD;
import static java.lang.annotation.ElementType.TYPE;
import static java.lang.annotation.RetentionPolicy.RUNTIME;

import org.omnifaces.cdi.ViewScoped;

import jakarta.enterprise.inject.Stereotype;
import jakarta.inject.Named;
import java.lang.annotation.Documented;
import java.lang.annotation.Retention;
import java.lang.annotation.Target;

/**
 * Stereotype for OmniFaces ViewScoped and Named to allow easy transition to
 * view scope from our custom PageScoped.
 */
@Named
@ViewScoped
@Documented
@Stereotype
@Target({TYPE, METHOD, FIELD})
@Retention(RUNTIME)
public @interface PageScoped {

}
```

**Comment by pizzi80** [comment]
thanks for the tip!!

**Comment by BalusC** [comment]
I'm not going to change it.

As an alternative, you could scan for undesired annotations and log a warning or even throw an exception as follows:
```java
package com.example;

import static org.omnifaces.util.Utils.startsWithOneOf;

import java.util.logging.Logger;

import jakarta.enterprise.event.Observes;
import jakarta.enterprise.inject.spi.Extension;
import jakarta.enterprise.inject.spi.ProcessAnnotatedType;

public class VetoAnnotatedTypeExtension implements Extension {

    private static final Logger logger = Logger.getLogger(VetoAnnotatedTypeExtension.class.getName());

    private static final String[] EXCLUDED_PACKAGES = { "com.sun.faces.", "org.apache.myfaces.", "org.omnifaces." };

    public <T> void processAnnotatedType(@Observes ProcessAnnotatedType<T> type) {
        var beanClass = type.getAnnotatedType().getJavaClass();

        if (!startsWithOneOf(beanClass.getPackageName(), EXCLUDED_PACKAGES) && beanClass.isAnnotationPresent(jakarta.faces.view.ViewScoped.class)) {
            logger.warning("@jakarta.faces.view.ViewScoped found on " + type.getAnnotatedType().getJavaClass()
                    + "! You might want to migrate it to @org.omnifaces.cdi.ViewScoped to save memory.");
        }
    }
}
```
which is activated by `src/main/resources/META-INF/services/jakarta.enterprise.inject.spi.Extension` file with the following content:
```
com.example.VetoAnnotatedTypeExtension
```

**Comment by pizzi80** [comment]
Sorry to reply to a closed issue, but I'm a bit confused:

Does using the OmniFaces version of `@ViewScoped` have any drawbacks ?

For example do they have the same behaivouir respect to _"the browser back button"_ and/or the `ViewExpiredException`?

If there aren't any drawbacks, why this is not the default behaviour of Faces/Mojarra?

We could simply fix the bug and improve Faces reducing confusion between the 2 versions ...

**Comment by BalusC** [comment]
There aren't drawbacks. In the contrary!

It couldn't be part of Faces spec for long because there was no standardized way to successfully hit server during window unload. But these days the beforeunload and pagehide events (which were for a long time non-standard), is finally included in HTML5 spec, and the navigator.sendBeacon is widely implemented (previously synchronous XHR was the only way but it became de-facto deprecated, e.g. Chrome spitting JS console warnings).

These days it should indeed be possible to make it part of Faces spec.

**Comment by pizzi80** [comment]
> There aren't drawbacks. In the contrary!
> 
> It couldn't be part of Faces spec for long because there was no standardized way to successfully hit server during window unload. But these days the beforeunload and pagehide events (which were for a long time non-standard), is finally included in HTML5 spec, and the navigator.sendBeacon is widely implemented (previously synchronous XHR was the only way but it became de-facto deprecated, e.g. Chrome spitting JS console warnings).


thanks for the reply!

now it's clear also why they have the same name ...

> These days it should indeed be possible to make it part of Faces spec.

This could be a big improvement for the next (2025) major release of Faces...
