### ISSUE TITLE
Feature Request: New component <o:criticalStylesheet> for Critical CSS

### ISSUE THREAD

**Issue by banifou** [omnifaces/omnifaces#797]
It is such a pity that there is nothing like '**criticalCSS**' for JSF. It would be nice to have at least a new component like '<o:criticalStylesheet>'. When this component appears in the header, the CombinedResourceHandler should leave the CSS file inlined and remove all separate stylesheet resources, creating a combined and **non-blocking** one for all stylesheets.

The non-blocking stylesheet should look as follows:
`<link rel="preload" href="nonBlockingCombined.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
<noscript><link rel="stylesheet" href="nonBlockingCombined.css"></noscript>
`

It should have an option, whether the nonBlockingCombined CSS should or should not contain the primefaces stylesheets components.css and layout.css.

**Comment by BalusC** [comment]
`<o:criticalStylesheet>` has been added to OmniFaces 4.5. 
The `CombinedResourceHandler` transparently recognizes it.

---

> It should have an option, whether the nonBlockingCombined CSS should or should not contain the primefaces stylesheets components.css and layout.css.

Simply explicitly redeclare them as `<o:criticalStylesheet>`:

```xml
<o:criticalStylesheet library="primefaces" name="components.css" />
<o:criticalStylesheet library="primefaces" name="layout.css" />
```
