### ISSUE TITLE
Feature - Function to retrieve child UIParameters of UIComponent

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#80]
In a few places I am using following function which retrieves all child UIParameters of an UIComponent.

* Perform redirect after an AJAX request (in combination with `getBookmarkableURL`)
* Get bookmarkable URL to pass to e-mail, with parameters defined in view
* Simply show link using converter and `h:outputText` or create canonical URL
* Separate implicit bean navigation from action method (JAVASERVERFACES_SPEC_PUBLIC-1176 was rejected so i use my own solution)

I could not find a built-in equivalent and mojarra itself has this logic duplicated on multiple places for its link components.

Function

	/**
	 * Retrieves all child UIParameter components of
	 * the current component using SimpleParam.
	 *
	 * Useful to pass GET parameters to AJAX requests.
	 *
	 * @param component UIComponent who's child UIParameter are parsed
	 *
	 * @return
	 */
	public static Collection<ParamHolder> getComponentParams(final UIComponent component)
	{
		if (component == null)
			throw new IllegalArgumentException("Component must not be null.");

		final List<ParamHolder> params = new ArrayList<>(component.getChildCount());

		for (final UIComponent child : component.getChildren())
			if (child instanceof UIParameter)
			{
				final UIParameter param = (UIParameter) child;
				final String name = param.getName();

				if (!param.isDisable() && !StringUtils.isBlank(name))
					params.add(new SimpleParam(param.getName(), param.getValue()));
			}

		return params;
	}

**Separate implicit bean navigation from action method**

This method maybe usefull for others and can be added to a request bean.

*This method could be enhanced adding paramters `boolean redirect, boolean includeViewParams` and perform redirect or forward`

	/**
	 * Navigates to the given outcome and building a bookmarkable URL using all
	 * child UIParameter's of the current component.
	 *
	 * @see https://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1176
	 *
	 * @param outcome
	 *
	 * @return
	 */
	public void performActionParams(final String outcome)
	{
		final FacesContext context = FacesContext.getCurrentInstance();
		final UIComponent component = UIComponent.getCurrentComponent(context);

		final String uri = FacesLocal.getBookmarkableURL(context, outcome,
			FacesContextUtils.getComponentParams(component));
		FacesContextUtils.redirect(context, uri);
	}

	<p:commandButton icon="ui-icon-search"
		action="#{appBean.performActionParams(cc.attrs.outcome)}" update="@form">
		<o:param name="foo" value="#{cc.attrs.foo}" converter="#{appBean.fooConverter}"/>
		<o:param name="bar" value="#{cc.attrs.bar}" converter="#{appBean.barConverter}"/>
		<f:param name="query" value="#{cc.attrs.query}" disable="#{empty cc.attrs.query}"/>
	</p:commandButton>

**Comment by djmj** [comment]
Thanks for adding this feature.

Any specific reason an unmodifiable collection returned? (It is also not documented)

I have use cases where i add a speficic param programmatically to the list to further pass it to `getBookmarkableURL`. 
I could create a new list instance, but just curious.

**Comment by BalusC** [comment]
It would otherwise create the impression that the newly added param would get reflected into the component, while you should be using `component.getChildren().add(...)` for this. I've clarified the javadoc. Thank you for the hint on that.
