### ISSUE TITLE
unload not working after update form

### ISSUE THREAD

**Issue by zeners** [omnifaces/omnifaces#809]
when update the whole form, no unload event is triggered leaving the page

adding `<p:commandButton update=":form" value="Update Form"/>` an press this button will lost the ability to send the omnifaces unload-event

browser: firefox, chrome, edge
spring-boot: 3.2.4
JSF/Mojarra:  4.0.6
joinfaces: 5.2.4
Primefaces: 13.0.8
omnifaces: 4.3

any hints, whats going wrong?

edit:

sample-project:
------
 https://github.com/zeners/omnifaces-is809
spring-boot: 3.2.5
joinfaces: 5.2.5
omnifaces: 4.4

reproduce:
---------------
start project / main -App
navigate to http://localhost:8080/index.xhtml
press "Update Form" - button
navigate to other location like http://localhost:8080/
notice: no unload-beacon request is send

jakarta faces viewstate hidden field not send in partial form-update - in consequence the hidden field is removed from form

**Comment by zeners** [comment]
workaround:

copy current viewState-value to "old" form cached by omnifaces' event-listener  (patch omnifaces)
```
            <h:outputScript target="body">
                var oldForm = form
                window.onbeforeunload = function() {
                    var viewStateValue = OmniFaces.Util.getFacesForm()['jakarta.faces.ViewState']
                    if (!oldForm['jakarta.faces.ViewState']) if( viewStateValue) if( viewStateValue.value) {
                        oldForm['jakarta.faces.ViewState'] = { 'value': viewStateValue.value }
                    }
                }
            </h:outputScript>
```
explicitly re-add viewstate hidden inputfield (patch jsf?)
```
            <h:form id="form" name="form">
                <ui:fragment rendered="#{faces.ajaxRequest}">
                    <input type="hidden" name="jakarta.faces.ViewState" id="j_id1:jakarta.faces.ViewState:0" autocomplete="off"/>
                </ui:fragment>

```

**Comment by BalusC** [comment]
Fixed for upcoming 3.14.6 and 4.5 via https://github.com/omnifaces/omnifaces/commit/bbb7feb9a5047b732dbeeae47a8acc776b27cebc and https://github.com/omnifaces/omnifaces/commit/2535493e855a23cac46eb19f0b220e6831c51159

**Comment by BalusC** [comment]
Sorry for accidental close/reopen. I confused issue numbers.

We'll take a closer look at this later.

**Comment by BalusC** [comment]
It works fine when you use `update="@form"` instead of `update="idOfParentForm"`. The former is actually the canonical approach, but I'll fix the bug nonetheless.
