### ISSUE TITLE
conditionally rendered deferredScript and CombinedResourceHandler bug?

### ISSUE THREAD

**Issue by Jens-dojo** [omnifaces/omnifaces#812]
Hi,

I use 

<o:deferredScript> 

and I have activated CombinedResourceHandler

This all works fine - except if I render some part of the code conditionally:
```

	<ui:fragment rendered="#{false}">

	<o:deferredScript group="test" library="test"
			name="test.js"  />
</ui:fragment>
```

The produced xhtml source code always includes
OmniFaces.DeferredScript.add(
for all scripts

Any ideas?
Thank you
Jens

**Comment by Jens-dojo** [comment]
Update:

if I replace 
<ui:fragment 
by 

<c:if test="#{false}">

then it works and the scripts are not included. 
So we can close this as this workaround seems to work.

**Comment by BalusC** [comment]
This is actually a bug.

`<o:deferredScript ... rendered="#{false}">` will work.
The `CombinedResourceHandler` mistakenly doesn't check for its parents and should be fixed.
