### ISSUE TITLE
5.0: Use URN instead of URL as XML namespace URI

### ISSUE THREAD

**Issue by BalusC** [omnifaces/omnifaces#818]
To catch up Faces itself, migrate OmniFaces XML namespaces as well:
- `http://omnifaces.org/ui` --> `omnifaces.ui` 
- `http://omnifaces.org/functions` --> `omnifaces.functions`

**Comment by melloware** [comment]
@BalusC i was going to ask about this what version do you plan to do this in?  I will update OpenRewrite EE migration to make these changes to my pages just curious if this is EE10, EE11 or Faces.next?

**Comment by BalusC** [comment]
OmniFaces 5.0 is targeted at EE11.

Note: old URL will be kept for backwards compatibility until next major version.

**Comment by melloware** [comment]
for PF I cheated and use just Maven plugin to do it so we wouldn't have two copies of the taglib :)

https://github.com/primefaces/primefaces/pull/11924/files
