### ISSUE TITLE
Zeef Page?

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#819]
@BalusC your Zeef page is gone but we have gotten some questions about it.

We found some in the WayBack machine but do you by chance have a copy of all those links so we can re-create that page?  People find it very handy!

https://archive.md/20160628025243/https://jsf.zeef.com/bauke.scholtz

**Comment by BalusC** [comment]
https://balusc.omnifaces.org/2024/03/jsfzeefcom-is-down.html :)

**Comment by melloware** [comment]
You rock as always!
