### ISSUE TITLE
ToCollectionConverter with inheritance

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#820]
This is a reminder to open a discussion about 
how to improve `ToCollectionConverter` ... 

I had a lot of trouble to make it work with a controller that extends another one

in combination with a stateless view (transient="true")

After a lot of debug I was able to retrieve the correct type 
with pure reflection instead of EL `ValueExpression` return type

The following code is adatped from my tests 
and written directly on github so probably should be adjusted

Eventually I'll try to update the example

```
@Named
@ViewScoped
public ViewController {

       static final DecentLogger log = DecentLogger.get( ... );

       public enum TestEnum { A,B,C }

	private List<TestEnum> enums;

	public List<TestEnum> getEnums() {return enums;}
	public void setEnums(List<TestEnum> enums) { this.enums = enums; }

	private TestEnum choice;

	public TestEnum getChoice() {return choice;}

	public void setChoice(TestEnum choice) { this.choice = choice; }


       public void init() {
                enums = List.of( TestEnum.A , TestEnum.B );
       }

	public void submit() {
		log.info("enums {0} -> choice {1}", enums, choice);
	}

}

```

```
@Named
@RequestScoped
public RequestController extends ViewController {


}
```

```
<f:view transient="true">
    <f:metadata>
       <f:viewAction action="#{requestController.init}" />
   </f:metadata>

<o:form id="test" includeRequestParams="true" partialSubmit="false">
  
   <o:inputHidden id="enums" value="#{requestController.enums}" converter="omnifaces.ToCollectionConverter" />

    <h:commandButton id="submit" value="TEST" action="#{requestController.foo}" >
      <f:ajax execute="@form" render="out" />
    </h:commandButton>
    
    <h:panelGroup id="out">
      <h:messages />
      #{requestController.enums} - #{requestController.choice}
    </h:panelGroup>

</o:form>

</f:view>
```

**Comment by pizzi80** [comment]
After a second read to the `ToCollectionConverter` code 

I found that my algo is very similar,
so the problem is inside

`ExpressionInspector.getMethodReference(context.getELContext(), valueExpression).getMethod();`

probably the real Class of the Bean it's not correctly "unwrapped"

**Comment by BalusC** [comment]
Sorry I don't understand the problem.
Code snippet is working for me (after making common sense changes so that the code compiles and runs). 
The ToCollectionConveter on o:inputHidden is working fine both ways.

Try adding a real reproducer and describing the use case containing the unexpected behavior as well as the expected behavior.

**Comment by pizzi80** [comment]
Even I don't understand/remember the exact situation :sweat_smile: 

I made a lot experiments with `@RequestScoped` + `o:inputHidden` 
and was not able to keep the state of an Enum.values across requests ... 

I solved with a simplified and stateless (`@ApplicationScoped`) version 
of the `ToCollectionConverter` but I should investigate further

**Comment by BalusC** [comment]
OK (re)open issue when you have a concrete reproducer and use case.
