### ISSUE TITLE
BrotliResponsFilter similar to GzipResponseFilter

### ISSUE THREAD

**Issue by melloware** [omnifaces/omnifaces#821]
Just a suggestion but a BrotliResponseFilter similar to GZipResponseFilter using Brotli4J: https://github.com/hyperxpro/Brotli4j?tab=readme-ov-file#compressing-a-stream

Brotli is faster than GZip and supported in all major browsers since about 2016.  In my tests Brotli was about the same compression size but always faster than GZip.

https://www.cloudways.com/blog/brotli-vs-gzip/

```
GZIP
40 requests
2.64 MB / 1.21 MB transferred
Finish: 941 ms
DOMContentLoaded: 929 ms
load: 934 ms

BROTLI
40 requests
2.64 MB / 1.21 MB transferred
Finish: 883 ms
DOMContentLoaded: 871 ms
load: 879 ms
```

**Comment by melloware** [comment]
There is also a Google Java Brotli impl: https://github.com/google/brotli/blob/master/java/org/brotli/pom.xml

Apache Commons Compress has this: https://github.com/apache/commons-compress/tree/master/src/main/java/org/apache/commons/compress/compressors/brotli

**Comment by BalusC** [comment]
OmniFaces intends to be free of 3rd party dependencies and Brotli is not part of JDK (yet?).

**Comment by melloware** [comment]
Totally understand.  I was wondering though because your code is so clever and handles SHA-256 and CombinedResourceHandler i wonder if we could make one that would only work if...

a) the person had the dependency in their own pom.xml not brought in transitively by OmniFaces
b) smart classloader to check for the existence of a class before loading? It looks like that is what Commons Compress does?

**Comment by BalusC** [comment]
An optional dependency could totally work. It could fall back to gzip when Brotli is unavailable or unsupported by client.

**Comment by jepsar** [comment]
I would prefer an exception if the dependency / class was not found.

**Comment by BalusC** [comment]
> There is also a Google Java Brotli impl: https://github.com/google/brotli/blob/master/java/org/brotli/pom.xml
> 
> Apache Commons Compress has this: https://github.com/apache/commons-compress/tree/master/src/main/java/org/apache/commons/compress/compressors/brotli

I took a look but none of them have a "Brotli output stream", I could only find a `BrotliInputStream`.

I found at least two libs having a "Brotli output stream" 
- https://github.com/hyperxpro/Brotli4j (already mentioned by you)
- https://github.com/nixxcode/jvm-brotli

So I added a `org.omnifaces.filter.CompressedResponseFilter` which supports these Brotli impls. Currently it's completely optional and it will fall back to Gzip or even further to Deflate (this is also new) when Brotli (or Gzip) is unavailable. 

I tested following two Brotli impls:
```xml
<dependency>
    <groupId>com.nixxcode.jvmbrotli</groupId>
    <artifactId>jvmbrotli</artifactId>
    <version>0.2.0</version>
</dependency>
```
```xml
<dependency>
    <groupId>com.aayushatharva.brotli4j</groupId>
    <artifactId>brotli4j</artifactId>
    <version>1.16.0</version>
</dependency>
```
It must be said that these were slightly slower than Gzip at my Linux machine with i9 10900x. Probably some HW/OS-related optimization missing as I noticed that these Brotli impls depend further on a bunch of native libs?

---
> I would prefer an exception if the dependency / class was not found.

That's possible by explicitly telling the `CompressedResponseFilter` that you want Brotli and nothing else.

```xml
<init-param>
    <param-name>algorithm</param-name>
    <param-value>Brotli</param-value>
</init-param>
```
Else it'll be automatic.

**Comment by melloware** [comment]
Awesome!

**Comment by melloware** [comment]
I will let you know the results of some apps i have GZipResponseFilter on and report back once this is released.
