### ISSUE TITLE
Feature Request: o:link

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#822]
Extends the default behaviour to include all the request parameters 
even if not defined with `f:viewParam`, like the `<o:form includeRequestParams="true" />`

or at least add an attribute to include a set of defined params, for example

```
<o:link outcome="/list" value="list" includeRequestParams="true" />

<o:link outcome="/list" value="list" includeViewParams="category,tag,order"  />
```

This is very useful when you use beans that process get parameters 
with the OmniFaces `@Param` annotation

**Background**
https://showcase.omnifaces.org/components/param
https://stackoverflow.com/questions/12810434/hlink-includeviewparams-true-does-not-include-url-parameters

**Comment by BalusC** [comment]
Great suggestion. I thought it already existed but I confused with [<o:url>](https://showcase.omnifaces.org/components/url).

**Comment by pizzi80** [comment]
:wink: :wink: 

Yes, I should have written that I was talking about extending `h:link` :sweat_smile:
