### ISSUE TITLE
How to define the target of converter messages when using @Param?

### ISSUE THREAD

**Issue by commodis** [omnifaces/omnifaces#824]
# Summary

Converter Messages through `@Param` are not rendered in global `h:messages`.

# Details

We have a global `<h:messages globalOnly="true"/>` and it does not render the messages thrown by the `@Param` annotation. I added a local `<h:messages />` and this **works** with `@Param`. Is it possible to somehow define the target like `@Param(converterTarget = null)`?

XHTML

```xml
<h:messages globalOnly="true" />
```

Bean

```java
@Param(required = false, converterClass = UUIDConverter.class, converterMessage = "Invalid UUID")
private UUID id;
```

**Comment by BalusC** [comment]
Point taken.

Work around: put `<h:messages redisplay="false">` _after_ all message components (relocate if necessary with CSS/JS).

**Comment by BalusC** [comment]
As per OmniFaces 4.5 you'll be able to use `@Param(globalMessage=true)` to indicate that it needs to add a global message.
