### ISSUE TITLE
Call of @ViewScoped bean B from @PreDestroy of @ViewScope bean A creates a new ViewScope

### ISSUE THREAD

**Issue by skybber** [omnifaces/omnifaces#828]
Calling a method on a `@ViewScoped` bean `B` from the `@PreDestroy` method of another `@ViewScoped` bean `A` creates a new ViewScope with a new instance of `B`.

For example:

```java
@ViewScoped
public class B {
  public void hello() {
    System.out.println("hello");
  }
}

@ViewScoped
public class A {
  @Inject
  private B b;

  @PostConstruct
  public void onInit() {
    b.hello();
  }

  
  @PreDestroy
  public void onDestroy() {
    b.hello();
  }
}
```

According to my understanding of the CDI specification, within the `@PreDestroy` method of `A`, the instance of `B` should belong to the same scope. No new scope should be created - it creates memory leaks in session.

**Suggestion:** Remove the view scope as the last step in `ViewScopeStorageInSession.destroyBeans();`.

**Comment by BalusC** [comment]
Fixed, thanks for reporting!
