### ISSUE TITLE
Internet has gone - OmniFaces Showcase

### ISSUE THREAD

**Issue by kurtomerfaruk** [omnifaces/omnifaces#829]
When entering the Omnifaces showcase, the message "Internet has gone" is displayed. SSL certificate seems to have expired

**Comment by allout58** [comment]
I have found that, as a workaround, I was able to open the Omnifaces showcase in Chrome (I usually use Firefox), accept the Certificate Expired warning, and have everything work.

**Comment by BalusC** [comment]
Fixed. Sorry for late action, I was having vacations.
