### ISSUE TITLE
BUG LruCache ConcurrentModificationException

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#850]
If multiple threads insert values and read all values from read only collections

**Step to reproduce**

1) Merge my PR https://github.com/omnifaces/omnifaces/pull/851
2) execute the test `TestLruCache.testImmutableViewsThreadSafety`

**Step to fix**
1) Merge my PR https://github.com/omnifaces/omnifaces/pull/852
2) execute again the test

**Comment by BalusC** [comment]
Thank you!

**Comment by pizzi80** [comment]
😉😉
