### ISSUE TITLE
BUG | TestUtils.testSerializeURLSafe do not work

### ISSUE THREAD

**Issue by pizzi80** [omnifaces/omnifaces#853]
```
[ERROR] Failures: 
[ERROR]   TestUtils.testSerializeURLSafe:37 expected: <eNrLSixLrNBLS0xOLbbKKk7Tyyquyc_Ny4QIwFlAYQBPNQ_-> but was: <eNrLSixLrNBLS0xOLbbKKk7Tyyquyc_Ny4QIwFl6WcUATzUP_g>
[INFO] 
[ERROR] Tests run: 55, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by BalusC** [comment]
Oh wow ok. Which JDK are you using? I genreally rely on OpenJDK based ones. Seems like there are non-OpenJDK-based JDKs with different (and apparently less efficient as yours is 2 chars longer) ZLIB compression impl.

I should probably adjust the test to check the JDK being used or to be JDK-independent.

**Comment by pizzi80** [comment]
Oh wow

I didn't know anything about it

for OmniFaces project I'm using Amazon Corretto 17.0.12 at the moment (should be the latest)

**Comment by BalusC** [comment]
Hmm ok Corretto is OpenJDK based. Probably they rewrote ZLIB impl. I'll have to adjust the test.
