### ISSUE TITLE
Beans.getActiveInstances(Class<S> scope) not working as expected

### ISSUE THREAD

**Issue by wshuman3** [omnifaces/omnifaces#86]
This method accepts S extends NormalScope  which will only ever work with NormalScope.   Note http://docs.jboss.org/cdi/api/1.1/javax/enterprise/context/package-tree.html. 

It should still be S extends Annotation.  Maybe I'm missing something and not understanding the API.  How can I get all SessionScoped beans?

**Comment by BalusC** [comment]
That was an embarrassing mistake. I fixed it for [2.1 SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.1-SNAPSHOT/).

Thank you for reporting!
