### ISSUE TITLE
o:importConstants enum, javax.el.PropertyNotFoundException if Enum contains static member

### ISSUE THREAD

**Issue by Totemuegerli** [omnifaces/omnifaces#864]
Firstly a big thanks for Omnifaces, 

Well i get a Error if enum contains a static member.

Example:
JSF
```html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:o="http://omnifaces.org/ui"
>
<f:view>
    <o:importConstants type="org.omnifaces.showcase.model.ExampleEnum" />
    <h:selectOneMenu >
        <f:selectItems value="#{ExampleEnum.values()}" var="exampleEnum"
                       itemValue="#{exampleEnum}" itemLabel="#{exampleEnum.friendlyName}" />
    </h:selectOneMenu>
</f:view>
</html>
``` 

Enum
```java
package org.omnifaces.showcase.model;

import java.util.EnumSet;

public enum ExampleEnum {
	ONE, TWO, THREE;

	public String getFriendlyName() {
		return name().charAt(0) + name().substring(1).toLowerCase();
	}

	public static final EnumSet<ExampleEnum> FOO_ENUMSET = EnumSet.of(ExampleEnum.ONE, ExampleEnum.THREE);
}
``` 

Stacktrace:
`	Caused by: javax.el.PropertyNotFoundException: Die Eigenschaft [friendlyName] wurde fÃ¼r den Typ [java.util.RegularEnumSet] nicht gefunden
		at javax.el.BeanELResolver$BeanProperties.get(BeanELResolver.java:253)
		at javax.el.BeanELResolver$BeanProperties.access$300(BeanELResolver.java:206)
		at javax.el.BeanELResolver.property(BeanELResolver.java:322)
		at javax.el.BeanELResolver.getValue(BeanELResolver.java:93)
		at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:156)
		at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:184)
		at org.apache.el.parser.AstValue.getValue(AstValue.java:168)
		at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:189)
		at org.jboss.weld.module.web.el.WeldValueExpression.getValue(WeldValueExpression.java:50)
		at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:73)
		... 93 more
`

Without the static member (FOO_ENUMSET), it works fine

**Comment by BalusC** [comment]
Point taken, but this is unfortunately as per the specification. We also want to be able to access `#{ExampleEnum.FOO_ENUMSET}`.

Work around for now, grab the values via one of the known enum members instead:
```
<f:selectItems value="#{ExampleEnum.ONE.values()}" ...>
```
For the future OmniFaces 4.6 version, you'll be able to use the [new `members()` method](https://github.com/omnifaces/omnifaces/commit/732507fa42259f0f451fffc21d03fd0556e441b6) to access exclusively enum mebers:
```
<f:selectItems value="#{ExampleEnum.members()}" ...>
```
Thank you for reporting the issue and improving OmniFaces!

**Comment by Totemuegerli** [comment]
Hi BalusC, thx for fast answer, just as a clarification, maybe we misunderstand each other.
From View-Side i don't need to access #{ExampleEnum.FOO_ENUMSET}, just get all Enum values as SelectItems

**Comment by BalusC** [comment]
Yes I already understood that. But the issue is that `FOO_ENUMSET` is in eyes of the Java compiler **also** a constant and there exist people who want to be able to use `#{ExampleEnum.FOO_ENUMSET}`. The `<o:importConstants>` is to import constants of any class and not specifically enum constants. See also https://showcase.omnifaces.org/taghandlers/importConstants
