### ISSUE TITLE
Bug in method for add response cookie - httpOnly parameter is ignored

### ISSUE THREAD

**Issue by jacekzwroclawia** [omnifaces/omnifaces#866]
Method in FacesLocal has a bug - parameter httpOnly is ignored and it is passed as true - it is error-prone.

Version: **4.5.1**

```
    /**
     * @see Faces#addResponseCookie(String, String, String, String, int, boolean)
     */
    public static void addResponseCookie(FacesContext context, String name, String value, String domain, String path, int maxAge, boolean httpOnly) {
        addResponseCookie(context, name, value, domain, path, maxAge, true, null);
    }
```

**Comment by BalusC** [comment]
Yeah fixed on the fly during https://github.com/omnifaces/omnifaces/commit/a807d6f#diff-354e0419d75dbfdc9022caeeddcb1a6ad4a2871079e4d87305f42d48fcbbf192R1417 Will be in 4.6. 

Thanks!
