### ISSUE TITLE
o:viewScoped and unload

### ISSUE THREAD

**Issue by cocorossello** [omnifaces/omnifaces#868]
This is more a question than a defect.

Many times, when we switch a bean from JSF's ViewScoped to an Omnifaces's ViewScoped  we get some concurrency errors saying that the bean.someProperty is null.

The problem is that if the user starts an "slow" ajax (which takes about lets say 100ms) and at the same time reloads the page, the ajax can fail with a NPE exception.

This is not Omnifaces's fault of course, as the ajax will not go anywhere, but the error plagues the logs and it's very difficult to decide whether it's a real error or not, since anything in the render phase can throw an NPE.

I arranged a small reproducer in https://github.com/cocorossello/primefaces-test/
 

Just run `mvn  jetty:run -Pmyfaces23next`, navigate to http://localhost:8080/primefaces-test/ and reload the page many times fast. Eventually it will happen

![image](https://github.com/user-attachments/assets/aa16f4d6-a569-4879-bf42-c151d35e8997)

Do you think that is there any way to detect that a ViewScoped was removed from the view so we can just discard the error in the exception handler?

**Comment by cocorossello** [comment]
A naive solution can be to delay the actual unload 1 second

**Comment by cocorossello** [comment]
I think that here:

```
		BeanStorage beanStorage = storage.getBeanStorage(beanStorageId);

		if (beanStorage == null) {
			beanStorage = new BeanStorage(DEFAULT_BEANS_PER_VIEW_SCOPE);
			storage.setBeanStorage(beanStorageId, beanStorage);
		}
```

Can we assume that if the request is ajax and beanStorage ==null then we can safely throw a ViewExpiredException? 

Something like:

```
        if (beanStorage == null) {
            if (Faces.isAjaxRequest()) {
                throw new ViewExpiredException("View destroyed during ajax request");
            }
            beanStorage = new BeanStorage(DEFAULT_BEANS_PER_VIEW_SCOPE);
            storage.setBeanStorage(beanStorageId, beanStorage);
        }
```

**Comment by BalusC** [comment]
> Can we assume that if the request is ajax and beanStorage ==null then we can safely throw a ViewExpiredException?

Nope, the condition is the same when navigating to another page during an ajax request, or explicitly rebuilding the view. But point is taken, I'll take a closer look.

**Comment by cocorossello** [comment]
Yes, I tried and didn't work. Also, a ui:fragment not rendered in the GET request using a specific bean may be rendered in an ajax, hence initializing the bean (because of lazy initialization). 

I don't really have the idea of how to do it

**Comment by BalusC** [comment]
Fixed, thank you very much for reporting this peculiar corner case and improving OmniFaces!

**Comment by cocorossello** [comment]
Thanks for the fix, also for taking the time to backport it.

One question: isn't the recentlyDestroyedViewStates capacity too small? Being a unique cache in the whole application, 20 seems a low value.

In our case, we have 60k unload view events per hours (peak hour). 

I can increase it myself in my application, I'm just asking.

**Comment by BalusC** [comment]
Point taken, I'll take a second look later. Managing it via ViewScopeStorageInSession wasn't working as expected.

**Comment by BalusC** [comment]
Fixed now.
