### ISSUE TITLE
o:moveComponent dublicates moved component when mojarra release 4.0.8 is used

### ISSUE THREAD

**Issue by OBreidenbach** [omnifaces/omnifaces#871]
In our project we using o:moveComponent since years to move buttons inside a composite component.

After upgrading Mojarra from release 4.0.7 to 4.0.8 the button is not moved but dublicatet. 

I did create a small reproducer with the primefaces-test project: 
https://github.com/OBreidenbach/primefaces-test/tree/reproducer_moveComponent

I have no idee, if this the failure of omnifaces or mojarra. 
But as @BalusC is involved in both projects, you will figure out, I guess.

To see the diffrent behavior, change the used mojarra release in the pom.xml  4.0.7 <-> 4.0.8.

Thank you for your great work on these projects.

**Comment by BalusC** [comment]
According to https://github.com/eclipse-ee4j/mojarra/compare/4.0.7-RELEASE...4.0.8-RELEASE the most possible cause is the fix to https://github.com/eclipse-ee4j/mojarra/issues/5445. I'll need to take a closer look and introduce o:moveComponent integration tests as well.

**Comment by BalusC** [comment]
For the time being you could in your specific case use f:facet/cc:renderFacet instead of o:moveComponent because you already have a composite component there.

**Comment by OBreidenbach** [comment]
https://github.com/eclipse-ee4j/mojarra/issues/5522

I just tried mojarra release 4.0.9 and move component is working as expected again.
Thanks for fixing mojarra.
https://github.com/eclipse-ee4j/mojarra/pull/5523

**Comment by BalusC** [comment]
You're welcome!
