### ISSUE TITLE
DNSSEC not working for omnifaces.org

### ISSUE THREAD

**Issue by Quentin-Quarantino** [omnifaces/omnifaces#872]
Hi all, 

In our environment we have DNSSEC enabled and the domain omnifaces.org cant work on our side becuse it is not setup correctly on the name cheap servers.

Steps to reproduce
Try to visit omnifaces.org when your DNS server is validating DNSSEC.
The web browser fails to load the site.

Here i have additional tests and sources for testing DNSSEC.  

https://dnsviz.net/d/omnifaces.org/dnssec/
https://zonemaster.se/en/result/6b3abcca3e6f9efb

(Looks like the same issue) 
https://github.com.mcas.ms/mermaid-js/mermaid/issues/5331

https://developers.cloudflare.com/dns/dnssec/troubleshooting/

Thanks and KR

**Comment by BalusC** [comment]
We're looking into this. This might take a few days to catch up.

**Comment by BalusC** [comment]
Should be sorted out by now as per https://dnsviz.net/d/omnifaces.org/dnssec/ which has now only a few notices instead of a bunch of errors. Can you please verify on your side? These notices are unfortunately beyond our control btw.

**Comment by Quentin-Quarantino** [comment]
Hi @BalusC 
Thanks for the fix. Now it works fine.

**Comment by BalusC** [comment]
Great, thanks for the suggestion and the feedback!
