### ISSUE TITLE
Ajax with execute="@this" removes component value from request if ClientBehaviorContext contains a sourceId

### ISSUE THREAD

**Issue by cmunier** [omnifaces/omnifaces#879]
I have a custom UIComponent that renders ajax behavior using [AjaxBehaviorRenderer#getScript(ClientBehaviorContext)](https://github.com/eclipse-ee4j/mojarra/blob/4.0.4-RELEASE/impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java#L63).

If a `sourceId` is included in the context, Mojarra calls [faces.ajax.request](https://github.com/eclipse-ee4j/mojarra/blob/4.0.4-RELEASE/impl/src/main/resources/META-INF/resources/jakarta.faces/faces-uncompressed.js#L2452) with a string value containing the client ID of the component instead of the current HTMLElement (also see [AjaxBehaviorRenderer#L214](https://github.com/eclipse-ee4j/mojarra/blob/4.0.4-RELEASE/impl/src/main/java/com/sun/faces/renderkit/html_basic/AjaxBehaviorRenderer.java#L214)).

The [wrapping ajax request handler in Omnifaces](https://github.com/omnifaces/omnifaces/blob/4.5.1/src/main/resources/META-INF/resources/omnifaces/omnifaces.js/Form.ts#L55) always assumes a HTMLElement (call to `source.id`).
As a consequence, `@this` is replaced with `undefined` in `executeIds` and the `containsNamedChild` method cannot operate properly. The values of child components are then filtered from the ViewState and are not included in the ajax request.

OmniFaces version: 4.5.1
Mojarra version: 4.0.4

**Comment by cmunier** [comment]
I prepared a fix in https://github.com/omnifaces/omnifaces/pull/880 that shows a possible solution that would work in my case.

**Comment by BalusC** [comment]
Can you backport it for 3.x? https://github.com/omnifaces/omnifaces/blob/3.x/src/main/resources/META-INF/resources/omnifaces/form.unminified.js (note it's indeed JS instead of TS).

**Comment by cmunier** [comment]
Sure - here is a backport for 3.x. (Note: I had no time yet to test this with JSF 2.3 on my machine.)
https://github.com/omnifaces/omnifaces/pull/881

**Comment by BalusC** [comment]
Thank you!
