### ISSUE TITLE
org.omnifaces.exception_uuid differs from log to page

### ISSUE THREAD

**Issue by crick77** [omnifaces/omnifaces#882]
I've extended the FacesExceptionFilter like this:

   
```
protected void logException(...) {
        String uri = request.getRequestURI();
        if (exception instanceof ViewExpiredException) {
            // With exception==null, no trace will be logged.
            super.logException(request, null, location, message, parameters);
        }
        else {   
            logger.error("UUID [{}]  -- INIZIO --", request.getAttribute("org.omnifaces.exception_uuid"));
            logger.error("Pagina [{}]", uri);            
            logger.error("Destinazione [{}]", location);            
            logger.error("Messaggio [{}]", message);
            logger.error("Eccezione di base [{}]", exception!=null ? exception.toString() : null);
            logger.error("StackTrace:\n{}", stackTraceToString(exception!=null ? exception.getCause() : exception));
            logger.error("UUID [{}] -- FINE --", request.getAttribute("org.omnifaces.exception_uuid"));
        }
}
```

then in the error.xhml simple as:

`
#{requestScope['org.omnifaces.exception_uuid']}
`

The problem is that the value in the log file does not match the one in the page. For counter-test I've just added a line in the log that copies the _org.omnifaces.exception_uuid_ request attribute in another one:

```
//...
else {   
            request.setAttribute("UUID", request.getAttribute("org.omnifaces.exception_uuid"));

            logger.error("UUID [{}]  -- INIZIO --", request.getAttribute("org.omnifaces.exception_uuid"));

            logger.error("Pagina [{}]", uri);       

/...
```

in the page I just output both and the one assoicated to _UUID_ name is exactly the one logged. It seems that during some other code inside the FacesExceptionFilter the uuid value is regenerated.

Thank you,
Ric.

Jakarta EE 10 on Payara 6.2024.8, PrimeFaces+Ext 14.0.6, OmniFaces 4.5.1, Mojarra 4.0.0.payara-p2, JDK 21

**Comment by BalusC** [comment]
Probably another exception occurred while showing the error page? Or you have two active instances of `FacesExceptionFilter`? Put a breakpoint at `request.setAttribute(EXCEPTION_UUID, UUID.randomUUID().toString());` line in both the `FacesExceptionFilter` and the `FullAjaxExceptionHandler`.

**Comment by BalusC** [comment]
Right, since OmniFaces 4.5 the FullAjaxExceptionHandler will automatically register the FacesExceptionFilter when absent, but this check failed when you have a custom FacesExceptionFilter. It has been fixed now. Thank you very much for reporting the issue!

**Comment by crick77** [comment]
Ok...I will have a look ASAP using 4.6M1 and let you know. Thank you
