### ISSUE TITLE
Feature request: add Object... args to Faces#getBundleString to format the string

### ISSUE THREAD

**Issue by jepsar** [omnifaces/omnifaces#885]
So you can format a message right away. For example, if bundle string entry is `helloXxx=Hello {0}!`, you could do `Faces.getBundleString("helloXxx", "world")`.

**Comment by BalusC** [comment]
That'll have to be as per MessageFormat#format rules not as per those of String#format :)

**Comment by jepsar** [comment]
> That'll have to be as per MessageFormat#format rules not as per those of String#format :)

Yeah, that's probably more in line with what you would expect when it comes to message bundles!
