### ISSUE TITLE
CDNReourseHandler local resources support

### ISSUE THREAD

**Issue by MSzturc** [omnifaces/omnifaces#89]
To force multiple JSF Component libraries to use the same javascripts it would be nice to do the mapping through CDNReourseHandler 

Example: 
```
    <context-param>
        <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
        <param-value>bsf:jq/jquery.js=primefaces:jquery/jquery.js</param-value>
    </context-param>
```
As a workaround mapping the resource to the absoulte url works, but thant the application root is hardcoded in the web.xml.

Workaround:
```
    <context-param>
        <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
        <param-value>bsf:jq/jquery.js=http://localhost:8080/APP/javax.faces.resource/jquery/jquery.js?ln=primefaces</param-value>
    </context-param>
```

**Comment by BalusC** [comment]
Idea is sound. Nice one.

**Comment by BalusC** [comment]
Different solution: http://stackoverflow.com/questions/28968561/two-instances-of-jquery-ignore-the-second-inclusion

**Comment by BalusC** [comment]
In hindsight, I'd rather not implement that in CDN resource handler itself.

As EL is supported in CDN context param, you could workaround your specific case as below:

```
<context-param>
    <param-name>org.omnifaces.CDN_RESOURCE_HANDLER_URLS</param-name>
    <param-value>bsf:jq/jquery.js=#{resource['primefaces:jquery/jquery.js']}</param-value>
</context-param>
```
