### ISSUE TITLE
ClassCastException with ValidateOrder if short value is 0

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#93]
I recently added <o:validateOrder> to time range selection form which is bound to two short values.

My partner found out that selecting '0' results in a ClassCastException. Only with '0' !

Summary:

	java.lang.IllegalArgumentException: All values must implement java.lang.Comparable.
		at org.omnifaces.component.validator.ValidateOrder.validateValues(ValidateOrder.java:144)
	....
		Caused by: java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Long

Maybe this is related to JSF implementation because i saw similar bugs with other component/frameworks.

**Comment by BalusC** [comment]
Context is missing, but I think this one can be solved by explicitly specifying the `javax.faces.Short` converter.

**Comment by djmj** [comment]
I am using a custom converter for primefaces-extension timepicker component to convert the time string "00:00" to its `Long` representation. 

I could cast it to `Short` in my converter since my data object uses `Short`.


I was thinking about submitting this converter to omnifaces since this may be usable for other people. (It uses default pattern but could be extended to AM/PM version and custom separator.)

What do you think?

**Comment by BalusC** [comment]
OK, this is thus a bug in the converter.
