### ISSUE TITLE
Infinite loop in OmniApplicationFactory with OmniFaces 2.0

### ISSUE THREAD

**Issue by asw12** [omnifaces/omnifaces#95]
```
private synchronized Application createOmniApplication(final Application application) {
		Application newApplication = application;

		while (!(newApplication instanceof OmniApplication) && newApplication instanceof ApplicationWrapper) {
			newApplication = ((ApplicationWrapper) application).getWrapped();
		}

        ...
	}
```

This can loop infinitely when there are more than one ApplicationWrappers since application is the final parameter and application.getWrapped() is always the same value. I think what was intended was 
`newApplication = ((ApplicationWrapper) newApplication).getWrapped();`

**Comment by BalusC** [comment]
Indeed overlooked that one during fixing #38. Thank you!
