### ISSUE TITLE
distributable flag in web-fragment.xml

### ISSUE THREAD

**Issue by zerounix** [omnifaces/omnifaces#96]
Hi,

we are trying to get our JSF application up and running on a jboss domain mode cluster. After some research we found out that using omnifaces.jar breaks out distributable flag. As to the spec it seams that all fragments need to be distributable or none.

Adding the distributable flag to omnifaces.jar fixes our issue.

Do you see any possibility to add the flag to omnifaces web-fragment.xml?

**Comment by BalusC** [comment]
Thank you!
