### ISSUE TITLE
Feature - zero to one based index converter

### ISSUE THREAD

**Issue by djmj** [omnifaces/omnifaces#99]
This is a very small feature but still no reason for everyone to reimplement it.

My current use case is pagination data with bookmarkable URL's and SEO `next` and `prev` links. E.g: *www.example.com?page=1* to convert it in bean to 0 for easier calculations.

	<o:viewParam name="page" value="#{bean.page}" converter="package.ZeroIndexConverter" />

	<h:link outcome="#{view.viewId}>
		<o:param name="page" value="#{bean.page}" converter="package.ZeroIndexConverter"/>
	</h:link>

	@FacesConverter("package.ZeroIndexConverter")
	public class ZeroIndexConverter extends ValueChangeConverter
	{
		@Override
		public Object getAsChangedObject(final FacesContext context, final UIComponent component, final String value)
		{
			try
			{
				return Long.parseLong(value) - 1;
			}
			catch (final NumberFormatException e)
			{
	
			}
	
			return null;
		}
	
		@Override
		public String getAsString(final FacesContext context, final UIComponent component, final Object value)
		{
			if (value instanceof Number)
				return String.valueOf(((Number) value).longValue() + 1);
	
			return null;
		}
	}

**Comment by BalusC** [comment]
This doesn't solve a general JSF problem/shortcoming.
